### ISSUE TITLE
Attempting to install Firebase Admin SDK with Composer

### ISSUE THREAD

**Issue by goodrickstar** [kreait/firebase-php#100]
First time with composer and trying to install any dependencies. I executed the following commands in **Putty SSH** logged in as **root** on my dedicated server running **cPanel/Linux**, **Apache 4**, and **PHP 7** to install composer. Below is exact install procedure followed from https://www.contrid.co.za/2016/09/install-composer-on-cpanelwhm/

```
cd /tmp 
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
```
Composer version 1.4.2 was successfully installed. I then attempt to install the Firebase Admin SDK using composer globally with the following with the same SSH root login.

`composer require kreait/firebase-php ^3.0`

**Installation fails with this error**

> [Composer\Downloader\TransportException]
> The "https://packagist.org/packages.json" file could not be downloaded: **allow_url_fopen must be enabled in php.ini** (https:// wrapper is disabled in the server configuration by **allow_url_fopen=0**
> failed to open stream: no suitable wrapper could be found)

Problem is, my php.ini files at root and user level both look like this and have **allow_url_fopen=on**

> ; cPanel-generated php ini directives, do not edit
> ; Manual editing of this file may result in unexpected behavior.
> ; To make changes to this file, use the cPanel MultiPHP INI Editor (Home >> Software >> MultiPHP INI Editor)
> ; For more information, read our documentation (https://go.cpanel.net/EA4ModifyINI)
> 
> allow_url_fopen = On
> allow_url_include = On
> display_errors = On
> enable_dl = On
> file_uploads = On
> max_execution_time = 30
> max_input_time = 60
> max_input_vars = 1000
> memory_limit = 32M
> session.gc_maxlifetime = 1440
> session.save_path = "/var/cpanel/php/sessions/ea-php70"
> upload_max_filesize = 5M

**Comment by jeromegamez** [comment]
Hey @goodrickstar! I assume that PHP on the command line uses a different configuration than the one you've looked into. You can see which one it is by checking the output of `php --ini` on the command line.

As this is a general PHP configuration topic, I'm going to close this issue now, but feel free to add more comments if you need further help.

**Comment by goodrickstar** [comment]
jeromegamez here is the output of your suggestion 

`[root@www ~]# php --ini`

> Configuration File (php.ini) Path: /opt/cpanel/ea-php70/root/etc
> Loaded Configuration File:         /opt/cpanel/ea-php70/root/etc/php.ini

`[root@www ~]# cd opt`

> -bash: cd: opt: No such file or directory

Apparently I'm more confused than I thought. The path clearly says 
> opt
 but 
`cd opt` 
returns does not exist

**Comment by jeromegamez** [comment]
You have to `cd /opt` with a leading slash. Also, you can't `cd` to a binary: if you want to go to the directory composer is in, you have to do `cd /usr/local/bin`.

Usually, `/usr/local/bin` is in the include paths of your shell, so you don't have to change your current working directory to the directory where composer is located.

If you want to check if `allow_url_fopen` is enabled in the CLI environment, you can to it by issuing

```bash
php -i | grep allow_url_fopen
```

I assume this will return something like

```bash
❯ php -i | grep allow_url_fopen
allow_url_fopen => Off => Off
```

Based on your output above, you can now double check if this is what actually is set in your php.ini:

```bash
grep allow_url_fopen /opt/cpanel/ea-php70/root/etc/php.ini
```

which probably will return

```
allow_url_fopen = Off
```

Which means that you should change this value to `On` in the file `/opt/cpanel/ea-php70/root/etc/php.ini`.

I hope this helps!
