### ISSUE TITLE
Getting: 'This token has an invalid issuer.'

### ISSUE THREAD

**Issue by willdeangelis** [kreait/firebase-php#101]
Hi there,

New to this project, but am very hopeful it's still being maintained and is what I need. I've set it up but unfortunately, I'm getting the error:

Uncaught Firebase\\Auth\\Token\\Exception\\InvalidToken: This token has an invalid issuer.

When I check the values that are causing this error on line 81 of Verifier.php:

$token->getClaim('iss')  RETURNS  'accounts.google.com'
sprintf('https://securetoken.google.com/%s', $this->projectId)  RETURNS  'https://securetoken.google.com/MYPROJECTID' 

(Where MYPROJECTID is my real project id)

I'm using the Firebase Javascript SDK to login and then get the credential's idToken on the front end. Then I pass that token (a 917 character string) to my backend where I run the check on it using the following code:

`$firebase = (new Firebase\Factory())->create();
$tokenHandler = $firebase->getTokenHandler();
$idTokenString = MYTOKEN;
$idToken = $tokenHandler->verifyIdToken($idTokenString);
$uid = $idToken->getClaim('sub');`

(Where MYTOKEN is my real idToken)

I verified that the token is getting generated and passed correctly. 

What else could I be doing wrong? 

Please help! Many thanks in advance!

**Comment by willdeangelis** [comment]
Figured it out. Wrong token. Thx / best wishes!

**Comment by izzudin96** [comment]
How did you solved this problem? I'm currently facing this issue.
