### ISSUE TITLE
The JWT string must have two dots

### ISSUE THREAD

**Issue by paradox37** [kreait/firebase-php#102]
Hello,

I tried using this SDK to try and verify token which I get when user subscribes to web push notification. But I'm getting this error: The JWT string must have two dots.

Am I missing some step here? The token I get from Firebase indeed does not look like JWT.

Do I need to do something with it before or this SDK can't be used to verify Firebase web notification token?

**Comment by jeromegamez** [comment]
Hey @paradox37, and thanks for reaching out. Token verification can be applied only to ID tokens as described in https://firebase.google.com/docs/auth/admin/verify-id-tokens

**Comment by MGParisi** [comment]
Then how do we get the User ID to verify the userID?

**Comment by jeromegamez** [comment]
The IdToken is authenticated by another application and you can verify that it has been authenticated correctly. If you just want to get a user by ID, you don't need to generate an IdToken to then verify it - just use the UID directly.

**Comment by MGParisi** [comment]
How
