### ISSUE TITLE
Class 'Firebase\Database' not found

### ISSUE THREAD

**Issue by goodrickstar** [kreait/firebase-php#103]
I'm attempting to utilize the server value of timestamp in my php project to entries into Firebase Realtime DB.

```
<?php
require 'vendor/autoload.php';
use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;
use Firebase\Database;
$serviceAccount = ServiceAccount::fromJsonFile('.config/google.json');
$firebase = (new Factory)->withServiceAccount($serviceAccount)->withDatabaseUri('https://my-ap.firebaseio.com/')->create();
$db = $firebase->getDatabase();
$ref = $db->getReference('reservoir')->push('created_at', Database::SERVER_TIMESTAMP)->getKey();
print_r($ref);
```
prints the following  

> Fatal error: Uncaught Error: Class 'Firebase\Database' not found

Firebase was installed by composer using composer `require  kreait/firebase-php ^3.0`

What am I needing to require to access the Database class?

**Comment by jeromegamez** [comment]
Hey @goodrickstar, this was an error in the documentation - please remove the `use Firebase\Database;` line and your code should work as expected, with `$db` containing the database instance.

**Comment by movify** [comment]
Hi there, 

So it looks I dont have in my php:
use Kreait\Firebase\Database;

But instead I have:
use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

And this error persists, any help¿?

**Comment by jeromegamez** [comment]
@movify If an existing issue and it’s comments doesn‘t solve your problem, please open a new issue and follow the instructions in the issue template.

Especially provide a full code example (without secrets) so that the problem can be reproduced.

Based on our previous communications, please make sure that on your server, the PHP version is the same as in your development environment and that the vendor directory exists.

**Comment by movify** [comment]
Hi Jerome,

The fact is that I send a POST by html to Stripe, and in this .PHP file I try to create the instance of my Firebase Database without any success.

*****************


Is there any step-by-step guideon getting just Snapshot fromFirebase in PHP?
*****************

/vendor exists in my ftp server and the PHP Version installed in my Mac is 7.1.7.

Do I have install on the FTP server a PHP?


Best,

**Comment by jeromegamez** [comment]
I posted a link to a usage example as a reply to your comment on the other thread - you do actually need PHP in each environment a script is running in, so yes, you need to install a PHP on your FTP-Server.
