### ISSUE TITLE
getUser method

### ISSUE THREAD

**Issue by P110** [kreait/firebase-php#104]
Hi,
Thanks for creating this!

I was wondering if it would be possible to add the getUser method, from the node & Python SDKs, to the authentication portion of this SDK??

Essentially just to use a userId recovered from a token to get the user's information (displayName etc), it's referenced [here](https://firebase.google.com/docs/auth/admin/manage-users#retrieve_user_data) in the docs.

(Creating and updating would be nice too but I'm not gonna push it).

Thanks & have a great day!

**Comment by jeromegamez** [comment]
I am currently working on exactly that 🤗. Expect a new release with some basic user management functionality in the coming week or two!

**Comment by jeromegamez** [comment]
I just created #105, all progress can be tracked there (and you're all invited to test it excessively 😉 )
