### ISSUE TITLE
ServiceAccount::fromJsonFile() not working

### ISSUE THREAD

**Issue by setiawanandre06** [kreait/firebase-php#106]
I tried to follow the setup instruction (Manually), and I got this fatal error message:

> Fatal error: Uncaught Error: Call to private method Kreait\Firebase\ServiceAccount::fromJsonFile() from context '' in C:\xampp\htdocs\QR-wallet-admin\setup.php:8 Stack trace: #0 {main} thrown in C:\xampp\htdocs\QR-wallet-admin\setup.php on line 8

Here is my code : 

`<?php

require __DIR__.'\vendor\autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/google-service-account.json');

$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->create();
?>`

DId I make a wrong path with my 'google-service-account.json'?

**Comment by dri94** [comment]
I have this same issue with ServiceAccount::fromJson()

**Comment by setiawanandre06** [comment]
Oh yeah, right. I just read the docs and It only supports 3.1 version. Thanks!

**Comment by movify** [comment]
Hi guys,

Can you explain me how you solved the problem?

It looks I have the same issue and I can not access correctly the ServiceAccount.

Is there any step-by-step guide on getting a Snapshot from Firebase in PHP?

Best,

**Comment by jeromegamez** [comment]
There is a usage example at http://firebase-php.readthedocs.io/en/latest/overview.html#usage-example which writes something into the RealtimeDatabase and then fetches it (`getValue()` is a shortcut for `getSnapshot()->getValue()`).

Make sure to also require the autoloader (the first line in the code snippet)
