### ISSUE TITLE
Support conditional requests/transactions

### ISSUE THREAD

**Issue by jeromegamez** [kreait/firebase-php#108]
see https://firebase.google.com/docs/database/rest/save-data#section-conditional-requests

**Comment by EECOLOR** [comment]
So this didn't get in?

**Comment by EECOLOR** [comment]
Instead of adding suport for conditional requests you could provide access to the api client and http client of a reference. In that case we could use the client to manually call the correct endpoints with the correct headers.

**Comment by jeromegamez** [comment]
@EECOLOR [4.21](https://github.com/kreait/firebase-php/releases) is out and includes transactions/conditional requests 🎉
