### ISSUE TITLE
where I must to add token?

### ISSUE THREAD

**Issue by karanshahmuradyan** [kreait/firebase-php#109]
Fatal error: Uncaught Kreait\Firebase\Exception\InvalidArgumentException: C:\xampp\htdocs\firebase-php/google-service-account.json does not exist. in C:\xampp\htdocs\firebase-php\src\Firebase\ServiceAccount.php:122 Stack trace: #0 C:\xampp\htdocs\firebase-php\index.php(8): Kreait\Firebase\ServiceAccount::fromJsonFile('C:\\xampp\\htdocs...') #1 {main} thrown in C:\xampp\htdocs\firebase-php\src\Firebase\ServiceAccount.php on line 122

**Comment by jeromegamez** [comment]
Sorry, your "bug report" doesn't provide anything I could work with or that you couldn't figure out yourself. Which version of the library are you using? What is your PHP version? What code did you write that lead to this error?

The exception states that no service account JSON file could be found at the given location. I would recommend starting with that :)
