### ISSUE TITLE
should getResultFromResponse method use array_filter?

### ISSUE THREAD

**Issue by insaneDev** [kreait/firebase-php#11]
I just downloaded kreait/firebase-bundle. After playing around with some code of the example section I got an "Warning: strlen() expects parameter 1 to be string" error

i tracked down the error until Firebase@getResultFromResponse line 175.
$rawResult is an array when it gets there after call, by example:

$firebase->get('services', array('shallow' => true));

**Comment by jeromegamez** [comment]
Hey Oscar,

I am currently in the process of refactoring the firebase library which this Bundle relies on. Please expect the method calls to change, but also the warning to disappear :)

**Comment by iamtankist** [comment]
Sorry guys, it's in my top prio list to take a look at this issue, but still not getting to it. 
Should be fixed within next few days.

**Comment by jeromegamez** [comment]
Hey Oscar,

sorry for the super late reply - I am just trying to figure out the problem. Could you provide an example data set which caused the error for you?

**Comment by jeromegamez** [comment]
Hi Oscar,

please checkout the latest release (0.4.2) of the library - I hope it will resolve your issue. Please note that `Firebase::get()` doesn't support options since a couple of releases.

The recommended way to get a shallow result is the following:

```php
$firebase = new Firebase('https://my-firebase-instance.firebaseio.com');

$query = new Query();
$query->shallow();

$data = $firebase->query('path/to/my/location', $query);
```
