### ISSUE TITLE
Conflict with Firebase JWT

### ISSUE THREAD

**Issue by dri94** [kreait/firebase-php#110]
#### 1. Which version of `kreait/firebase-php` are you using?
3.1

*You can use `composer show kreait/firebase-php` to see the installed version in the `versions` line.*

#### 2. Which version of PHP are you using?
7
*You can use `php -v` on the system the issue occurs on to get the PHP version.* 

#### 3. What's the issue?
Conflict when adding firebase jwt php library

```
- kreait/firebase-php 3.1.0 requires google/auth ^0.11.0 -> satisfiable by google/auth[v0.11.1, v0.11.0].
    - google/auth v0.11.1 requires firebase/php-jwt ~2.0|~3.0|~4.0 -> satisfiable by firebase/php-jwt[2.0.0, v2.1.0, v2.2.0, v3.0.0, v4.0.0] but these conflict with your requirements or minimum-stability.
    - google/auth v0.11.0 requires firebase/php-jwt ~2.0|~3.0|~4.0 -> satisfiable by firebase/php-jwt[2.0.0, v2.1.0, v2.2.0, v3.0.0, v4.0.0] but these conflict with your requirements or minimum-stability.
    - google/auth v0.11.1 requires firebase/php-jwt ~2.0|~3.0|~4.0 -> satisfiable by firebase/php-jwt[2.0.0, v2.1.0, v2.2.0, v3.0.0, v4.0.0] but these conflict with your requirements or minimum-stability.
    - Installation request for kreait/firebase-php 3.1 -> satisfiable by kreait/firebase-php[3.1.0].
```

**Comment by jeromegamez** [comment]
@dri94 Thanks for reporting this. I just created a new release ([3.1.2](https://github.com/kreait/firebase-php/releases/tag/3.1.2)) that should fix the issue.
