### ISSUE TITLE
Slow any request like update, set, query

### ISSUE THREAD

**Issue by klimoma** [kreait/firebase-php#113]
#### 1. Which version of `kreait/firebase-php` are you using?

3.1.2

#### 2. Which version of PHP are you using?

7.1.8

#### 3. What's the issue?

I have problem, that every action like query, set or update ... are very slow. its about 1-2s. I dont think that problem is in code. I have just very easy script. But i didnt found any solution yet. Do you know any recommendation, where shoud be a probelm? Thank you.

#### 4. Code that lead to the issue

```
$milliseconds = round(microtime(true) * 1000);
$database = $firebase->getDatabase();
$queueRef = $database
    ->getReference('testTable');
$queueSnapshot = $queueRef->orderByChild('status')->equalTo(0)->getSnapshot();
$values = $queueSnapshot->getValue();
$milliseconds2 = round(microtime(true) * 1000);
var_dump($milliseconds2 - $milliseconds);

```

**Comment by jeromegamez** [comment]
Unfortunately, there is not much we can do here. The speed of the operations depends on the speed of the network connection between the executing machine and the Firebase REST API (which this library relies on) and on the amount of data that is transmitted.

If the same operation performs better with one of the offical SDKs (https://firebase.google.com/docs/admin/setup) and speed is an issue, you should use one of those.

For comparison, you could try the same operation the Firebase CLI Tools (https://github.com/firebase/firebase-tools).
