### ISSUE TITLE
how to set FIREBASE_CREDENTIALS and GOOGLE_APPLICATION_CREDENTIALS ERROR 

### ISSUE THREAD

**Issue by dhamechavivek** [kreait/firebase-php#116]
#### 1. Which version of `kreait/firebase-php` are you using?

versions : * 3.1.2

#### 2. Which version of PHP are you using?

7.0.23

#### 3. What's the issue?

how to verify FIREBASE_CREDENTIALS and GOOGLE_APPLICATION_CREDENTIALS ?
i am using google cloud appengine to deploy my laravel app that is using kreait/firebase-php. but i have error like

#### 4. Code that lead to the issue

Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "FIREBASE_CREDENTIALS" is not set.
Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "GOOGLE_APPLICATION_CREDENTIALS" points to "/var/www/html/laravel_fb/productfinder-179211-firebase-adminsdk-pl475-58753ec78c.json", but has errors: /var/www/html/laravel_fb/productfinder-179211-firebase-adminsdk-pl475-58753ec78c.json does not exist.
Kreait\Firebase\ServiceAccount\Discovery\FromGoogleWellKnownFile: The well known file is not readable or invalid

**Comment by richard457** [comment]
Any update to this issue?

**Comment by Mantas0726** [comment]
@dfquicazanr 's answer worked like charm, thanks dude
