### ISSUE TITLE
Support Firestore

### ISSUE THREAD

**Issue by jeromegamez** [kreait/firebase-php#117]
See https://firebase.googleblog.com/2017/10/cloud-firestore-for-rtdb-developers.html

**Comment by aloisejulian** [comment]
Yess! we want support for firestore... Do we have a estimate date? Thanks!!

**Comment by ChrisSmith5** [comment]
Any update on Firestore? Very excited for this new feature!

**Comment by jeromegamez** [comment]
Unfortunately I cannot provide an ETA for new features - I am working on this library in my limited free time and (unfortunately 😅) quite picky/thorough with new code, so this will certainly take some time.

**Comment by aloisejulian** [comment]
@jeromegamez thanks! i will wait for the release. Meanwhile i will use firebase

**Comment by anelad** [comment]
Even you cannot give an exact ETA, can you say something like in 3 months or in 5 months? We will start to implement my project in 2 weeks, so I need to know if I need to do some changes on project's design. Thank you.

**Comment by etopian** [comment]
here is a class to get you on your way.
https://gist.github.com/jasonbyrne/6b63e7d59c5ed97ef95ff2c78791cfae

**Comment by P110** [comment]
+1 for this feature if possible!

**Comment by P110** [comment]
Sidenote: For anyone wanting to do this before we get support in this SDK you might be able to use this, I'm going to try and use it later on today to see how stable it is.

**Comment by riyuk** [comment]
The (huge) downside of the googlecloudplatform framework is that it requires the gRPC extension which you normally dont get on a shared hosting

**Comment by jeromegamez** [comment]
Yep, that's why haven't looked deeper into that yet. Just exposing the googlecloudplatform implementation with `getFirestore()` in the `Firebase` class would be easy enough - but as you said, this would require everybody to install the gRPC extension.

On the other hand, I'm not really keen on re-implementing everything here 😅.

On the other other hand it should also be not too much of a problem to use both in tandem.

**Comment by morrislaptop** [comment]
As discussed in #198, Firestore is now supported in a separate package at https://github.com/morrislaptop/firestore-php

Which is standing on the shoulder of giants of this package :)

@jeromegamez Could you add to the readme?
