### ISSUE TITLE
Clarification on deprecated withServiceAccount() and withApiKey() methods

### ISSUE THREAD

**Issue by vigneshgurusamy** [kreait/firebase-php#121]
#### 1. Which version of `kreait/firebase-php` are you using?

Version 3.2

#### 2. Which version of PHP are you using?

PHP 7.1.9

#### 3. What's the issue?

Methods like `withServiceAccount()` and `withApiKey()` were deprecated in favour of new method `withServiceAccountAndApiKey()`. I'm only using firebase database feature, which can be accessed by using service account credentials, but the new method forces me to pass a web api key. Still I can work with this new method by passing an empty string instead of api key.

Could you tell me why those methods are deprecated?

It doesn't make sense with method name which has service account & api key but I only pass one proper value.

Can you bring back those deprecated methods?

**Comment by jeromegamez** [comment]
I was planning on removing those methods in the next major version to reduce some complexity in the library. At the moment, I have to check whether the API key is set when Auth features are being used. Performing requests in the name of a given user(-id) is more complex this way as I have to maintain two different authentication methods.

But I understand and respect your valid point and will undeprecate the methods in the next minor release.

**Comment by vigneshgurusamy** [comment]
@jeromegamez Thanks for your understanding. Eagerly waiting for next minor release.

**Comment by jeromegamez** [comment]
@vigneshgurusamy Here it is: https://github.com/kreait/firebase-php/releases/tag/3.2.1 \o/
