### ISSUE TITLE
Support Firebase Cloud Messaging (FCM)

### ISSUE THREAD

**Issue by jeromegamez** [kreait/firebase-php#126]
See https://firebase.google.com/docs/cloud-messaging/send-message

**Comment by spitcat** [comment]
+1

**Comment by aloisejulian** [comment]
We have a ETA for this?

**Comment by webleaf** [comment]
+1

**Comment by lashae** [comment]
@jeromegamez Hi, It's me again :-)

Is there any plan for this issue? 

I have an immediate requirement on FCM, I started evaluating possible implementations and I may contribute back to this lovely repo if you like and I can accomplish :-)

**Comment by jeromegamez** [comment]
@lashae @webleaf @aloisejulian @spitcat @gyimgabor @JulienSopheos, @michael-wolfram Please have a look at #189 - it's really early progress, and I currently can't test if and how the messages arrive at the clients (I only see that the API doesn't return an error), but if you test and engage, I am sure we can bring the topic forward rather sooner than later :)

**Comment by lashae** [comment]
@jeromegamez I would like to give it a shot, as soon as I have an available time slot ;-) By the way, thank you for your efforts for keeping things going ;-)

**Comment by jeromegamez** [comment]
Released with [4.5.0](https://github.com/kreait/firebase-php/releases/tag/4.5.0), Documentation can be found at https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html 🎉
