### ISSUE TITLE
Problem with persistent session

### ISSUE THREAD

**Issue by corocraft** [kreait/firebase-php#134]
Hello,

Thank you very much for the SDK has been very useful but i don't know how to keep the user logged in.
I log in without problems with email and password:

```
$serviceAccount = ServiceAccount::fromJsonFile($ruta);
        $firebase = (new Factory)
            ->withServiceAccountAndApiKey($serviceAccount, $apiKey)
            ->create();
        $auth = $firebase->getAuth();
```

```
        try{    
            $user = $auth->getUserByEmailAndPassword($user, $pass);
            $userConnection = $firebase->asUser($user);
            }catch(\Exception $e){
                $errores['user'] = $e->getMessage();
                return Redirect::to('/')->withErrors($errores)->withInput();
        }
```

but how should I keep the session in another view or controller? 

I thought I could save the token and uuid that I got with getUserByEmailAndPassword ($user, $ pass) in a localstorage, session or cookie and then use them in the requests but I think that is not the correct way.

Could you help me with this please?

Thank you.

**Comment by jeromegamez** [comment]
Depending on the framework you're using, you could keep the `$user` instance in the session.

In general, I would recommend to not use the Admin SDK to login the user - log them in with a Firebase Web Library, retrieve the ID Token in the browser and pass the ID token to the backend. You can then just get the user's UID from the ID token (https://firebase-php.readthedocs.io/en/stable/authentication.html#working-with-tokens-directly) and use the `Firebase::asUserWithClaims()` method (I marked it as deprecated, but it still works, I will provide a way to use the ID Token directly in an upcoming release).

I hope this helps at least a little!

**Comment by jeromegamez** [comment]
Here's a code snippet for that:

```php
use Kreait\Firebase\Auth\User;

$idTokenString = 'ID token string from your frontend application';
$idToken = $firebase->getAuth()->verifyIdToken($idTokenString);
$user = User::create($idToken);
```

**Comment by jeromegamez** [comment]
As it is not an issue with the library itself and not a feature that will be included, I'll close this issue now. You're welcome to join the Firebase Community Chat, perhaps this is a challenge that others would like to discuss with you.
