### ISSUE TITLE
firebase cloud firestore

### ISSUE THREAD

**Issue by winglovecola** [kreait/firebase-php#137]
#### 1. Which version of `kreait/firebase-php` are you using?

*You can use `composer show kreait/firebase-php` to see the installed version in the `versions` line.*

#### 2. Which version of PHP are you using?

*You can use `php -v` on the system the issue occurs on to get the PHP version.* 

#### 3. What's the issue?

*Please don't just copy and paste a PHP exception trace.*

#### 4. Code that lead to the issue

*Please use [syntax highlighted code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) with code that can be used to reproduce the issue.*

https://guides.github.com/features/mastering-markdown/

**Comment by winglovecola** [comment]
Hello Jérôme,

   thank you for making the firebase PHP admin SDK. It is very useful for PHP developer. I'm wondering by any chance will you going to add the new cloud firestore functions into the admin SDK soon? 

Best regards,
Wing.

**Comment by bennyt2** [comment]
See Issue #117. Looks like it's in progress but no ETA at this time.

**Comment by jeromegamez** [comment]
It's not in progress (just an item in my todo list), but indeed a duplicate 😅.
