### ISSUE TITLE
Mismatch token timestamp web client and php server cause exception

### ISSUE THREAD

**Issue by alexswe1** [kreait/firebase-php#139]
I am using version 3.5 of the library. The issue is that the timestamp on the client with firebase web and the timestamp on the php server is mismatched and that causes an exception to be thrown when validating token in php. See details below:

On the client i get the token with:

```javascript
fbase_auth.currentUser.getIdToken(true)
  .then((token) => {
        // return token
});
```

On the php server i run this code:

```php
public function getUserFromTokenId($idTokenString) {
   $idToken = $this->auth->verifyIdToken($idTokenString);
   $uid = $idToken->getClaim('sub');			
   return $this->auth->getUser($uid);		
}
```

With the $idTokenString sent in from the client.

When running verifyIssuedAt in IdTokenVerifier class i get the error message:

"This token has been issued in the future."

The problem is that inside that code you have:

```php
private function verifyIssuedAt(Token $token)   {
    if (!$token->hasClaim('iat'))  {            
        throw new InvalidIdToken('The claim "iat" is missing.');
     }

     if ($token->getClaim('iat') > time())  {  // this fails..			
        throw new InvalidIdToken('This token has been issued in the future.');        
   }    
}
```

The problem is as mentioned that the token from the client is in the future compared to the timestamp on the server. The test i ran the timestamp (from clock) on the server was 5 minutes slower then on client, so mismatch in timestamp caused it to not work (exception thrown)..

**Comment by jeromegamez** [comment]
Hey @alexswe1! Thank you for your report - this seems to be the same issue as in #140 - if you agree, I'd like to close this issue and we can continue the discussion over there, where I already added a proposal to work around this issue: https://github.com/kreait/firebase-php/issues/140#issuecomment-350273278

**Comment by alexswe1** [comment]
Yes, same issue, although I reported it first.

On Fri Dec  8  9:18 , Jérôme Gamez <notifications@github.com> sent:

>Hey @alexswe1! Thank you for your report - this seems to be the same issue as in #140 - if you agree, I'd like to close this issue and we can continue the discussion over there, where I already added a proposal to work around this 
issue: #140 (comment)
>
>—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>  
>  
>
>
>
>
>{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kreait/firebase-php","title":"kreait/firebase-php","subtitle":"GitHub 
repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kreait/firebase-php"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jeromegamez in #139: Hey @alexswe1! Thank you for your report - this seems to be 
the same issue as in #140 - if you agree, I'd like to close this issue and we can continue the discussion over there, where I already added a proposal to work around this issue: https://github.com/kreait/firebase-
php/issues/140#issuecomment-350273278"}],"action":{"name":"View Issue","url":"https://github.com/kreait/firebase-php/issues/139#issuecomment-350273621"}}}

**Comment by jeromegamez** [comment]
Continued in #140

**Comment by jeromegamez** [comment]
[4.9.0](https://github.com/kreait/firebase-php/releases/tag/4.9.0) ([Documentation](https://firebase-php.readthedocs.io/en/latest/authentication.html#verify-a-firebase-id-token)) should fix the issue for special use cases.
