### ISSUE TITLE
Access ApiClient's client property

### ISSUE THREAD

**Issue by FouadRaheb** [kreait/firebase-php#141]
It would be useful to have the `client` property in `ApiClient` class set to `public` so we can create custom requests.

I currently have it set to `public` in order to request user data through `getAccountInfo` and I'm handling the exceptions manually.

```
try
{
    $userDataResponse = $apiClient->client->request(RequestMethod::METHOD_POST, 'getAccountInfo', ['json' => array_filter([
        'idToken' => (string)$idToken,
        'returnSecureToken' => true,
    ])]);		
}
catch (\Exception $e) 
{
    $message = $e->getMessage();
    if ($e->getResponse() && JSON::isValid($responseBody = (string) $e->getResponse()->getBody())) {
        /** @noinspection ExceptionsAnnotatingAndHandlingInspection */
        $errors = JSON::decode($responseBody, true);
        $message = $errors['error']['message'] ?? $message;
    }
    
    if ($message == 'INVALID_ID_TOKEN') {
        echo 'Invalid Token';
    }
    else if ($message == 'USER_NOT_FOUND') {
        echo 'User Not Found';
    }

}
```

**Comment by jeromegamez** [comment]
You can always fork the SDK and open it up as you wish. I am aware that in its current state, the library and its functions are far from complete compared to the official SDKs, but everything that is available works as advertised and I feel comfortable maintaining it. Making the request method public would result in "my code isn't working" bug reports that are not coverable by my tests.

**Comment by FouadRaheb** [comment]
I totally understand, thanks for this useful SDK!
