### ISSUE TITLE
Fatal error: Uncaught Kreait\Firebase\Exception\InvalidArgumentException: 

### ISSUE THREAD

**Issue by murugesh1** [kreait/firebase-php#142]
I have just write webservice use for  firebase . i just follow this link 
 https://firebase-php.readthedocs.io/en/stable/overview.html. Everything is ok. Composer istall . But now i have this issue

Fatal error: Uncaught Kreait\Firebase\Exception\InvalidArgumentException: /opt/lampp/htdocs/firebase2/firebase/google-service-account.json ˓→ does not exist. in /opt/lampp/htdocs/firebase2/firebase/src/Firebase/ServiceAccount.php:122 Stack trace: #0 /opt/lampp/htdocs/firebase2/firebase/test.php(7): Kreait\Firebase\ServiceAccount::fromJsonFile('/opt/lampp/htdo...') #1 {main} thrown in /opt/lampp/htdocs/firebase2/firebase/src/Firebase/ServiceAccount.php on line 122

How to fix this issue

**Comment by murugesh1** [comment]
kindly check and help me

**Comment by jeromegamez** [comment]
The exception message already tells you where the error is: `/opt/lampp/htdocs/firebase2/firebase/google-service-account.json does not exist` - you need to have a Service Account JSON File as per https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app and place it in the root directory of your project (-> `/opt/lampp/htdocs/firebase2/firebase`).

**Comment by murugesh1** [comment]
ok sir i noted but this is my firebase  website  url
https://firebase.google.com/docs/admin/setup#workarea-cb10b
This is haved only node.js,java,python only. there is no javascript?How can i find my json file

**Comment by jeromegamez** [comment]
The code snippets above the button are just code examples.

https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app also applies to this library. If you follow the steps and click on the "Generate new private key" button, it will download the JSON file.

**Comment by murugesh1** [comment]
ya its working.thank you sir

**Comment by murugesh1** [comment]
hai sir,

   this is my firebase code, i have to sent multiple values updat ein fire base database, But now update only one value in firebase database .How to update multiple values in database ,This is my code
	                                                           $database = $firebase->getDatabase();
										$newPost = $database
										->getReference('drivers_request')
										->set([
										$driver_id  => $res_driver
										]);
										$newPost->getKey(); 
										$newPost->getUri();
										$newPost->getValue(); 


$driver_id  => $res_driver  this is my dynamic values

**Comment by jeromegamez** [comment]
There is no method to update multiple fields in the database at once, you will have to iterate over the values yourself.

**Comment by murugesh1** [comment]
ya i will check sir

**Comment by murugesh1** [comment]
hai sir,
   How to remove firebase in updated data,Below is my firebase updated data,structure,Here is any possible


drivers_request
       8
            TotalAmount: "0"
           TotalDistance: 0.0296
           title: "Service Complete"

**Comment by murugesh1** [comment]
hai sir

Is it is any possible to  get firebase in database value using php

**Comment by jeromegamez** [comment]
I don‘t understand the question :). But please feel free to join the Firebase Slack community (Link in the readme) for help from more people on how to interact with Firebase.
