### ISSUE TITLE
create user feature

### ISSUE THREAD

**Issue by pavankumarkatakam** [kreait/firebase-php#143]
#### 1. Which version of `kreait/firebase-php` are you using?
3.7.0

#### 2. Which version of PHP are you using?
7.0

#### 3. What's the issue?
It is not an issue but a feature request, that node js sdk of firebase createUser and updatedUser features. But this package doesn't have so I request to add that if possible

**Comment by jeromegamez** [comment]
There are methods to create users and update certain user properties, you can find the documentation at http://firebase-php.readthedocs.io/en/stable/user-management.html

More user management features are planned, unfortunately I can't provide you with a timeline.

**Comment by pavankumarkatakam** [comment]
Yeah I have already seen that doc, But I'm actually looking for **createUser** with more details like **displayName**, **photoUrl**, email and emial verified

**Comment by pavankumarkatakam** [comment]
I actually make the request method public and tried to post the request with valid json but it is throwing the error "Operation Not allowed"

`$auth->getApiClient()->request('signupNewUser',['json'=>['uid'=>'pavankumar','email'=>'katakampavan.btech@gmail.com','emailVerified'=>true,'displayName'=>'PavanKumar']])`

**Comment by pavankumarkatakam** [comment]
I changed a little bit that already you are keeping the `json` so i removed and checked now it is working fine, the only thing is we need to make the request method in `ApiClient` as `public`. Think about that?

**Comment by jeromegamez** [comment]
As I want to keep the SDK in the spirit of "it is not able to do everything, but what it does, it does well", I will not make the `request` method public, because this would expose this project to issues like in your previous comment "I tried `->request(...)` and it didn't work".

Of course you are free to fork the library and change everything as you see fit ^^

**Comment by pavankumarkatakam** [comment]
Ok, I like your spirit. I will make modifications, for now, maybe i can give a pull request keeping extra functions without changing to the public. Thank you for the repo.
