### ISSUE TITLE
composer update error

### ISSUE THREAD

**Issue by ronaldofreitas** [kreait/firebase-php#145]
after run 'composer update' on terminal:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 72 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.2.0) Downloading: 100%         
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/html/firebase-php/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 95

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/www/html/firebase-php/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 95

**Comment by jeromegamez** [comment]
I can't confirm this problem. However, the "syntax error" indicates that you are running PHP < 7.0.

**Comment by ronaldofreitas** [comment]
Yes true. I'm using PHP 5.6, maybe this is the problem. Thank you.

**Comment by jeromegamez** [comment]
You're welcome! If you're on PHP 5.6, you can use the 1.x branch of the repo: https://github.com/kreait/firebase-php/tree/1.x
