### ISSUE TITLE
How to get data from Firebase database using PHP?

### ISSUE THREAD

**Issue by murugesh1** [kreait/firebase-php#146]
Hai sir,
I am working now firebase in php, Every thing good . my data's  add in firebase database. Now is it is any possible   to get and display firebase in databse values using php.

**Comment by jeromegamez** [comment]
Please read the documentation on how to retrieve data from Firebase: https://firebase-php.readthedocs.io/en/stable/realtime-database.html#retrieving-data , and join the #php channel in the Firebase Community Slack at https://firebase-community.appspot.com/ where you can get help from other users of the library.

I would like to kindly ask you to not post support/usage questions as issues on the repository - the issues are meant for problems in the library's code base, so if something doesn't or if there's a missing feature. Thank you!
