### ISSUE TITLE
How to use ajax for moving marker in php jquery javascript

### ISSUE THREAD

**Issue by murugesh1** [kreait/firebase-php#148]
Hi,
i am already hered this question,He is answered this question inthis link

https://github.com/kreait/firebase-php/issues/147

But  Sir i have one doubt ,Above i have define my question in fire base is not required. Because i haved all values getted from fire base database.i want now fetch multiple lat long in google map, And move thats is all. its use only javascript and jquery?

,I am using google map marker for show purpose..I want to show move the marker after adding new latitude, longitude point in firebase,I am working now web service for android and ios apps.
(in firebase) file without refreshing the page means i want to show live tracking.. after adding new coordinates in firebase or updated without refreshing the page marker move from before location to new location... please give me some idea or ajax code.....Here is my code

My index file:
                                <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
                          <script src="https://maps.googleapis.com/maps/api/js?key=mykey"></script>

                    <script type="text/javascript">

                    onload = function(){

                    setInterval(function(){
                    $.ajax({
                    type: 'json',
                    url: 'google-ajax.php',
                    cache: false,
                    data: $('#dvMap').serialize(),
                    dataType: 'json',
                    success: function(data){
                    var markers =data;

                    var mapOptions = {
                    center: new google.maps.LatLng(markers[0].lat, markers[0].lng),
                    zoom: 10,               
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                    };

                    var map = new google.maps.Map(document.getElementById("dvMap"), mapOptions);

                    var infoWindow = new google.maps.InfoWindow();

                    var lat_lng = new Array();

                    var latlngbounds = new google.maps.LatLngBounds();

                    for (i = 0; i < markers.length; i++) {
                    var data = markers[i]
                    var myLatlng = new google.maps.LatLng(data.lat, data.lng);
                    lat_lng.push(myLatlng);
                    var marker = new google.maps.Marker({
                    position: myLatlng,
                    map: map,
                    title: data.title,
                    icon:"images/carnew.svg"
                    });
                    latlngbounds.extend(marker.position);
                    (function (marker, data) {
                    google.maps.event.addListener(marker, "click", function (e) {
                    infoWindow.setContent(data.description);
                    infoWindow.open(map, marker);
                    });
                    })(marker, data);
                    }
                    map.setCenter(latlngbounds.getCenter());
                    map.fitBounds(latlngbounds);

                    }
                    });

                    },10000);
                    }

                    /*$(document).ready(function(){

                    onload(); //Call auto_load() function when DOM is Ready

                    });

                    //Refresh auto_load() function after 10000 milliseconds
                    setInterval(onload,10000);*/
                    </script>

                    </div>

                    <div id="dvMap"></div>

-----------------------------------------------------------------------

My ajax file:
                                    <?php
                                     session_start();
                                     include('functions/myClass.php');
                                     include('functions/config.php');
                                        include('functions/functions-new.php');
                                           require __DIR__.'/webservice/firebase/firebaserequire.php';

             $connection = new createCon();
               $connection->connect();

    $database = $firebase->getDatabase();
       $newPost = $database
     ->getReference('drivers_location');
     $locations=$newPost->getValue(); 

     $count=count($locations);

     if($count > 0)
       {
	$i = "0";

	foreach ($locations as $category => $value) {

	     foreach ($value as $key => $var) 
	     {

	                foreach ($var as $key => $finalresult)
	                 {
	                    if($key == "l"){
	                        $finalData[$i]['description'] = $category;
	                        $finalData[$i]['lat'] = $finalresult['0'];
	                       $finalData[$i]['lng'] = $finalresult['1'];
	                       $i++;        
	                    }   
	                    
	                        
	                 }
	     }
	} 
	$finalData = json_encode($finalData); 

	echo $finalData;

                   }
                   else
                    {
	     echo "There is no location";
                        }
                      ?>
Thanks in advance...

**Comment by jeromegamez** [comment]
Dear @murugesh1, the issue section of this repository is only for errors in this library or requests for missing features, not for questions regarding custom applications. This will not change just because you rephrase your question a little bit :).

The right place for your questions are stackoverflow (https://stackoverflow.com/questions/tagged/firebase) and https://firebase.community . When you post your question there, also make sure that the formatting of your code examples works - as you can see above, the code is not fully formatted to be readable (monospace vs non-monospace, indentation).

Again: if you want to react in realtime to changes in your Firebase database, don't use an *Admin* SDK, use the official *Client* SDKs instead. You can find everything you need in the official Firebase documentation, for instance at https://firebase.google.com/docs/database/web/read-and-write#listen_for_value_events
