### ISSUE TITLE
verify method now expects token instead of  string

### ISSUE THREAD

**Issue by hernandev** [kreait/firebase-php#152]
#### 1. Which version of `kreait/firebase-php` are you using?

`3.8.1`

#### 3. What's the issue?
Introduced on 3.8.1, `$auth->verifyTokenId()` method id no longer expecting a string but a `\Lcobucci\JWT\Token` instance.

----
I'll provide a PR for it on the next couple hours.

Thanks

**Comment by jeromegamez** [comment]
@hernandev Thank you again for the fast discovery and pointing into the right direction!

resolved [3.8.2](https://github.com/kreait/firebase-php/releases/tag/3.8.2)

**Comment by hernandev** [comment]
:+1:
