### ISSUE TITLE
This method is deprecated and will be removed in the next major release 3.9.0 

### ISSUE THREAD

**Issue by testdnmedia** [kreait/firebase-php#154]
please help me to fix this. 
`use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/database-pos-firebase-adminsdk-kxrn0-be13a9eb0c.json');
$firebase = (new Factory)
       ->withServiceAccount($serviceAccount)
        ->create();
$db = $firebase->getDatabase();`

"This method is deprecated and will be removed in the next major release."
how do i solve it ?

**Comment by bevss** [comment]
I'm also getting this error. Looks like issue with "withTokenHandler" function in Firebase.php.

    public function __construct(
        ServiceAccount $serviceAccount,
        UriInterface $databaseUri,
        TokenHandler $tokenHandler = null,
        Firebase\Auth $auth = null,
        Factory $factory = null
    ) {
        $this->databaseUri = $databaseUri;
        $this->tokenHandler = $tokenHandler;
        $this->auth = $auth;

        $factory = ($factory ?: new Factory())
            ->withServiceAccount($serviceAccount)
            ->withDatabaseUri($databaseUri)
            ->withTokenHandler($tokenHandler); // here!

        $this->factory = $factory;
    }

Can someone explain what happen here? I've manage to work it by removing the "->withTokenHandler"

**Comment by jeromegamez** [comment]
That's not an error, it's a deprecation notice that should be muted on a production system. But you're right that it is unnerving in the development environment. I will create a new release shortly that fixes it.

**Comment by jeromegamez** [comment]
To be clear: this *is* my mistake - I shouldn't have deprecated the method and still use it :)

**Comment by jeromegamez** [comment]
@testdnmedia @feridi94 Please update to [release 3.9.1](https://github.com/kreait/firebase-php/releases/latest) and see if that helps.
