### ISSUE TITLE
Type error: Return value of Kreait\Firebase\Exception\ApiException::getRequest() must implement interface Psr\Http\Message\RequestInterface, null returned

### ISSUE THREAD

**Issue by VovikeMS** [kreait/firebase-php#155]
#### 1. Which version of `kreait/firebase-php` are you using?

`3.8.2`

#### 2. Which version of PHP are you using?

`7.1.4`

#### 3. What's the issue?

Sometimes Firebase Realtime Database return 503 status code.

When i try to retrieve the request or response instance from `Kreait\Firebase\Exception\ApiException`instance on the `catch` block when this exception was throwed if request to Firebase Realtime Database returned with HTTP status 503 it throw a type error: `Type error: Return value of Kreait\Firebase\Exception\ApiException::getRequest() must implement interface Psr\Http\Message\RequestInterface, null returned`.

I cannot investigate why RDB return 503 sometimes because cannot get original request and response.

#### 4. Code that lead to the issue

```php
try {
    $db->getReference('/path')->getValue();
} catch (\Kreait\Firebase\Exception\ApiException $exception) {
    $exception->getRequest()->getBody()->getContents();
}
```

**Comment by jeromegamez** [comment]
@VovikeMS Thank you for taking the time to report this issue! Please update to [v3.9.2](https://github.com/kreait/firebase-php/releases/tag/3.9.2), this should solve the issue.

**Comment by VovikeMS** [comment]
@jeromegamez Thanks a lot for your great job 👍
