### ISSUE TITLE
Is it possible to do a bulk insert?

### ISSUE THREAD

**Issue by kiwo12345** [kreait/firebase-php#158]
I am inserting one row to firebase using laravel 5.4 like this:

```
try {
             app('firebase')->getDatabase()->getReference('items/'.$newItem->id)->set([
             'blabla' => 'something',
             'blabla' => 'something',
             'blabla' => 'something',
        ]);
         } catch (\Kreait\Firebase\Exception\FirebaseException $e) {
             //Log error
         }
```

This will insert one record into Firebase, but I was wondering if its possible to insert many records at the same time since this will save me some requests.

Eg in Laravel I can do a bulk insert by passing an array containing items to my inert() like this:

```
\App\Example::insert([
    [
        'name' => 'abc',
        'value' => '123',
    ],
    [
        'name' => 'def',
        'value' => '456',
    ],
    // etc...
]);
```

Is there any way I can do something like this in kreait/firebase-php?

Thanks for a great lib.

**Comment by jeromegamez** [comment]
I assume different data (because it's not possible to have an array with multiple entries with the same key ('blabla').

Try this:

```php
$updates = [];
foreach ($items as $item) {
    $updates['item_'.$item->id] = [
        'title' => $item->title,
        'body' => $item->body
    ];
}

app('firebase')->getDatabase()->getReference('items')->update($updates);

**Comment by jeromegamez** [comment]
I’m closing this issue now because it isn’t related to a problem/bug in the library itself, but feel free to add further comments.

**Comment by kiwo12345** [comment]
@jeromegamez yes it was a typo it should be:

```
try {
             app('firebase')->getDatabase()->getReference('items/'.$newItem->id)->set([
             'text' => '$newItem->sometext',
             'catid' => '$newItem->catid',
             'type' => '$newItem->type',
        ]);
         } catch (\Kreait\Firebase\Exception\FirebaseException $e) {
             //Log error
         }
```

I could not get your example to work. I dont know if its because you used `update` instead of `set` although I am inserting new items and not updating items that exist.

Or I dont know if your example puts everything under "item" ?

I need to insert mutliple items in firebase like

/item/2
/item/3
/item/4
/item/5

**Comment by jeromegamez** [comment]
The example worked for me, though... are you using a 3.x release? Or are you on PHP <7, which would mean you‘re using the 1.x release.

I know „update“ seems not the right command at first, but it‘s the same way with the other, official libraries, and called „multi path updates“: https://firebase.google.com/docs/database/admin/save-data
