### ISSUE TITLE
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException : Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `400 Bad Request`

### ISSUE THREAD

**Issue by sharang26071994** [kreait/firebase-php#163]
#### php ^ 7

PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException : Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `400 Bad Request` response:
{
 "error": "invalid_grant",
 "error_description": "Invalid JWT: Token must be a short-lived token (60 minutes) and in a (truncated...)
 in /home/mantrasc/public_html/test/testlogin/testlogin/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/mantrasc/public_html/test/testlogin/testlogin/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/mantrasc/public_html/test/testlogin/testlogin/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/mantrasc/public_html/test/testlogin/testlogin/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/mantra in /home/mantrasc/public_html/test/testlogin/testlogin/vendor/kreait/firebase-php/src/Firebase/Exception/QueryException.php on line 38

**Comment by jeromegamez** [comment]
It’s hard to help if you don’t provide the code that led to the issue :)

**Comment by jeromegamez** [comment]
But the error message is already telling: invalid_grant. Are you sure you are using the correct service account JSON file?

**Comment by sharang26071994** [comment]
Sorry, for not providing the code. Everything thing was working fine on my localhost. But when i hosted it on web, it is giving me this error in error_logs.
Is there any extra token or credentials required for hosting on web ? 

$data = $_POST;
require __DIR__ . '/vendor/autoload.php';
use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__ . '/secret/firebase_credentials.json');
$firebase       = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->create();

$database  = $firebase->getDatabase();
$reference = $database->getReference('Users');

**Comment by jeromegamez** [comment]
Strange... no, the environment should not matter. Do you use different service accounts for each environment? If so, are the permissions for both service accounts the same? You can check in the google developer console.

If everything looks ok to you, try generating a new key for your server environment in the Firebase project settings.

**Comment by sharang26071994** [comment]
Is solved. 
Sorry, the issue wasn't in your code. The host system timings were wrong. 

Thanks for the awesome Library and support.

**Comment by jeromegamez** [comment]
Glad to hear that it is solved, and thank you for the kind words! 🌺

**Comment by hacktisch** [comment]
Thanks for the tip guys,
I fixed it permanently on my (Centos) server by setting up automatic time synchronization with the NTP service:

`yum install ntp`
`systemctl start ntpd`
`systemctl enable ntpd`
`ntpdate -q 0.rhel.pool.ntp.org`
`systemctl restart ntpd`
