### ISSUE TITLE
Error getting reference

### ISSUE THREAD

**Issue by ThallyssonKlein** [kreait/firebase-php#166]
I'm trying to get a reference from my database, but It's result in an error, see it:

![image](https://user-images.githubusercontent.com/16887598/36172043-d8af6356-10eb-11e8-9330-2c25477b030f.png)

That's my code:

```
<?php
require __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromArray(
  array('project_id' => 'kapp-a7ea2',
        'client_id' => '139118961877-t5hnajp1ido24a226278irvam7hhf4sd.apps.googleusercontent.com',
        'client_email' => 'thallyssonklein@gmail.com',
        'private_key' => '*******',
  )
);
$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->withDatabaseUri('https://kapp-a7ea2.firebaseio.com')
    ->create();

$database = $firebase->getDatabase();

$rasteira = $database->getReference('/kapp-a7ea2/movements/Rasteira');

echo $rasteira->getValue();
//$website = 'https://api.telegram.org/bot530496822:AAEa8Xq5LMAA7_qKbEk0rlPK9cSMLDZB3cA/sendMessage?chat_id=270877409&text=';
?>
```

Someone can to help me to understand what's happening here?

**Comment by jeromegamez** [comment]
It looks like an OpenSSL error on your remote machine. Please make sure that you have a recent version of OpenSSL is installed on the machine, and that PHP has the OpenSSL extension installed (you can check that with `php -m` or by looking at the output of `phpinfo()` in a browser).

**Comment by jeromegamez** [comment]
Also, please remove the value of your private key from your code snippet, otherwise someone could grab it and access your Firebase project.

**Comment by ThallyssonKlein** [comment]
I'm deploying this application on Heroku and I can't to verify and install if isn't installed. Does not possible to add it on composer.json to be installed on deploy?

**Comment by jeromegamez** [comment]
It was obviously too late for me yesterday, so I didn't read the error message carefully enough 😅. It says "supplied key param can not be coerced into a private key", which is an indication for your private key not being correct.

You must use the key provided in the service account JSON file that you can download from your Firebase project settings. The private key starts with `-----BEGIN PRIVATE KEY-----\n` and ends with `\n-----END PRIVATE KEY-----\n`.

**Comment by ThallyssonKlein** [comment]
Thank you, It's resolved. I found the service accounts tab and generated the file.
