### ISSUE TITLE
Help error

### ISSUE THREAD

**Issue by idlana** [kreait/firebase-php#172]
![tr](https://user-images.githubusercontent.com/18338607/36638314-5c80bdf6-1a24-11e8-8732-9fec820bc742.png)

how to solve this? I use php 7.1

thanks 😄

**Comment by jeromegamez** [comment]
To be honest, I'm seeing this kind of error for the first time 😅. I just tested requiring the SDK in a new directory myself and as it worked fine, there are just some suggestions I have:

- Perhaps packagist.org was down at the time, so if you try it again now it might work
- Another possibility could be that the composer on your machine is outdated, please try `composer self-update` (Output should show version 1.6.3)

I don't have any more ideas at the moment, but please let me know if you were able to resolve the issue.

**Comment by idlana** [comment]
oke work with
`git clone https://github.com/kreait/firebase-php.git && cd firebase-php && composer install`
thanks bro 👌
