### ISSUE TITLE
Feature request: create user only with uid as this is only required field

### ISSUE THREAD

**Issue by svycka** [kreait/firebase-php#175]
would be nice to be able to create new users with my uid not auto-generated by firebase.
from docs:
> The uid to assign to the newly created user. Must be a string between 1 and 128 characters long, inclusive. If not provided, a random uid will be automatically generated.

so should be really easy to implement this

**Comment by jeromegamez** [comment]
It's a little more complicated than this, but I hope to have something ready in a couple of days.

**Comment by svycka** [comment]
is it more complicated than adding method like this to `Kreait\Firebase\Auth\ApiClient`?
````php
    public function signupNewUserWithId(string $uid): ResponseInterface
    {
        return $this->request('signupNewUser', [
            'uid' => $uid,
        ]);
    }
````

**Comment by jeromegamez** [comment]
I am currently working on creating/updating users with all possible properties, not just creating a user with one single property, so, in the case of what I want to achieve with this library: yes :)

**Comment by svycka** [comment]
oh, okay :D

**Comment by jeromegamez** [comment]
@svycka Please have a look at https://github.com/kreait/firebase-php/pull/177, this should give you what you are looking for ^^

**Comment by svycka** [comment]
thanks, will try today

**Comment by svycka** [comment]
@jeromegamez thanks, #177 seems to work so far.
