### ISSUE TITLE
Creating custom token produces invalid JWT token

### ISSUE THREAD

**Issue by prmelehan** [kreait/firebase-php#179]
#### 1. Which version of `kreait/firebase-php` are you using?

4.x-dev

#### 2. Which version of PHP are you using?

7.1.7

#### 3. What's the issue?

When using the Firebase Auth `createCustomToken` method, the payload contains a token with an invalid signature. My service account instance points to the correct JSON file that I've been using in the rest of my project, but the JWT still says invalid signature on jwt.io and when I send the request to firebase via `firebase.auth().signInWithCustomToken(token)`

#### 4. Code that lead to the issue

```
$serviceAccount = ServiceAccount::fromJsonFile('auth/firebase/firebase-auth.json');

$firebase = (new Factory)->withServiceAccount($serviceAccount)->create();

$auth = $firebase->getAuth();
$token = $auth->createCustomToken("234234234234234");
$token = $token->getPayload(); // the result of this call returns a token string with an invalid signature

```

**Comment by jeromegamez** [comment]
Could you please try again with `$tokenString = (string) $token`? I'm on the road at the moment, but I am sure this should work.

The getPayload() method only returns the payload, so the header is missing.

**Comment by jeromegamez** [comment]
Yes, that was it :). I updated the documentation (https://github.com/kreait/firebase-php/commit/a9ebb94bbc1282d38e0822e0edf3bb28bdd0a94d) - thank you for hinting at the missing bit!

**Comment by prmelehan** [comment]
Works for me! Thanks
