### ISSUE TITLE
Syntax error on kreait\firebase-php\src\Firebase.php

### ISSUE THREAD

**Issue by Jkzyftw** [kreait/firebase-php#180]
#### 1. Which version of `kreait/firebase-php` are you using?
latest

#### 2. Which version of PHP are you using?

7.1

#### 3. What's the issue?

Syntax error on kreait\firebase-php\src\Firebase.php on line 33 unexpected ':', expecting ';' or '{'

#### 4. Code that lead to the issue

`public function getDatabase(): Database
    {
        return $this->database;
    }
`

can someone help with this

**Comment by jeromegamez** [comment]
Please check the environment you are running the code in - the error message indicates that you are not running it with PHP 7, but PHP 5.

**Comment by jeromegamez** [comment]
Also see: https://github.com/kreait/firebase-php/issues?utf8=%E2%9C%93&q=syntax+error

**Comment by Jkzyftw** [comment]
oh sure thanks a lot!
