### ISSUE TITLE
Typo'd method name in Storage -> getFileystem

### ISSUE THREAD

**Issue by Slessi** [kreait/firebase-php#182]
#### 1. Which version of `kreait/firebase-php` are you using?

4.1.2 (not fixed in 4.2.0)

#### 2. Which version of PHP are you using?

7.1.14

#### 3. What's the issue?

You misspelled `getFilesystem` as `getFileystem`

#### 4. Code that lead to the issue

https://github.com/kreait/firebase-php/commit/de214f928015034770ec21dbb04c36952d6138fd#diff-03020db82dcfbb102a957bc71f04e655R57

```php
public function getFileystem(string $bucketName = null): FilesystemInterface
```

**Comment by jeromegamez** [comment]
Good catch, thanks!
