### ISSUE TITLE
Auth->updateUser() works quite awkwardly with emailVerified while email is not provided

### ISSUE THREAD

**Issue by swayok** [kreait/firebase-php#183]
#### 1. Which version of `kreait/firebase-php` are you using?

4.21

#### 2. Which version of PHP are you using?

7.1

#### 3. What's the issue?

Auth->updateUser() is not working correctly with `emailVerified` when `email` is not provided.

Here is UpdateUser:
```
Kreait\Firebase\Request\UpdateUser::__set_state(array(
   'attributesToDelete' => 
  array (
  ),
   'uid' => 
  Kreait\Firebase\Value\Uid::__set_state(array(
     'value' => 'q7Tqp2eXBsdyOpgo2OgzJhSnbhC2',
  )),
   'email' => NULL,
   'displayName' => NULL,
   'emailIsVerified' => true,
   'phoneNumber' => NULL,
   'photoUrl' => NULL,
   'markAsEnabled' => NULL,
   'markAsDisabled' => NULL,
   'clearTextPassword' => NULL,
))
```
While json_encode() of this object generates: `{"localId":"q7Tqp2eXBsdyOpgo2OgzJhSnbhC2"}`

The reason is in EditUserTrait line 257 - it drops `emailVerified` silently causing time loss debugging this. 
I suggest to either remove this condition or throw exception because silent dropping is a bad idea that makes developers think that SDK is not working.

#### 4. Code that lead to the issue

```
if ($isVerified) {
     $updates = UpdateUser::new()->markEmailAsVerified();
} else {
     $updates = UpdateUser::new()->markEmailAsUnverified();
}
\FirebaseAdminSDK::getAuth()->updateUser($this->firebase_uid, $updates);
```

**Comment by jeromegamez** [comment]
@swayok Thanks for bringing this to my attention - please test #184, this should fix the issue.
