### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\RequestException

### ISSUE THREAD

**Issue by d3v3lop** [kreait/firebase-php#185]
#### 1. Which version of `kreait/firebase-php` are you using?
v4.2.0
*You can use `composer show kreait/firebase-php` to see the installed version in the `versions` line.*

#### 2. Which version of PHP are you using?
v7.0
*You can use `php -v` on the system the issue occurs on to get the PHP version.* 

#### 3. What's the issue?
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 56: SSL read: errno -5961 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /hosts/public_html/lib/FireBase/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187 Stack trace: #0 /hosts/public_html/lib/FireBase/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /public_html/lib/FireBase/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /hosts/public_html/lib/FireBase/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 /publi in /hosts/public_html/lib/src/Firebase/Exception/ApiException.php on line 40
*Please don't just copy and paste a PHP exception trace.*

#### 4. Code that lead to the issue
This issue is not persistent. This was reported one time by a user.
*Please use [syntax highlighted code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) with code that can be used to reproduce the issue.*

**Comment by jeromegamez** [comment]
Please check if https://firebase-php.readthedocs.io/en/latest/troubleshooting.html#curl-error-xx-ssl-certificate-validation-failed helps and https://github.com/kreait/firebase-php/issues?utf8=✓&q=ssl to see if there is something that can help - I'm afraid there is not much I can do from the code perspective.
