### ISSUE TITLE
Different exceptions thrown on same error

### ISSUE THREAD

**Issue by swayok** [kreait/firebase-php#186]
#### 1. Which version of `kreait/firebase-php` are you using?

4.2.2

#### 2. Which version of PHP are you using?

7.1

#### 3. What's the issue?

`Auth->getUser(), Auth->getUserByEmail(), Auth->getUserByPhoneNumber()` throw `UserNotFound` exception
`Auth->deleteUser()` and other ApiClient methods throw `AuthException` with message `'USER_NOT_FOUND'` from `ApiClient->request()`

I think it would be more consistent to throw `UserNotFound` exception from `ApiClient->request()` instead of `AuthException` with `'USER_NOT_FOUND'` message. 
Sometimes you don't actually need to know if there was an account in Firebase when you for example delete it. In this case filtering `UserNotFound` exceptions is the easiest way.

`UserNotFound` exception updates:

```
namespace Kreait\Firebase\Exception;

class UserNotFound extends OutOfBoundsException
{
    const IDENTIFIER = 'USER_NOT_FOUND';
}
```
Maybe it should extend `AuthException`? It seems related.

 in `AuthException`:

```
public static $errors = [
    ...,
    UserNotFound::IDENTIFIER => UserNotFound::class,
];
```

**Comment by jeromegamez** [comment]
Hey @swayok, and thanks for reporting this, good observation, I added the `UserNotFound` exception to the array of AuthExceptions as you suggested (see c6aeb812a899ced5b17faac892af30450a32069b)

Concerning the filtering of the exception if a deleted user hasn't been there in the first place, I will keep it the way it is: it's easier to filter those exceptions in your project code than to unfilter it in case you *do* need the information that a user wasn't there to begin with (aka [no hidden surprises](https://github.com/kreait/firebase-php/issues/183#issuecomment-376400639) :trollface:)

**Comment by swayok** [comment]
Thanks! That's better now =) I'm going to use SDK quite widely so I think there will be some more issues reported =) 

> Sometimes you don't actually need to know if there was an account in Firebase when you for example delete it. In this case filtering UserNotFound exceptions is the easiest way.

That was just example and I mean't exactly this:

> Concerning the filtering of the exception if a deleted user hasn't been there in the first place, I will keep it the way it is: it's easier to filter those exceptions in your project code than to unfilter it in case you do need the information that a user wasn't there to begin with (aka no hidden surprises :trollface:)

Just wanted `UserNotFound` exception to be thrown.
