### ISSUE TITLE
undefined setToken after token update ?

### ISSUE THREAD

**Issue by testdnmedia** [kreait/firebase-php#188]
I have a problem updating the token in firebase

firebase.auth().currentUser.getIdToken(/* forceRefresh */ true).then(function(idToken) {
  // Send token to your PHP backend via HTTPS
  // ...
}).catch(function(error) {
  // Handle error
});

[PROBLEM]
...
$firebase->setToken(idToken]);
Call to undefined method Kreait\Firebase::setToken()

is there any solution of my problem this. thank you

**Comment by jeromegamez** [comment]
Yes, there is. Please read the documentation on how to use this library, especially https://firebase-php.readthedocs.io/en/latest/authentication.html#verify-a-firebase-id-token
