### ISSUE TITLE
Very slow to get data

### ISSUE THREAD

**Issue by sgasser** [kreait/firebase-php#19]
I use the symfony-bundle - i think there is a problem with this main library.
If it's a problem in the bundle I will open the issue on the other repo.

With following code I have to wait > 15 sec to get the response:

```
$tokenGenerator = $this->firebase->getConfiguration()->getAuthTokenGenerator();
$token = $tokenGenerator->createToken($id, $provider);
$this->firebase->setAuthToken($token);
$user = $this->firebase->getReference('users/'.$userId)->getData();
```
Generating the token works very fast, but for the call
```
$this->firebase->getReference('users/'.$userId)->getData();
```
 I have to wait > 15sec.

The same request over to the firebase api: 
```
https://*.firebaseio.com/users/1.json?auth=123
```
takes < 300ms

In the next days i will take a look inside the library to find the problem.

Any Idea where is the problem or where do I make a mistake?

**Comment by sgasser** [comment]
It's a problem of my installed php 7.

**Comment by pathikvejani** [comment]
How to update status = 0 in firebase database where status = 1?

What I have tried is:

    <?php
    require __DIR__.'/vendor/autoload.php';
    use Kreait\Firebase\Configuration;
    use Kreait\Firebase\Firebase;
    $firebase = new Firebase('LINK', $configuration);
    $users = $firebase->get('/users');
    for ($i=0; $i < count($users) ; $i++) {
    	$data = array('status' => '0');
    	$nodeUpdateContent = $firebase->update(['status' => '1'],$users[$i].'/presence/status');
    	print_r($nodeUpdateContent);
    }
    ?>

But when I see in the firebase database, it is not updating anything. Why so?

I am following this link: [Firebase-php][1]


Update data using this link: [Update-data][2]

I am getting in `$users`:

    <?php
    [1] => Array
    (
    	[presence] => Array
    	(
    		[loginTimestamp] => 1460117596561
    		[status] => 1
    	)
    
    )
    
    [2] => Array
    (
    	[presence] => Array
    	(
    		[loginTimestamp] => 1460117596561
    		[status] => 1
    	)
    )
    
    [3] => Array
    (
    	[presence] => Array
    	(
    		[loginTimestamp] => 1460117596561
    		[status] => 1
    	)
    )
    
    ?>

I am getting response for this: <br>**$nodeUpdateContent = $firebase->update(['status' => '1'],$users[$i].'/presence/status');**

    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )

`It is just printing the status which value is 1, but not updating it.`

    getting error here: Array to string conversion --> $nodeUpdateContent = $firebase->update(['status' => '1'],$users[$i].'/presence/status');


  [1]: https://github.com/kreait/firebase-php/tree/c0adb0ced970b2a8a2968a7bf6f803786a2f7ca2
  [2]: https://github.com/kreait/firebase-php/blob/master/doc/firebase.md

Can you please help?
