### ISSUE TITLE
Call to undefined method Kreait\Firebase\RemoteConfig::getTemplate()

### ISSUE THREAD

**Issue by akashvarlani** [kreait/firebase-php#191]
#### 1. Which version of `kreait/firebase-php` are you using?

 * 4.4.0

#### 2. Which version of PHP are you using?

7.1.14

#### 3. What's the issue?

I just wanted to get my remote configs but when calling this method $remoteConfig->getTemplate(); i am getting undefined function error.

#### 4. Code that lead to the issue

$serviceAccount = ServiceAccount::fromJsonFile(public_path('MY-JSON-FILE.json'));
        $firebase = (new Factory)
            ->withServiceAccount($serviceAccount)
            ->create();
        $remoteConfig = $firebase->getRemoteConfig();

$template = $remoteConfig->getTemplate();
        echo json_encode($template, JSON_PRETTY_PRINT);

**Comment by jeromegamez** [comment]
Oops, this was an error in the documentation that I fixed with 8f2f8a8e687c7658511d54e20ea6187a0f8d2e26

The correct usage is `$remoteConfig->get()` to fetch the template and `$remoteConfig->publish()` to publish it.

Thanks for notification!
