### ISSUE TITLE
Questions about FCM support

### ISSUE THREAD

**Issue by lashae** [kreait/firebase-php#192]
Just before the release of messaging features on this library, the best bet of a PHP developer to utilize FCM capabilities was `redjanym/fcm-bundle`. And we used that bundle to feature messaging on our product. 

What we are doing via this bundle is as follows:
1. Subscribing 1 device to 1 certain topic.
2. Unsubscribing 1 device from 1 certain topic.
3. Subscribing n devices to 1 certain topic in a single request.
4. Unsubscribing n devices from 1 certain topic in a single request.
5. Send push notification to 1 device.
6. Send same push notification to n devices in a single request.
7. Send push notification to 1 certain topic.

After the relase of the FCM capabilities on this library (kreait/firebase-php) we would like to migrate since the bundle we have been using `redjanym/fcm-bundle` embraces **legacy** FCM protocol.

However we need to be sure that the above mentioned requirements are supported here. Especially, sending the same push notification to multiple devices in a single request is critical to us since nobody is a fan of network latency :-)

Could you please clarify which of the above items from 1 to 7 are supported in `kreait/firebase-php`?

**Comment by jeromegamez** [comment]
Hey @lashae, and thank you for your questions!

Currently, only (5) and (7) are supported by the library. With the FCM HTTP v1 API (which is the only one not marked as legacy on https://firebase.google.com/docs/cloud-messaging/server#choose ), (6) could be simulated by sending messages asynchronously, but this of course is not the same as sending one message to multiple recipients.

All other methods are currently not supported by the HTTP v1 API. There are two ways to go about this:

- The first is to wait until the HTTP v1 API supports the same methods as the legacy APIs and implement them step by step.
- The second is to use the HTTP v1 API in tandem with the legacy HTTP API - which is even suggested in the official docs, and replace the old calls with new ones once the newer API supports them.

The challenge here is that the request and response formats differ between the protocols, which makes it difficult for me to provide a unified (PHP-)API to work with. In the first step, I will probably just return the response messages as a decoded array (that's the current implementation) and try to come up to somehow with a way to "translate" messages between protocols.

As always, no ETA though 😅

**Comment by jeromegamez** [comment]
@lashae Please check out #200 - if this works and gets merged, (1) to (4) should be covered :)
