### ISSUE TITLE
ServiceBuilder dependency error

### ISSUE THREAD

**Issue by tux240** [kreait/firebase-php#194]
#### 1. Which version of `kreait/firebase-php` are you using?

Version 4.6.0

#### 2. Which version of PHP are you using?

PHP 7.2.3

#### 3. What's the issue?

Hello,

One of my dependencies (superbalist/flysystem-google-cloud-storage) requires usage of google/cloud-storage <1.4, not allowing a recent google/cloud to be installed.

I can install firebase-php 4.6.0 but get this error :
`Class 'Google\Cloud\Core\ServiceBuilder' not found  `
Should composer.json require a recent version of google/cloud ?

How can I can make flysystem-google-cloud-storage and firebase-php work ?

**Comment by jeromegamez** [comment]
The SDK requires the same library, but in version ^7.0 - if another dependency in your project requires version <1.4, this is a difference that cannot be bridged. If possible, try to update your other dependencies as much as possible or replace them with equivalents. Other than that there is not much we can do in the scope of the SDK. I could test it using older releases, but from 7.x down to 1.x is not likely to work.

**Comment by jeromegamez** [comment]
I'm closing this issue now because there is not much I can do in scope of this library, but feel free to add further comments if you'd like.
