### ISSUE TITLE
No way to remove phone number

### ISSUE THREAD

**Issue by swayok** [kreait/firebase-php#195]
#### 1. Which version of `kreait/firebase-php` are you using?

4.6.0

#### 2. Which version of PHP are you using?

7.1

#### 3. What's the issue?

Seems like there is no way to remove phone number

#### 4. Code that lead to the issue

`\FirebaseAdminSDK::getAuth()->updateUser($this->firebase_uid, ['phone' => null]);`

Throws `Type error: Argument 1 passed to Kreait\Firebase\Value\PhoneNumber::__construct() must be of the type string, null given`

Also I haven't found alternative way like `['deleteattribute' => 'phone']` (this one ignored) or `['deletephone' => true]` (this one not exists)

**Comment by jeromegamez** [comment]
Hey @swayok, you're right, this is currently not possible - but I just started working on it, I'll notify you once the release is ready.

**Comment by jeromegamez** [comment]
@swayok Here it is: https://github.com/kreait/firebase-php/releases/tag/4.7.0

**Comment by swayok** [comment]
Perfect! Thank you!
