### ISSUE TITLE
egeloen/http-adapter deprecated

### ISSUE THREAD

**Issue by dkvk** [kreait/firebase-php#20]
Would be nice to go over to httpplug.

This message is outputted when doing a `composer install/update`

`Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.`

**Comment by jeromegamez** [comment]
@dkvk Sorry for the late reply - I am currently rewriting the library using the official google api client (https://github.com/google/google-api-php-client) which relies on Guzzle, so this message should go away by then.

:octocat:
