### ISSUE TITLE
Call to undefined method Kreait\Firebase\Factory::getDatabase()

### ISSUE THREAD

**Issue by erixrevolver** [kreait/firebase-php#204]
<img width="717" alt="captura de pantalla 2018-06-01 a la s 23 34 48" src="https://user-images.githubusercontent.com/7634958/40870445-064a5cae-65f5-11e8-864a-92d657bb49aa.png">

![captura de pantalla 2018-06-01 a la s 23 34 21](https://user-images.githubusercontent.com/7634958/40870446-09f5b010-65f5-11e8-91a0-71fbf79ecbd1.png)

I have the error shown in the attached image, I already tried everything, but I can not solve it, idea, greetings!

#### 1. Which version of `kreait/firebase-php` are you using?

V4.8.0

#### 2. Which version of PHP are you using?

PHP 7.1

#### 3. What's the issue?

Fatal error: Uncaught Error: Call to undefined method Kreait\Firebase\Factory::getDatabase() in /Users/eduartml/Documents/PHP/firebase/index.php:10 Stack trace: #0 {main} thrown in /Users/eduartml/Documents/PHP/firebase/index.php on line 10

#### 4. Code that lead to the issue

*Please use [syntax highlighted code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) with code that can be used to reproduce the issue.*

**Comment by erixrevolver** [comment]
Excuse me, I found my mistake when creating the instance, I leave the code in case someone had a similar problem

<img width="717" alt="captura de pantalla 2018-06-01 a la s 23 34 48" src="https://user-images.githubusercontent.com/7634958/40870529-1d085d72-65f7-11e8-8b59-a857d763a988.png">

**Comment by jeromegamez** [comment]
You can always find the currently correct way to instantiate the SDK in the documentation at https://firebase-php.readthedocs.io/en/5.x/#quick-start
