### ISSUE TITLE
php version 7.0 getting fatal error issue

### ISSUE THREAD

**Issue by php1webmobtech** [kreait/firebase-php#206]
I am using ^3.0 version for kreait/firebase-php and php version 7.0.

I want to use realtime database api

when i run code i'm getting below error

FatalErrorException in ServiceAccount.php line 16: syntax error, unexpected ':', expecting ';' or '{'

``` 
<?php
include('vendor/autoload.php');
use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromJsonFile('developemt-c-firebase-adminsdk-kxcwf-7d0145b49f.json');
$firebase = (new Factory)
->withServiceAccount($serviceAccount)
->create();
$database = $firebase->getDatabase();

$newPost = $database->getReference('post/')
        ->push([
        'message' => 'testing push1'
        ]);


echo $newPost->getKey();

return true;
?>
````

Please give me solution for support php version 7.0

**Comment by jeromegamez** [comment]
The error is an indication that the environment you‘re running the script in is not 7.x - please check the environment.

**Comment by php1webmobtech** [comment]
php version is 7.0.
It's not work in this

**Comment by php1webmobtech** [comment]
![cpanel_server_information](https://user-images.githubusercontent.com/13380046/41159030-bd1fc560-6b48-11e8-93d5-776a9a6c18e5.png)

it's my server information

**Comment by jeromegamez** [comment]
Please insert the following line after the `<?php` (in the second line):

```php
echo phpversion(); exit
```

What is the output?

**Comment by php1webmobtech** [comment]
It's give me 5.6.36 php version.
In this version how it's work? What's the solution for this version?

**Comment by jeromegamez** [comment]
If you want to use this library, you will have to upgrade to PHP 7.

I don‘t know of another PHP library that currently works reliably with Firebase.

I‘m closing this issue now because it is not related to this library, but feel free to share your findings in additional comments.
