### ISSUE TITLE
[SUGGESTION] Removing the requirement for superbalist/flysystem-google-storage

### ISSUE THREAD

**Issue by udAL** [kreait/firebase-php#208]
#### 1. Which version of `kreait/firebase-php` are you using?
4.9

#### 2. Which version of PHP are you using?
7.2.4

#### 3. What's the issue?
The requirement for the package [superbalist/flysystem-google-storage](https://packagist.org/packages/superbalist/flysystem-google-storage) it's very inconvenient since the last version uses an outdated version of [google/cloud-storage](https://packagist.org/packages/google/cloud-storage).
Since you probably only need it when cloud storage it's used, could you make it a suggestion?
Otherwise maybe use the official google/cloud-storage?
Thanks

#### 4. Code that lead to the issue
composer install

**Comment by jeromegamez** [comment]
It‘s not possible to change the requirement without releasing a new major release or breaking SemVer, so I‘m afraid this will not be possible with a 4.x release - 5.x will be a rewrite with modularity built-in, but I can‘t foresee when this will happen, not in the near future.

A better solution would probably be to add an issue or a PR to the superbalist repo to resolve the version restriction on the google package.

**Comment by udAL** [comment]
I'll try, thanks for the response
