### ISSUE TITLE
sound support

### ISSUE THREAD

**Issue by stvalentin** [kreait/firebase-php#209]
#### 1. Which version of `kreait/firebase-php` are you using?

4.9.0
#### 2. Which version of PHP are you using?

7.2

#### 3. What's the issue?

Does the package support push notification with sound, and so what do I need to set them up.

**Comment by jeromegamez** [comment]
You can add any property that is supported by the FCM HTTP specification, including sound, so: yes :)

You can find the specification here: https://firebase.google.com/docs/cloud-messaging/http-server-ref
