### ISSUE TITLE
update records in firebase database

### ISSUE THREAD

**Issue by pathikvejani** [kreait/firebase-php#21]
How to **update status = 0 in firebase database where status = 1?**

What I have tried is:

    <?php
    require __DIR__.'/vendor/autoload.php';
    use Kreait\Firebase\Configuration;
    use Kreait\Firebase\Firebase;
    $firebase = new Firebase('LINK', $configuration);
    $users = $firebase->get('/users');
    for ($i=0; $i < count($users) ; $i++) {
    	$data = array('status' => '0');
    	$nodeUpdateContent = $firebase->update(['status' => '1'],$users[$i].'/presence/status');
    	print_r($nodeUpdateContent);
    }
    ?>

But when I see in the firebase database, it is not updating anything. Why so?

I am following this link: [Firebase-php][1]

Update data using this link: [Update-data][2]

I am getting in `$users`:

    <?php
    [1] => Array
    (
    	[presence] => Array
    	(
    		[loginTimestamp] => 1460117596561
    		[status] => 1
    	)
    
    )
    
    [2] => Array
    (
    	[presence] => Array
    	(
    		[loginTimestamp] => 1460117596561
    		[status] => 1
    	)
    )
    
    [3] => Array
    (
    	[presence] => Array
    	(
    		[loginTimestamp] => 1460117596561
    		[status] => 1
    	)
    )
    
    ?>

I am getting response for this: <br>**$nodeUpdateContent = $firebase->update(['status' => '1'],$users[$i].'/presence/status');**

    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )

`It is just printing the status which value is 1, but not updating it.`

    getting error here: Array to string conversion --> $nodeUpdateContent = $firebase->update(['status' => '1'],$users[$i].'/presence/status');

  [1]: https://github.com/kreait/firebase-php/tree/c0adb0ced970b2a8a2968a7bf6f803786a2f7ca2
  [2]: https://github.com/kreait/firebase-php/blob/master/doc/firebase.md

**Comment by jeromegamez** [comment]
Thank you for the detailed issue description - as I think that this is the same as in #22, I am closing this one, and we should continue the discussion there.
