### ISSUE TITLE
Cache firebase's public keys

### ISSUE THREAD

**Issue by Guglio95** [kreait/firebase-php#210]
Hi
I'm just trying to cache firebase's public keys as shown [here](https://github.com/kreait/firebase-tokens-php/blob/master/README.md).

But, I found no way to externally create a "Verifier" object or customize HttpKeyStore instance used by the Verifier because all objects are created internally in [Factory::createAuth()
](https://github.com/kreait/firebase-php/blob/master/src/Firebase/Factory.php#L152)
So I think there's actually no way to use a real caching system.

Do you think this will be useful in terms of performance? I looked at the default caching mechanism ([InMemoryCache](https://github.com/kreait/firebase-tokens-php/blob/master/src/Cache/InMemoryCache.php)) and it seems like a plain array, so every time you'll have to download back the keys from Google.

Thankyou :smile:

**Comment by jeromegamez** [comment]
Thanks for this useful suggestion! I will add a method to the factory in the next release.

**Comment by jeromegamez** [comment]
Here it is 🎉: https://github.com/kreait/firebase-php/releases/tag/4.10.0
