### ISSUE TITLE
How can using it in cakePHP 2.6

### ISSUE THREAD

**Issue by tomnyson** [kreait/firebase-php#211]
I have issue when import with cakephp 2.6
can you can show me how import  this composer in cake php

**Comment by jeromegamez** [comment]
Hey @tomnyson 

If your CakePHP project has been installed with composer, you should have a `composer.json` in your project root directory and should be able to add the Firebase PHP Admin SDK as an additional dependency.

If your CakePHP project is *not* installed with composer, there is no easy way to use this (or any other 3rd party) library within your project.

**Comment by tomnyson** [comment]
can you can show me detail
I  have folder Vendor/ Firebase/src/Firebase.php and Firebase/src/Firebase
I decided import 
`<?php
App::uses('AppController', 'Controller');
App::import('Vendor', 'Firebase', array('file' => 'Firebase'.DS.'src'.DS.'Firebase.php'));
class ChatController extends AppController
{
    function index() {
       // $firebase = new Firebase();
        // $firebase->dosomething();
        if (class_exists('Firebase')) {
            echo '111';
        } else {
            echo '22222';
        }
       //$serviceAccount = ServiceAccount::discover();
        //die;
        
    }
}`
but It error 503. can you can suggest me right way

**Comment by jeromegamez** [comment]
When I said "there is no easy way", I should have said "this is virtually impossible". You would have to import *every* file of the SDK and every file of its dependencies. In the end, you would have import statements for a couple thousand files. Don't do this, it's not worth it.

If you can't upgrade your project to a current CakePHP release, you could write your own methods/plugin based on the Firebase REST APIs

https://firebase.google.com/docs/reference/rest
