### ISSUE TITLE
Error with firebase library

### ISSUE THREAD

**Issue by Sudhanshu4U** [kreait/firebase-php#215]
#### 1. Which version of `kreait/firebase-php` are you using?

4.0

#### 2. Which version of PHP are you using?

7.2

#### 3. What's the issue?

PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/html/webpush6/vendor/kreait/firebase-php/src/Firebase.php on line 47

#### 4. Code that lead to the issue

<?php
require __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;
?>
*

**Comment by jeromegamez** [comment]
You are not using PHP 7.2 on the system that you are executing your script on. Please see e.g. #206, #145, #75
