### ISSUE TITLE
Add validate_only attribute when sending Firebase Cloud Messageing

### ISSUE THREAD

**Issue by steffdimitrov** [kreait/firebase-php#216]
#### 1. Which version of `kreait/firebase-php` are you using?

versions : * 4.11.0

#### 2. Which version of PHP are you using?

PHP 7.2.7-1+ubuntu16.04.1+deb.sury.org+1

#### 3. What's the issue?

There is missing functionality for Firebase Cloud Messaging. If you want just to verify message you can pass validate_only attribute to request payload (https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send#request-body)

**Comment by jeromegamez** [comment]
Here you are: https://github.com/kreait/firebase-php/releases/tag/4.12.0 :)

**Comment by steffdimitrov** [comment]
Thanks!!!
