### ISSUE TITLE
fromJsonFile throws error

### ISSUE THREAD

**Issue by andreashsagen** [kreait/firebase-php#217]
Hi,

inexperienced kreait/firebase-php user here.

kreait/firebase-php version: 3.0.1. (not using composer, got that from the changelog)
php version: 7.0.30

Issue: 
I followed the instructions at https://firebase-php.readthedocs.io/en/latest/user-management.html. This results in:
PHP Fatal error:  Uncaught Error: Call to private method Kreait\Firebase\ServiceAccount::fromJsonFile() from context '' in [...]

The code looks like this:

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;
**$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/[redacted].json');**
$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->create();
$auth = $firebase->getAuth();

Help would be much appreciated. Thanks.

**Comment by jeromegamez** [comment]
Hey Andreas,

I just checked, and it's true, in Version 3.0.1, the given method is indeed private (see https://github.com/kreait/firebase-php/blob/3.0.1/src/Firebase/ServiceAccount.php#L118) and you should use `ServiceAccount::fromValue(...)` here.

If you want to stay within the 3.x branch, you should safely be able to go to version 3.9.3 of which you can find the documentation at https://firebase-php.readthedocs.io/en/3.9.3/

But when you're using PHP 7.x, you should also be able to go with Release 4.x - may I ask why you chose not to? Is there a feature in 3.0.1 that you are missing in 4.x?

**Comment by andreashsagen** [comment]
Hello,

not really - it's just took over someone else's project. I installed the 4.12 version, and seems to be working fine after i updated kreait/firebase-tokens. Thanks for your quick help!
