### ISSUE TITLE
RemoteConfig: Using existing condition fails validation

### ISSUE THREAD

**Issue by starkwong** [kreait/firebase-php#218]
#### 1. Which version of `kreait/firebase-php` are you using?
4.10.0
#### 2. Which version of PHP are you using?
7.2.6
#### 3. What's the issue?
If I tries to add a parameter that uses existing condition, publishing fails with "Uncaught Kreait\Firebase\Exception\InvalidArgumentException: Not all given conditional values refer to an existing condition."

#### 4. Code that lead to the issue
(Where "android" and "ios" are existing conditions already in remote config)

```
	$remoteConfig = $firebase->getRemoteConfig();
	$template = $remoteConfig->get();

	$parameter = RemoteConfig\Parameter::named('data', null);
	foreach (['android','ios'] as $platform) {
		$parameter = $parameter->withConditionalValue(new RemoteConfig\ConditionalValue($platform, $fbstorage_urls[$platform]));
	}
	$template = $template->withParameter($parameter);
	$remoteConfig->publish($template);

```

The issue is caused by imported conditions do not have string keys. Changing the code in Template->conditionExists() to the following fixes the issue:

```
        foreach ($this->conditions as $condition) {
            if ($condition->name() == $conditionName) return true;
        }
        return false;
```

**Comment by jeromegamez** [comment]
Hey @starkwong and thanks for taking the time to report this issue with a detailed description. I just pushed some changes that should fix the problem.

I'll create a new release as soon as the tests on Travis CI are green.

**Comment by jeromegamez** [comment]
And here it is: https://github.com/kreait/firebase-php/releases/tag/4.12.1 🎉
