### ISSUE TITLE
firebase/php-jwt composer incompatibility 

### ISSUE THREAD

**Issue by Manuelacosta98** [kreait/firebase-php#219]
"kreait/firebase-php": "^1.2"
php 5.5.9

 What's the issue?
is a composer releated problem i am triying to install booth firebase/php-jwt and kreait/firebase-php proyects in my symfony api proyect, the composer problems are as follow:

Problem 1
   - Installation request for microsoft/windowsazure ^0.4.5 -> satisfiable by microsoft/windowsazure[v0.4.5].
   - microsoft/windowsazure v0.4.5 requires firebase/php-jwt ^4.0 -> satisfiable by firebase/php-jwt[v4.0.0] but these conflict with your requirements or minimum-stability.
 Problem 2
   - kreait/firebase-php 1.2 requires firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].
   - kreait/firebase-php 1.2.1 requires firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].
   - kreait/firebase-php 1.2.2 requires firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].
   - firebase/token-generator v3.0.0 requires firebase/php-jwt ^3.0 -> satisfiable by firebase/php-jwt[v3.0.0] but these conflict with your requirements or minimum-stability.
   - Installation request for kreait/firebase-php ^1.2 -> satisfiable by kreait/firebase-php[1.2, 1.2.1, 1.2.2].

my symfony composer.json looks like this:
"require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/swiftmailer-bundle": "~2.3,>=2.3.10",
        "symfony/monolog-bundle": "^3.0.2",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "nelmio/api-doc-bundle": "^2.13",
        "lexik/jwt-authentication-bundle": "^2.1",
        "nelmio/cors-bundle": "^1.5",
        "sendgrid/sendgrid": "^5.0",
        "microsoft/windowsazure": "^0.4.5",
        "google/apiclient": "^2.1",
        "facebook/graph-sdk": "^5.4",
        "mjaschen/phpgeo": "^1.3",
        "aws/aws-sdk-php": "^3.36",
        "beberlei/DoctrineExtensions": "^1.0",
        "firebase/php-jwt": "^5.0",
        "kreait/firebase-php": "^1.2"
    },

My question is what are the right version of kreait/firebase-php adn firebase/php-jwt than can be added in my proyect under php 5.5.9 Thanks.

**Comment by jeromegamez** [comment]
The 1.x release of this library requires `firebase/token-generator`, which requires the 3.x version of `firebase/php-jwt`, so the only way to use both is to replace

```
"firebase/php-jwt": "^5.0",
"kreait/firebase-php": "^1.2"
```

with

```
"firebase/php-jwt": "^3.0",
"kreait/firebase-php": "^1.2"
```

I don't actively support the 1.x branch of this library anymore, so a second possibility could be that you fork this repo and try to re-implement the token generation.

Last but not least, you could try to use [ktamas77/firebase-php](https://github.com/ktamas77/firebase-php) instead. Please be aware though that the other library seems to be abandoned and doesn't support authentication via a ServiceAccount JSON file.

**Comment by Manuelacosta98** [comment]
I appreciate your taking the time to answer my question, now i have a problem with microsoft azure dependency:

Problem 1
   - Installation request for microsoft/windowsazure ^0.4.5 -> satisfiable by microsoft/windowsazure[v0.4.5].
   - microsoft/windowsazure v0.4.5 requires firebase/php-jwt ^4.0 -> satisfiable by firebase/php-jwt[v4.0.0] but these conflict with your requirements or minimum-stability.

thats no good because i need v 3.0 of  firebase/php-jwt

**Comment by jeromegamez** [comment]
Release 0.4.4 of `microsoft/windowsazure` is the last release to support `firebase/php-jwt ^3.0` (https://packagist.org/packages/microsoft/windowsazure#v0.4.4), so in your `composer.json` you will have to change

```
"microsoft/windowsazure": "^0.4.5",
```

to 

```
"microsoft/windowsazure": "0.4.4",
```
