### ISSUE TITLE
Support for continueUrl for reset and verify emails

### ISSUE THREAD

**Issue by wadewomersley** [kreait/firebase-php#221]
#### 1. Which version of `kreait/firebase-php` are you using?

4.12.1

#### 2. Which version of PHP are you using?

7.2

#### 3. What's the issue?

Cannot pass continueUrl to reset or verify emails

#### 4. Code that lead to the issue

See PR to fix at https://github.com/kreait/firebase-php/pull/220/files

**Comment by jeromegamez** [comment]
Thanks Wade! One PR/issue is enough 😅, so I'll close this and continue over at #220

**Comment by wadewomersley** [comment]
Wasn't sure on the process, will keep that in mind for the future!
