### ISSUE TITLE
resulted in a `400 Bad Request` response:

### ISSUE THREAD

**Issue by bobykurniawan11** [kreait/firebase-php#222]
Hi, i'm trying to create new record. here is what i do. 

```
function createData($params){
$randomkey = $this->firebase->getDatabase()->getReference($this->reference)->push()->getKey();
		$this->firebase
				->getDatabase()->getReference($this->reference)
				->getChild($randomkey )->set($params);
	}
```

and $params

```
$data = [
    'fullname' => 'My awesome post title'
];
```

but i get this error message 

> Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://blablaxxxi.firebaseio.com/posts` resulted in a `400 Bad Request` response:
> {
>   "error" : "No data supplied."
> }
> 
>  in D:\xampp\htdocs\firebase-php\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
> Stack trace:
> #0 D:\xampp\htdocs\firebase-php\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
> #1 D:\xampp\htdocs\firebase-php\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
> #2 D:\xampp\htdocs\firebase-php\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
> #3 D:\xampp\htdocs\firebase-php\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
> #4 D:\xampp\htdocs\firebase-php\vendor\guzzlehttp\promises\src\Promi in D:\xampp\htdocs\firebase-php\vendor\kreait\firebase-php\src\Firebase\Exception\ApiException.php on line 40

everything else are working (`Read`, `update` and `delete`)

After another try and I'm totally sure the error happened when generating the  `$randomkey`. Because when i do this 

```
$this->firebase
				->getDatabase()->getReference($this->reference)
				->getChild("asdfasdf")->set($params);

```
it is working . 

sorry for my english

**Comment by bobykurniawan11** [comment]
I have fix this and it was my stupidiness . 

```
$newInput = $this->firebase
				->getDatabase()->getReference($this->reference)->push($params);
		$newInput->push()->getKey();
```

**Comment by jeromegamez** [comment]
Too bad you deleted your second comment and changed the original issue description, but I’m glad you got it working!

**Comment by bobykurniawan11** [comment]
Sorry, i don’t really know how to use github. Now, i’m trying to create codeigniter library with this. Is it ok ?

**Comment by simone-b** [comment]
Hi !

@bobykurniawan11 I fixed the issue by using it this way (passing an empty array to push method) : 

`$firebase->getDatabase()->getReference($this->reference)->push([])->getKey();`

@jeromegamez : The problem can be fixed by setting default value of `$value` at an empty array instead of a null value in `Kreait\Firebase\Database\Reference@push line 351`. 
Because then when Guzzle is called with a null value for key `json`, guzzle doesn't add a body in the request. And firebase APIs needs at least an empty json : 
```
{

}
```

Hope that it'll help you !

**Comment by jeromegamez** [comment]
Thanks for looking further into it and the hint, @simone-b! `->set()` has a similar issue. To re-iterate:

- It should be possible to push to a reference without a value just to get a key
- When `set`ting a reference with `null`, the reference is deleted.

I'll work this in and create a new release as soon as I'm done!

**Comment by jeromegamez** [comment]
@bobykurniawan11 @simone-b Here it is: https://github.com/kreait/firebase-php/releases/tag/4.13.1
