### ISSUE TITLE
401 configuration problem

### ISSUE THREAD

**Issue by Manuelacosta98** [kreait/firebase-php#223]
1. Which version of `kreait/firebase-php` are you using?
--"kreait/firebase-php": "^1.2"

2. Which version of PHP are you using?
php 5.5.9

 3. What's the issue?
I get 401 Permission Denied, when i change he permisions of my database even making the config with secret key, I need to have root access to read and write all the db with out worryng by the set of rules.

With out any rules push are successful on the db.

#### 4. Code that lead to the issue

i config firebase like this:
```php
$config = new Configuration();
$config->setFirebaseSecret(Constants::FIREBASE_DATABASE_SECRET);
$firebase = new Firebase(Constants::FIREBASE_DATABASE_BASE_URL, $config);
```

When triying to push an object with rules like this: 
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}

Sorry for my bad english, the proyect where i am working is to big to update php.

**Comment by jeromegamez** [comment]
No problem, Manuel, English is also not my native language :). Unfortunately though, I am unable to help you at this point. I haven‘t worked on the 1.x branch in a long time and all I can say that it worked back in the time.

The reason for your error could be that Firebase has started to disable authentication via the database secrets - I just checked in ktaas‘ library and found this: https://github.com/ktamas77/firebase-php/issues/82 - which seems to be the same problem.

You could try generating a new database secret in the Firebase Web Console and see if it works with a new secret.

If it doesn’t, I‘m afraid that you will not be able to access Firebase from PHP 5.x and should either upgrade (the jump to 7.x is not as big as it seems) or look for an implementation in another programming language :/
