### ISSUE TITLE
Missing manage-cookies

### ISSUE THREAD

**Issue by TheMrg** [kreait/firebase-php#224]
Hi. I missing the feature:
https://firebase.google.com/docs/auth/admin/manage-cookies

Create session cookie
- aka 
admin.auth().createSessionCookie 
(node.js SDK)

Is there a way to do this with your nice Firebase PHP SDK?

Thanks

ups issue here:
Support for Session Cookies #202

**Comment by jeromegamez** [comment]
Yep ^^. Closing as duplicate and continuing over there :)
