### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by jcousin74** [kreait/firebase-php#226]
Hi, I'm trying to use the lib, but I'm getting this error>
cURL error 60: SSL certificate problem: unable to get local issuer certificate

I already check the issues and on google, I add the .cert file, but I still have this error.

  'default_cert_file' => string 'C:\Program Files\Common Files\SSL/cert.pem' (length=42)

Thanks for helping me

**Comment by jeromegamez** [comment]
Unfortunately this is not an error I can reliably assist you with, my recommendation is that you check https://firebase-php.readthedocs.io/en/latest/troubleshooting.html#curl-error-xx and perform the steps described in that section if you haven't already.

In case you're using Windows, this is an approach targeted at Windows and a Wamp Server environment: https://stackoverflow.com/a/49071524/284325

There certainly is a solution to this problem, but as it isn't directly related to the SDK, I'm gonna close the issue now. Please feel free to add a comment once you found a solution to share it with others that stumble upon it as well.
