### ISSUE TITLE
Poblems with indexing and queries

### ISSUE THREAD

**Issue by Manuelacosta98** [kreait/firebase-php#227]
#### 1. Which version of `kreait/firebase-php` are you using?
kreait/firebase-php 1.2.2

#### 2. Which version of PHP are you using?
php 5.5.9

#### 3. What's the issue?

Hello, I have a Database with the following structure:

```
"rooms": {
    "roomuid1": {
      "members": {
        "userId": "hash",
        "candidateId": "hash",
      },
      "publication": {
        "id1": true,
      },
      "messages": {
        "uid" : true
      },
      "lastMessage": "lastMessageuid",
      "disabledReasons": {
        "statusuid": true
      },
    }
  }

```

then i run a query to get all the rooms of a particular candidate inside, knowing his uid the query is:

Firebase.database().ref('rooms').orderByChild("members/candidateId").equalTo(_candidateUid)

In the client side the query is succesfull, but throws a warning: 

FIREBASE WARNING: Using an unspecified index. Your data will be downloaded and filtered on the client. Consider adding ".indexOn": "members/candidateId" at /rooms to your security rules for better performance.

But in the server side, i get an exception: 

[Kreait\Firebase\Exception\FirebaseException] 
...
with data "": Index not defined, add ".indexOn": "members/candidateId", for path "/rooms", to the rules

I tried to add an index in candidateId this way: 
```
{
 "rules": {
   ".read": "auth != null",
   ".write": "auth != null",
   
   "rooms": {
     "$room_id": {
       "members": {
         ".indexOn": ["userId", "candidateId"],
         "userId": {
           ".validate": "root.child('users/'+newData.val()).exists() "
           
         },
         "candidateId": {
           ".validate": "root.child('candidates/'+newData.val()).exists() "
         }
       }
     }  
     }
   }
}
```

But the error continues in the server side, mi question is, How i can index candidateId to be able to run the query in server side ?

**Comment by jeromegamez** [comment]
I can't say for sure, but the error hints toward this:

```
{
  ...
  "rooms": {
    ".indexOn": ["members/candidateId", "members/userId"],
    "$room_id": {
      "members": {
        // No ".indexOn" here
      }
    }
  }
}
```

This is not related to the library itself  - for general Firebase questions, please go to 
https://firebase.community/ and for this case, join the #database-rules channel, the people there certainly can help better and faster than I can.
