### ISSUE TITLE
Client error: `POST https://fcm.googleapis.com/v1/projects/myapp-cloud-xxxxx/messages:send` resulted in a `403 Forbidden`

### ISSUE THREAD

**Issue by clebersonfalk** [kreait/firebase-php#231]
Hi, I migrated my mobile app from GCM service to FCM, then downloaded the file `google-services.json` and configured my application, finally I generated a new private key used by the `firebase-php` library.

However, when I try to send notifications from my PHP system, the execution is generating the following error:

## Error

Client error: `POST https://fcm.googleapis.com/v1/projects/myapp-cloud-xxxxx/messages:send` resulted in a `403 Forbidden` response:
{
  "error": {
    "code": 403,
    "message": "Firebase Cloud Messaging API has not been used in project 2973486xxxxx b (truncated...)

- PHP Version (`php -v`): PHP 7.1.18-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun 11 2018 14:22:30) ( NTS )
- Firebase PHP SDK version (`composer show | grep kreait`): "kreait/firebase-php": "^4.13"

## Details

I tested this library in a testing application and did not have this problem. Strangely, the problem occurred only with the application app already in place in GCM and imported into FCM Firebase.

**NOTE:** If I try to send a Push Notification through the Firebase console using the same `token` used by php, it works. But trying to send through the library occurs the error.

## Code to reproduce issue

```
$serviceAccount = ServiceAccount::fromJsonFile(APPLICATION_PATH . '/myapp-cloud-firebase-adminsdk.json');
$firebase = (new Factory)->withServiceAccount($serviceAccount)->create();

// Message
$config = AndroidConfig::fromArray([
    'ttl' => '3600s',
    'priority' => 'normal',
    'notification' => [
        'title' => $this->_data['title'],
        'body' => $this->_data['message'],
        'icon' => 'icon',
        'color' => 'white'
    ]]);
$message = MessageToRegistrationToken::create($device['token'])
    ->withAndroidConfig($config);

// Send message
$messaging = $firebase->getMessaging();
try {
    $messaging->send($message);
} catch (Exception $e) {
    var_dump($e->getMessage());
}
```

Could you help me? Thank you.

**Comment by clebersonfalk** [comment]
**I discovered a solution:**

Strangely, even if you imported the project into Firebase, you still had to sign in to the Google Cloud Platform and activate Firebase API.

Anyway, the problem is not in your library, on the contrary, your library is fantastic, thank you!

### More details on how I discovered the problem:

The solution posted by the user @niocncn:
Link: https://github.com/firebase/firebase-admin-go/issues/116

Link to enable the Firebase API:
https://console.cloud.google.com/apis/api/fcm.googleapis.com/overview

**Comment by jeromegamez** [comment]
Perfect case of rubber duck debugging :D. I just wanted to suggest checking the Google Cloud Console when I saw that you just closed the issue ^^. I'm glad that you like the library, and that you were able to work it out! Thank you for sharing the solution, I will add a section to the troubleshooting docs shortly so that others can more easily discover it!

**Comment by clebersonfalk** [comment]
I think your suggestion is very good. Thank you!

**Comment by jeromegamez** [comment]
FYI and for others who stumble on this, here's the new section, including the other relevant APIs that need to be enabled: 

https://firebase-php.readthedocs.io/en/latest/troubleshooting.html#forbidden-errors

**Comment by semsphy** [comment]
@jeromegamez , I followed your troubleshooting and enabled the service, but I still got the forbitdden errors. Any ideas, please?

**Comment by jeromegamez** [comment]
@semsphy Guessing is hard. You could check if the project IDs match, if other connections, e.g. to the database work, and you could debug the exceptions you‘re getting, as well as enabling Debug via the HTTP client options.
