### ISSUE TITLE
GcpMetadata overrides provided service account

### ISSUE THREAD

**Issue by JBBx2016** [kreait/firebase-php#233]
## The problem

I am running firebase and GCP VMs on two seperate projects. I therefore use a service account providing access to firebase project using (new Factory())->withServiceAccount(...).

Despite this I get:

 Kreait\Firebase\Exception\Messaging\AuthenticationError: Client error: `POST https://fcm.googleapis.com/v1/projects/schoollink-150710/messages:send` resulted in a `403 Forbidden` response:
cron_1                     | {
cron_1                     |   "error": {
cron_1                     |     "code": 403,
cron_1                     |     "message": "Request had insufficient authentication scopes.",
cron_1                     |     "status": "PERMISS (truncated...)
cron_1                     |  in /home/schoollink/web/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingException.php:76

## Environment

- PHP Version 7.2
- Works in 4.13 - does not work in 4.15

## Details

I found change in the Factory::createGoogleAuthTokenMiddleware function starting in (v4.14 or v4.15) I think causes this issue:

![image](https://user-images.githubusercontent.com/25931756/43755778-fa66cd86-9a11-11e8-983c-cafdfb9c6b9b.png)

**Comment by jeromegamez** [comment]
Uh, not good! I already have an idea where the issue lies, thanks for reporting it, I’ll fix it shortly.

**Comment by JBBx2016** [comment]
@jeromegamez Thanks a lot - I have now upgraded to v4.15.1 and I no longer encounter this issue.
