### ISSUE TITLE
Class 'Kreait\Firebase\Messaging\CloudMessage' not found

### ISSUE THREAD

**Issue by akshay-kapase** [kreait/firebase-php#236]
Hi I'm receiving the above error, when I try to send message to a device.

**Comment by jeromegamez** [comment]
You are provided with an issue template when creating a new issue, please use it.

You are not using the latest version of the library - the CloudMessage class has been introduced with [release 4.14](https://github.com/kreait/firebase-php/releases/tag/4.14.0), please update your composer dependencies

```bash
$ composer require kreait/firebase-php:^4.15.1
```

or, in your `composer.json`:

```json
{
  "require": {
    "kreait/firebase-php": "^4.15.1"
  }
}
```

**Comment by akshay-kapase** [comment]
ok thanks.
