### ISSUE TITLE
Numeric Type in PUSH method

### ISSUE THREAD

**Issue by rebigliazzi** [kreait/firebase-php#237]
Hello, when entering an numeric type using the PUSH method, the following situation occurs, as shown in the attached image. Can you help me ?tks
![error](https://user-images.githubusercontent.com/12715786/44213244-9b964f00-a143-11e8-995c-a963cf720bbc.jpg)

**Comment by jeromegamez** [comment]
Sorry, but I can't reproduce an issue without knowing what you're working with and without code that I can use to reproduce the issue.

You were provided with a template when creating this issue, please use it.

**Comment by rebigliazzi** [comment]
tks @jeromegamez  , follow

1. Which version of kreait/firebase-php are you using?
latest

2. Which version of PHP are you using?
7.1

3. What's the issue?
when entering an numeric type using the PUSH method, the following situation occurs, as shown in the attached image
![error](https://user-images.githubusercontent.com/12715786/44214758-42c8b580-a147-11e8-88bc-7bb3ac84e88c.jpg)

4. Code that lead to the issue
https://pastebin.com/c3zsQQ7J

**Comment by jeromegamez** [comment]
Thanks! Does „latest“ mean „4.15.1“?

**Comment by rebigliazzi** [comment]
@jeromegamez 

thats right ! ^4.15.1

**Comment by jeromegamez** [comment]
Your code says

```php
$array = (
     'cliente' => 'teste',
        'endereco' => 'teste',
        'valor' => 24500
);
```

instead of

```php
$array = [
    'cliente' => 'teste',
    'endereco' => 'teste',
    'valor' => 24500
];
```

or 

```php
$array = array(
    'cliente' => 'teste',
    'endereco' => 'teste',
    'valor' => 24500
);
```
