### ISSUE TITLE
Firebase Topic Management (adding on top of Topic Subscription Management)

### ISSUE THREAD

**Issue by The-Don-Himself** [kreait/firebase-php#238]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added). 

Firebase Topic Management (adding on top Topic Subscription Management).

This really isn't an issue but a feature request. The official Firebase FCM Admin docs (https://firebase.google.com/docs/cloud-messaging/admin/) don't have instructions to create topics, that vital information is included elsewhere for example in Google Docs.

I think it would be great to have this feature supported by this wonderful library, another feature to tick in the readme that libraries in other languages don't support :)

Thoughts?

**Comment by jeromegamez** [comment]
Could you please point me to the docs where this feature is described? As far as I know, topics are automatically created once you send a message to one. I read somewhere that it takes up to one day until a newly created topic then appears in the Firebase Console.

**Comment by The-Don-Himself** [comment]
Thanks for your response.

I think you might be referring to this SO question (https://stackoverflow.com/questions/37367292/how-to-create-topic-in-fcm-notifications)

It's possible to manually create topics, actually it's the preferred way, the automatic topic creation on initial subscription was a hack (and was actually removed from the web i.e clients can create topics from web sdk just by subscribing to one).

The rest remains true though, still several hours to reflect on the Firebase Console.

**Comment by jeromegamez** [comment]
Yes, that was the SO thread 😅

Nonetheless - if you can provide me with the API docs to create topics, I‘ll look into it - although I wonder why Google/Firebase wouldn‘t document a „preferred“ but instead promote a „hacky“ way.

I saw something with the IID API, but if this requires introducing a new parameter besides the ServiceAccount, I‘d rather not do it.

**Comment by The-Don-Himself** [comment]
Sorry, just remembered I opened an issue here after doing a composer update and seeing you released a new version :) Big up for that :+1: 

So, back to this (non) issue, basically Firebase don't have the best of ways to create topics so far. What some of us prefer is just send a message to the topic, thereby creating it automatically :)

Think of a sports or news app, you probably don;t have a token from the backend when a match begins, and creating one specifically to create a topic is hacky, admittedly so is sending a message with no one in mind. Either way, I agree with you, this is probably beyond the logic for this handy library especially since I think/hope the FCM topic API changes for the better.

So I'll close this.

**Comment by jeromegamez** [comment]
As soon as it does/I get aware of it, you can be sure I‘ll implement it. Cheers!
