### ISSUE TITLE
Call to undefined method Kreait\Firebase::getStorage()

### ISSUE THREAD

**Issue by metd** [kreait/firebase-php#239]
## The problem
Call to undefined method Kreait\Firebase::getStorage()

## Environment

- PHP Version (`php -v`):
PHP 7.0.30
- Firebase PHP SDK version (`composer show | grep kreait`):
kreait/firebase-php                4.0.2    Firebase Admin SDK
kreait/firebase-tokens             1.7.1    A library to work with Firebase tokens

## Code to reproduce issue

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$firebase = (new Factory())
        ->withServiceAccount($serviceAccount)
        ->create();

$storage = $firebase->getStorage();

**Comment by jeromegamez** [comment]
Storage support has been added in release 4.1 - you can safely upgrade to ^4.15 to get all documented/supported features and the bugfixes, the SDK follows semantic versioning, so there are no breaking changes.

**Comment by metd** [comment]
Thank you.
