### ISSUE TITLE
Firebase v3.0 custom uid

### ISSUE THREAD

**Issue by jwasinski** [kreait/firebase-php#24]
It doesn't seem to be possible to set a custom UID server side in firebase 3.0. Allowing for server specific rules to be created in firebase. 

See [Authenticating Privileged Workers](http://stackoverflow.com/questions/37408684/is-it-still-possible-to-do-server-side-verification-of-tokens-in-firebase-3)

**Comment by jeromegamez** [comment]
Yes, the current implementation only works with Firebase <3.0, but you can still use the 2.x/Database Secret workflow.

I am currently rewriting the lib to make the switch to the Firebase 3.0 SDK (that is authentication through a service account), but it's still in very early stages and it will be PHP 7 only. If you're interested in testing it, please let me know.

**Comment by jeromegamez** [comment]
@jwasinski I just released a new patch version (see https://github.com/kreait/firebase-php/releases/tag/0.10.2) which adds support for setting custom UIDs and claims.

Please let me know if it works for you and reopen this issue if not.

:octocat:
