### ISSUE TITLE
Call to undefined method getIdToken()

### ISSUE THREAD

**Issue by hxdef2517** [kreait/firebase-php#242]
I decided to update my firebase-php package to the latest version, and noticed that I cant generate a user token anymore using previous method:

```
$this->_firebase = (new Factory)
            ->withServiceAccount($this->_serviceAccount)
            ->create();

        $user = $this->_firebase->getAuth()->getUser($slug);

        return $user->getIdToken();
```

Now it throws an error that getIdToken method is no longer exist, and I also haven't found any information in the official documentation regarding how to achieve this. Please suggest on how can I generate a token by just providing a uid, its very very useful for debugging and for development purposes. Thanks

**Comment by jeromegamez** [comment]
Hey @hxdef2517, you can generate custom tokens as documented in https://firebase-php.readthedocs.io/en/latest/authentication.html#create-custom-tokens

**Comment by hxdef2517** [comment]
@jeromegamez I don't want to generate a custom token, because it won't be validated by Firebase later, I want to generate normal one as I did previously, but seems like this method was removed. Is there a way to get a token for particular user by UID?(

**Comment by jeromegamez** [comment]
Ah, I misunderstood. Yes, this is possible, you can see an example here: 

https://github.com/kreait/firebase-php/blob/c30740e5df6d7aafd98fdc3f94ca9f06c26e2592/tests/Integration/AuthTest.php#L145-L148

The retrieval of users has changed - in previous releases a user was fetched by quasi logging them in, now the SDK uses the API methods to fetch user records instead of users themselves.

**Comment by jeromegamez** [comment]
As this is not an error in the library itself but rather a helpdesk issue, I'll close this now, but feel free to add further comments if needed, or join https://gitter.im/kreait/firebase-php

**Comment by hxdef2517** [comment]
@jeromegamez I don't want to generate a custom token, because it won't be validated by Firebase later, I want to generate normal one as I did previously, but seems like this method was removed. Is there a way to get a token for particular user by UID?(

**Comment by hxdef2517** [comment]
@jeromegamez again, you are showing an example of how to obtain a custom token, but what I need is normal one

**Comment by jeromegamez** [comment]
Did you see the `->exchangeCustomTokenForIdAndRefreshToken()` method? It will return a response with a JSON encoded array which looks like this

```
[
    'refreshToken' => '...',
    'idToken' => '...',
]
```

So, the process is:

- Create a custom token
- Request an ID token from the Firebase API (which is only possible via a custom token)
- Process the response from the API and extract the ID token from the response

**Comment by hxdef2517** [comment]
@jeromegamez yea it works now! Thanks =) I mistakenly thought it refer to different kind of tokens
