### ISSUE TITLE
Better error reporting while loading config file

### ISSUE THREAD

**Issue by codeasashu** [kreait/firebase-php#243]
## The problem

Error report while loading a service configuration is not relevant enough.

## Environment

- PHP Version (`php -v`): 7.1.11
- Firebase PHP SDK version (`composer show | grep kreait`):4.16.0

## Details

I tried loading a wrong json file (used by android client) in PHP (considering I am total noob). Got exception `\/var\/www\/path-to-project\/google-service-account.json can not be read`. After investigating about 1 hour, I realised I am loading the file which never had the needed configuration variables.

## Code to reproduce issue

try loading a empty or invalid json file.

## Suggestion
The file can not be read can mean either the file is unavailable or it does not have the configuration as requested. Instead, pointing to exact issue (for instance, `wrong configuration in json`) might save user's time.

**Comment by jeromegamez** [comment]
Thanks for the suggestion! I added the error details with https://github.com/kreait/firebase-php/commit/427fa45c8699cad56f5d9373f76b0b2eeee29614

**Comment by jeromegamez** [comment]
Released with [4.17.0](https://github.com/kreait/firebase-php/releases/tag/4.17.0) 🎉

**Comment by codeasashu** [comment]
Thanks a ton. That was pretty quick. Thank for keeping the hard and beautiful work :)
