### ISSUE TITLE
How to set an auto increment id?

### ISSUE THREAD

**Issue by hassaan-dev** [kreait/firebase-php#247]
I did not find answer for this one in issue or every where.
I want to insert order wise keys for example

1 for first entry
2 for second entry
3 for third entry

Currently I am using `numChildren()` got get last key and then +1 to last key and add record to firebase path. But if I have 600K entries then this will not become slow?

My current line
`$last_key = $db->getReference('blog/posts')->getSnapshot()->numChildren();`

Can you please suggest me the proper way?

**Comment by jeromegamez** [comment]
This should work:

```php
$lastItem = $db->getReference('blog/posts')
    ->orderByKey()
    ->limitToLast(1)
    ->getValue();

$lastKey = key($lastItem);
```

Also see https://firebase-php.readthedocs.io/en/latest/realtime-database.html#queries for more information on querying the Realtime Database.

**Comment by jeromegamez** [comment]
That being said, it is not recommended to use "auto-incrementing" ids in the Realtime Database:

https://firebase.google.com/docs/database/admin/save-data#section-push

**Comment by hassaan-dev** [comment]
Thanks

**Comment by hassaan-dev** [comment]
`$lastKey = key($lastItem);` this was not working fine if start counting from 0

So I update above code into `$lastKey = end(array_keys($last_id))`

I hope this will help someone :)
