### ISSUE TITLE
Key not found..

### ISSUE THREAD

**Issue by alien3d** [kreait/firebase-php#249]
## The problem

Some of people like me thinking normal google json key instead of  other key.Kinda waste me time 5 hour  clicking to find solution.

## Environment

- PHP Version (`php -v`):
PHP 5.6
- Firebase PHP SDK version (`composer show | grep kreait`):
"kreait/firebase-php": "^4.17",
## Details

Wrong key

## Solution .

Provide more information on exception handling at ServiceAccount.php

 ```
 if (!isset($config['project_id'])) {
            throw new InvalidArgumentException('Missing/empty project id in Service Account Config.');
        }
        if (!isset($config['client_id'])) {
            throw new InvalidArgumentException('Missing/empty client id in Service Account Config.');
        }
        if (!isset($config['client_email'])) {
            throw new InvalidArgumentException('Missing/empty client email in Service Account Config.');
        }
        if (!isset($config['private_key'])) {
            throw new InvalidArgumentException('Missing/empty private key in Service Account Config.');
        }
        if (!isset($config['project_id'], $config['client_id'], $config['client_email'], $config['private_key'])) {
            throw new InvalidArgumentException('You may download the wrong key . Firebase ->settings -> Service Key -> Generate New Private Key ');
        }
        ...
}
```

**Comment by jeromegamez** [comment]
I’ll look to it, but:

What’s a “normal” Google JSON key? The documentation at https://firebase-php.readthedocs.io/en/latest/setup.html and the official Firebase Docs are pretty clear about the required key being for a Service Account.

How did you get a 4.x release running on PHP 5.6? :)

**Comment by alien3d** [comment]
oops my mistake own server version . PHP 7.2

**Comment by jeromegamez** [comment]
The documentation and the Setup section are there so that you don't have to assume :) - and Client SDK != Admin SDK. But here you are:

- Fine grained error messages: cdcdb2f5c2e9e8bec4db6e4c4366d1c07d559135
- Link from Installation to Setup: 7f57ded261a67773b202112b70939bd3e869f976
