### ISSUE TITLE
can i combine slim and firebase-php

### ISSUE THREAD

**Issue by kiam123** [kreait/firebase-php#251]
can i combine slim and firebase-php? Because i have slim and firebase-php two project, but they have different vendor folder and autoload.php

**Comment by jeromegamez** [comment]
If you want to use them together, you have to install the Firebase SDK inside your Slim Project, not separately, so that they share one vendor folder and autoload.php.

So, inside your Slim folder (which already has a `vendor` dir, you can add the SDK like this.

```bash
cd path/to/my/slim-project
composer require kreait/firebase-php
```
