### ISSUE TITLE
An uncaught Exception was encountered

### ISSUE THREAD

**Issue by subi786** [kreait/firebase-php#252]
**_PHP version 7.2_**

** FIrebase SDK version 3.9.2**

## The problem

An uncaught Exception was encountered
Type: Kreait\Firebase\Exception\ApiException

## Environment

- PHP Version (`7.2`):
- Firebase PHP SDK version (`3.9.2`):

## Details

When i am working on my local server (MAMP) it is working fine. But when i try to upload my code on server then this error occurs.
An uncaught Exception was encountered
Type: Kreait\Firebase\Exception\ApiException
Message: cURL error 7: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Filename: /home/www/projects.gianttech.net/test/qem/vendor/kreait/firebase-php/src/Firebase/Exception/ApiException.php

Line Number: 40

i don't know why this error is occurring. Please help me out to resolve this issue. Thanks.

**Comment by jeromegamez** [comment]
Hey @subi786, cURL Error 7 means "Couldn't connect" (see https://curl.haxx.se/libcurl/c/libcurl-errors.html#CURLECOULDNTCONNECT). You could try debugging this on your server by issuing a `curl -XGET -I https://<your-project>.firebaseio.com/.json` (you can find the URL of your realtime database in the Database section of the Firebase Web Console) - if you get a response from the console command, it could be that you have to update the PHP cURL bindings on your systems.

If you can't connect, perhaps the Firewall on your server is set to block outgoing requests.
