### ISSUE TITLE
with openssl_sign error

### ISSUE THREAD

**Issue by superbogy** [kreait/firebase-php#256]
openssl_sign(): supplied key param cannot be coerced into a private key

php 7.1.22

"kreait/firebase-php": "^4.17",

**Comment by jeromegamez** [comment]
Sorry, but this is not a report I can work with - the error is not a bug in the SDK. Please ensure that:

- you have recent version of openssl on the system
- PHP is compiled with the openssl extension
- you are using the correct Service Account credentials

Have a look at the following issues for further hints:

- https://github.com/firebase/php-jwt/issues/98
- https://stackoverflow.com/questions/37801444/setting-up-firebase-v3-custom-auth-with-php/38002277#38002277

**Comment by jeromegamez** [comment]
I closed the MR as it is not directly related to this library, but feel free to add further comments and share your findings in case you get to a solution, so that others can benefit.
