### ISSUE TITLE
Foreach from a snapshot

### ISSUE THREAD

**Issue by rebigliazzi** [kreait/firebase-php#257]
## The problem

Hi,
There is no problem, there is a doubt.
I would like to know how to perform a foreach, from a snapshot?
Tks

## Environment

- PHP Version (`php -v`): 7.2.10
- Firebase PHP SDK version (`composer show | grep kreait`): latest

## Details

https://pastebin.com/NJTZtJvq

**Comment by jeromegamez** [comment]
You have to use `->getSnapshot()->getValue()` or `->getValue()` to get the data from the retrieved Snapshot.

PS: Please include the code example in the issue description next time :)

**Comment by rebigliazzi** [comment]
Tks @jeromegamez ,

Follow the snapshot results
https://pastebin.com/9ybi8Qq7

I need to make a foreach of this arrays to put the results in a table

Tks

**Comment by jeromegamez** [comment]
A Snapshot object is class is not iterable- if you want to access the object properties, you have to use Reflection 

http://php.net/manual/en/book.reflection.php
