### ISSUE TITLE
Error : Call to private Method

### ISSUE THREAD

**Issue by Isaac009** [kreait/firebase-php#258]
I am using Firebase Admin SDK for PHP v 3.9.3
Problem 
Error: Call to private method Kreait\Firebase\ServiceAccount::fromJsonFile() from context 

While trying to use some methods as follows;
$serviceAccount = ServiceAccount::fromJsonFile(__DIR__ . '/firebase_credentials.json');
        $firebase = (new Factory)
            ->withServiceAccount($serviceAccount)
            ->create();
I tried to edit fromJsonFile() from private to public and seemed like it worked then I landed to another issue, this method  withServiceAccount does not exists
Error : Call to undefined method Kreait\Firebase\Factory::withServiceAccount()

**Comment by jeromegamez** [comment]
As you're using the 3.x branch of the SDK, the 4.x documentation doesn't apply. On the documentation pages, there's a version switcher at the bottom left where you can select the version of the SDK that you're using.

The 3.x documentation is located here: https://firebase-php.readthedocs.io/en/3.9.3/overview.html

Out of curiosity, why aren't you using version 4.x of the SDK?

**Comment by Isaac009** [comment]
Honestly, I didn't know if version 4.x was existing... I upgraded to version 4.8.0 and it worked perfectly, thanks a lot.

**Comment by jeromegamez** [comment]
Good to hear! You can upgrade straight to 4.17 - except if there is a limitation that I‘m not aware of :/

**Comment by Isaac009** [comment]
> Good to hear! You can upgrade straight to 4.17 - except if there is a limitation that I‘m not aware of :/

I will try it and let you know...

**Comment by jeromegamez** [comment]
I closed the issue as it‘s not a bug, but feel free to add further comments if needed.

**Comment by Isaac009** [comment]
> I closed the issue as it‘s not a bug, but feel free to add further comments if needed.

OK
