### ISSUE TITLE
Unable to use set???

### ISSUE THREAD

**Issue by ziron999** [kreait/firebase-php#259]
Please avoid using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a help channel at https://gitter.im/kreait/firebase-php (you can sign in with your GitHub account). If nobody can answer your question, tag @jeromegamez in your question.

Also see past issues and https://firebase-php.readthedocs.io/en/latest/troubleshooting.html to check if your problem has already been covered.

Please chose a descriptive title for your issue and delete everything before and including this line before submitting the issue.

## The problem

Unable to use set during query

## Environment

- PHP Version (`php -v`):
PHP 7.0.32 (cli) (built: Sep 17 2018 14:40:36) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.0.3, Copyright (c) 2002-2017, by ionCube Ltd.
    with Zend OPcache v7.0.32, Copyright (c) 1999-2017, by Zend Technologies

- Firebase PHP SDK version (`composer show | grep kreait`):
kreait/firebase-php                  dev-master bd11f8f Firebase Admin SDK
kreait/firebase-tokens               1.7.1
kreait/gcp-metadata                  1.0.1  

## Details

Why is set not found???

Full ERROR:
Fatal error: Uncaught Error: Call to undefined method Kreait\Firebase\Database\Snapshot::set() in /home/public_html/authTokenUpdate.php:62 Stack trace: #0 /home/public_html/authTokenUpdate.php(97): FIREBASEauthTokenUpdate->updateToken(Array, 'testemail') #1 {main} thrown in /home/public_html/authTokenUpdate.php on line 62

## Code to reproduce issue

```
	public function updateToken(array $Token, string $Email)
	{
		if (empty($Token) || empty($Email) || !isset($Token)|| !isset($Email)) { return false; }
		if ($this->database->getReference($this->dbname)->getSnapshot()->hasChild($Email))
		{
			foreach ($Token as $key => $value)
			{
				$reference = $this->database->getReference($this->dbname)->getSnapshot()->getChild($Email)->getChild($key);
				$attempt = $reference->set($value);
				$attempt;
			}
			return true;
			//email not in database
		} else { echo "Email not in database"; }
	}
```

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by jeromegamez** [comment]
Duplicate of #260
