### ISSUE TITLE
equalTo

### ISSUE THREAD

**Issue by 4dglobal** [kreait/firebase-php#26]
Hi,

I wonder is there a reason why equalTo is not implemented into this package?

https://www.firebase.com/docs/web/api/query/equalto.html

**Comment by jeromegamez** [comment]
Good question :). I will look to implement it in the coming days, thanks for the notice!

**Comment by jeromegamez** [comment]
Hey @4dglobal, equalTo support is implemented in [Release 1.1](https://github.com/kreait/firebase-php/releases/tag/1.1) 🎉
