### ISSUE TITLE
Send push notification to TOPIC with Condition & Enable Sound/Vibration

### ISSUE THREAD

**Issue by hassaan-dev** [kreait/firebase-php#262]
According to this [documentation](https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#send-conditional-messages) 
It easy to send notification to specific topic or condition but I need to send notification to specific topic with condition. 

So, is it possible to use `withTarget` multiple times with same request?

2nd. I want to add default sound  & vibration to push notification for web & iOS.
Can someone guide me in this?

**Comment by jeromegamez** [comment]
The title of this issue doesn't match the description.

You can send a fully configured message to a condition as described in the documentation.

Sending a message to multiple targets in one request is not possible (see also #261, #192), but I just released [4.18.0](https://github.com/kreait/firebase-php/releases/tag/4.18.0) which allows you to re-use a message to send it to another target: https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html#changing-the-message-target

I know this is not optimal, but at the moment it's the best we can do without breaking backwards compatibility.

**Comment by hassaan-dev** [comment]
Can you guide me to enable sound on notification?

**Comment by hassaan-dev** [comment]
I done the sound notifcation with [RAW](https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#sending-a-fully-configured-raw-message) message
