### ISSUE TITLE
"GOOGLE_APPLICATION_CREDENTIALS" is not set

### ISSUE THREAD

**Issue by alexlovar** [kreait/firebase-php#263]
## The problem

run the script always give me a fatal error
Fatal error: Uncaught Kreait\Firebase\Exception\ServiceAccountDiscoveryFailed: Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "FIREBASE_CREDENTIALS" is not set.

## Environment

`- PHP Version (`php -v`): PHP 7.2.11-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 25 2018 06:44:08) ( NTS )
- Firebase PHP SDK version (`composer show | grep kreait`):
kreait/firebase-php                  4.18.0   Firebase Admin SDK
kreait/firebase-tokens               1.7.2    A library to work with Firebase tokens
kreait/gcp-metadata                  1.0.1    Get the metadata from a Google Cloud Platform environment.`

## Details

the enviroment var already set the command  **printenv** give me this:

GOOGLE_APPLICATION_CREDENTIALS=/var/www/html/myjson.json
........
FIREBASE_CREDENTIALS=/var/www/html/myjson.json

 **the .json file is with the correct information and structure**

i created the defual auth file with  gcloud auth application-default login and get the default json file too.

## Code to reproduce issue

the php code that i run:

````
<?php
require 'vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;
use Kreait\Firebase;

$serviceAccount = ServiceAccount::fromJsonFile('/var/www/html/myjson.json');
$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->create();
```

**Comment by alexlovar** [comment]
the real problem was that php can't read enviroment vars, this must be declar into the etc/apache2/envars
add this lines to this file, solved my problem

export GOOGLE_APPLICATION_CREDENTIALS=/var/www/html/myjson.json
export FIREBASE_CREDENTIALS=/var/www/html/myjson.json

**Comment by jeromegamez** [comment]
You don‘t need to declare environment variables when using `ServiceAccount::fromJsonFile()` - environment variables are only used with autodiscovery
