### ISSUE TITLE
Not sound in IOS

### ISSUE THREAD

**Issue by leonelsonpalima** [kreait/firebase-php#265]
Greetings, friends
I have a problem sending a notification with the library.
In iOS it receives the notification, but without sound.
When I send the notification from Firebase if it has sound, has it happened to you before?

**Comment by jeromegamez** [comment]
Hey @leonelsonpalima! It's hard to help if you don't use the template that you have been given when creating this issue, especially without an example of the code that you used and that didn't work as expected.

That said, you can find the documentation on platform specific configuration at https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#adding-target-platform-specific-configuration, for the ApnsConfig at https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#apns

The docs also include a link to the Google documentation at https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#apnsconfig which in turn links to the Apns Service Developer documentation at https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1
