### ISSUE TITLE
Custom push key

### ISSUE THREAD

**Issue by kenramirez12** [kreait/firebase-php#267]
Hello, i need to push user info into the database, i'm doing this way:

```
//...
$createdUser = $this->auth->createUser($userProperties); 

$query = [
                $createdUser->uid => [
                    'email' => $createdUser->email,
                    'uid' => $createdUser->uid,
                ]
            ];

$database = $this->firebase->getDatabase();
$database->getReference('users')->push($query);

```
This insert the user info into the users data but with a random key at the beginning (red box in the image), but i need to set the uid as the key (green box in the image).

![captura](https://user-images.githubusercontent.com/23389041/48981411-1e179e80-f0a3-11e8-8b5d-7b8430c939b0.PNG)

There is a way to solve this? Thank you.

**Comment by jeromegamez** [comment]
If you want to specify a child key, use `set()` instead of `push()`:

```php
$data = [
    'email' => $createdUser->email,
    'uid' => $createdUser->uid,
];

$database->getReference('users/'.$createdUser->uid)->set($data);
// or
$database->getReference('users')->getChild($createdUser->uid)->set($data);
```

**Comment by kenramirez12** [comment]
> If you want to specify a child key, use `set()` instead of `push()`:
> 
> ```
> $data = [
>     'email' => $createdUser->email,
>     'uid' => $createdUser->uid,
> ];
> 
> $database->getReference('users/'.$createdUser->uid)->set($data);
> // or
> $database->getReference('users')->getChild($createdUser->uid)->set($data);
> ```

it works! thank you so much.

**Comment by jeromegamez** [comment]
You're welcome 😊
