### ISSUE TITLE
Problem catching AuthException

### ISSUE THREAD

**Issue by kenramirez12** [kreait/firebase-php#268]
Hello!, i'm got troubles catching a specific error when i try to register a new user: i put a long phone number to generate this error and i'm trying to get the message error to return it into a view but i can't.

```
try {
    $this->fbnewuser = $this->fbauth->createUser($this->fbuser_details);
 } catch(Kreait\Firebase\Exception\AuthException $e) {
    return $e->getMessage();
 }
```

Result:
![captura](https://user-images.githubusercontent.com/23389041/49237525-60efb400-f3cc-11e8-87ac-61cdaf6e7269.PNG)

Any idea please? Thank you!

**Comment by jeromegamez** [comment]
```php
try {
	$this->fbnewuser = $this->fbauth->createUser($this->fbuser_details);
} catch(\Kreait\Firebase\Exception\AuthException $e) {
    return $e->getMessage();
}
```

Please notice the leading `\` in front of `Kreait`

Either that, or add `use Kreait;` in your block of `use` statements at the top of your file.

**Comment by kenramirez12** [comment]
> ```
> try {
> 	$this->fbnewuser = $this->fbauth->createUser($this->fbuser_details);
> } catch(\Kreait\Firebase\Exception\AuthException $e) {
>     return $e->getMessage();
> }
> ```
> 
> Please notice the leading `\` in front of `Kreait` - without it, PHP tries to catch an exception inside your current namespace. If your current namespace is `App\Controller`, you would then try to catch `App\Controller\Kreait\Firebase\Exception\AuthException` and as this doesn't exist, it will never be caught.
> 
> Either that, or add `use Kreait;` in your block of `use` statements at the top of your file.

lol, thank you so much!
