### ISSUE TITLE
proxy setting 

### ISSUE THREAD

**Issue by linbob** [kreait/firebase-php#269]
the code like this:

$config = array(
    'proxy' => array(
        'https' => 'someDns:3128',
        'http' => 'someDns:3128'
    )
);
$serviceAccount = ServiceAccount::fromJsonFile('someFolder/google-service-account.json');
$firebase = (new Factory)->withServiceAccount($serviceAccount)->withHttpClientConfig($config)->create();
$reference = $firebase->getDatabase()->getReference('rooms');
$value = $reference->getValue();//error here
var_dump($value);

In linux without proxy environment, 
If I access firebase cli, I can get the value what I want. 
If I access the php code without proxy config, I can get the value.

In linux with proxy environment, 
If I access firebase cli, I still can get the value. 
If I access the code without proxy config, I cannot get the value.
If I access the code with proxy config, I cannot get the value and the error like this:

cURL error 28: Connection timed out after 150000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) someFolder/vendor/kreait/firebase-php/src/Firebase/Exception/ApiException.php, line: 40

How to set the proxy setting and have another way to access it ?

**Comment by jeromegamez** [comment]
Unfortunately, I am not able to help with proxy settings - as seen in the past, this is highly dependent on the environment, and it's not related to the library itself.

Please check out https://github.com/kreait/firebase-php/issues/176 and especially https://github.com/kreait/firebase-php/issues/176#issuecomment-372292671 (tracing the route can give a hint to what's wrong)

https://github.com/kreait/firebase-php/issues/234 could give some hints as well.
