### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response: { "error": "invalid_grant", "error_description": "Invalid JWT: Token must be a short-lived token

### ISSUE THREAD

**Issue by ramv55** [kreait/firebase-php#270]
require __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

// This assumes that you have placed the Firebase credentials in the same directory
// as this PHP file.
$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/critollfree-b3315-firebase-adminsdk-ssm2h-6da257d2a3.json');
// var_dump($serviceAccount);

$firebase = (new Factory)
            ->withServiceAccount($serviceAccount)
         ->withDatabaseUri('https://critollfree-b3315.firebaseio.com')
        ->create();

$database = $firebase->getDatabase();

$newPost = $database
    ->getReference('post')
    ->push([
        'title' => 'Post title',
        'category' => 'This should probably be longer.'
    ]);

$newPost->getKey();
$newPost->getUri(); 

$newPost->getChild('title')->set('Changed post title');
$newPost->getValue(); // Fetches the data from the realtime database
$newPost->remove();

I am working on localhost. i am getting following error.

 Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response: { "error": "invalid_grant", "error_description": "Invalid JWT: Token must be a short-lived token (60 minutes) and in (truncated...) in /Applications/XAMPP/xamppfiles/htdocs/tollfreeport/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/tollfreeport/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /Applications/XAMPP/xamppfiles/htdocs/tollfreeport/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /Applications/XAMPP/xamppfiles/htdocs/tollfreeport/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /Applications/XAMPP/xam in /Applications/XAMPP/xamppfiles/htdocs/tollfreeport/vendor/kreait/firebase-php/src/Firebase/Exception/ApiException.php on line 41

**Comment by jeromegamez** [comment]
The issue template is there for a reason :). Please update the issue with the requested information and please format the code samples so that they are readable.

Having parsed what you've given me so far, please check that the time in your environment is correct.

**Comment by ramv55** [comment]
No issue with time in my environment. I am using the code as per instruction which are given in this link https://firebase-php.readthedocs.io/en/stable/
I have installed firebase admin sdk through composer 
composer require kreait/firebase-php ^4.18

Can you please let me know what are the information should i send?
Thanks.

**Comment by ramv55** [comment]
Sorry the issue is with time in my system which lags 5 mins. issue has been solved when i correct my computer clock.
