### ISSUE TITLE
[Kreait\Firebase\Exception\FirebaseException] The url "" is invalid.

### ISSUE THREAD

**Issue by waleedazam** [kreait/firebase-php#276]
hello
i run php artisan config:cache
and php artisan cache:clear
but this error appear
[Kreait\Firebase\Exception\FirebaseException] The url "" is invalid.
and all firebase request return with exception The url "" is invalid.
@jeromegamez
i am using version 1 with php 5 and laravel 5.2

**Comment by jeromegamez** [comment]
I'm closing this because the problem is not related to the library itself, and the PHP, Laravel and Firebase SDK versions you are using are unsupported since several years - also, you have cross-posted this in Gitter :)
