### ISSUE TITLE
verifyAuthTime throws InvalidToken exception when auth time is in the future

### ISSUE THREAD

**Issue by pasmat** [kreait/firebase-php#278]
## The problem

I am using Android library to generate firebase authentication token which I am sending to server, however due to time synchronization difference in my server and firebases server, the token is in the future, by couple of seconds..

a $allowFutureTokens parameter is provided to verifyIdToken, but it only helps with the issue when the token is issued in the future, not when the tokens auth_time is in the future.

If $allowFutureTokens is to be supported, it should perhaps work when auth_time is in future too. a possible fix would be just to make Verifier's verifyAuthTime function throw IssuedInTheFuture exception when auth_time is in future.

in this case IssuedInTheFuture isn't really a well describing name to the exception. Instead of having a hard no, there could also be a maximum amount of time the token can be in future for it to be accepted, however I don't even understand why its a security concern to accept future tokens?

Shouldn't we just trust the authentication server to provide sane tokens, or is this a common practice when verifying tokens?

**Comment by jeromegamez** [comment]
Could you please try if https://github.com/kreait/firebase-php/tree/a-different-kind-of-future works for you? I don‘t like what this functionality has become, but for know I‘m fine with it if it gets the job done :)

**Comment by jeromegamez** [comment]
Released with [4.19.0](https://github.com/kreait/firebase-php/releases/tag/4.19.0)
