### ISSUE TITLE
Getting Permission Denied while getting reference data

### ISSUE THREAD

**Issue by tejasrsuthar** [kreait/firebase-php#28]
First of all thanks for the contribution. 

I'm getting permission denied while fetching reference from Firebase. Steps to reproduce.

- Install firebase-php via Composer
- Setup Service account in Google
- Get .JSON file for service account creation and set it up in my project folder

```
$config = new Configuration();
$config->setAuthConfigFile(__DIR__.'google-service-account.json');
$firebase = new Firebase(FIREBASE_URL, $config);
$result = $firebase->get('test');
```

**Exact Error Received:**
Fatal error: Uncaught exception 'Kreait\Firebase\Exception\PermissionDeniedException' with message 'Server error (401) for URL FBURL_HERE/test.json with data "": Permission denied' in C:\wamp\www\test_firebase_api\vendor\kreait\firebase-php\src\Exception\FirebaseException.php on line 80

Using [version 1.x ](http://firebase-php.readthedocs.io/en/1.x/search.html?q=permission&check_keywords=yes&area=default)

Am I doing anything wrong or any steps missing??

**Comment by tejasrsuthar** [comment]
Sorry, It was from my side. 
I was able to get it resolved by giving **read permission** from database tab from firebase console.

**Comment by jeromegamez** [comment]
From what I can see, it looks like there's missing a slash `__DIR__.'/google-service-account.json' - of course, in this case, the library should have thrown a PHP error or a warning...

**Comment by jeromegamez** [comment]
Ah, very good, you resolved it yourself. Sometimes it helps to just talk about it :).

**Comment by tejasrsuthar** [comment]
@jeromegamez No, I think, with newly created test app, I just forgot to give read access. Everything seems to be fine now.
