### ISSUE TITLE
Issue encountered in Firebase.php

### ISSUE THREAD

**Issue by Rashrish** [kreait/firebase-php#281]
Thanks a lot for the excellent piece of work. 
## The problem
The Admin SDK has no issues when run from localhost, but when run from shared hosting server (production server) the code breaks without throwing any errors.  The investigation shows that the code breaks in kreait\vendor\kreait\firebase-php\src\Firebase.php.

## Environment

- PHP Version (`php -v`): PHP 7.0.33
- Firebase PHP SDK version: 4.18.1 (production);  4.13 (localhost)

## Details

The below lines from Firebase.php cause the problem 

    public function getDatabase(): Database
    {
        return $this->database;
    }

    public function getAuth(): Auth
    {
        return $this->auth;
    }

    public function getStorage(): Storage
    {
        return $this->storage;
    }

    public function getRemoteConfig(): RemoteConfig
    {
        return $this->remoteConfig;
    }

    public function getMessaging(): Messaging
    {
        return $this->messaging;
    }

when all the above lines are commented, the control at least flows just before the below line and hitting the below line obviously breaks because of the above commented lines.

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__."/$_serviceAccountFilename");

The domain is whitelisted in the firebase console.  Any help would be great, please.

**Comment by jeromegamez** [comment]
If no errors are thrown, the error reporting on the production system seems to be disabled (which is fine :D), but for debugging, could you please add the following lines in the script that causes the error:

```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
echo 'Current PHP version: ' . phpversion();
```

This should temporarily show the error that occurs and show the PHP version before throwing the error.

It would also help if you provided the code that you use to instantiate the Firebase instance. For example, the `Firebase` class and the `ServiceAccount` class are not related, meaning: if `ServiceAccount::fromJsonFile()` breaks, this has nothing to do with the methods of the `Firebase` class being commented out.

**Comment by jeromegamez** [comment]
The usual candidates for code not working are:

- Unsupported PHP version:
  - If you use the SDK 4.x on a PHP 5 environment, the code will break because it's not PHP5 compatible
  - If you do `composer install` on a PHP 5 environment, an 1.x release of the SDK will be installed instead of the 4.x release
- Missing import statements and/or missing requiring the composer autoloader

Just from the top of my head - if you provide a full code example that leads to the error, I can help investigate further

**Comment by Rashrish** [comment]
Thanks.  With appropriate functions I always log errors with the script name and the line number, but this issue does not log any errors just breaks, I tried few times to ensure it.  I simplified the code as follows to test.  The php version in production is 7.0.33 and firebase admin SDK is 4.18.1 and in the localhost php is 7.0.3 with firebase SDK 4.18.0. 

/** start of the php script **/

echo "Checkpoint 1 ...";

require __DIR__.'/composer/firebase/kreait/vendor/autoload.php';

echo "Checkpoint 2 ...";

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

echo "Checkpoint 3 ...";
$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/firebase-adminsdk-key.json');

echo "Checkpoint 4 ...";  

/** end of the script **/
 
This script on production server breaks after displaying "Checkpoint 1" but on local server (localhost) crosses all 4 checkpoints.  As I mentioned earlier the autoload.php invokes autoload_real.php which includes (require) all the necessary files including Firebase.php where the script breaks exactly at the very first line that I stated in my first message.  If it would be no inconvenience and uncomfortable to you I can create a test account on the server in question with a redundant domain I have and give the credentials to you to test but not sure if I can email you or provide my email id, this is my humble suggestion, provided that there is no convenience to you at all.  Thank you again for your help.

> If no errors are thrown, the error reporting on the production system seems to be disabled (which is fine :D), but for debugging, could you please add the following lines in the script that causes the error:
> 
> ```
> ini_set('display_errors', 1);
> ini_set('display_startup_errors', 1);
> error_reporting(E_ALL);
> echo 'Current PHP version: ' . phpversion();
> ```
> 
> This should temporarily show the error that occurs and show the PHP version before throwing the error.
> 
> It would also help if you provided the code that you use to instantiate the Firebase instance. For example, the `Firebase` class and the `ServiceAccount` class are not related, meaning: if `ServiceAccount::fromJsonFile()` breaks, this has nothing to do with the methods of the `Firebase` class being commented out.

**Comment by Rashrish** [comment]
The problem is resolved, it was with the version mismatch in the sub domain config, also removed and upgraded to Firebase SDK 4.18.2.  Your clues on versions helped to fix the issue.  Thanks a lot for the help and for the excellent piece of work.
