### ISSUE TITLE
multiple arduino to 1 firebase is supported by kreait?

### ISSUE THREAD

**Issue by xiaomy12** [kreait/firebase-php#285]
Please avoid using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a help channel at https://gitter.im/kreait/firebase-php (you can sign in with your GitHub account). If nobody can answer your question, tag @jeromegamez in your question.

Also see past issues and https://firebase-php.readthedocs.io/en/latest/troubleshooting.html to check if your problem has already been covered.

Please chose a descriptive title for your issue and delete everything before and including this line before submitting the issue.

## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added). 

## Environment

- PHP Version (`php -v`):
- Firebase PHP SDK version (`composer show | grep kreait`):

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code to reproduce issue

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by jeromegamez** [comment]
Please use the issue tracker as it is intended to be used, you were given an issue template, you should have read and used it :)

To answer your question: there is no reason why you shouldn't be able to install the SDK on multiple arduinos.
