### ISSUE TITLE
"error": { "code": 400, "message": "INSUFFICIENT_PERMISSION"

### ISSUE THREAD

**Issue by zigou13** [kreait/firebase-php#286]
Hello, I encounter this error when disabling a user

Fatal error: Uncaught GuzzleHttp \ Exception \ ClientException: Client error: `POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/setAccountInfo` resulted in a 400 Bad Request` response: {" error ": {" code ": 400," message ":" INSUFFICIENT_PERMISSION "," errors ": [{" message ":" IN (truncated ...) in / home / stadi168 / api-external / firebase-php-master / vendor / guzzlehttp /guzzle/src/Exception/RequestException.php:113 Stack trace: # 0 /home/stadi168/api-externe/firebase-php-master/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp \ Exception \ RequestException :: create (Object (GuzzleHttp \ Psr7 \ Request), Object (GuzzleHttp \ Psr7 \ Response)) # 1 / home / stadi168 / api-external / firebase-php-master / vendor / guzzlehttp / promises / src / Promise .php (203): GuzzleHttp \ Middleware :: GuzzleHttp \ {Closure} (Object (GuzzleHttp \ Psr7 \ Response)) # 2 / home / stadi168 / api-external / firebase-php-master / vendor / guzzlehttp / promises / src /Promise.php(156): GuzzleHttp \ Promise \ Promise :: callHandler (1, Object (GuzzleHttp \ Psr7 \ Response), Arr ay) # 3 / in /home/stadi168/api-externe/firebase-php-master/src/Firebase/Exception/AuthException.php on line 55

Can you help me
thank you

**Comment by jeromegamez** [comment]
Could you please share the code that you executed to get this error? Insufficient permissions could mean that not all necessary APIs are enabled for your project, please check https://firebase-php.readthedocs.io/en/latest/troubleshooting.html#forbidden-errors to make sure that all APIs are enabled.

**Comment by zigou13** [comment]
Hello, Yes they are active API link, here is the code

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromJsonFile('/home/stadi168/api-externe/firebase-php-master/stadiumgo-76cf0-0f650717e3f9.json');

$firebase = (new Factory)
	->withServiceAccount($serviceAccount)
	->create();
$auth = $firebase->getAuth();
$uid = 'F6pcXQqhW7gtM1HozUBQafZf6Up2';
$user = $auth->getUser($uid);

**Comment by zigou13** [comment]
OR 

$serviceAccount = ServiceAccount::fromJsonFile('/home/stadi168/api-externe/firebase-php-master/stadiumgo-76cf0-0f650717e3f9.json');

$firebase = (new Factory)
->withServiceAccount($serviceAccount)
->create();

$database = $firebase->getDatabase();
//debug($database);
$newPost = $database
    ->getReference('blog/posts')
    ->push([
        'title' => 'Post title',
        'body' => 'This should probably be longer.'
    ]);

$newPost->getKey(); // => -KVr5eu8gcTv7_AHb-3-
$newPost->getUri(); // => https://my-project.firebaseio.com/blog/posts/-KVr5eu8gcTv7_AHb-3-

$newPost->getChild('title')->set('Changed post title');
$newPost->getValue(); // Fetches the data from the realtime database
//$newPost->remove();

**Comment by jeromegamez** [comment]
Which line causes the error then? I assume `getKey()` and `getUri()` worked?

Do you have security rules on your firebase database that prevent write operations? Has the Service Account you're using sufficient permissions to write/delete items from the Realtime Database?

Do be sure, please issue a new Service Account file from your project settings and try again.

**Comment by zigou13** [comment]
if I just have this code I always have an error

```
use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromJsonFile('/home/stadi168/api-externe/firebase-php-master/stadiumgo-76cf0-0f650717e3f9.json');

$firebase = (new Factory)
	->withServiceAccount($serviceAccount)
	->create();


$auth = $firebase->getAuth();
$uid = 'F6pcXQqhW7gtM1HozUBQafZf6Up2';

$updatedUser = $auth->disableUser($uid);
debug($updatedUser);
```

I recreated the service account 5 times

**Comment by zigou13** [comment]
no restrictions on firebase

`{
  /* Visit https://firebase.google.com/docs/database/security to learn more about security rules. */
  "rules": {
    ".read": true,
    ".write": true
  }
}`

**Comment by jeromegamez** [comment]
Okay, disabling a user is an operation that involves the authentication APIs… could you please try this:

```php
$serviceAccount = ServiceAccount::fromJsonFile('path/to/your/service_account.json');
$firebase = (new Factory())
    ->withServiceAccount($serviceAccount)
    ->create();

$auth = $firebase->getAuth();

$user = $auth->createAnonymousUser();

echo 'User created'.PHP_EOL;
var_dump($user);

$disabledUser = $auth->disableUser($user->uid);

echo 'User disabled'.PHP_EOL;
var_dump($disabledUser);

$auth->deleteUser($disabledUser->uid);
```

If this works (it does for me), your service account is generally capable of creasting/updating/deleting users, and something is "wrong" with the user you're trying to access. In that case, please ensure that the user is indeed part of the project you're using (= you can see them in the Firebase Web Console in your project).

**Comment by zigou13** [comment]
I just understood my problem, on console google, in the service account, I had to create a we account then I should create a key on the existing account firebase sdk admin 

Thank You !

**Comment by jeromegamez** [comment]
Good to hear, glad you got it working! 🎉
