### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by zigou13** [kreait/firebase-php#291]
Hello I would like to have a descending order on the value date_timestamp by key
Here is my code

`$list = $database->getReference('previsions/')->orderByChild('date_timestamp')->getKey();`

and here is the image of firebase
![Capture](https://user-images.githubusercontent.com/32574412/54757384-6591df80-4bea-11e9-9313-8904ddcfa857.PNG)
`{
  "rules": {
    "previsions": {
    	".read": true,
    	".write": true,
     	".indexOn": ["date_timestamp"] 
    }
  }
}`
Can you help me ?

**Comment by jeromegamez** [comment]
The Firebase Realtime Database doesn't support sorting other than in ascending order, so you will have to work around that. This StackOverflow answer describes a workaround based on a date based decreasing priority: https://stackoverflow.com/a/25613337 

In the context of this SDK, this would mean pushing data something like this:

```php
$database->push([
    'date_timestamp' => time(),
    '.priority' => 0 - time(),
]);
```

Unfortunately, the PHP SDK doesn't provide any priority related functionality so far (I'm surprised I missed this and that nobody needed it so far ^^), but I'm adding it to my to do list and hope to have a new release ready in the near future.

**Comment by zigou13** [comment]
Ok thank you :)

**Comment by jeromegamez** [comment]
Okay, I remember now why I didn't implement this: [the REST API Documentation has a section on priorities](https://firebase.google.com/docs/database/rest/retrieve-data#orderbypriority), but I couldn't get it to work back then (and also didn't get it to work today).

The official JavaScript library [has an `orderByPriority()` method](https://firebase.google.com/docs/reference/js/firebase.database.Query#orderByPriority), but also says "Applications need not use priority but can order collections by ordinary properties (see Sort data for alternatives to priority."

And in addition to that, according to Frank, who works on Firebase [priorities are a relic from the past](https://stackoverflow.com/a/31578297/284325).

With all that met-information, here is the solution to your problem: when saving your data, add an additional field that you use explicitly for sorting:

```php
$now = time();

$ref->push([
    'date_timestamp' => $now,
    'sort_value' => 0 - $now,
]);
```

and for retrieving the values:

```php
$orderedByTimeStamp = $ref->orderByChild('timestamp')->getValue();
$orderedBySortValue = $ref->orderByChild('sort_value')->getValue();
```

Please note that you'll have to add an index to the `sort_value` field in the Firebase RealTime Database Rules.

I hope, this helps!

**Comment by jeromegamez** [comment]
BTW, if you push values as children to a reference, you can use the child keys to order them by timestamp (just in case you used the `date_timestamp` field only for that purpose ^^

Here is my complete script that I used to test if the method I described above actually works:

```php
<?php

require 'vendor/autoload.php';

use Kreait\Firebase\Database\RuleSet;
use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;
use Kreait\Firebase\Util\JSON;

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/tests/_fixtures/test_credentials.json');
$firebase = (new Factory())
    ->withServiceAccount($serviceAccount)
    ->create();

$db = $firebase->getDatabase();
$rules = $db->getRules()->getRules();

$rules['rules']['sorting_test'] = [
    '.indexOn' => ['timestamp', 'sort_value'],
];

// $db->updateRules(RuleSet::fromArray($rules));

$ref = $db->getReference('sorting_test');
// $ref->remove();

$now = new DateTimeImmutable();

$newChild = $ref->push([
    'display_date' => $now->format('d-m-Y'),
    'timestamp' => $now->getTimestamp(),
    'sort_value' => 0 - $now->getTimestamp(),
]);

$orderedByTimeStamp = $ref->orderByChild('timestamp')->getValue();
$orderedBySortValue = $ref->orderByChild('sort_value')->getValue();

echo JSON::prettyPrint($orderedByTimeStamp);
echo JSON::prettyPrint($orderedBySortValue);
```

**Comment by zigou13** [comment]
Ok it works well, if I want to make an
`orderByChild ('date_timestamp') DESC,`
is it possible? or
`orderByChild ('date_timestamp')->startAt(time())`

because the result is the same in both cases

**Comment by jeromegamez** [comment]
It‘s not possible to sort in descending order, the Firebase API doesn‘t support that. If you followed the example, `orderByChild('sort_value')` should give you what you want.

You can of course rename („sort_value“) to anything you like, e.g. „reversed_date_timestamp“ or something else that makes the intention clearer.

In addition, you could add helper functions in your project to hide this perhaps unintuitive workflow.

**Comment by zigou13** [comment]
Ok, the order works well but I have you order too.
Question: API supports FCM? to send notifications via a php project

**Comment by jeromegamez** [comment]
Yes: https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html

**Comment by zigou13** [comment]
Ok, thanks for your help.
