### ISSUE TITLE
ForEach on DataSnapshot

### ISSUE THREAD

**Issue by m-eyal** [kreait/firebase-php#292]
## The problem
Iterating over a DataSnapshot is not available in the PHP SDK, in contrast to the JS SDK [(https://firebase.google.com/docs/reference/js/firebase.database.DataSnapshot#foreach)](url).

Briefly describe the issue you are experiencing (or the feature you want to see added). 
This is the node I need to query:

 "users_groups" : {
    "iXdpQnOK2WOTjVIR96PE2qG7cey2" : {
      **"-LaVlWUXvtuLAcJ_khiZ"**,
      "-LaWPacHNu3w43rw83e2",
    },
    "sXzsoY5zBcdSSY1XzAtUSUvWjLo2" : {
      **"-LaVlWUXvtuLAcJ_khiZ"** ,
      "-LaWVtDwQshC6aenUNKT"
    }
  }

I would like to query the 'users_groups' node and once I have the whole node - perform a "forEach()" in order to find and remove all instances of a specific "id" (the lines in Bold are the ones I'm looking to remove from the node).

As far as I know I can perform a query on each "child", but on the JS SDK the ForEach feature is a more efficient and reliable way to achieve what I need.

Any help would be much appreciated.
## Environment

- PHP Version (`php -v7.3`):
- Firebase PHP SDK version (4.18.2):

**Comment by jeromegamez** [comment]
Assuming that the JSON that you provided was meant to look like this:

```json
{
    "user_groups": {
        "iXdpQnOK2WOTjVIR96PE2qG7cey2": [
            "-LaVlWUXvtuLAcJ_khiZ",
            "-LaWPacHNu3w43rw83e2"
        ],
        "sXzsoY5zBcdSSY1XzAtUSUvWjLo2": [
            "-LaVlWUXvtuLAcJ_khiZ",
            "-LaWVtDwQshC6aenUNKT"
        ]
    }
}
```

<img width="344" alt="image" src="https://user-images.githubusercontent.com/67554/54880169-53aa7980-4e42-11e9-88b0-94b3fd24ae49.png">

Depending on how atomic you want to be, there are different ways to approach this:

### Iterate and delete each user id individually

```php
$userGroupsRef = $db->getReference('user_groups');

$userIdToDelete = '-LaVlWUXvtuLAcJ_khiZ';

foreach ($userGroupsRef->getValue() as $groupId => $userIds) {
    foreach ($userIds as $key => $userId) {
        if ($userId === $userIdToDelete) {
            $userGroupsRef->getChild($groupId.'/'.$key)->remove();
        }
    }
}
```

<img width="337" alt="image" src="https://user-images.githubusercontent.com/67554/54880224-d16e8500-4e42-11e9-8446-a39f17f5b29c.png">

### Iterate and rewrite each group individually

```php
$userGroupsRef = $db->getReference('user_groups');

$userIdToDelete = '-LaVlWUXvtuLAcJ_khiZ';

foreach ($userGroupsRef->getValue() as $groupId => $userIds) {
    $newUserIds = array_values(array_filter($userIds, function ($userId) use ($userIdToDelete) {
        return $userId && $userId !== $userIdToDelete;
    }));

    $userGroupsRef->getChild($groupId)->set($newUserIds);
}
```

<img width="337" alt="image" src="https://user-images.githubusercontent.com/67554/54880304-a0db1b00-4e43-11e9-97b8-754c20f55096.png">

### Rewrite all user groups in one go

```php
$userGroupsRef = $db->getReference('user_groups');

$userIdToDelete = '-LaVlWUXvtuLAcJ_khiZ';
$rewrittenUserGroups = [];

foreach ($userGroupsRef->getValue() as $groupId => $userIds) {
    $newUserIds = array_values(array_filter($userIds, function ($userId) use ($userIdToDelete) {
        return $userId && $userId !== $userIdToDelete;
    }));

    $rewrittenUserGroups[$groupId] = $newUserIds;
}

$userGroupsRef->set($rewrittenUserGroups);
```

<img width="337" alt="image" src="https://user-images.githubusercontent.com/67554/54880304-a0db1b00-4e43-11e9-97b8-754c20f55096.png">

Note: `$ref->getValue()` is a shorthand for `$ref->getSnapshot()->getValue()`
