### ISSUE TITLE
ApiException Uncaught exception TypeError

### ISSUE THREAD

**Issue by maxehhh** [kreait/firebase-php#295]
The problem occurs sometimes and sometimes doesn't, unfortunately i can't access our docker container logs.
Getting return error type on ApiException line 35.

## Environment
- PHP 7.2.11
- Firebase Admin SDK 4.20.0
- Firebase-tokens 1.7.2 
- Gcp-metadata 1.0.1

## Details

> TypeError: Uncaught exception 'TypeError' with message 'Return value of Kreait\Firebase\Exception\ApiException::getPreciseMessage() must be of the type string, array returned' in /var/www/vendor/kreait/firebase-php/src/Firebase/Exception/ApiException.php:77

## Code to reproduce issue
```
$g = (new Kreait\Firebase\ServiceAccount())->fromJsonFile('./serviceAccountKey.json');
$firebase = (new Kreait\Firebase\Factory())->withServiceAccount($g)->create();

try {
  $database = $firebase->getDatabase();
  $database->getReference('notifications')->push($set); // Error line
  return $total;
} catch ( ApiException $e ) {
  $request = $e->getRequest();
  $response = $e->getResponse();
  error_log($request->getUri());
  error_log($request->getBody());

  if ($response) {
    error_log($response->getBody());
  }
}

**Comment by jeromegamez** [comment]
Hey @maxehhh and thanks for reporting this issue. I was able to recreate the issue by simulating an error response as described on https://firebase.google.com/docs/reference/rest/auth/#section-error-response

I'll fix this shortly and create a new release shortly after that.

**Comment by jeromegamez** [comment]
@maxehhh I'm confident that [4.20.1](https://github.com/kreait/firebase-php/releases/tag/4.20.1) will fix the issue 🎉

**Comment by maxehhh** [comment]
> @maxehhh I'm confident that [4.20.1](https://github.com/kreait/firebase-php/releases/tag/4.20.1) will fix the issue 🎉

Thank you very much 😄
