### ISSUE TITLE
Usage with Laravel

### ISSUE THREAD

**Issue by theunreal** [kreait/firebase-php#298]
Hi, similiar to the issue I opened 2 years ago:

https://github.com/kreait/firebase-php/issues/61

Now I did "composer update" and got the following error:

`Class 'Firebase' not found`

I am still using the same file as FirebaseProvider:

```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Firebase as FirebaseFactory;
use Firebase\V3\Firebase;

class FirebaseServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton(Firebase::class, function() {
            return FirebaseFactory::fromServiceAccount(
                // Here the file is in the project root, but it could be anywhere
                base_path('google-service-account.json')
            );
        });

        $this->app->alias(Firebase::class, 'firebase');
    }
}
```

**Comment by jeromegamez** [comment]
Unfortunately, you didn't use the template that you were provided when creating the issue, but I'm assuming you're updating to the 4.x release of the SDK?

**Comment by theunreal** [comment]
Yes @jeromegamez . I did composer update to update my project dependencies and got the 4.x version.

**Comment by jeromegamez** [comment]
If you want to stay on the 3.x branch, you should edit your composer dependencies to read like this:

```json
"require": {
  "kreait/firebase-php": "^3.0"
}
```
so that your current setup doesn't break.

**Comment by theunreal** [comment]
Thanks. I just opened the issue to let know that a documentation for the upgrade proccess between 2.x -> 3.x / 3.x -> 4.x would be nice to have.

**Comment by jeromegamez** [comment]
Wait, looking at the code example you've given, you're not upgrading from 3.x to 4.x, but from an earlier release (although I don't - for this you can find the upgrade path here: https://firebase-php.readthedocs.io/en/3.9.3/migration.html#x-to-3-0

You can see what has changed between 3.x and 4.x in the changelog at https://github.com/kreait/firebase-php/blob/master/CHANGELOG.md#400---2018-02-14, there is no distinct upgrade path.

Also, here's a Laravel example that should still work: https://github.com/kreait/firebase-php/issues/61#issuecomment-317985671

**Comment by jeromegamez** [comment]
@theunreal In case you need further information on how to integration the 4.x release with Firebase, there's a new tutorial here: https://medium.com/@javinunez/how-to-integrate-laravel-with-google-firebase-512188adae13
