### ISSUE TITLE
Can't unset all custom user attributes with auth->setCustomUserAttributes

### ISSUE THREAD

**Issue by clytras** [kreait/firebase-php#300]
## The problem

Hello. Thanks for the great library!

I have spent more than 5 hours trying to figure out how to completely unset user `customAttributes` using `getAuth()->setCustomUserAttributes` with no success. I've tried an empty array `[]`, an emty object `(object)[]` with no results. I tried with `null` but the type of arguments is an array unnullable. Finally after some debugging I figured out that in order to delete all custom attributes an empty object has to be given at the request data like this (printed with `json_encode($options)` at request function before `try/catch`):

`{"json":{"localId":"...","customAttributes":{}}}`

but the JSON encoding at https://github.com/kreait/firebase-php/blob/master/src/Firebase/Request/UpdateUser.php#L160 converts any objects to strings so firebase ignores them:

`{"json":{"localId":"...","customAttributes":"{}"}}`

When I removed the encoding and passed `$data['customAttributes'] = $this->customAttributes;` with `(object)[]` (haven't tried with single `[]`) firebase deleted all user custom attributes.

Unless I am missing something, I think in order for this to work there have to be a check whether `customAttributes` is an empty array and then pass without using JSON encoding and use JSON encoding for all other situations.

## Environment

- PHP Version:
```
PHP 7.1.29 (cli) (built: May  3 2019 07:39:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.29, Copyright (c) 1999-2018, by Zend Technologies
```

- Firebase PHP SDK version:
```
kreait/firebase-php                   4.22.0   Firebase Admin SDK
kreait/firebase-tokens                1.7.2    A library to work with Firebase tokens
kreait/gcp-metadata                   1.0.1    Get the metadata from a Google Cloud Platform environment.
```

## Code to reproduce issue

```
// Expecting to remove all custom user attributes and it does not
$firebase->getAuth()->setCustomUserAttributes($uid, []);
```

**Comment by jeromegamez** [comment]
Thank you for the detailed issue description! 

I just added 8004c59c2ee25075b79218b83a07d32e52f2d873, which should fix the issue. With this, you should get the expected result when executing the method as you wrote it, but you could also use `\Kreait\Firebase\Auth::deleteCustomUserAttributes($uid)` which does exactly the same 😅

Let me know if this works for you, and I will create a new release soon!

**Comment by clytras** [comment]
Hello @jeromegamez and thank for for tha superfast fix!

I can confirm that in https://github.com/kreait/firebase-php/commit/8004c59c2ee25075b79218b83a07d32e52f2d873 is now working as expected. Passing an empty array to `setCustomUserAttributes` will reset all custom user attributes and `deleteCustomUserAttributes` will also delete everything.

Thanks again! 🍺🍺🍻

**Comment by jeromegamez** [comment]
And [here's the 4.23 release](https://github.com/kreait/firebase-php/releases)! 🎉
