### ISSUE TITLE
PHP type

### ISSUE THREAD

**Issue by aliazizi** [kreait/firebase-php#301]
## The problem

For all method I get this error in PHPStorm ide

## Environment

- PHP Version (`php -v`): v7
- Firebase PHP SDK version (`composer show | grep kreait`): lastest

## Details

this because all `string` type should replace with `\string`

**Comment by jeromegamez** [comment]
This is an issue with the IDE configuration, not with the SDK itself (it works fine without the backslashes ^^). I had this once myself, but I don't remember right now how I fixed it... but it could be that it's a combination of mismatching PHP language level and PHP CLI interpreter settings.

Either way, this is not an issue within the SDK, so I'll close the issue, but feel free to add further comments/questions (or join the [kreait Discord](https://discord.gg/nbgVfty)), this is certainly something we can figure out!
