### ISSUE TITLE
How to use FCM parameter analytics_label to specify push platform ios or android

### ISSUE THREAD

**Issue by L-Y** [kreait/firebase-php#309]
```
use Kreait\Firebase\Messaging\FcmOptions;

$fcmOptions = FcmOptions::create()
    ->withAnalyticsLabel('my-analytics-label');
// or
$fcmOptions = [
    'analytics_label' => 'my-analytics-label';
];

$message = $message->withFcmOptions($fcmOptions);
```
my-analytics-label? 
How should I fill out, if I only give android push message

**Comment by jeromegamez** [comment]
If you do it like this, Firebase should™ automatically populate your Android push message with it. If you want to be more explicit, you could also do

```php
$message = $message->withAndroidConfig([
    'fcm_options' => [
		'analytics_label' => 'my-analytics-label'
    ]    
]);
```

The intention for both approaches is that you can specify an FCM option for the whole message for all target platforms (Android, APNs, WebPush) by using `withFcmOptions()` on the message and override values for specific platforms.

I hope this example helps:

```php

$message = CloudMessage::new()
    ->withFcmOptions(['analytics_label' => 'will-be-used-if-not-overridden'])
    ->withAndroidConfig([
        'fcm_options' => [
            'analytics_label' => 'overrides-label-for-android'
        ]
    ])
    ->withApnsConfig([
        'fcm_options' => [
            'analytics_label' => 'overrides-label-for-apns'
        ]
    ])
    // ->withWebPushConfig() is not used, so the label will be 'will-be-used-if-not-overridden'
;
```

**Comment by L-Y** [comment]
@jeromegamez As the information how to customize 'overrides-label-for-apns' and 'overrides-label-for-android',where do i set up?

**Comment by jeromegamez** [comment]
I think you can use any value you want, and it will appear (somewhere) in Firebase Analytics

**Comment by L-Y** [comment]
@jeromegamez I'm here to specify the package name, the package name of android but ios also received a push message,this code:
```
            $config ['android']= Firebase\Messaging\AndroidConfig::fromArray([
                'ttl' => ($data['validity']*3600)."s",
                'priority' => 'HIGH',
                'collapse_key' => 'new_msg',
                'restricted_package_name' => 'com.arabsada.news.debug',
//                'data' => json_encode($data),
                'notification' => [
                    'title' => $data["title"],
                    'body' => $data["description"],
//                    'icon' => '',
//                    'color' => '#f45342',
                    'click_action' => 'FLUTTER_NOTIFICATION_CLICK',
                    'image' => $data['img'],
                    'sound' => 'default',
                ]
            ]);
```

**Comment by jeromegamez** [comment]
Could you show me the full message configuration you're sending, please? If you're sending the message to a topic, all devices subscribed to the topic will receive a notification, no matter if Android, iOS or WebPush

If you send a message to a registration token only, only that device should receive the notification.

You could try to send a message only with android config and test if this changes something:

```php
$messaging->sendMessage([
    // 'token' => '...',
    // or
    // 'topic' => '...',
    // no other top level configuration
    'android' => [
        'ttl' => ($data['validity']*3600)."s",
        'priority' => 'HIGH',
        'collapse_key' => 'new_msg',
        'restricted_package_name' => 'com.arabsada.news.debug',
//                'data' => json_encode($data),
        'notification' => [
            'title' => $data["title"],
            'body' => $data["description"],
//                    'icon' => '',
//                    'color' => '#f45342',
            'click_action' => 'FLUTTER_NOTIFICATION_CLICK',
            'image' => $data['img'],
            'sound' => 'default',
        ]
    ]
]);
```

**Comment by L-Y** [comment]
@jeromegamez  this have full code,thank you!
[https://github.com/L-Y/golang_practice/blob/master/test.php](url)

**Comment by jeromegamez** [comment]
Everything looks ok to me on first glance - but again: if you're sending a message to a topic or condition, every subscribed device will receive a notification, you then cannot configure the message to "send only to android devices"

If I misunderstood the problem, please explain :)

**Comment by L-Y** [comment]
@jeromegamez You understand that's right, I just want to just give android message, but every time the ios also will receive a message, what should I do

**Comment by jeromegamez** [comment]
If you send to a topic or condition, I don't think there is something you can do, except subscribing all android devices to a topic like "android only" and send to that topic.

If you are sending to a list of tokens, you could filter the targets by using the App instance information introduced in release 4.28.0 of the SDK, see documentation here: https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html#app-instance-management

You could then do something like this:

```php
$tokens = [/*...*/];
$androidTokens = [];

foreach ($tokens as $token) {
    $appInstance = $messaging->getAppInstance($token);

    if (strtolower($appInstance->rawData()['platform'] ?? '') === 'android') {
        $androidTokens[] = $token;
    }
}

$messaging->sendMulticast($message, $androidTokens);
```

**Comment by L-Y** [comment]
ok ，I try it ,thank you !

**Comment by L-Y** [comment]
Call to undefined method Kreait\Firebase\Messaging::getAppInstance()?

**Comment by jeromegamez** [comment]
You're not using [release 4.28.0](https://github.com/kreait/firebase-php/releases/tag/4.28.0) of the SDK, please update.

**Comment by L-Y** [comment]
perfect！Very good！
