### ISSUE TITLE
Server error (400) for URL 

### ISSUE THREAD

**Issue by dungphanxuan** [kreait/firebase-php#31]
Hello, i try to run firebase on custom domain so it's has error
![screenshot_1](https://cloud.githubusercontent.com/assets/10725732/17705087/4fb4fa5e-6401-11e6-82d2-6aa2d6d78e0c.png)

How can i fix it. thank!

**Comment by jeromegamez** [comment]
Hi @dungphanxuan,

could you show me the command (in your PHP code) that you use? It seems as if you are doing a `set()` or `push()` without data.

**Comment by dungphanxuan** [comment]
It work thank you, that code set empty data so has error.
