### ISSUE TITLE
json decode error from service account.php

### ISSUE THREAD

**Issue by Techiedie** [kreait/firebase-php#310]
Uncaught Kreait\Firebase\Exception\InvalidArgumentException: C:\xampp\htdocs\fireabase/mydata.json could not be parsed to a Service Account: json_decode error: Syntax error in C:\xampp\htdocs\fireabase\vendor\kreait\firebase-php\src\Firebase\ServiceAccount.php:164 Stack trace: #0 C:\xampp\htdocs\fireabase\getdata.php(9): Kreait\Firebase\ServiceAccount::fromJsonFile('C:\\xampp\\htdocs...') #1 {main} thrown in C:\xampp\htdocs\fireabase\vendor\kreait\firebase-php\src\Firebase\ServiceAccount.php on line 164

```
<?php
require __DIR__.'/vendor/autoload.php';
use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

echo "Path = " .  __DIR__.'/mydata.json';
// This assumes that you have placed the Firebase credentials in the same directory
// as this PHP file.
$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/mydata.json');
echo "serviceAccount=".$serviceAccount;

$firebase = (new Factory)
   ->withServiceAccount($serviceAccount)
   ->withDatabaseUri('https://XXXXXXXXXXXXX.firebaseio.com')
   ->create();
$database = $firebase->getDatabase();
var_dump($database);
?>
```

**Comment by jeromegamez** [comment]
The stack trace mentions a syntax error and the error is triggered in https://github.com/kreait/firebase-php/blob/9614b26a8327bc0ac0b052166e16afb7154b4a58/src/Firebase/ServiceAccount.php#L158-L165

As far as I can tell, there are two possible issues, which you can test with the following:

```php
if ($content = file_get_contents($path)) {
    echo "The file is readable, and here is its content: {$content}\n";
} else {
    echo "The file is not readable\n";
    exit;
}

$data = json_decode($content, true);

if (json_last_error() !== JSON_ERROR_NONE) {
    echo "The file doesn't contain valid json: ".json_last_error_msg()."\n";
    exit;
}

try {
    $serviceAccount = ServiceAccount::fromArray($data);
} catch (InvalidArgumentException $e) {
    echo "The file doesn't contain a valid Service Account definition: ".$e->getMessage()."\n";
    exit;
}

var_dump($serviceAccount);
exit;
```

**Comment by jeromegamez** [comment]
@Techiedie You 👍-d my last comment, does this mean this helped you resolve the problem?

**Comment by Techiedie** [comment]
yes, its work for me to find the error.

Thank you so much @jeromegamez
