### ISSUE TITLE
Getting an error while I am trying to call insert function to insert values to the firebase realtime database "PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:"

### ISSUE THREAD

**Issue by sherazam51** [kreait/firebase-php#313]
Please help me to solve this issue. I am really very stuck and don't know what to do. I am new with this tool. I am trying to insert values to the database but it cannot allow me due to some reason please help me to find the reason. 
I am using 
- PHP Version is 7.3.8
- Firebase PHP SDK version is 4.29

<?php
require_once './vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

class Users
{
    protected $database;
    protected $dbname = 'users';
    public function __construct()
    {
        $acc = ServiceAccount::fromJsonFile( __DIR__ . '/secret/firebasics-f6632-firebase-adminsdk-he7wf-2ab3b5a897.json');
        $firebase = (new Factory) -> withServiceAccount($acc)->create();

        $this->database = $firebase->getDatabase();
    }
    public function get(int $userID = NULL)
    {
        if(empty($userID) || !isset($userID)) {return FALSE;}

        if($this->database->getReference($this->dbname)->getSnapshot()->hasChile($userID))
        {
            return $this->databse->getReference($this->dbname)->getChild($userID)->getValue();
        }
        else
        {
            return FALSE;
        }
    }
    public function insert(array $data)
    {
        if(empty($data) || !isset($data)) {return FALSE;}
        foreach($data as $key => $value)
        {
            $this->database->getReference()->getChild($this->dbname)->getChild($key)->set($value);
        }
        return TRUE;
    }
    public function delete($userID)
    {
        if(empty($userID) || !isset($userID)) {return FALSE;}
        if($this->database->getReference($this->dbname)->getSnapshot()->hasChild($userID))
        {
            $this->database->getReference($this->dbname)->getChild($userID)->remove();
            return TRUE;
        }
        else
        {
            return FALSE;
        }
    }
}
$users = new Users();
var_dump($users->insert([
    '1' => 'Sher',
    '2' => 'Azam',
    '3' => 'Usman'
]));
?>
Errors:
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Invalid JWT: Token must be a short-lived token (60 minutes) and in (truncated...)
 in C:\xampp\htdocs\firebasics\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Pro in C:\xampp\htdocs\firebasics\vendor\kreait\firebase-php\src\Firebase\Exception\DatabaseApiExceptionConverter.php on line 65

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad
Request` response:
{
  "error": "invalid_grant",
  "error_description": "Invalid JWT: Token must be a short-lived token (60 minutes) and in (truncated...)
 in C:\xampp\htdocs\firebasics\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
PS C:\xampp\htdocs\firebasics>  php Users.php
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Invalid JWT: Token must be a short-lived token (60 minutes) and in (truncated...)
 in C:\xampp\htdocs\firebasics\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Pro in C:\xampp\htdocs\firebasics\vendor\kreait\firebase-php\src\Firebase\Exception\DatabaseApiExceptionConverter.php on line 65

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad
Request` response:
{
  "error": "invalid_grant",
  "error_description": "Invalid JWT: Token must be a short-lived token (60 minutes) and in (truncated...)
 in C:\xampp\htdocs\firebasics\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 C:\xampp\htdocs\firebasics\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Pro in C:\xampp\htdocs\firebasics\vendor\kreait\firebase-php\src\Firebase\Exception\DatabaseApiExceptionConverter.php on line 65

**Comment by sherazam51** [comment]
Here is the code
`require_once './vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

class Users
{

    protected $database;
    protected $dbname = 'users';

    public function __construct()
    {
        $acc = ServiceAccount::fromJsonFile( __DIR__ . '/secret/firebasics-f6632-firebase-adminsdk-he7wf-2ab3b5a897.json');
        $firebase = (new Factory) -> withServiceAccount($acc)->create();

        $this->database = $firebase->getDatabase();
    }

    public function get(int $userID = NULL)
    {
        if(empty($userID) || !isset($userID)) {return FALSE;}

        if($this->database->getReference($this->dbname)->getSnapshot()->hasChile($userID))
        {
            return $this->databse->getReference($this->dbname)->getChild($userID)->getValue();
        }
        else
        {
            return FALSE;
        }
    }

    public function insert(array $data)
    {
        if(empty($data) || !isset($data)) {return FALSE;}

        foreach($data as $key => $value)
        {
            $this->database->getReference()->getChild($this->dbname)->getChild($key)->set($value);
        }
        return TRUE;
    }

    public function delete($userID)
    {
        if(empty($userID) || !isset($userID)) {return FALSE;}

        if($this->database->getReference($this->dbname)->getSnapshot()->hasChild($userID))
        {
            $this->database->getReference($this->dbname)->getChild($userID)->remove();
            return TRUE;
        }
        else
        {
            return FALSE;
        }
    }
}

$users = new Users();

var_dump($users->insert([
    '1' => 'Sher',
    '2' => 'Azam',
    '3' => 'Usman'
]));`

**Comment by sherazam51** [comment]
I just synchronize my time with internet time and issue resolved. Thanks

**Comment by jeromegamez** [comment]
Happy you got it :)

**Comment by HaniHairul** [comment]
> I just synchronize my time with internet time and issue resolved. Thanks

Hye, may I ask what is the meaning of the internet time?
