### ISSUE TITLE
How to install kreait/firebase in laravel 5.2

### ISSUE THREAD

**Issue by Lordofcodes** [kreait/firebase-php#314]
I visited previous issues but I couldn't find any which solves my problem; provided solutions are outdated.
I want to know how to install this package in laravel 5.2, and setup all the required configuration?

**Comment by jeromegamez** [comment]
Please see https://firebase-php.readthedocs.io/en/latest/tutorials.html

**Comment by Lordofcodes** [comment]
@jeromegamez Sorry, but it doesn't help setting the configs for cloud-messaging. Please help. How can I setup it for cloud messaging.

**Comment by jeromegamez** [comment]
You don't need a special configuration for cloud messaging, what is it that you want to achieve, and what have you tried so far?

**Comment by Lordofcodes** [comment]
I want to send messages to devices  which have subscribed to a topic.
I installed the package and I can use the doc for cloud messaging.
But, Internally how this package gets config values config means.
My server key and sender ID. These values are necessary for cloud messaging. 
Do I need to set these keys in .env of laravel project? Or in the srvices.php as described in the tutorial on medium shared by you.

**Comment by jeromegamez** [comment]
Server Key and Sender ID are *not* necessary for cloud messaging (at least not with `kreait/firebase-php`).

I don't know how you've set up your project, but once you have an instance of the `Firebase` class, you can do

```php
$firebase->getMessaging()->send([
    'token' => '...',
    'notification' => [
        'title' => 'Notification title',
        'body' => 'Notification body',
    ]
]);
```

Please see also

* https://firebase-php.readthedocs.io/en/latest/setup.html
* https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html

**Comment by jeromegamez** [comment]
I will create a Laravel package to make all this easier.

**Comment by Lordofcodes** [comment]
@jeromegamez  I will be grateful for you. I am only using firebase for cloud messaging, and not other services like database or others.

**Comment by Lordofcodes** [comment]
@jeromegamez  I solved it for now. I am using **Manual** method described here https://firebase-php.readthedocs.io/en/latest/setup.html 
Here is steps I followed.
1. installed the package using `composer require kreait/firebase-php`
2. now I followed manual method placing the credential.json in root directory
It is working fine now.
But,  I get error if I define all the values in .env and pass it here as FIREBASE_CREDENTIALS.
   ```
 public function getDefaultMethods(): array
 {
        return [
            new Discovery\FromEnvironmentVariable('FIREBASE_CREDENTIALS'),
            new Discovery\FromEnvironmentVariable(CredentialsLoader::ENV_VAR),
            new Discovery\FromGoogleWellKnownFile(),
            new Discovery\OnGoogleCloudPlatform(),
        ];
    }
```
Placing credentials.json is not a solution. And instantiating $serviceAccount to get a $firebase object is also not efficient. As, I am doing something like this now. 

```
 $serviceAccount = ServiceAccount::fromJsonFile('./firebase_credentials.json');
        $firebase = (new Factory)
            ->withServiceAccount($serviceAccount)
            ->create();
        $firebase
            ->getMessaging()
            ->subscribeToTopic($topic, $token);
        $messaging = $firebase->getMessaging();
        $message = CloudMessage::withTarget('topic', $topic)
            ->withNotification([
                'title' => 'Notification title',
                'body' => 'Notification body',
            ]) // optional
            ->withData([
                'key_1' => 'Value 1',
                'key_2' => 'Value 2'
            ]); // optional
         $messaging->send($message);
```
What It should like, a facade which I can use to get a firebase object, something like this
```
use Firebase;
class FirebaseMessagningController
{
   $firebase = new Firebase;
   //now here $firebase->getMessaging()
}
```
It should load all the credentials from .env file to give $firebase object.

**Comment by jeromegamez** [comment]
Thanks for sharing your solution!

If you‘re interested in being the first tester, would you like to ja a look at https://github.com/kreait/laravel-firebase/ ? If it works as good for you as it does for me, it should make things a lot easier.

**Comment by Lordofcodes** [comment]
@jeromegamez  Thanks a lot.

**Comment by Lordofcodes** [comment]
@jeromegamez  I tested and it's working very well. 
It's easier to use. Just installed it and set the environment  variable FIREBASE_CRENDETIALS to the firebase_credentials.json
But, Still I can't use facades and Automatics injections; I get errors.
```
use FirebaseMessaging;
use Illuminate\Http\Request;

class FirebaseMessagingController extends Controller
{
    public function send_notificaiton()
    {

        $messaging = new FirebaseMessaging;
        $registrationTokens = "my_registration_token";
        $topic = 'Test';
        $messaging->subscribeToTopic($topic, $registrationTokens);
        $message = $messaging->withTarget('topic', $topic)
        ->withNotification(["title"=>"Hello","body"=>"How are you doing?"]) // optional
        ->withData(['key' => 'value']); // optional
        $messaging->send($message);

Call to undefined method Kreait\Laravel\Firebase\Facades\FirebaseMessaging::subscribeToTopic()

``
```
use Kreait\Firebase;
use Kreait\Firebase\Messaging\CloudMessage;
class FirebaseMessagingController extends Controller
{
    public function send_notificaiton()
    {
        $firebase = (new Firebase\Factory())->create();
        $messaging = $firebase->getMessaging();
        
        //user registration token
        $registrationTokens =  "myregistration_token_if_you_want_yours_get_it_it's_free";
        $topic = 'Test';
        //subscribe usr to a topic
        $firebase
        ->getMessaging()->subscribeToTopic($topic, $registrationTokens);
        $message = CloudMessage::withTarget('topic', $topic)
            ->withNotification(["title"=>"Hello","body"=>"How are you doing?"]) // optional
            ->withData(['key' => 'value']); // optional
        $messaging->send($message);
    }
}
```

**Comment by jeromegamez** [comment]
I think it is even easier than this. Before continuing, please make a `composer update` - the `kreait/laravel-firebase` should be shown as updated.

After that, this should work:

### with method injection

```php
<?php
use Kreait\Firebase\Messaging;

class FirebaseMessagingController extends Controller
{
    public function send_notification(Messaging $messaging)
    {
        $token = '...';

        $messaging->subscribeToTopic('test', $token);

        $messaging->send([
            'topic' => 'test',
            'notification' => [
                'title' => 'Hello',
                'body' => 'How are you doing'
            ]
        ]);
    }
}
```

### with Facade

```php
<?php

class FirebaseMessagingController extends Controller
{
    public function send_notification()
    {
        $token = '...';

        FirebaseMessaging::subscribeToTopic('test', $token);

        FirebaseMessaging::send([
            'topic' => 'test',
            'notification' => [
                'title' => 'Hello',
                'body' => 'How are you doing'
            ]
        ]);
    }
}
```

**Comment by Lordofcodes** [comment]
@jeromegamez  Thank you so much you are amazing, so is this package. I appreciate your effort and support.  But, I wonder why you didn't develop this kind of package for laravel before? 
Because It will be easier to use now in laravel for everyone. I suggest you to attach this link in the doc, and on the main project on github, so that everyone don't waste their time in searching for a better way to use this package.

**Comment by jeromegamez** [comment]
I‘m glad you like it 😊. I added links to the package in the readme and in the docs just yesterday, so I hope it‘s easier to find for others in the future!

The reason I hadn‘t a Laravel package before was that I wanted to concentrate on the core functionality of the SDK and that I thought that people would create a simple Service Provider in their Laravel project on their own, but you‘re right: it‘s much easier this way.

So, thanks for pushing me to do make the package in the end after all 😊
