### ISSUE TITLE
A Key with ID Could not be found

### ISSUE THREAD

**Issue by vkiranmaniya** [kreait/firebase-php#315]
I'm receiving the Exception as A key with ID "60f4060e58d75fd3f70beff88c794a775327aa31" could not be found.

**Comment by jeromegamez** [comment]
This is not enough information to provide any kind of help. You‘ve been provided with a template when opening the issue, why didn‘t you use it? What did you try to do? What code did you write?

**Comment by jeromegamez** [comment]
I see that this is the same issue you described in https://github.com/kreait/firebase-tokens-php/issues/15 - let‘s not talk about the same thing in two different issues on two different repos :)

**Comment by doradomiguel35** [comment]
Hi same problem here,

**Comment by vkiranmaniya** [comment]
@doradomiguel35  Its happening because IOS sdk uses web redirect based login

**Comment by vkiranmaniya** [comment]
@doradomiguel35 refer the SO post https://stackoverflow.com/questions/55121166/phone-authentication-validation-from-server-side-firebase-php of mine
