### ISSUE TITLE
fcm_options link is not working

### ISSUE THREAD

**Issue by aleemb** [kreait/firebase-php#316]
```
$messaging = $firebase->getMessaging();
$config = WebPushConfig::fromArray([
    'notification' => ['title' => $title, 'body' => $body, 'icon' => $icon],
    'fcm_options' => ['link' => $link],
]);
$message = CloudMessage::withTarget('topic', 'test')->withWebPushConfig($config);
```

The notifications sends fine but clicking the OSX sidebar toast doesn't open the link (Firefox). Instead clicking the toast just brings the browser into focus.

**Comment by aleemb** [comment]
Quick aside, there is a typo at https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html#webpush

`ApnsConfig::fromArray` should be `WebPushConfig::fromArray`.

**Comment by jeromegamez** [comment]
Thanks for the hint to the documentation error!

Concerning the link I‘m afraid there is not much I can do - it‘s the key that the Firebase docs provide (https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#webpushfcmoptions) and that the browser is focused is a hint that it‘s working at least in theory :/

Is the link you provide an HTTPS link? That‘s the only gotcha I can think of...

**Comment by aleemb** [comment]
The link is HTTPS. I am currently using another library which works just fine with clickable links. Porting over, I noticed the links stopped working in this lib.

https://github.com/sngrl/php-firebase-cloud-messaging/blob/master/src/Notification.php#L63

```
use sngrl\PhpFirebaseCloudMessaging\Message as FCMMessage;
use sngrl\PhpFirebaseCloudMessaging\Notification as FCMNotification;

...

        $message = new FCMMessage();
        $message->setPriority($priority);
        $message->addRecipient(new FCMTopic($topic));
        $message->setTimeToLive($timeToLive);

        $notification = new FCMNotification();
        $notification->setTitle($title);
        $notification->setBody($body);
        $notification->setIcon($icon);
        $notification->setClickAction($link);
        $message->setNotification($notification);
```

Roughly the above works. Not sure what's up, but maybe that provides some hint.

**Comment by jeromegamez** [comment]
The reason is that the other library is using the legacy HTTP protocol, whereas this one is using the HTTP v1 API.

I just tested and can confirm the behavior you described, and I hope that I can find a solution 🤞

**Comment by aleemb** [comment]
So I got it to work with your lib.

This doesn't result in hyperlinking:

```
$config = WebPushConfig::fromArray([
    'notification' => ['title' => $title, 'body' => $body, 'icon' => $icon],
    'fcm_options' => ['link' => $link],
]);
```

This, however, does:

```
$config = WebPushConfig::fromArray([
    'notification' => ['title' => $title, 'body' => $body, 'icon' => $icon, 'click_action' => $link],
]);
```

Might be worth documenting for others who trip up.

Aside, I'm using your new `laravel-firebase`. I realized it exposes `FirebaseMessaging::send()` but would be more useful to be able to write `FirebaseMessaging::withTarget()->withNotification()`, etc. Or maybe even `FirebaseMessaging::getMessaging()`.

**Comment by jeromegamez** [comment]
I just got it to work as well, with any of the following:

```php
$notification = [
    'title' => $title,
    'body' => $body,
    'icon' => $icon
];

$config = WebPushConfig::fromArray([
    'notification' => $notification,
    'fcm_options' => ['link' => $link],
]);
//$message = CloudMessage::withTarget('topic', $topic)
//    // ->withNotification(['title' => $title, 'body' => $body, 'icon' => $icon])
//    ->withWebPushConfig($config);

$message = CloudMessage::withTarget('topic', $topic)
    // ->withNotification($notification)
    ->withWebPushConfig([
        'notification' => $notification,
        'fcm_options' => [
            'link' => $link,
        ]
    ]);

$messaging->send($message);
```

I haven't found out yet why, though, do you see a difference between your example and mine?

Concerning `FirebaseMessaging` - it's already a facade for `Kreait\Firebase\Messaging`, so `getMessaging()` would probably not make sense there. I don't think that this is too unconvenient.

**Comment by jeromegamez** [comment]
Okay, what I found out with

```php
$topic = 'a-test';
$title = 'WebPush notification title';
$body = 'WebPush notification body';
$icon = 'default';
$link = 'https://github.com/kreait/firebase-php';

// $messaging->subscribeToTopic($topic, $firefoxToken);

$config = WebPushConfig::fromArray([
    'notification' => ['title' => $title, 'body' => $body, 'icon' => $icon],
    'fcm_options' => ['link' => $link],
]);

$message = CloudMessage::withTarget('topic', $topic)->withWebPushConfig($config);

$messaging->send($message);
```

If Firefox has an open window, it works. If Firefox is loaded (so, on macOS, active in the Dock), but has *no* windows, it doesn't.

**Comment by aleemb** [comment]
In my case, the links didn't trigger even when FF is open. It's possible that I have a service worker which handles notifications, so in my case, if my site is open (even if FF is in the background) there is no OSX toast. However, if another site is in focus (whether FF is in background or foreground), the toast appears.

In either scenario, your code didn't have a clickable link for me. I'm on FF68 on High Sierra. Strange.

**Comment by aleemb** [comment]
> Concerning FirebaseMessaging - it's already a facade for Kreait\Firebase\Messaging, so getMessaging() would probably not make sense there. I don't think that this is too unconvenient.

I can't do `FirebaseMessaging::withTarget()->withNotification()` etc. I only see `Firebasemessaging::send([...])`. Not a biggie, I suppose I can build up a large array blob and pass it to send. Is that the recommended approach with the `FirebaseMessaging` Facade?

**Comment by jeromegamez** [comment]
But you can do

```php
$message = CloudMessage::withTarget()->withNotification();
FirebaseMessaging::send($message);
```

The Facade is just a way to quickly access the Messaging Component/Service, not a shortcut to `CloudMessage`? With your proposed usage, how would you actually send the message?

**Comment by aleemb** [comment]
I end up with something like this

```
use Kreait\Firebase\Messaging\CloudMessage;
use Kreait\Firebase\Messaging\WebPushConfig;
use FirebaseMessaging;

// ...

$config = WebPushConfig::fromArray([...]);
$message = CloudMessage::withTarget('topic', $topic)->withWebPushConfig($config);
FirebaseMessaging::send($message);
```

I suppose I had some initial thoughts on how the function calls *should* work and I got carried away (Some of Laravel's internal Facades work this way, the DX is quite convenient). Initially, I had thought I shouldn't have to build a `WebPushConfig` object and by default it could accept an array. That would provide a very clean API without having to `use` any other dependencies. Leaving me with just:

```
FirebaseMessaging
  ::withTarget('topic', 'test')
  ->withWebPushConfig([
    'notification' => ['title' => $title, 'body' => $body]
    ]);
```

Not a biggie though. Thanks very much for being super responsive.

**Comment by aleemb** [comment]
Okay I see `withWebPushConfig([...])` works `withNotification([...])` does not accept an `Array` by default. So some asymmetry in the API, hence my confusion. Feel free to move along.

**Comment by jeromegamez** [comment]
What exactly doesn't work? `withNotification()` accepts a `Notification` or an `array` that will then be converted to a `Notification` 

A notification supports the fields `title`, `body` and `image` as specified in https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Notification

```php
CloudMessage::new()->withNotification([/* ... */])
```

Concerning the inconsistencies - yes, there are some, the 4.x branch is quite old and under heavy development and I rushed some features. It will get better, but in order to not break BC, probably only later in a 5.x release

**Comment by aleemb** [comment]
It does indeed! My confusion. I'm still playing the API and getting rid of `use` statements. It's pretty clean now.
