### ISSUE TITLE
Call to undefined method GuzzleHttp\Psr7\Response::subResponses()

### ISSUE THREAD

**Issue by kapitoxapux** [kreait/firebase-php#317]
Hello, can some one help me to figure out what is need to be done, don't have a clue....
I'm sending `$sendReport = $messaging->sendAll($messages);` and got the push on my phone, but instead of report got this:
Call to undefined method GuzzleHttp\Psr7\Response::subResponses() in 
/vendor/kreait/firebase-php/src/Firebase/Messaging.php
111:
 `return MulticastSendReport::fromRequestsAndResponses($request->subRequests(), $response->subResponses());`

**Comment by jeromegamez** [comment]
Too bad you didn't use the issue template you were given :), so let me ask you explicitly:

- Which PHP version are you using? (`php -v`) (You should at least be on `4.30.1`)
- Which version of the `kreait/*` libraries are you using? (`composer show | grep kreait`)
- Are you on windows, macOS, or Linux?

We had the exact same issue reported a couple of days ago in the community Discord and I added an at least partial workaround and it seems not to happen everywhere, perhaps I need to add more checks.

**Comment by kapitoxapux** [comment]
Hey! Thanks for the quick reply. I apologize if I posted the issue
incorrectly. Here is the system installed: php 7.2, latest kreait, Gentoo.
Thanks again!

вт, 20 авг. 2019 г., 19:47 Jérôme Gamez <notifications@github.com>:

**Comment by jeromegamez** [comment]
I‘m currently on the road, but before I left, I pushed the „multipart-workaround“ branch which should be usable by specifying „dev-multipart-workaround as 4.30.2“ in the composer.json file, if you have time, could you test it with this?

Unfortunately, I can‘t reproduce this issue, but I will try to implement some kind of debugging in the next days... there‘s something in the responses that doesn‘t add up - or it is in my implementation, but this I‘m not ready to consider yet 😂

**Comment by DamienHarper** [comment]
Hi @jeromegamez I encounter the same issue.
PHP: 7.3.8, Linux CentOS 7.6.1810
kreait/firebase-php                   4.30.1             Firebase Admin SDK
kreait/firebase-tokens                1.8.1              A library to work with Firebase tokens
kreait/gcp-metadata                   1.0.1              Get the metadata from a Google Cloud Platform environment.

**Comment by jeromegamez** [comment]
Hey @DamienHarper and thanks for confirming - could you please test with `dev-multipart-workaround as 4.30.2` as the version constraint for `kreait/firebase-php`?

If this doesn't help, if possible, could you help me debug the issue? Either here or on Discord (https://discord.gg/nbgVfty) ? /cc @kapitoxapux 😅

If this doesn't help, you would have to fix the version constraint to `4.28.0` until I figure out what's going on.

I just wish I could reproduce this :/

**Comment by DamienHarper** [comment]
`dev-workaround doesn't fix the issue for me

**Comment by jeromegamez** [comment]
Thank you! What I know is that this is where the FCM Batch response is not correctly recognized as a response with sub-responses:

https://github.com/kreait/firebase-php/blob/master/src/Firebase/Http/Middleware.php#L44-L64

Could you modify the Middleware so that it echos all headers and the full body? Something like

```php
    /**
     * Parses multi-requests and multi-responses.
     */
    public static function responseWithSubResponses(): callable
    {
        return static function (callable $handler) {
            return static function (RequestInterface $request, array $options = null) use ($handler) {

                file_put_contents('/tmp/test_request.txt', \GuzzleHttp\Psr7\str($request));
                
                return $handler($request, $options ?: [])
                    ->then(static function (ResponseInterface $response) {
                        
                        file_put_contents('/tmp/test_response.txt', \GuzzleHttp\Psr7\str($response));

                        $isMultiPart = \mb_stristr($response->getHeaderLine('Content-Type'), 'multipart') !== false;
                        $hasMultipleStartLines = ((int) \preg_match_all('@http/[\S]+\s@i', (string) $response->getBody())) > 1;

                        if ($isMultiPart && $hasMultipleStartLines) {
                            return new ResponseWithSubResponses($response);
                        }

                        return $response;
                    });
            };
        };
    }
```

and then send me the files, either as a private message on Discord, or as a private gist on gist.github.com?

**Comment by kapitoxapux** [comment]
Me too, but I have a couple of thoughts on this matter. This error occurs
only when inside the messages array lies only one element/message. Hope it
helps. Sorry, didn’t say right away, a lot of work

чт, 22 авг. 2019 г., 16:16 Damien Harper <notifications@github.com>:

**Comment by DamienHarper** [comment]
@jeromegamez done (check your private message on discord)

**Comment by jeromegamez** [comment]
Thanks to you both! I‘ll check and get back to you once I‘ve found something out (or have further questions 😅)

**Comment by jeromegamez** [comment]
Thanks to both of you! The "one element" hint by @kapitoxapux paired with the debug output from @DamienHarper finally made me see.

I'm now confident that this is fixed with https://github.com/kreait/firebase-php/commit/0c7dbf7daefb49933d56eac6c81442cead11b6f7 and secured with https://github.com/kreait/firebase-php/commit/ac4e78c9d2e11a7b066e1cad8601111efd94565a

If you try with `dev-master as 4.31.0`, it should™ work now 🤞

**Comment by DamienHarper** [comment]
@jeromegamez works like a charm 👍

**Comment by jeromegamez** [comment]
Wonderful! I'm happy to announce that [4.31.0](https://github.com/kreait/firebase-php/releases/tag/4.31.0) has just been released 🎉

**Comment by jeromegamez** [comment]
So... now that this is handled... why do you use `sendMulticast()` or `sendAll()` with just one recipient/message? 😅

**Comment by kapitoxapux** [comment]
Well... it’s very difficult to delete 100500 messages from the phone, so
for the test I sent only one ))

чт, 22 авг. 2019 г. в 17:54, Jérôme Gamez <notifications@github.com>:
