### ISSUE TITLE
onCreate() function

### ISSUE THREAD

**Issue by Adron55** [kreait/firebase-php#319]
İ searched[ Firebase documentations](https://firebase.google.com/docs/functions/database-events) and if i am not wrong we can listen to database with onCreate() function .

-onCreate(), which triggers when new data is created in the Realtime Database.

Is there any method in this package to do same thing like listening to database ?

**Comment by jeromegamez** [comment]
Hi @Adron55, that's currently not possible with this package. There's #40, but since the introduction of [Cloud Functions](https://firebase.google.com/docs/functions/) this feature is very low on the priorities list and will probably not make it in a 4.x release.

**Comment by jeromegamez** [comment]
I closed the issue but feel free to add further comments if you wish
