### ISSUE TITLE
How to implement signout of a user.

### ISSUE THREAD

**Issue by susanhita** [kreait/firebase-php#322]
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth.html#signOut()

This should sign out the current user and clears it from the disk cache.

**Comment by jeromegamez** [comment]
Do you mean this? https://firebase-php.readthedocs.io/en/latest/user-management.html#invalidate-user-sessions

**Comment by susanhita** [comment]
Yes that works well for me. Thank you. 
Will you ever add something exactly like signout() ? Something that will clear the cache?

**Comment by jeromegamez** [comment]
What cache do you mean? The SDK doesn‘t cache  user sessions, and we wouldn‘t be able to clear caches on client devices like in Android apps or web apps.

In the scope of the SDK we can only make sure that an ID token that has been used previously cannot be used for authentication again.

Did I misunderstand what you mean?

**Comment by susanhita** [comment]
Confirmed firebase signout does exactly this - "deletes the access token used by Firebase to confirm the users' identity". 
Thanks for clearing that the SDK  doesn‘t cache user session.
The session storage should be handled by me https://firebase.google.com/docs/auth/admin/manage-cookies#sign_out

That clears up the issue. Closing this PR.
