### ISSUE TITLE
How do I know how many messages I sent after I sent a push through the topic?

### ISSUE THREAD

**Issue by MasakiOvO** [kreait/firebase-php#323]
How do I know how many messages I sent after I sent a push through the topic?

**Comment by jeromegamez** [comment]
It‘s not possible to get that information via API calls, you will only know that Firebase has accepted the message if the send doesn‘t result in an error.

I‘m not sure, but if you want to track the delivered messages, my best guess is to trigger a Firebase Analytics Event from the client application when the message has arrived there.

**Comment by MasakiOvO** [comment]
thanks
