### ISSUE TITLE
How to search data

### ISSUE THREAD

**Issue by tkmine** [kreait/firebase-php#324]
How to search data
![Untitled](https://user-images.githubusercontent.com/26906261/64536276-02843880-d343-11e9-9e1b-bf3b121004f5.png)

**Comment by jeromegamez** [comment]
The Realtime Database has no full (text) search, but you can filter data from the realtime database as documented at https://firebase-php.readthedocs.io/en/latest/realtime-database.html#filtering-data

If you need more, Firestore might be a better fit, also see https://firebase.google.com/docs/firestore/solutions/search (this SDK doesn't support Firestore, though :))

**Comment by tkmine** [comment]
thanks!!!

**Comment by tkmine** [comment]
<3 👯‍♂
