### ISSUE TITLE
How do i send fcm with server key instead of json file

### ISSUE THREAD

**Issue by ivybridge-3c33** [kreait/firebase-php#329]
How do i send fcm with server key instead of json file

**Comment by jeromegamez** [comment]
The Messaging component of this SDK is built on the FCM HTTP v1 API which requires Service Account credentials for authentication/authorization.

The Server Key is used for the Legacy FCM Protocol, which is not supported by this SDK.

This is described in detail at https://firebase.google.com/docs/cloud-messaging/auth-server

I'd recommend migrating to the new FCM API, but if you have to use the server key, there are a number of popular PHP libraries that support it https://packagist.org/?query=fcm

**Comment by jeromegamez** [comment]
I closed the issue, but feel free to add further comments if needed!
