### ISSUE TITLE
guzzlehttp error at verify token

### ISSUE THREAD

**Issue by akadebnath** [kreait/firebase-php#334]
I installed firebase-php using composer.
> composer require kreait/firebase-php ^4.32

I have a client Android app where I am authenticating users and sending IdToken to server to verify the logged in user. My server side code is below, but I am getting guzzlehttp error.

I have tried in both Windows localhost and Linux hosting server.
PHP Version: 7.1

```php
<?php
require __DIR__.'/vendor/autoload.php';
use Kreait\Firebase\Factory;
use Firebase\Auth\Token\Exception\InvalidToken;

$factory = (new Factory)
    ->withServiceAccount('google-service-account.json');

$auth = $factory->createAuth();

$idTokenString = 'idToken-generated-in-client-app';

try {
    $verifiedIdToken = $auth->verifyIdToken($idTokenString);
} catch (InvalidToken $e) {
    echo $e->getMessage();
}

$uid = $verifiedIdToken->getClaim('sub');
$user = $auth->getUser($uid);
print_r($uid);
print_r($user);
?>
```

Error:

> [21-Sep-2019 03:21:43 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/getAccountInfo` resulted in a `400 Bad Request` response:
>  (truncated...)
>  in /home/cutqlahc/server/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
> Stack trace:
> #0 /home/cutqlahc/server/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
> #1 /home/cutqlahc/server/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
> #2 /home/cutqlahc/server/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
> #3 /home/cutqlahc/server/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
> #4 /home/cutqlahc/ in /home/cutqlahc/server/vendor/kreait/firebase-php/src/Firebase/Exception/AuthApiExceptionConverter.php on line 111

**Comment by jeromegamez** [comment]
The `getUser()` call is throwing the exception. If you echo the value of `$uid` beforehand, you should be able to inspect its value.

Please also add an `exit;` in the `catch` block - if an exception is thrown while verifying the ID token, and you continue processing the token afterwards, this might be cause for follow up issues.

**Comment by akadebnath** [comment]
That's awesome. I am authenticating successfully.
Now I am trying to retrive a user's details

```php
$user = $auth->getUser('user-uid-from-authentication');
print_r($user);
```
and getting the same error as mentioned.

**Comment by jeromegamez** [comment]
That‘s strange - could you please catch the exception and inspect the included response? The exception message and the response body should give a clue about what went wrong. The strange thing is that all Guzzle Exceptions should be caught and converted to more specialized exceptions, could it be that the exception you‘re seeing is just the last exception in the stack trace?

**Comment by jeromegamez** [comment]
The verification works, so the basic authentication via your Service Account seems to work. I don‘t know why fetching the user fails afterwards. 

Can you make sure that your Service Account has all required permissions (and/or try creating a new one) and that all required APIs are enabled for your project? 

https://firebase-php.readthedocs.io/en/4.32.0/troubleshooting.html#forbidden-errors

**Comment by akadebnath** [comment]
I get a different error:

> Warning:  curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE* in <my-project-root>\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 56
> Warning:  curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE* in <my-project-root>\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 56
> Warning:  curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE* in <my-project-root>\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 56
> Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in <my-project-root>\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186
> Stack trace:
> #0 <my-project-root>\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(517): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
> #1 <my-project-root>\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(146): GuzzleHttp\Handler\CurlFactory::retryFailedRewind(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Array)
> #2 <my-project-root>\vendor\guzzlehttp\guzzle\src\Handler\CurlFact in <my-project-root>\vendor\kreait\firebase-php\src\Firebase\Exception\AuthApiExceptionConverter.php on line 111


Here is my full code:

```php
<?php
require __DIR__.'/vendor/autoload.php';
use Kreait\Firebase\Factory;
use Firebase\Auth\Token\Exception\InvalidToken;

$factory = (new Factory)
    ->withServiceAccount('google-service-account.json');

$auth = $factory->createAuth();
$idTokenString = 'idToken-generated-in-client-app';

try {
    $verifiedIdToken = $auth->verifyIdToken($idTokenString);
} catch (InvalidToken $e) {
    echo $e->getMessage();
	exit;
}




print_r($verifiedIdToken);
echo '
<h2>Getting User information</h2>
';




$firebase = (new Factory)
	->withHttpClientConfig([
        'debug' => true
    ])
    ->withServiceAccount('google-service-account.json')
    ->create();

$auth2 = $firebase->getAuth();

try {
    $users = $auth2->listUsers($defaultMaxResults = 1000, $defaultBatchSize = 1000);
	print_r($users);
} catch (InvalidToken $e) {
    echo $e->getMessage();
	exit;
}

try {
    $user = $auth2->getUser('user-uid-from-authentication');
	print_r($user);
} catch (InvalidToken $e) {
    echo $e->getMessage();
	exit;
}

?>
```

I am sure that I am doing something wrong. I need your help to find it out.

**Comment by jeromegamez** [comment]
Uh, I haven't seen this one before! Your code looks fine though... If you google for `cannot represent a stream of type Output as` you'll find [quite some results](https://www.google.com/search?hl=de&q=php%20%22cannot%20represent%20a%20stream%20of%20type%20Output%22), perhaps this helps. Right now, I don't have a clue 😞

**Comment by akadebnath** [comment]
Oh that's so sad. I am sure this is quite common usage of the library, and I don't see any other issues posted. That means other have made it successfully. I have no direction what to do. If I send you my full project in zip, can you help?

**Comment by jeromegamez** [comment]
As this seems to be an error with cURL, I added the ability to override the Guzzle HTTP handler (it's auto-discovered by default) so that you can test if it works with other handlers. You can find the documentation for it at https://firebase-php.readthedocs.io/en/latest/setup.html#using-a-custom-http-handler

To be able to use this (for now, until 4.33 is released), you need to `composer require kreait/firebase-php:dev-master`.

Please let me know if this helped to pin down the issue.

**Comment by jeromegamez** [comment]
@akadebnath New releases of the SDK have been released in the meantime - where you able to debug the issue?
