### ISSUE TITLE
Support for Device Groups

### ISSUE THREAD

**Issue by mfcodeworks** [kreait/firebase-php#335]
Does this package have support for Device Groups?

https://firebase.google.com/docs/cloud-messaging/android/device-group#managing_device_groups

I can see there's support for multi-cast messages and topics but is there device group support available for creating/updating groups?

Usually I prefer topics for specific topics e.g. order-441 but I'll use Device Groups for a user. If a user logs in on Android, iOS, and web then I add each token to a user device group and I only send to the group token to notify each of their apps

That would be the second part of the request, if targeting a token has support for group tokens? Even if the group token was created with a separate package would I be able to send to it using this package?

**Comment by jeromegamez** [comment]
Not yet, but I‘ll look into it. Consider this an accepted feature request ^^

**Comment by mfsoftworks** [comment]
So currently impossible to send device group messages with the new SDK? :/
I think for now I'll stick to the legacy API for groups and message sending, SDK for subscription management and admin features
