### ISSUE TITLE
Question: Does this package internally use REST API call for messaging service?

### ISSUE THREAD

**Issue by sujeet-agrahari** [kreait/firebase-php#337]
I was doing cURL call before I came to know this package. Like below : 
Token a user details via token : 
```
GET https://iid.googleapis.com/iid/info/{user_token_here}?details=true

Header - Authorization :key=AAAAdSax7X0:__server_key_like_this
```

It was slow because there was no open connection between my server and firebase server. I want to how this package manages this issue.
**Does this package establish a persistent connection with firebase like web sockets or other to manage things, Or It just makes API calls using cURL under the hood?**

**Comment by jeromegamez** [comment]
The package does use the Firebase REST APIs and uses cURL or other supported HTTP handlers supported by Guzzle.

If you send multiple messages at once (`Messaging::sendAll()`, `Messaging::sendMulticast()`), a batch request is used, meaning one request for all provided messages or message targets.

**Comment by Lordofcodes** [comment]
@jeromegamez   I am facing a problem. Server doesn't respond if I send multiple notification.
Have a look on the below code.
```
 $results = User::select('id')

                            ->where('isDeleted', '=', env('NOTDELETED'))

                            ->where('verified', '=', env('ACCEPTED'))

                            ->where('status', '=', env('ACTIVE'))

                            ->where('isLogged', '=', env('LOGGED'))

                            ->get()->toArray();
            //send notification to All and All_hi topics
             $messaging->send([
                         'topic' => 'All',
                         'data' =>$message
                         ]);
             $messaging->send([
                         'topic' => 'All_hi', 
                         'data' =>$message_hi
                         ]);
             //save notification for users who have commodities as favourtie
             foreach ($results as $result) {
                 $this->addStoreNotificationRecord($result['id'], $message, $message_hi);
             }
             return true;
```
Above code will fetch the users and and then it will fire two notifications on two topics. 
After sending notifications it will store the notification for every user in the database.
I just want to know _Is any change that making multiple call to sending notification causing the issue?_

**Comment by jeromegamez** [comment]
Which server doesn't respond? Your server or the Firebase servers? What is the error you are receiving? I can't tell you what is causing issues just by guessing 😅.

As I said before: use `Messaging::sendAll()` for optimized requests.

```php
$messaging->sendAll([
    ['topic' => 'All', 'data' => $message],
    ['topic' => 'All_hi', 'data' => $message_hi],
]);
```

**Comment by Lordofcodes** [comment]
@jeromegamez Ofcourse my server, actually Godaddy's Server. 😂
