### ISSUE TITLE
Invalid JSON payload received.

### ISSUE THREAD

**Issue by krkias** [kreait/firebase-php#341]
**Describe the bug**
Hello, could I ask you for a help?

I have this problem. I am sending notifications by sendMulticast() method. Message is created how it shows below. And I got this error message **"Invalid JSON payload received. Unknown name \"notification\" at 'message': Proto field is not repeating, cannot start list."**

```php
$this->notification = Notification::fromArray([
            'title' => $this->title,
            'body' => $this->text
        ]);

...

$message = CloudMessage::new()
            ->withNotification($this->notification)
            ->withData($this->data);
        $report = $this->messaging->sendMulticast($message, $tokens);
```

Thank you for your time.

**Comment by jeromegamez** [comment]
Did you find a solution? What was the problem?

**Comment by krkias** [comment]
@jeromegamez Yes I found solution. I was sending a CloudMessage with Notification, which had 'title' and 'body' as null, there could be some exception for easier developing. This caused this abstruse response from firebase.

**Comment by jeromegamez** [comment]
I added a check with https://github.com/kreait/firebase-php/commit/d4ffe4436d41dcd77cb2aa9ceff9aac4cc683191 so that it will be included in the next release! Thanks for bringing this issue up! 🌺
