### ISSUE TITLE
How to use library without composer in WordPress ?

### ISSUE THREAD

**Issue by anhhtz** [kreait/firebase-php#343]
Hi,
I search on Google today for the way to use this library without composer on my WordPress theme.
I read it: 
[https://github.com/kreait/firebase-php/issues/97](https://github.com/kreait/firebase-php/issues/97)
and this is I do:

**functions.php**:

```php
add_action ( 'init' , 'class_loader' );

function class_loader () {
    // register an autoloader function for template classes
    spl_autoload_register ( 'template_autoloader' );
}

function template_autoloader ( $class ) {
if ( file_exists ( __DIR__ . "/libs/Firebase/{$class}.php" ) ) 
    include __DIR__ . "/libs/Firebase/{$class}.php";
}
```

**Firebase.php** and **Firebase** directory are inside **.../wp-content/themes/my-theme/libs**.

**page-test.php** the page I want to fecth Realtime database

```php
use Kreait\Firebase\Factory;

$factory = (new Factory) //this is line 8
    ->withServiceAccount('path/to/service-account.json')
    // The following line is optional if the project id in your credentials file
    // is identical to the subdomain of your Firebase project. If you need it,
    // make sure to replace the URL with the URL of your project.
    ->withDatabaseUri('https://my-project-id.firebaseio.com');

$database = $factory->createDatabase();
```

**Error**:

`
Fatal error: Uncaught Error: Class 'Kreait\Firebase\Factory' not found in /home/xxx/domains/xxx.yyy.me/public_html/wp-content/themes/my-theme/page-test.php:8 Stack trace: #0 /home/xxx/domains/xxx.yyy.me/public_html/wp-includes/template-loader.php(78): include() #1 /home/xxx/domains/xxx.yyy.me/public_html/wp-blog-header.php(19): require_once('/home/xxx/...') #2 /home/xxx/domains/xxx.yyy.me/public_html/index.php(17): require('/home/xxx/...') #3 {main} thrown in /home/xxx/domains/xxx.yyy.me/public_html/wp-content/themes/wp-bootstrap/page-test.php on line 8
The site is experiencing technical difficulties.
`

Hope you and give me some advices.

Thanks so much !

**Comment by jeromegamez** [comment]
This SDK has a lot of dependencies (other libraries that are needed so that the SDK works), and those dependencies again have other dependencies, so I'm afraid this will be an almost impossible task. I would recommend researching on how to use Wordpress with Composer, and to start with https://roots.io/using-composer-with-wordpress and https://www.google.com/search?q=wordpress%20composer

This really exceeds the scope of this SDK/repository so that I'll close this issue here, but feel free to share your findings for others in further comments.

**Comment by anhhtz** [comment]
I want to share the way I found:

- Install & run composer on local/development machine.
- Use composer install **firebase-php**.
- When the installation is done. Just copy **vendor** folder from local to server (WordPress site). In my case the location is **/wp-content/themes/my-theme/libs**.
- Continue follow document page to write code :)

**Comment by jeromegamez** [comment]
Sometimes I can‘t think of the most obvious workarounds 😅. Well done! 🙌

**Comment by demiantres** [comment]
Here is another solution: https://php-download.com/package/kreait/firebase-php

**Comment by getpinc** [comment]
> Here is another solution: https://php-download.com/package/kreait/firebase-php

why is this a thumbs down ?
