### ISSUE TITLE
I can't send notification with sound

### ISSUE THREAD

**Issue by malikdoksoz** [kreait/firebase-php#344]
**Describe the bug**
I want to send a voice notification. Both android and ios one device.

```

$factory = (new Factory())
    ->withServiceAccount('12.json');
$messaging = $factory->createMessaging();
$message = CloudMessage::withTarget('token', $deviceId)
->withNotification([
    'title' => 'Notification title',
    'body' => 'Notification body',
])
->withApnsConfig([
    'notification' => [
        'sound' => 'default',
    ],
    'payload' => [
        'aps' => [
            'alert' => [
                'title' => '$GOOG up 1.43% on the day',
                'body' => '$GOOG gained 11.80 points to close at 835.67, up 1.43% on the day.',
            ],
            'badge' => 42,
        ],
    ],
]);

$messaging->send($message);
```

**Expected behavior**
```

[21-Oct-2019 23:41:18 Asia/Famagusta] PHP Fatal error:  Uncaught Kreait\Firebase\Exception\Messaging\InvalidMessage: Invalid JSON payload received. Unknown name "notification" at 'message.apns': Cannot find field. in /Users/malikdoksoz/TumDosyalar/Dosyalar/SiteProjeler/fcm/vendor/kreait/firebase-php/src/Firebase/Exception/Messaging/InvalidMessage.php:43
Stack trace:
#0 /Users/malikdoksoz/TumDosyalar/Dosyalar/SiteProjeler/fcm/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingApiExceptionConverter.php(84): Kreait\Firebase\Exception\Messaging\InvalidMessage->withResponse(Object(GuzzleHttp\Psr7\Response))
#1 /Users/malikdoksoz/TumDosyalar/Dosyalar/SiteProjeler/fcm/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingApiExceptionConverter.php(97): Kreait\Firebase\Exception\MessagingApiExceptionConverter->convertResponse(Object(GuzzleHttp\Psr7\Response))
#2 /Users/malikdoksoz/TumDosyalar/Dosyalar/SiteProjeler/fcm/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingApiExceptionConverter.php(42): Kreait\Firebase\Exception\MessagingApiExceptionConvert in /Users/malikdoksoz/TumDosyalar/Dosyalar/SiteProjeler/fcm/vendor/kreait/firebase-php/src/Firebase/Exception/Messaging/InvalidMessage.php on line 43

```

**Environment (please complete the following information):**
 - OS:  macos 10.15
 - PHP version: 7.2
 - Firebase SDK Version: latest

**Comment by jeromegamez** [comment]
I don't know what you mean by "voice notification" 😅, but as the error message `Unknown name "notification" at 'message.apns'` suggests, you can't have a `notification` field in the APNs config.

The [docs for the SDK](https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#apns) point to the [official Firebase Docs](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#apnsconfig) which point to [the current APNs field reference](https://goo.gl/32Pl5W).

For a custom sound, you can specify a field `sound` at the same level as `alert` and `badge` in your example. Please refer to the docs on which values are supported for that.

I hope this helps! 🌺

**Comment by malikdoksoz** [comment]
> I don't know what you mean by "voice notification" 😅, but as the error message `Unknown name "notification" at 'message.apns'` suggests, you can't have a `notification` field in the APNs config.
> 
> The [docs for the SDK](https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#apns) point to the [official Firebase Docs](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#apnsconfig) which point to [the current APNs field reference](https://goo.gl/32Pl5W).
> 
> For a custom sound, you can specify a field `sound` at the same level as `alert` and `badge` in your example. Please refer to the docs on which values are supported for that.
> 
> I hope this helps! 🌺

You're right, my thought has come :)
 I fixed with this code but the phone is not shaking
```$message = CloudMessage::fromArray([
    'token' => $deviceId,
    'notification' => ['title' => 'dsad', 'body' => 'dasdasd'], // optional
    'data' => ['hi' => 'hi'], // optional
        'android' => [
            'notification' => [
                'sound' => 'default',
            ],
        ],
    'apns' => [
        'payload' => [
            'aps' => [
                'sound' => 'default',
                'badge' => 2
            ],
        ],
    ],
       
]);```

**Comment by jeromegamez** [comment]
Unfortunately, I don't know the device-specific configuration well enough to give you good support, but there could be many reasons for no sounds playing... I'd recommend this Google search https://www.google.com/search?q=fcm%20sound%20not%20playing, and perhaps https://stackoverflow.com/a/51048292/284325 in particular

**Comment by malikdoksoz** [comment]
I fixed. Thank you for reply
```

$message = CloudMessage::fromArray([
    'token' => $deviceId,
    'notification' => ['title' => 'dsad', 'body' => 'dasdasd'],
    'data' => ['hi' => 'hi'], // optional
    'android' => [
            'notification' => [
                'default_vibrate_timings' => true,
                'default_sound' => true
            ],
        ],
    'apns' => [
        'headers' => [
            'apns-priority' => '10',
        ],
        'payload' => [
            'aps' => [
                'alert' => [
                    'title' => '$GOOG up 1.43% on the day',
                    'body' => '$GOOG gained 11.80 points to close at 835.67, up 1.43% on the day.',
                ],
                'badge' => 42,
            ],
        ],
    ],
       
]);
```

**Comment by Ev-Filips** [comment]
Malikdoksoz, thank you, you helped me a lot. It works
