### ISSUE TITLE
random error

### ISSUE THREAD

**Issue by simplyniceweb** [kreait/firebase-php#345]
**Describe the bug**
Invalid service account specification.

**To Reproduce**
It's just a random error, when trying to update every 3mins the online count sometimes it works and randomly i get that error "Invalid service account specification."

```php
// Code to reproduce the behavior
```

**Expected behavior**
Wanted it to go away :D

**Screenshots**
![err](https://user-images.githubusercontent.com/5621415/67486237-3ff81780-f69e-11e9-9dba-13e6153b1928.png)

**Environment (please complete the following information):**
 - OS: Win10
 - PHP 7.2.19
 - "kreait/firebase-php": "4.35"

**Additional context**

**Comment by jeromegamez** [comment]
If it sometimes works and sometimes not, it‘s hard to assume what might be wrong, but it‘s most probably an environment issue, meaning, on the machine(s) that your application is running on.

Also, if on Windows, it could be an issue with directory separators. If you‘re specifying a path to the service account file, try replacing forward slashes with the `DIRECTORY_SEPARATOR` constant.

**Comment by simplyniceweb** [comment]
![image](https://user-images.githubusercontent.com/5621415/70166099-10a5e300-16ff-11ea-8acb-e1b17de0df25.png)

after doing it manually and not using the .env it is now working and no random errors at all.
