### ISSUE TITLE
PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ConnectException: cURL error 7

### ISSUE THREAD

**Issue by ahqmrf** [kreait/firebase-php#346]
Getting this exception in apache2 error.log:

`PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ConnectException: cURL error 7: Failed to connect to oauth2.googleapis.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/beta/v1/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200\nStack trace:\n#0 /var/www/html/beta/v1/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)\n#1 /var/www/html/beta/v1/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#2 /var/www/html/beta/v1/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#3 /var/www/html/beta/v1/vendor/guzzlehttp/guzzle/src/Handler/Proxy.ph in /var/www/html/beta/v1/vendor/kreait/firebase-php/src/Firebase/Exception/DatabaseApiExceptionConverter.php on line 49`

**To Reproduce**
I did not find why it actually happening. :( 

**Environment:**
 - OS: Ubuntu 18.04,
 - PHP version: [e.g. 7.3.8]
 - Firebase SDK Version: latest

**Comment by jeromegamez** [comment]
There‘s unfortunately not much I can help you with - if the request to the Google APIs fails, it could have several reasons: bad internet connection, a firewall, your IP could be blocked from accessing the services, ...

**Comment by ahqmrf** [comment]
Okay, but is there any way to set custom timeout duration to the firebase requests?

**Comment by jeromegamez** [comment]
https://firebase-php.readthedocs.io/en/stable/setup.html#http-client-options-and-middlewares

**Comment by danyjadhav** [comment]
I am also getting the below exception.

`{
	"File": "\/var\/www\/html\/local\/vendor\/kreait\/firebase-php\/src\/Firebase\/Exception\/DatabaseApiExceptionConverter.php",
	"Line": 49,
	"Message": "Unable to connect to the API: cURL error 7: Failed to connect to oauth2.googleapis.com port 443: Connection timed out (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)"
}`

**kreait/firebase:** 
**php:** 7.1

Connection code like
`$serviceAccount = ServiceAccount::fromJsonFile($firebase_path);
                $firebase = (new Factory)
                    ->withServiceAccount($serviceAccount)
                    ->withDatabaseUri($firebase_database_path)
                    ->create();
                $database = $firebase->getDatabase();`
It was working fine before, but getting error from last week.

**Comment by jeromegamez** [comment]
It's the same kind of error as before - on the machine the code is running on, a connection to the Google API was not possible... unfortunately that's nothing that we can fix in code.

**Comment by helojianxin** [comment]
please cheak your url。I said this because I got messages like you and found a space between “ and h....
