### ISSUE TITLE
How to create custom key (not auto generated)

### ISSUE THREAD

**Issue by adesm** [kreait/firebase-php#347]
I know if I want to set custom key just call set() method. but it will overwrite all existing data. If call push() method, bingo data not overwrite, it will append data to the list, but this method will create auto generated key.
confusing -.-

Maybe we can combine method with update(). but how to update the name of the auto generated key?

**Comment by jeromegamez** [comment]
The docs are indeed overcomplicated, I will try to make them better, thank you for bringing this up!

Updating or appending fields should be possible with something like this:

```php
$path = 'path/to/my/data';
$initialData = ['key_1' => 'value 1', 'key_2' => 'value 2'];
$dataToAppend = ['key_3' => 'value 3', 'key_4' => 'value 4'];
$expectedResult = array_merge($initialData, $dataToAppend);

$db = $factory->createDatabase();
$ref = $db->getReference($path);

$ref->set($initialData);
assert($ref->getValue() == $initialData);

$ref->update($dataToAppend);
assert($ref->getValue() == $expectedResult);
```
I hope this helps!

**Comment by adesm** [comment]
> The docs at https://firebase-php.readthedocs.io/en/stable/realtime-database.html#update-specific-fields are indeed overcomplicated, I will try to make them better, thank you for bringing this up!
> 
> Updating or appending fields should be possible with something like this:
> 
> ```
> $path = 'path/to/my/data';
> $initialData = ['key_1' => 'value 1', 'key_2' => 'value 2'];
> $dataToAppend = ['key_3' => 'value 3', 'key_4' => 'value 4'];
> $expectedResult = array_merge($initialData, $dataToAppend);
> 
> $db = $factory->createDatabase();
> $ref = $db->getReference($path);
> 
> $ref->set($initialData);
> assert($ref->getValue() == $initialData);
> 
> $ref->update($dataToAppend);
> assert($ref->getValue() == $expectedResult);
> ```
> 
> I hope this helps!

Actually I have found the solution. Forgot to update this thread :)

yes, same concept. Merging array.
I call current key, if null then set(), else retrieve data getValue(), merging new data to retrieved data then set() again

Thanks anyway

**Comment by jeromegamez** [comment]
Just to be clear - in my code snippet, I'm not merging the arrays, I used `array_merge()` only to have a check value to test against.

You can use `$ref->update([/* fields */])` without having to merge anything beforehand:

```php
$db->getReference('path/to/data')->update(['new_key' => 'new value']);
```

In fact, you shouldn't merge the data in PHP and then overwrite everything because without a transaction - you could lose data in the meantime if someone else has already updated the values.

If you want to merge the data with PHP, I strongly recommend to use Realtime Database Transactions: https://firebase-php.readthedocs.io/en/stable/realtime-database.html#database-transactions

**Comment by adesm** [comment]
But the update() method just replace the value, not the key. CMIIW

Oh ya Transactional, let me try. Thank you

**Comment by adesm** [comment]
> In fact, you shouldn't merge the data in PHP and then overwrite everything because without a transaction - you could lose data in the meantime if someone else has already updated the values.
> 
> If you want to merge the data with PHP, I strongly recommend to use Realtime Database Transactions: https://firebase-php.readthedocs.io/en/stable/realtime-database.html#database-transactions

I have tried Transactional. Works fine. Thank you for warn me
