### ISSUE TITLE
Firebase Cloud messaging: Uncaught Error: Call to protected method Kreait\Firebase\Factory::createMessaging() 

### ISSUE THREAD

**Issue by andrewhamili** [kreait/firebase-php#349]
What is the meaning of this error?
![image](https://user-images.githubusercontent.com/20767537/68020377-40656380-fcd9-11e9-9bf3-a63e1099584c.png)

Here is my code:

`<?php

    require __DIR__.'/vendor/autoload.php';
    
    use Kreait\Firebase;
    use Kreait\Firebase\Factory;
    use Kreait\Firebase\ServiceAccount;
    use Firebase\Auth\Token\Exception\InvalidToken;
    use Kreait\Firebase\Messaging\CloudMessage;
    use Kreait\Firebase\Messaging\Notification;

    class FirebaseClass{

        function auth($param){

            $firebaseResult = new FirebaseResult();

            try{

                if(!array_key_exists('idTokenString', $param)){
                    
                    throw new Exception('invalid endpoint params passed');
                }

                $serviceAccount = ServiceAccount::fromJsonFIle(__DIR__ . '/google-services.json');
        
            }catch(Exception $e){
        
                error_log($e->getMessage());
                $error= $e->getMessage();

                $firebaseResult->error = true;
                $firebaseResult->errorMessage = $error;

                return $firebaseResult->returnResult();

        
            }
            try{
                $firebase = (new Factory)
                ->withServiceAccount($serviceAccount)
                ->asUser('my-service-worker')
                ->create();

            }catch(Exception $e){

                error_log($e->getMessage());

                $error= $e->getMessage();

                $firebaseResult->error = true;
                $firebaseResult->errorMessage = $error;

                return $firebaseResult->returnResult();

            }

            try{
    
                $verifiedIdToken = $firebase->getAuth()->verifyIdToken($param['idTokenString'], true, false);

                $uid = $verifiedIdToken->getClaim('sub');
                $user = $firebase->getAuth()->getUser($uid);

                $firebaseResult->error=false;

                
                $firebaseResult->result=$user;

                return $firebaseResult->returnResult();

            }catch(Exception $e){

                error_log($e->getMessage());

                $error= $e->getMessage();

                $firebaseResult->error = true;
                $firebaseResult->errorMessage = $error;

                return $firebaseResult->returnResult();

            }

        }
        function updateUser($uid, $displayName, $phoneNumber, $photoUrl, $changeImage){

            if($changeImage){
                $properties=[
                    'displayName'=>$displayName,
                    'phoneNumber'=>$phoneNumber,
                    'photoUrl'=>$photoUrl
                ];
            }else{
                $properties=[
                    'displayName'=>$displayName,
                    'phoneNumber'=>$phoneNumber
                ];
            }

            

            $serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/google-services.json');

            $firebase = (new Factory)
                ->withServiceAccount($serviceAccount)
                ->create();

            $auth = $firebase->getAuth();

            $updatedUser = $auth->updateUser($uid, $properties);

        }
        function sendMessage(){

            $serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/google-services.json');

            $firebase = (new Factory)
                ->withServiceAccount($serviceAccount)
                ->create();

            $messaging = (new Firebase\Factory())->createMessaging();

            $notification = Notification::fromArray([
                'title'=>'title',
                'body'=>'body',
                'image'=>'https://storage.hamiliserver.com/images/picture.png'
            ]);

            

            $message = CloudMessage::withTarget('topic', 'topic')
                -withNotification($notification);

            $messaging->send($message);
            

        }

    }
    class FirebaseResult{

        public $error;

        public $errorMessage;

        public $result;

        function returnResult(){

            $arrayResult = array(

                'error'=>$this->error,
                'errorMessage'=>$this->errorMessage,
                'result'=>$this->result

            );

            return $arrayResult;

        }

    }

?>`

**Comment by jeromegamez** [comment]
It means that you are not using the latest version of the SDK, you can update the package with `composer require kreait/firebase-php ^4.35` or with a `composer update` to update all your project dependencies.

**Comment by andrewhamili** [comment]
Updated my firebase-php but got a new error:

`<b>Deprecated</b>:  The parameter $allowTimeInconsistencies is deprecated and was replaced with a default leeway of 300 seconds. in <b>/home/andrewhamili/public_html/localserver.com/Social-API/App/Firebase/vendor/kreait/firebase-php/src/Firebase/Auth.php</b>`

**Comment by jeromegamez** [comment]
Remove the deprecated parameter, so replace

```php
$firebase->getAuth()->verifyIdToken($param['idTokenString'], true, false);
```

with

```php
$firebase->getAuth()->verifyIdToken($param['idTokenString'], true);
```

**Comment by andrewhamili** [comment]
Already applied to code. Will read the docs again. Thank you.
