### ISSUE TITLE
syntax error, unexpected ':', expecting ';' or '{' in /home/chawtechsolution/public_html/mdev/firstcall/vendor/kreait/clock/src/Clock.php on line 11

### ISSUE THREAD

**Issue by dmansijain** [kreait/firebase-php#350]
When we use kreait/firebase-php 3.9. it shows this error on php 5.6, anyone have the solution please help me.

**Comment by jeromegamez** [comment]
The clock is not part of release 3.x, and is only compatible with PHP 7.0 and newer - something must have gone wrong. Have you installed your project locally and then uploaded to a PHP 5.6 server?

**Comment by dmansijain** [comment]
yes. now i have installed kreait/firebase-php 1.2.2.. I have found the solution for this. Thanks
