### ISSUE TITLE
Always getting a "This token has an invalid issuer." error on a valid JWT 

### ISSUE THREAD

**Issue by VillaCebras** [kreait/firebase-php#351]
**Describe the bug**
When validating a JWT (created from a custom provider) in a project with a projectID containing "." or ":", you always get a "This token has an invalid issuer." error.

**To Reproduce**
1. Create a custom token from a project with an ID containing "." or ":" (for example: test.com:my-project-12345678901)

2. Use a sign In with custom token client function to get a valid firebaseJWT

3. Validate this token with "verifyIdToken" function

**Environment :**
 - OS: MacOS 10.15
 - PHP version: 7.2
 - Firebase SDK Version: 4.32.0

I've debugged project code and I've found that the problem is in "getSanitizedProjectId" from ServiceAccount.php. 

` if (!$this->sanitizedProjectId) {`
`            $this->sanitizedProjectId = \preg_replace('/[^A-Za-z0-9\-]/', '-', $this->projectId);`
`        }`
`        return $this->sanitizedProjectId;`

preg_replace removes "." and ":" from projectID and then, while validating, the token issuer does not match with the service account ID.

This is my first issue in github! Sorry if I miss something in the description.

Thanks!

**Comment by jeromegamez** [comment]
HI @VillaCebras, and thank you for taking the time to create this issue!

Could you show me how exactly you are creating the custom token and how you're verifying it? A Project ID can't contain dots and colons, and "This token has an invalid issuer" usually means that the custom token has been created in Project A, but was verified using a Service Account from Project B.

![image](https://user-images.githubusercontent.com/67554/68200944-28cff880-ffc1-11e9-9413-2f664f350136.png)

**Comment by jeromegamez** [comment]
Hm, but now it reminds me of https://github.com/kreait/firebase-php/issues/228 ... 

Please try something for me: Go to `https://securetoken.google.com/xxx` and replace `xxx` with your project ID - which one works? The one with `domain.tld:my-project-xxx`, `domain-tld-my-project-xxx` or both?

**Comment by VillaCebras** [comment]
Hi @jeromegamez thanks for your answer!

This project is an old one created on Google Cloud Platform and then it was migrated to Firebase, so Google kept its original project ID...

I've also tried what yoy asked about `https://securetoken.google.com/xxx` and none of both options works :(

**Comment by jeromegamez** [comment]
I think it's debugging time 😅

Could you try this in a test-file in the root of your PHP project:

```php

require 'vendor/autoload.php';

use Lcobucci\JWT\Parser;

$idTokenString = '';

$parser = new Parser();
$parsedToken = $parser->parse($idTokenString);

echo 'Audience:'.$parsedToken->getClaim('aud').PHP_EOL;
echo 'Issuer:'.$parsedToken->getClaim('iss').PHP_EOL;
```

The SDK here follows the guidelines on https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library to verify ID tokens, and there it says:

 Claim | Meaning | Description
-- | -- | --
aud | Audience | Must be your Firebase project ID, the unique identifier for your Firebase project, which can be found in the URL of that project's console.
iss | Issuer | Must be `https://securetoken.google.com/{projectId}`, where `{projectId}` is the same project ID used for `aud` above.

I hope that with this additional information we can get a step further

**Comment by echoesbr** [comment]
@jeromegamez apparently Google allowed the creation of projects with colon values in the past. As @VillaCebras mentioned, projects created via GCP might have had this format by default. Which is my case as well. 
Is this something you can change/support in the SDK?

**Comment by jeromegamez** [comment]
@echoesbr Sorry for the late reply 🙇 - I just added a commit (44d30381381f41cf7d4215abb75fb7cc9ccc49ce) so that colons and dots are not replaced anymore and will create a release shortly 🤞. Thanks for the heads-up!

**Comment by echoesbr** [comment]
> @echoesbr Sorry for the late reply 🙇 - I just added a commit ([44d3038](https://github.com/kreait/firebase-php/commit/44d30381381f41cf7d4215abb75fb7cc9ccc49ce)) so that colons and dots are not replaced anymore and will create a release shortly 🤞. Thanks for the heads-up!

Hi @jeromegamez, thanks for following up on this! Much appreciated 🙏
