### ISSUE TITLE
How this manages cURL calls and when it closes the connection?

### ISSUE THREAD

**Issue by Lordofcodes** [kreait/firebase-php#353]
I have already asked a question here regarding this package's internal behavior for making API calls.
I have been told that this packages do uses cURL calles for API calls.
**_I want to know when a method 
for example `$messaging->send([])` closes the cURL connection?
How can I know the response time?
Is it synchronous call or asynchronous?_**

**Comment by jeromegamez** [comment]
The SDK doesn‘t manage cURL calls, this is managed by the underlying HTTP handler, Guzzle.

You can configure the HTTP client and add middlewares for debugging and Information gathering as described in https://firebase-php.readthedocs.io/en/stable/setup.html#http-client-options-and-middlewares and http://docs.guzzlephp.org/

The calls are synchronous.
