### ISSUE TITLE
Internal error encountered. {"userId":1,"exception":"[object] (Kreait\\Firebase\\Exception\\Messaging\\ServerError(code: 500)

### ISSUE THREAD

**Issue by Xoshbin** [kreait/firebase-php#355]
For the last three days I have been receiving this error `nternal error encountered. {"userId":1,"exception":"[object] (Kreait\\Firebase\\Exception\\Messaging\\ServerError(code: 500)` and I don't know what's the issue. I have been using this package for sending notifications for a year without any issue but in the last three days it's not working. I have generated a new credential and changed this library to the laravel-firebase but got no luck and I thought that it's form Firebase servers that they may be down but I checked there servers there's no issue there too. I'm stuck I don't know what to do next? is there nay updates that i"m not aware of it? I'm using the credential json file from google cloud platform as it's written in the documentation "it was working before" and I think not using anything else for the cloud messaging. so is there anything that I need to put for the cloud messaging because it's not written anywhere in this library?
Thanks in advance

**Comment by jeromegamez** [comment]
Could you show me the code you‘re using to send the message? Which version of the SDK are you using? Is it a 4.x release and are you on the latest version?

**Comment by jeromegamez** [comment]
Does it actually say `UserId: 1`?

**Comment by Xoshbin** [comment]
Right now I'm using the latest version fo laravel-firebase and I was using the latest version of this package too.
```
<?php

namespace App\Listeners;

use App\Events\PostFeatured;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

use Symfony\Component\Cache\Simple\FilesystemCache;

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

use Kreait\Firebase;
use Kreait\Firebase\Messaging\CloudMessage;
use Kreait\Firebase\Messaging\MulticastSendReport;
use Kreait\Firebase\Messaging\FcmOptions;
use Kreait\Firebase\Messaging\Notification;

class SendNotificationFeaturedEventFired
{

    protected $post;
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  PostFeatured  $event
     * @return void
     */
    public function handle(PostFeatured $event)
    {

        $messaging = (new Firebase\Factory())->createMessaging();

        if ($event->topic == "NEWS_TOPIC") {
            $fcmOptions = [
                    'analytics_label' => $event->topic,
                ];

                $notification = Notification::create($event->title, $event->excerpt, $event->postImage);

                $data = [
                    'title' => $event->title,
                    'body' => $event->excerpt,
                    'topic' => strval($event->topicId),
                    'link' => $event->postLink,
                    'imageUrl' => $event->postImage,
                    'id' => strval($event->id),
                    'click_action' => 'FLUTTER_NOTIFICATION_CLICK',
                ];

                $condition = "'NEWS_TOPIC' in topics && ('{$event->locale}' in topics)";

                $message = CloudMessage::withTarget('condition', $condition)
                    ->withNotification($notification) // optional
                    ->withData($data) // optional
                    ->withFcmOptions($fcmOptions);

                $messaging->send($message);
        }
    }
}
```

**Comment by Xoshbin** [comment]
@jeromegamez Yes that's the error form the log file

**Comment by jeromegamez** [comment]
Thanks for the code! Let's first move some things out of the way to see if that already helps.

You're currently instantiating the messaging component with `$messaging = (new Firebase\Factory())->createMessaging();`, but this doesn't make use of the configuration and the dependency injection features that the Laravel package provides - in that case, the factory will not use the configuration at all.

Here's how it is intended to be used:

```php
<?php

namespace App\Listeners;

// ...
use Kreait\Firebase\Messaging;
// ...

class SendNotificationFeaturedEventFired
{
    /** @var Messaging */
    private $messaging;

    public function __construct(Messaging $messaging)
    {
        $this->messaging = $messaging;
    }

    public function handle($event)
    {
        // ...
        $this->messaging->send($message);
        // ...
    }
}
```

If you type-hint the component that you want to use, Laravel will automatically retrieve it for you.

Could you please update your code to use this and see if this already helps?

**Comment by Xoshbin** [comment]
It's still giving the same error, I don't think it's related to dependency injection because before using laravel-firebase package I was using firebase-php package directly. and that was my code for that too:
```
        $cache = new FilesystemCache();

        $serviceAccount = ServiceAccount::fromJsonFile(base_path('credential.json'));

        $firebase = (new Factory)
            ->withServiceAccount($serviceAccount)
            ->withVerifierCache($cache)
            ->create();

        $messaging = $firebase->getMessaging();
```
So I think the issue is not related to the code, it's mostly related to either this package, or my Firebase account that I think there may no connection between firebase and admin skd. which I'm not sure yet.

**Comment by jeromegamez** [comment]
Too bad, I was hoping that it would be that „easy“ :/. Could you try wrapping the call to `send()` in a try/catch and log the exception message? I just realized that the „real“ exception is only wrapped in the log message, hence the user Id of „1“, I didn‘t realize that this is the Laravel user id.

Perhaps this can give a clue what the actual server error is.

Have you tried using the Firebase CLI tool with the same service account and does that work?

Honestly, I would like this to be an error in the SDK or the package, because then I could fix this, but I just tried it myself and it works for me - and unfortunately, I do sometimes hear from people that have issues with accessing Firebase like you have, but not so many that I think this is a code issue (like you said) :/

**Comment by Xoshbin** [comment]
It's not passing the try catch, so it gives the same error. like it's not counting it as an error:
               ```
try {
                    $this->messaging->send($message);
                } catch (Exception $e) {
                    Log::debug($e);
                }
```

**Comment by jeromegamez** [comment]
Try this:

``php
try {
    $this->messaging->send($message);
} catch (\Throwable $e) {
    Log::debug($e);
}
```

Not sure if PHP will try to catch the root exceptions in your code or if it tries to catch an `App\Listeners\Exception` (which it can't find).

If that's not the problem, wouldn't that mean that the error is occurring elsewhere?

**Comment by Xoshbin** [comment]
Thanks, You were right about the exception. anyway it gives this error now which it's still looks the same as before.
```
Kreait\Firebase\Exception\Messaging\ServerError: Internal error encountered.
in /home/188510.cloudwaysapps.com/xhzhajzzxb/public_html/vendor/kreait/firebase-php/src/Firebase/Exception/Messaging/ServerError.php:43
```

**Comment by jeromegamez** [comment]
I get the same error as you (when I tried, I used a token, not a topic condition).

Unfortunately, there's nothing we can do code-wise, you/we are using it as described in https://firebase.google.com/docs/cloud-messaging/send-message#send_messages_to_topics, so it indeed is an error on the Firebase API side.

**Comment by futureco-de** [comment]
Hi there. I have the same issue. Excitingly WE also use FCM via this library to send a push for Flutter apps. However. What I noticed is that I only encounter this error when sending an FCM request with a topic condition. i.E. not key-value `{topic: "topicA"}`, but `{condition: "('topicA' in topics || 'topicB' in topics)"}`.

I asked the Firebase Support and got this reply:
> if you're using the HTTP v1 API, and setting the 'condition' field on your message request? If so, you're affected by a known issue on our end. We're now looking for all possible solutions to fix this. I'll keep you posted.
> For now, you can use the [Legacy HTTP protocol](https://firebase.google.com/docs/cloud-messaging/http-server-ref) as its ‘condition’ field is working as intended.

**Comment by jeromegamez** [comment]
Thanks for the update, @futureco-de!

**Comment by Xoshbin** [comment]
Thank you @futureco-de for the update, And thanks @jeromegamez 👍 for your help.

**Comment by EdwardBock** [comment]
We had the same issue. It's working again now. Seems like they fixed the problem already? Can you confirm?

**Comment by futureco-de** [comment]
Yes, can confirm. I also got this feedback by Firebase team, that the issue was fixed this night at 5am (CET)

**Comment by Xoshbin** [comment]
Yes, can confirm too. It's working again now. thank you guys.

**Comment by TipiT** [comment]
Really nice! Thank you everybody.
