### ISSUE TITLE
Disabled auto discovery still throws exception on createMessaging

### ISSUE THREAD

**Issue by danielsetreus** [kreait/firebase-php#357]
**Describe the bug**
When disabling auto discovery in the factory exceptions are still thrown when creating the messaging instance.

**To Reproduce**
```php
$sa = ServiceAccount::fromJsonFile('/path/to/sa.json');
$sa->withProjectId('project-id');
$factory = new Factory();
$factory->withServiceAccount($sa)->withDisabledAutoDiscovery();
$messaging = $factory->createMessaging();
/** Throws:
Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "FIREBASE_CREDENTIALS" is not set.
Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "GOOGLE_APPLICATION_CREDENTIALS" is not set.
Kreait\Firebase\ServiceAccount\Discovery\FromGoogleWellKnownFile: The well known file is not readable or invalid
*/ 
```

**Expected behavior**
No required environment variables or well known file.

**Environment (please complete the following information):**
 - OS: Docker php-fpm:7.2
 - PHP version: 7.2.24
 - Firebase SDK Version: 4.35.1

**Additional context**
Perhaps I am doing something wrong here - but I would expect this code to fully disable auto discovery.

**Comment by jeromegamez** [comment]
Each call on the factory will return a new instance of the factory, so when you're calling `$factory->createMessaging()`, you're actually using the Factory from the `$factory = new Factory();` line.

This should work:

```php
$factory = new Factory();
$factory = $factory->withServiceAccount($sa)->withDisabledAutoDiscovery();

$messaging = $factory->createMessaging();
```
