### ISSUE TITLE
How to upload file or image to firebase storage 

### ISSUE THREAD

**Issue by waleedazam** [kreait/firebase-php#36]
Hello 
How to upload file or images to firebase storage using this library 
Regards

**Comment by jeromegamez** [comment]
This is not possible yet, but it is definitely on the roadmap!

**Comment by jeromegamez** [comment]
Replaced by #38 - progress will be tracked there.

**Comment by nwaughachukwuma** [comment]
@jeromegamez is this possible now?

**Comment by jeromegamez** [comment]
@nwaughachukwuma Yes, since 4.1.0, see https://firebase-php.readthedocs.io/en/latest/storage.html

**Comment by nwaughachukwuma** [comment]
Awesome! Thanks
