### ISSUE TITLE
Firebase JWT vs lcobucci JWT

### ISSUE THREAD

**Issue by andrews05** [kreait/firebase-php#362]
There's probably a good reason for this, but wondering why lcobucci/jwt is required rather than using the firebase/php-jwt that's already required by google/auth? Just seems redundant having two JWT libraries.

**Comment by jeromegamez** [comment]
I don't know if this qualifies as a _good_ reason 😅, but back in the time when I checked for available libraries on [jwt.io](https://jwt.io), lcobucci/jwt spoke more to me, because it, out of the box, supports more encryption algorithms and checks than the firebase library. I also liked the object-oriented approach better ^^

**Comment by andrews05** [comment]
Yeah, totally understand the OO approach. I was just hoping to avoid installing/loading both libraries, but it's not like it really impacts performance or anything.

**Comment by SimonPrague** [comment]
It would be still better to use the firebase/php-jwt because I can't use this project on AppEngine Standard which does not have the sodium libraries required by lcobucci/jwt.

Is there any workaround to not use lcobucci/jwt ??

**Comment by jeromegamez** [comment]
The 3.x releases of `lcobucci/jwt` don't require the sodium PHP extension, you should be able to work around this by locking the library in your project's root `composer.json`:

```bash
composer require "lcobucci/jwt:^3.4.1"
```

**Comment by ScorNinja** [comment]
Currently unable to use this with Google App Engine because of the sodium library issue. Can't downgrade lcobucci/jwt because it doesn't support PHP 8.1.

**Comment by ScorNinja** [comment]
> Currently unable to use this with Google App Engine because of the sodium library issue. Can't downgrade lcobucci/jwt because it doesn't support PHP 8.1.

Issue resolved by removing "extension=sodium" from php.ini and keeping composer require "ext-sodium" & platform "ext-sodium".
