### ISSUE TITLE
cloud-messaging (understand-delivery)

### ISSUE THREAD

**Issue by Waqaralipk** [kreait/firebase-php#366]
Is there any way to get [understand-delivery](https://firebase.google.com/docs/cloud-messaging/understand-delivery) with php SDK. I don't want to use Google BigQuery for that 
Can anyone please help to give a suggestion to use such an alternative. Is there any server-side support for Big Data?

**Comment by jeromegamez** [comment]
The page you're linking to only has information on how to get insight, what What specifically do you want/need, that this SDK would be able to provide? Let me go through the sections of the page:

### Message Delivery Reports

You can get those by visiting the [Reports](https://console.firebase.google.com/project/_/notification/reporting) tab in the firebase console. This includes all sent messages with a payload and messages with a label. You can add labels to messages as described in https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#adding-platform-independent-fcm-options

### BigQuery data exports

BigQuery is not in the scope of this library. You to link your Firebase project to BigQuery, and can then access BigQuery to inspect the data. If you want to do this with PHP, you can use the [google/cloud-bigquery](https://github.com/googleapis/google-cloud-php-bigquery) package.

You say you don't want to use BigQuery for that, but I don't see an alternative.

**Comment by Waqaralipk** [comment]
Thank you for always giving me the extra push I need.
