### ISSUE TITLE
No feedback/notification after seemingly succesful message

### ISSUE THREAD

**Issue by MagroGaming** [kreait/firebase-php#367]
Dear all,

I'm trying to implement firebase-php for Cloud Messaging. 
After following the instruction and trying to send the message to 1 (my) device, and returning/printing the output of $messaging->send($message) I get this:

**a:1:{s:4:"name";s:71:"projects/words-in-progress/messages/0:1577098824177447%f118c3d3f9fd7ecd";}**

No notification is coming in, and I don't see the result in the Reports section of the Firebase console. If I validate the message it doesn't throw an exception but returns this:
**a:1:{s:4:"name";s:51:"projects/words-in-progress/messages/fake_message_id";}**

Which, after reading stuff online seems like the expected result when it's validated. 

I'm not sure how I would go about debugging this issue, and I can't find anything online that could help me/direct me to the issue at hand. I've also tried looking in the issues section for a similar issue but couldn't find it.

Can anybody help me with this issue?

Thanks in advance.

Matti

**Comment by jeromegamez** [comment]
Unfortunately, there‘s not more feedback than the message ID on success, or an exception on error... but perhaps https://firebase.google.com/docs/cloud-messaging/understand-delivery is a good start for the investigation 🤞

**Comment by MagroGaming** [comment]
In case someone else runs into this problem:

It seems that the way I create the message didn't work as expected, my code was:

$token = $this->GetDeviceTokenByUserID($myId);
$title = "Test title";
$description = "Test description.";
$notification = Notification::create($title, $description);
$fcmOptions = FcmOptions::create()->withAnalyticsLabel('pn_test');
$message = CloudMessage::withTarget('token', $token);
$message->withNotification($notification);
$message->withFcmOptions($fcmOptions);
$resp = $this->GetService()->send($message);


After var_dumping the "message" object I saw NULL values in the Notification object inside Message.
I changed it to:

$token = $this->GetDeviceTokenByUserID($myId);
$title = "Test title";
$description = "Test description";
$notification = Notification::create($title, $description);
$fcmOptions = FcmOptions::create()->withAnalyticsLabel('pn_test');
$message = CloudMessage::withTarget('token', $token)->withNotification($notification)->withFcmOptions($fcmOptions);
$resp = $this->GetService()->send($message);

And now It works as a charm. Thanks jeromegamez for your time and help.

**Comment by jeromegamez** [comment]
Thank you for adding the code that included the issue as well as the fix, this will hopefully help others.

Just to reconfirm: `with`ers always return a new object, `set`ers change the internal state of an object. (the SDK uses `with`ers almost everywhere ^^)
