### ISSUE TITLE
Exception when sending payload containing non-string scalar values

### ISSUE THREAD

**Issue by CthulhuDen** [kreait/firebase-php#371]
**Describe the bug**
Library suddenly started spitting `Message data must be a one-dimensional array of string(able) keys and values.` exceptions.

**To Reproduce**
You payload data just has to have non-string scalar values or keys (e.g. integer).

**Expected behavior**
Cast to string should happen [here](https://github.com/kreait/firebase-php/blob/master/src/Firebase/Messaging/MessageData.php#L29) as it was with previous versions of this library.

Maybe you should check for `isScalar` instead of `isString`?

**Additional context**
It's very bad minor version update of library breaks working code.

**Comment by jeromegamez** [comment]
Yes, it's bad, but it sometimes happens, sorry 😅. I will create a new release with the change shortly. Please note that as previously, boolean values will be casted to `'0'` and `'1'` again and not remain booleans.

**Comment by jeromegamez** [comment]
Release [4.39](https://github.com/kreait/firebase-php/releases/tag/4.39.0) should fix the issue, sorry again for the inconvenience!

**Comment by CthulhuDen** [comment]
Thanks, that was really fast.
