### ISSUE TITLE
guzzlehttp/guzzle/src/Exception/RequestException.php at function verifyPassword()

### ISSUE THREAD

**Issue by LeMajstor** [kreait/firebase-php#372]
By calling the `verifyPassword()` function in Lumen framework i got the following error: 

`GuzzleHttp\\Exception\\ClientException(code: 400): Client error: POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword resulted in a 400 Bad Request response`

All the others methods shown in documentation work fine, I only have problem with this one.

Here's my code

```
public function __construct() {
        $serviceAccount = "{{ my_path }}";
        $factory = (new Factory)
            ->withServiceAccount($serviceAccount)
            ->withDatabaseUri('{{ my_url }}');
        $this->database = $factory->createDatabase();
        $this->auth = $factory->createAuth();
    }

```

verifyPassword function call

```
       public function login (Request $request) {

        $data = $request->header('Authorization');
        $email = $_SERVER['PHP_AUTH_USER'];
        $pwd = $_SERVER['PHP_AUTH_PW'];

        if ((isset($email) && !empty($email)) && (isset($pwd) && !empty($pwd))) {
            $user = $this->auth->verifyPassword($email, $pwd);
        }
    }
```

**Comment by jeromegamez** [comment]
Are you using https://github.com/kreait/laravel-firebase? With that, you don't have to create factory instances yourself.

You could debug this further with something like this:

```php
try {
    $auth->verifyPassword('jerome@gamez.name', 'wrongpassword');
} catch (Throwable $e) {
	echo get_class($e).': '.$e->getMessage();
}
```

What intrigues me is that a Guzzle ClientException should not be thrown directly in any case, but wrapped/converted into an SDK specific exception.
