### ISSUE TITLE
Fatal error: Uncaught Kreait\Firebase\Exception\InvalidArgumentException

### ISSUE THREAD

**Issue by fgamba** [kreait/firebase-php#374]
I've downloaded the latest version (4.35)
I ran composer and everything was installed.  My PHP version is 7.1 with mbstring support.

this is my code:
```php
$base = dirname(__FILE__);
$google = "/google-services.json";
$path = dirname(dirname(dirname($base)));
require $path.'/vendor/autoload.php';

use Kreait\Firebase\Factory;
$factory = (new Factory)
    ->withServiceAccount($path.$google)
    ->withDatabaseUri('https://parachute-f651a.firebaseio.com/')
	->create();
```
and this is the error I got:

Fatal error: Uncaught Kreait\Firebase\Exception\InvalidArgumentException: C:\EasyPHP-Devserver-17\eds-www\recap/google-services.json could not be parsed to a Service Account: The following fields are missing/empty in the Service Account specification: "project_id", "client_id", "client_email", "private_key". Please make sure you download the Service Account JSON file from the Service Accounts tab in the Firebase Console, as shown in the documentation on https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app

This is the google-service.json I downloaded from Firebase, I removed the IDs:

{
  "project_info": {
    "project_number": "xxxxxxxxxxxx",
    "firebase_url": "xxxxxxxxxxxxxxxxxxx",
    "project_id": "xxxxxxxxxxxxxxxxxx",
    "storage_bucket": "xxxxxxxxxxxxxxxxxxxxxxx"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "xxxxxxxxxxxxxxxxxxxxx",
        "android_client_info": {
          "package_name": "xxxxxxxxxxxxxxxxxx"
        }
      },
      "oauth_client": [
        {
          "client_id": "xxxxxxxxxxxxxxxxxxxxxxxx",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "xxxxxxxxxxxxxxxxxxxxxxxxx"
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": [
            {
              "client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
              "client_type": 3
            }
          ]
        }
      }
    }
  ],
  "configuration_version": "1"
}

Not sure what is wrong with the so called missing files

**Environment (please complete the following information):**
 - OS: Windows 7
 - PHP version: 7.1
 - Firebase SDK Version: 4.35

**Comment by jeromegamez** [comment]
The JSON file you are using is meant to be used with a client application, not with an Admin SDK. In order to create a credentials file for an Admin SDK, please follow the steps described in https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app and download the generated private JSON Key file. When you open that file, you will see that it has the same structure as in e.g. https://github.com/kreait/firebase-php/blob/3303904cc12e45e024706e7131c71557360719ac/tests/_fixtures/ServiceAccount/valid.json#L1-L12

PS: The latest version is 4.39.1 😅

**Comment by fgamba** [comment]
Thanks Jerome...will do it immediately and I will let you know

**Comment by fgamba** [comment]
Jerome,
After set the right json file I could be able to instanciate Firebase but when I try to create a message I got this


Fatal error: Uncaught Kreait\Firebase\Exception\ServiceAccountDiscoveryFailed: Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "FIREBASE_CREDENTIALS" is not set. Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "GOOGLE_APPLICATION_CREDENTIALS" is not set. Kreait\Firebase\ServiceAccount\Discovery\FromGoogleWellKnownFile: The well known file is not readable or invalid Error creating resource: [message] fopen(): php_network_getaddresses: getaddrinfo failed: Host desconocido. [file] C:\EasyPHP-Devserver-17\eds-www\recap\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php [line] 323 [message] fopen(http://metadata.google.internal/computeMetadata/v1/project/project-id): failed to open stream: php_network_getaddresses: getaddrinfo failed: Host desconocido. [file] C:\EasyPHP-Devserver-17\eds-www\recap\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php [line] 323 in C:\EasyPHP-Devserver-17\eds-www\recap\vendor\kreait\firebase-php\ in C:\EasyPHP-Devserver-17\eds-www\recap\vendor\kreait\firebase-php\src\Firebase\ServiceAccount\Discoverer.php on line 52

Not sure where I can set those environemnt variables, please advice...thanks in advance

**Comment by fgamba** [comment]
by the way, what I want to do is to set a "push notifications" messaging system using firebase, this is the code:
$google = "/parachute-f651a-firebase-adminsdk-tmlqh-d973c5d3f0.json";
$path = dirname(dirname(dirname($base)));

require $path.'/vendor/autoload.php';
use Kreait\Firebase;
use Kreait\Firebase\Factory;
use Kreait\Firebase\Messaging\CloudMessage;
$factory = (new Factory)
    ->withServiceAccount($path.$google)
    ->withDatabaseUri('https://parachute-f651a.firebaseio.com/')
	->create();
	
$messaging = (new Firebase\Factory())->createMessaging();

and this is the json file I am using now:

{
  "type": "service_account",
  "project_id": "xxxxxxx",
  "private_key_id": "xxxxxxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\xxxxxxxxxxxxxxxxxx\n-----END PRIVATE KEY-----\n",
  "client_email": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "client_id": "xxxxxxxxxxxxxxxxxxxxxx",
  "auth_uri": "xxxxxxxxxxxxxxxxxxxxx",
  "token_uri": "xxxxxxxxxxxxxxxxxxxxxxx",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "xxxxxxxxxxxxxxxxxxxxxxx"
}

**Comment by jeromegamez** [comment]
Your are instantiating a `Factory` twice, and the second time, you don't provide the service account, so the second instance resolves to autodiscovery and can't find the service account in the well known spaces.

You need to instantiate the factory only once and then get the components that you want from there:

```php
// In most cases you don't need
$factory = (new Factory)
    ->withServiceAccount($path.$google)
    // you don't need `withDatabaseUri` in most cases,
    // try first without using it
    //->withDatabaseUri('parachute-f651a.firebaseio.com')
;

$messaging = $factory->createMessaging();
```

Please note that `Factory::create)` has been deprecated since a few releases now, you should not rely on it.
