### ISSUE TITLE
Error with create notification

### ISSUE THREAD

**Issue by andrei2424** [kreait/firebase-php#381]
`$notification = Notification::create()
    ->withTitle('title')
    ->withBody('body');`

Exception: Firebase/Messaging/Notification.php:28

> throw new InvalidArgumentException('The title and body of a notification cannot both be NULL');

**Comment by jeromegamez** [comment]
Thanks for the... Notification 😅

Until this is addressed, please use

```
$notification = Notification::create('title', 'body');
```

**Comment by jeromegamez** [comment]
The documentation was indeed incorrect - as it's not possible to send a message with a Notification that doesn't have a title nor a body, it wouldn't make sense to be able to create a notification with neither 😅
