### ISSUE TITLE
Null values cant be sent in the notification from 4.38.0+

### ISSUE THREAD

**Issue by VaNGOgh94** [kreait/firebase-php#383]
**Describe the bug**
After we updated lib version from 4.37 to 4.38 our notifications system stopped working. Reason being that in most of notifications we had some keys with NULL value in the message data. 

**To Reproduce**
You payload data just has to have a key with value NULL

```php
$notification = [
            // Data  Payload
            'data' => [
                'key' => null,
            ],
         ...
];

return CloudMessage::fromArray($notification);

```

**Expected behavior**
Null values are stringable, and the library throws exception that it is not stringable.

**Environment (please complete the following information):**
 - PHP version: 7.3.8
 - Firebase SDK Version: [e.g. 4.38+]

**Additional context**
Proposed fix:
```php
    private static function isStringable($value): bool
    {
        return \is_null($value) || \is_scalar($value) || (\is_object($value) && \method_exists($value, '__toString'));
    }
```

**Comment by jeromegamez** [comment]
Thanks for the notice, I'll release a fix soon

**Comment by VaNGOgh94** [comment]
Thank you for the quick response!

**Comment by jeromegamez** [comment]
Sorry for breaking the functionality 😭

**Comment by VaNGOgh94** [comment]
We rolled back the version so there were no big issues in the company :)

**Comment by jeromegamez** [comment]
Release 4.39.2 is now out, it should hopefully fix this, and not break something else 🤞. Thank you!
