### ISSUE TITLE
Kreait\Firebase\Exception\ServiceAccountDiscoveryFailed

### ISSUE THREAD

**Issue by p99993** [kreait/firebase-php#384]
I use the [374 issues](https://github.com/kreait/firebase-php/issues/374/) method is no problem
I've downloaded the latest version (4.40)
I ran composer and everything was installed. My PHP version is 7.1 with mbstring support.

this is my code:
```
$array = [
	function () use ($serviceAccount) {
		return $serviceAccount;
	}
];
$discoverer = new Discoverer($array);
$factory = (new Factory())->withServiceAccountDiscoverer($discoverer);
$auth = $factory->createAuth();
```
and this is the error I got:

```
ERROR Kreait\Firebase\Exception\ServiceAccountDiscoveryFailed in /server/vendor/kreait/firebase-php/src/Firebase/ServiceAccount/Discoverer.php:52

 [Kreait\Firebase\Exception\ServiceAccountDiscoveryFailed]  
```

Environment (please complete the following information):

OS: Centos 7
PHP version: 7.1
Firebase SDK Version: 4.40

**Comment by jeromegamez** [comment]
Instead of `return $serviceAccount` use `return \Kreait\Firebase\ServiceAccount::fromValue($serviceAccount);`

**Comment by p99993** [comment]
> Instead of `return $serviceAccount` use `return \Kreait\Firebase\ServiceAccount::fromValue($serviceAccount);`

Thanks Jerome

**Comment by jeromegamez** [comment]
You're welcome :)
