### ISSUE TITLE
"Recipient of the message is not set." at sending to a specific device

### ISSUE THREAD

**Issue by chanbuu** [kreait/firebase-php#386]
**Describe the bug**
I have an error that display "Recipient of the message is not set.".
I want to sent a notification to a specific device.
I have tried following the documentation.
https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html#send-messages-to-specific-devices.

In a simple condition, it's success. like below.
```
Kreait\\Firebase\\Messaging\\CloudMessage Object
(
    [target:Kreait\\Firebase\\Messaging\\CloudMessage:private] => Kreait\\Firebase\\Messaging\\MessageTarget Object
        (
            [type:Kreait\\Firebase\\Messaging\\MessageTarget:private] => token
            [value:Kreait\\Firebase\\Messaging\\MessageTarget:private] => spefic_token_hoge
        )

    [data:Kreait\\Firebase\\Messaging\\CloudMessage:private] => 
    [notification:Kreait\\Firebase\\Messaging\\CloudMessage:private] => Kreait\\Firebase\\Messaging\
otification Object
        (
            [title:Kreait\\Firebase\\Messaging\
otification:private] => test
            [body:Kreait\\Firebase\\Messaging\
otification:private] => test
            [imageUrl:Kreait\\Firebase\\Messaging\
otification:private] => 
        )

    [androidConfig:Kreait\\Firebase\\Messaging\\CloudMessage:private] => 
    [apnsConfig:Kreait\\Firebase\\Messaging\\CloudMessage:private] => 
    [webPushConfig:Kreait\\Firebase\\Messaging\\CloudMessage:private] => 
    [fcmOptions:Kreait\\Firebase\\Messaging\\CloudMessage:private] => 
)
```

But the below is not able to work.
```
Kreait\\Firebase\\Messaging\\CloudMessage Object
(
    [target:Kreait\\Firebase\\Messaging\\CloudMessage:private] => Kreait\\Firebase\\Messaging\\MessageTarget Object
        (
            [type:Kreait\\Firebase\\Messaging\\MessageTarget:private] => token
            [value:Kreait\\Firebase\\Messaging\\MessageTarget:private] => specific_token_hoge
        )

    [data:Kreait\\Firebase\\Messaging\\CloudMessage:private] => 
    [notification:Kreait\\Firebase\\Messaging\\CloudMessage:private] => Kreait\\Firebase\\Messaging\
otification Object
        (
            [title:Kreait\\Firebase\\Messaging\
otification:private] => test
            [body:Kreait\\Firebase\\Messaging\
otification:private] => test
            [imageUrl:Kreait\\Firebase\\Messaging\
otification:private] => 
        )

    [androidConfig:Kreait\\Firebase\\Messaging\\CloudMessage:private] => Kreait\\Firebase\\Messaging\\AndroidConfig Object
        (
            [rawConfig:Kreait\\Firebase\\Messaging\\AndroidConfig:private] => Array
                (
                    [ttl] => 3600s
                    [priority] => high
                    [notification] => Array
                        (
                            [title] => test
                            [body] => test\x82\xbe\x82\xe6\x81I
                            [notification_count] => 1
                        )

                )

        )

    [apnsConfig:Kreait\\Firebase\\Messaging\\CloudMessage:private] => 
    [webPushConfig:Kreait\\Firebase\\Messaging\\CloudMessage:private] => 
    [fcmOptions:Kreait\\Firebase\\Messaging\\CloudMessage:private] => 
)
```

**To Reproduce**
My code is

```php our_class.php
$messaging  = (new Firebase\Factory())->createMessaging();
$message    = CloudMessage::withTarget('token', $device_token);
$message = $message->withNotification($this->_notification);
$message = $message->withData($this->_data);

$android_config = AndroidConfig::fromArray($android_message);
$message = $message->withAndroidConfig($android_config);

$ios_config = ApnsConfig::fromArray($ios_message);
$message = $message->withApnsConfig($ios_config);

 // validate.
try {
     $messaging->validate($message);
}catch(InvalidMessage $e){
    $this->_outputLog($e->errors());
    return false;
}
$responce = $messaging->send($message);

```

**Environment (please complete the following information):**
 - OS: CentOS 7.6
 - PHP version: 7.3.5
 - Firebase SDK Version: 4.40

Thank you.

**Comment by jeromegamez** [comment]
It's hard to read the output of a `var_dump()` do I see it correctly that the difference between working and not working is the Android Config?

If it works with the same code with one message but not the other, it's probably something inside the Android Config that Firebase is complaining about. From what I can see, the message composition itself looks ok 🤔

**Comment by chanbuu** [comment]
@jeromegamez 
Thank you for your comment.
Sorry. My output is so hard to read.

It didn't work when I had added the Android Config.
The difference is only the Android Config.
```
[
	 'ttl' => '3600s'
	,'priority' => 'high'
	,'notificction' => [
		 'title' => 'test'
		,'body'	 => 'test2'
		,'notification_count' => 1
	]
]
```
Is there more requirement key?

**Comment by jeromegamez** [comment]
I don‘t know if this is just a typo here, but `notificction` should probably be `notification` 😅

**Comment by chanbuu** [comment]
sorry. that is correct on my code

**Comment by jeromegamez** [comment]
I‘m sorry, I can‘t tell you why this is not working. From what you‘ve shown and comparing it to the specs at https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidNotification it should work...

**Comment by chanbuu** [comment]
@jeromegamez 
Thanks.

I have tried a sample in the document. It worked!
```php
// Example from https://firebase.google.com/docs/cloud-messaging/admin/send-messages#android_specific_fields
$config = AndroidConfig::fromArray([
    'ttl' => '3600s',
    'priority' => 'normal',
    'notification' => [
        'title' => '$GOOG up 1.43% on the day',
        'body' => '$GOOG gained 11.80 points to close at 835.67, up 1.43% on the day.',
        'icon' => 'stock_ticker_update',
        'color' => '#f45342',
    ],
]);

$message = $message->withAndroidConfig($config);
```

The cause is to send a message by multi-byte character.
I wanna to use Japanese. like ”タイトル" and "本文" ( it means "title" and "body")
But it's converted escape characters at when the AndroidConfig Object to JSON.
e.g. ) "これは" --> "\x82\xb1\x82\xea\x82\xcd"

How to send a message by multi-byte character?

**Comment by jeromegamez** [comment]
I tried it with the strings you provided, and it worked for me (I've sent it to a browser because I don't have an Android phone, but the sent message is the same), and it looks fine to me:

![image](https://user-images.githubusercontent.com/67554/75503540-2bbe8100-59d6-11ea-92a9-055c73f8c814.png)

This could be a file/text encoding issue... could you check if your code file is UTF-8 encoded? On Linux or MacOS you can do it with the `file` command, on Windows I don't know...

![image](https://user-images.githubusercontent.com/67554/75503672-95d72600-59d6-11ea-9478-1354f82ebd72.png)

Another reason could be that the Android App is not decoding the string correctly, but there I have no idea how to debug this or to fix it - I can just suggest checking that you're using the latest Android Client SDK...

I hope this helps at least a little!

**Comment by chanbuu** [comment]
Thanks.
I've tried again... It works!
So sorry... It's my eassssssssssssssssssssssy mistake.

It is a wrong file-encoding.Not UTF-8.
I corrected the encoding of the file. Then I could sent a message with the strings.

Thank you very very much for your cooperation.

**Comment by jeromegamez** [comment]
You‘re welcome! I‘m happy I could help! 🌺
