### ISSUE TITLE
How to push Cloud Messaging with "\n" for break line?

### ISSUE THREAD

**Issue by ptson1189** [kreait/firebase-php#393]
Hi,

Is there any way to push notification with multiline?
I try to add "\n" to notification body but the result has all text with "\n" too.

**Comment by jeromegamez** [comment]
How did you create the notification? Have you used double (`"`) or single (`'`) quotes when composing the notification body? If you used single quotes, control characters will not be evaluated.

I have tested this with the following command:

```php
$messaging->send(
    CloudMessage::withTarget('token', $firefoxToken)
        ->withNotification([
            'title' => 'Title',
			// 👇 Note the double quotes 👇
            'body' => "Body\nwith\nline breaks"
        ])
);
```

However, my browser didn't display the added line breaks and I am not sure that  FCM actually supports line breaks.

It is possible to add a subtitle for iOS Notifications (see https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support), but for Android notifications, I didn't see a similar option.

I hope this helps!

**Comment by ptson1189** [comment]
> How did you create the notification? Have you used double (`"`) or single (`'`) quotes when composing the notification body? If you used single quotes, control characters will not be evaluated.
> 
> I have tested this with the following command:
> 
> ```
> $messaging->send(
>     CloudMessage::withTarget('token', $firefoxToken)
>         ->withNotification([
>             'title' => 'Title',
> 			// Note the double quotes 👇
>             'body' => "Body\nwith\nline breaks"
>         ])
> );
> ```
> 
> However, my browser didn't display the added line breaks and I am not sure that FCM actually supports line breaks.
> 
> It is possible to add a subtitle for iOS Notifications (see https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support), but for Android notifications, I didn't see a similar option.
> 
> I hope this helps!

Thank you very much. It worked on IOS, but android still not.
