### ISSUE TITLE
Issues with Cloud Message

### ISSUE THREAD

**Issue by Munin67** [kreait/firebase-php#395]
Unable to use CloudMessage class due to the use of the reserved word new as the static function

Error at compiler output: unexpected new

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - PHP version: 7.2.4
 - Firebase SDK Version: latest
![cloudmessageerror](https://user-images.githubusercontent.com/62337580/76960714-e83f9e80-6913-11ea-8c34-62d8f45bca17.png)

**Comment by jeromegamez** [comment]
This should not throw an error 🤔, please see https://3v4l.org/pDDac for a working example. This class hasn't been touched for over half a year, and I'm sure the tests (or other SDK users) would have reported it already.

If you're using PHPStorm, have you set the PHP language level to at least 7.0 and using a PHP 7.x CLI interpreter?

PS: "latest" is not a helpful version number 😅

**Comment by Munin67** [comment]
Its 4.41.0
strange am using 7.2.4 PHP CLI.
Ah found out, could be the IDE problem, thanks
