### ISSUE TITLE
Cross project sign in with service account not working.

### ISSUE THREAD

**Issue by constantijn** [kreait/firebase-php#400]
Hi,

I'm trying to run integration tests with a JWT generated by the auth library but i'm running into errors.
Locally they work but when running on CI i get the following error.

```
 Kreait\Firebase\Auth\SignIn\FailedToSignIn: CONFIGURATION_NOT_FOUND
 /builds/phoenix/hn-services/auth-cms/auth-cms-api/vendor/kreait/firebase-php/src/Firebase/Auth/SignIn/FailedToSignIn.php:33
 /builds/phoenix/hn-services/auth-cms/auth-cms-api/vendor/kreait/firebase-php/src/Firebase/Auth/SignIn/GuzzleHandler.php:55
 /builds/phoenix/hn-services/auth-cms/auth-cms-api/vendor/kreait/firebase-php/src/Firebase/Auth.php:829
 /builds/phoenix/hn-services/auth-cms/auth-cms-api/tests/TestCase.php:27
```

TestCase:27 is `signInWithEmailAndPassword` in:
```
        $this->token = (new \Kreait\Firebase\Factory)
            ->withDatabaseUri("https://" . env("FIREBASE_AUTHDOMAIN"))
            ->createAuth()
            ->signInWithEmailAndPassword(env('TEST_USER'), env('TEST_PASS'))
            ->idToken();
```
I tried the `withDatabaseUri` with the https://, without it, and by completely leaving it out and i keep getting the same error.

I suspect the issue is that it can't find the correct firebase auth backend to authenticate against.
- The tests run in the CI-CD project with a service account that is also tied to the CI-CD project.
- The firebase auth the tests are supposed to run against is in another project that the service account has IAM permissions on.
- The library shouldn't use the project that the service account is tied to.

**Comment by constantijn** [comment]
@jeromegamez any chance you can take a look? thanks in advance :)

**Comment by jeromegamez** [comment]
`CONFIGURATION_NOT_FOUND` is an error that I haven't seen before (unfortunately it's also not documented on https://firebase.google.com/docs/reference/rest/auth) - all I could find so far is in https://github.com/firebase/firebase-admin-node/blob/master/src/utils/error.ts#L360-L362 ("There is no configuration corresponding to the provided identifier."), but I don't know (yet) what that means.

Could you try inspecting the full response body of the call? Perhaps it has some more information... it could look something like this:

```php
try {
    $this->token = (new \Kreait\Firebase\Factory)
        ->withDatabaseUri("https://" . env("FIREBASE_AUTHDOMAIN"))
        ->createAuth()
        ->signInWithEmailAndPassword(env('TEST_USER'), env('TEST_PASS'))
        ->idToken();
} catch (\Kreait\Firebase\Auth\SignIn\FailedToSignIn $e) {
    echo (string) $e->response()->getBody();
}
```
---
I'll push a branch/create a PR later today that enables explicitly setting/overriding the project ID when creating a factory (it's originally meant to try to address #399), that way you will be able to do something like this:

```php
$localProjectFactory = (new Factory)->withProjectId('local-project-id');
$remoteProjectFactory = (new Factory)->withProjectId('remote-project-id');
```
---
Side note: The database URI plays no role for authentication - it only specifies the endpoint for requests from the realtime database component when using `$factory->createDatabase()`.

**Comment by jeromegamez** [comment]
For the sake of completeness: is the email/password sign-in provider enabled in  the other project at https://console.firebase.google.com/u/0/project/_/authentication/providers ? 🙈

**Comment by constantijn** [comment]
The error i get if i do the echo you mentioned up there is:
```
{
   "error": {
     "code": 400,
     "message": "CONFIGURATION_NOT_FOUND",
     "errors": [
       {
         "message": "CONFIGURATION_NOT_FOUND",
         "domain": "global",
         "reason": "invalid"
       }
     ]
   }
 }
```
Also the tests worked if i run them locally, so that tells me everything is setup properly at the firebase auth side or that wouldn't work :)

**Comment by constantijn** [comment]
Looking forward to be able to run 
```php
$localProjectFactory = (new Factory)->withProjectId('local-project-id');
```
That just might fix the problem (or at least i hope it does ;))
Let me know when you want me to test it.

**Comment by jeromegamez** [comment]
@constantijn Please have a look at #401 - I hope it helps, at least a little 🤞

**Comment by constantijn** [comment]
Tried it, still get the same error :(

**Comment by jeromegamez** [comment]
I‘m afraid we‘re out of options at the moment then at least from the SDK point of view. As the error is returned from the API, perhaps a support request at Google would be in order 🤔 

Another possible path would be to integrate the API key used for client application (browser, mobile, etc.) for authenticating requests, but that‘s a bigger undertaking which I‘m not sure when I can tackle it (as this SDK is meant to be an Admin/Server-to-Server SDK), as I have other tasks on my pipeline :/

Sorry for not having a more satisfying response 😕

**Comment by constantijn** [comment]
Ok, then for now I'll add a separate service account to my pipeline that is owned by the project as a work around.
Thanks for all the help up to this point!
