### ISSUE TITLE
Call to private method Kreait\Firebase\ServiceAccount::fromJsonFile()

### ISSUE THREAD

**Issue by VivekGuna1994** [kreait/firebase-php#410]
I am not able to call the "fromJsonFile" method of "ServiceAccount", i am using php as backend and want to integrate firebase.
 
```php
<?php
require __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount; 

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/google-service-account.json');
$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->create();

$database = $firebase->getDatabase();

?>
``` 
Error:-
Fatal error: Uncaught Error: Call to private method Kreait\Firebase\ServiceAccount::fromJsonFile() from context '' in C:\xampp\htdocs\wordpress\wp-content\plugins\firebase-connection.php:7 Stack trace: #0 C:\xampp\htdocs\wordpress\wp-content\plugins\sb-api\sb_api.php(31): include() #1 C:\xampp\htdocs\wordpress\wp-settings.php(362): include_once('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\wordpress\wp-config.php(90): require_once('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\wordpress\wp-load.php(37): require_once('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\wordpress\wp-admin\admin.php(34): require_once('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\wordpress\wp-admin\index.php(10): require_once('C:\\xampp\\htdocs...') #6 {main} thrown in C:\xampp\htdocs\wordpress\wp-content\plugins\firebase-connection.php on line 7

The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

**Environment (please complete the following information):**
 - OS: Windows 10,
 - PHP version: 7.3.8
 - Firebase SDK Version: latest
 
Please help. 
@jeromegamez

**Comment by jeromegamez** [comment]
„Latest“ is not a version 😅, luckily I can safely say that you’re on a `5.x` release and are using 4.x methods that have been deprecated a long time ago and removed in 5.0.

Please read and follow the documentation at https://firebase-php.readthedocs.io/en/stable/setup.html

**Comment by VivekGuna1994** [comment]
Thank you so much @jeromegamez , i was refering to old documents.
Now i am able to connect to firebase.

Just one little question , **how am i able to send the OTP to mobile number ?**
Since i am doing PHP as backend , and doing OTP based authentication using firebase.
So can you please help me out with this.

**Comment by jeromegamez** [comment]
You're welcome, glad it works now! 🥳 

Firebase Phone authentication with a One-Time-Password is only possible on the client-side, not on the server-side. If you need OTP this way, you would have to implement it on your own, https://medium.com/@ResoluteSoftware/serverless-supercharged-one-time-password-based-authentication-with-firebase-cloud-backend-9a7afb96dc88 (Paywall possible) shows how you could do this.

As the original issue is resolved, I'm going to close the issue now, but feel free to add further comments if needed 😅.
