### ISSUE TITLE
Allow setting up sound option for notifications

### ISSUE THREAD

**Issue by kristijorgji** [kreait/firebase-php#411]
Right now it is not possible to specify the sound key when creating a notification of type
namespace Kreait\Firebase\Messaging\Notification

[More information about the option](https://firebase.google.com/docs/reference/admin/node/admin.messaging.NotificationMessagePayload#optional-sound)

**Comment by jeromegamez** [comment]
Yes, it is possible. 

As documented in https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#adding-target-platform-specific-configuration , the SDK is using the HTTP V1 API. 

There you can find a link to https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages which describes all possible config options.

See https://github.com/kreait/firebase-php/pull/299#issuecomment-494912788 for an example.

**Comment by kristijorgji** [comment]
Great, thanks I missed that ! Was only using the notification class
