### ISSUE TITLE
Error : Call to private Method

### ISSUE THREAD

**Issue by Denysetya1** [kreait/firebase-php#415]
I am using Firebase Admin SDK for PHP v 5.1.1
My problem
Fatal error: Uncaught Error: Call to private method Kreait\Firebase\ServiceAccount::fromJsonFile() from context

I use this method:
$acc = ServiceAccount::fromJsonFile(__DIR__.'/xxx.json');

**Comment by jeromegamez** [comment]
Duplicate of https://github.com/kreait/firebase-php/issues/410, https://github.com/kreait/firebase-php/issues/408
