### ISSUE TITLE
Unable to get environnement variable

### ISSUE THREAD

**Issue by Shifu33** [kreait/firebase-php#420]
**Describe the bug**
Unable to get environment variable to connect to Firebase in getServiceAccount function in the Factory bacause of the getEnv() function

**To Reproduce**
/config/packages/firebase.yaml
```yaml
kreait_firebase:
    projects:
        first:
            public: true
            default: false
            credentials: '%kernel.project_dir%/firebase_credentials.json'
            database_uri: 'https://firebaseurl-id.firebaseio.com'
```
.env.local
```env
FIREBASE_CREDENTIALS=/var/www/project/firebase_credentials.json
```
Firebase Test Manager
```php
<?php

namespace App\Service;

use Google\Cloud\Firestore\FirestoreClient;
use Kreait\Firebase\Factory;
use Kreait\Firebase\Firestore;

final class FirestoreTest
{
    private Factory $factory;
    private Firestore $firestore;
    private FirestoreClient $database;

    public function __construct(Factory $factory)
    {
        $this->factory   = $factory;
        $this->firestore = $this->factory->createFirestore();;
        $this->database  = $this->firestore->database();
    }

    public function test(): void
    {
        $collection = $this->database->collection("cities");
        $document = $collection->document("paris");

        $document->set(["field" => "test"]);
    }
}
```

**Expected behavior**
In theory, my resource must be created in my firestore.

**Screenshots**
![image](https://user-images.githubusercontent.com/23473081/80984778-9ce34000-8e2e-11ea-83cf-a5f3819f85c7.png)
![image](https://user-images.githubusercontent.com/23473081/80984833-ac628900-8e2e-11ea-987d-5274b588f589.png)
![image](https://user-images.githubusercontent.com/23473081/80984847-b3899700-8e2e-11ea-89b5-d8ca711e6861.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - PHP version: 7.4.5
 - google/cloud-firestore: 1.8
 - grpc/grpc: 1.27
 - kreait/firebase-bundle: 2.0
 - kreait/firebase-php: 5.2

**Additional context**
I have found this issue and I think it's connected https://github.com/symfony/recipes/issues/532

**My Workaround**
I have create my own factory and extended Kreait\Firebase\Factory to use $_ENV and $_SERVER and use it.

```php
<?php

namespace App\Firebase\Service;

use Kreait\Firebase\Factory as BaseFactory;
use Kreait\Firebase\ServiceAccount;

final class Factory extends BaseFactory
{
    const ENV_VAR_NAME = "FIREBASE_CREDENTIALS";

    protected function getServiceAccount(): ?ServiceAccount
    {
        if ($this->serviceAccount)
            return $this->serviceAccount;

        if ($credentials = $_ENV[static::ENV_VAR_NAME] ?? $_SERVER[static::ENV_VAR_NAME])
            return $this->serviceAccount = ServiceAccount::fromValue($credentials);

        return parent::getServiceAccount();
    }
}
```

So what to you think of my workaround ? Can I risk something ? And can you use $_ENV and $_SERVER in your Factory to avoid this workaround ?

**Comment by jeromegamez** [comment]
In the config I think it should be possible to write

```yaml
credentials: '%env(FIREBASE_CREDENTIALS)%'
```

Could you try if this works? I know it doesn't resolve the `getenv()` issue, but it should resolve the problem within a Symfony application.

**Comment by Shifu33** [comment]
Hello thanks for your reply !

I just tried and unfortunately I got the same error ... But it would be great if it could work!

**Comment by jeromegamez** [comment]
@Shifu33 Sorry for the long wait - could you please check if using `"kreait/firebase-php": "dev-master"` improves the situation? You can find the changes here: https://github.com/kreait/firebase-php/commit/8b8e5272cb86e4b4844671dca32950ab7d1753ec

If it helps, I will create a new release shortly 🤞

**Comment by Shifu33** [comment]
Hey @jeromegamez thank you very much for the fix, it worked perfectly ... You can add it on the next release and I waiting for it !

**Comment by jeromegamez** [comment]
Here it is 🥳 [5.3.0](https://github.com/kreait/firebase-php/releases/tag/5.3.0)
