### ISSUE TITLE
Firebase 

### ISSUE THREAD

**Issue by Joel9000** [kreait/firebase-php#423]
**Describe the bug**

**To Reproduce**
A self-contained code example to reproduce the behavior

```php
// Code to reproduce the behavior
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, MacOS 10.14, Ubuntu 18.04, ...]
 - PHP version: [e.g. 7.3.8]
 - Firebase SDK Version: [e.g. 4.28, **not** "latest"]

**Additional context**

**Comment by jeromegamez** [comment]
Are you planning to add something this issue or can you/I close it? 😅
