### ISSUE TITLE
Docs update for Cloud Messaging

### ISSUE THREAD

**Issue by redbayoub** [kreait/firebase-php#424]
**Is your feature request related to a problem? Please describe.**
this my first time to use this package and i was frustrated all day long trying to send FCM notification and i was getting strange error 
`Kreait/Firebase/Exception/Messaging/InvalidMessage with message 'Invalid JSON payload received. Unknown name "message": Proto field is 
not repeating, cannot start list.'`
what i found is that `CloudMessage::withTarget('topic', $topic)` return a **new** object and and **doesn't** apply to the same object 

**Describe the solution you'd like**
It should be cleared out in the docs that using with... return new object and **doesn't** apply
 the same object that was called from

**Comment by jeromegamez** [comment]
I'm not sure I understand... static methods like `Class::method()` always return new objects, am I missing something?

**Comment by jeromegamez** [comment]
I can/will add a general notice about the immutability of returned objects to the docs, but if you have more details about a particular issue, I‘d appreciate more details.

**Comment by redbayoub** [comment]
thanks my code looks like this before 

```
$message = CloudMessage::new(); 
$notification = Notification::create($title, $body);
$message->withNotification($notification);
$data = [
    'first_key' => 'First Value',
    'second_key' => 'Second Value',
];
$message->withData($data);
$messaging->send($message);
```
but that doesn't work at all even though the code looks right especially for me as a noob in Laravel
and coming from Java background 
and i didn't notice in the docs that you and new object each time you use "with.."
 `$message =  $message->withData($data);`

**Comment by jeromegamez** [comment]
Thank you for the clarification! Although I believe that the documentation is clear enough, I [added a note to the troubleshooting section](https://github.com/kreait/firebase-php/commit/1e136868cf7fa4799b203ef036ea737c2f2acdfe), just in case.
