### ISSUE TITLE
Phone auth with backend verification

### ISSUE THREAD

**Issue by GENL** [kreait/firebase-php#426]
As mentioned here: https://github.com/kreait/firebase-php/issues/293#issuecomment-635334717,

it is useful in some cases to have phone auth verification to the backend.

**Comment by jeromegamez** [comment]
Firebase doesn't provide the means to do phone auth verification on the backend. If there's a solution, it is out of the scope of this SDK.

I've written a lengthy comment on this exact topic on StackOverflow - it's from March 2019, but I still stand by it :) 

https://stackoverflow.com/questions/55121166/phone-authentication-validation-from-server-side-firebase-php/55171266#55171266

As soon as one of the official Firebase Admin SDKs provide such a solution, I might reconsider :)
