### ISSUE TITLE
I want to get a request when an API error occurs

### ISSUE THREAD

**Issue by tnkwmit** [kreait/firebase-php#428]
If I get an unexpected error when running FCM v1 API, I would like to get the request information for contacting support.
However, if response exists, $previous is set to null and RequestException cannot be obtained.

https://github.com/kreait/firebase-php/blob/a7c71ab4c6446965ad52b0efd671742bce7c7955/src/Firebase/Exception/MessagingApiExceptionConverter.php#L90-L92

Is it possible to set RequestException in the $previous even if response exists?

```
        if ($response = $e->getResponse()) {
            return $this->convertResponse($response, $e);
        }
```

**Comment by jeromegamez** [comment]
Good catch @tnkwmit! Of course it's possible 😅and will be included in the next release (see https://github.com/kreait/firebase-php/commit/994ec59d77e853f7f37e738ecaff4701edc921fe)
