### ISSUE TITLE
Failed to get statistics for dynamic link with laravel

### ISSUE THREAD

**Issue by rahulsree7** [kreait/firebase-php#429]
Here is my code:

 $factory=(new Factory())->withServiceAccount(__DIR__.'/firebase.json');
 $dynamicLinksDomain = 'https://example.page.link';
 $dynamicLinks = $factory->createDynamicLinksService($dynamicLinksDomain);
 $stats = $dynamicLinks->getStatistics('https://example.page.link/123');

Here function getStatistics() returns "Failed to get statistics for dynamic link ".

**Comment by jeromegamez** [comment]
You can only get statistics for a dynamic link that you have previously created, on a dynamic links domain that belongs to your Firebase project.

example.page.link doesn‘t belong to your project, and /123 is not a valid dynamic link

**Comment by rahulsree7** [comment]
> You can only get statistics for a dynamic link that you have previously created, on a dynamic links domain that belongs to your Firebase project.
> 
> example.page.link doesn‘t belong to your project, and /123 is not a valid dynamic link

            $factory=(new Factory())->withServiceAccount(__DIR__.'/firebase.json');
            $dynamicLinksDomain = 'https://companyname.page.link/';
            $dynamicLinks = $factory->createDynamicLinksService($dynamicLinksDomain);
            $stats = $dynamicLinks->getStatistics('https://companyname.page.link/CTck');
I had already created some code with laravel Kreait 
above noted is my original code.....

**Comment by jeromegamez** [comment]
https://firebase-php.readthedocs.io/en/5.3.0/dynamic-links.html#get-link-statistics has a code snippet to catch the error and display the error message, what does it say in your case?

**Comment by rahulsree7** [comment]
> https://firebase-php.readthedocs.io/en/5.3.0/dynamic-links.html#get-link-statistics has a code snippet to catch the error and display the error message, what does it say in your case?

Failed to get statistics for dynamic link
in catch I am getting this one.

**Comment by jeromegamez** [comment]
Sorry for not being able to provide a concrete code example (I’m not currently at my computer), but you can get the API response from the exception with `->response()` to inspect it further. A `echo $e->response()->getBody()->getContents()` should give you more information on the cause of the error.

**Comment by jeromegamez** [comment]
I just released version 5.5 which includes support for logging HTTP Requests - [you can find the documentation here](https://firebase-php.readthedocs.io/en/5.5.0/setup.html#logging).

Please update and let me know this helps to resolve the issue - if you could share your findings, I could perhaps add support to the SDK to handle cases like this one 🤞

**Comment by JexPY** [comment]
> Sorry for not being able to provide a concrete code example (I’m not currently at my computer), but you can get the API response from the exception with `->response()` to inspect it further. A `echo $e->response()->getBody()->getContents()` should give you more information on the cause of the error.


This was enough for me to get information about what was wrong with my statistics.
```php
        } catch (FailedToGetStatisticsForDynamicLink $e) {
            echo $e->response()->getBody();
            exit;
        }
```
For me, the problem was missing enough permissions.
```JSON
{
"error": {
  "code": 403,
  "message": "The caller does not have permission",
  "status": "PERMISSION_DENIED"
  }
}
```

**Comment by jeromegamez** [comment]
@JexPY That's valuable information! Would you mind creating an issue in the SDK's repo with a short description so that I can keep track of it? There's certainly a way to make this more "friendly", so that people don't have to to dig into the responses as you had to do 😅
