### ISSUE TITLE
I try to query  equalTo  many columns but return [ ] 

### ISSUE THREAD

**Issue by waleedazam** [kreait/firebase-php#43]
Hello 
I try to query  equal  many column but return [ ]  

example : 

```php
$query = new Query();
$query->orderByChildKey('isBusyDriver')
      ->equalTo('false')
      ->orderByChildKey('isOnline')
      ->equalTo('true');

$result = $firebase->query('/Driver', $query);
return $result;
```

please any help in this case or sample ?!
Regards

**Comment by jeromegamez** [comment]
Firebase only allows one kind of ordering/filtering at a time, so it is not possible to combine queries.

So, if you want to filter/order by more than one property, you will have to do this manually in your code, e.g. by performing the two queries separately and create an intersection between the two results.

**Comment by waleedazam** [comment]
I try to filter like that 
$query = new Query();
$query->orderByChildKey('isBusyDriver')
      ->equalTo(false)

$result = $firebase->query('/Driver', $query);
return $result;

 its return [ ] but i am sure there matched data should return 
its work when filter in string key like "false" but with boolean not work 

please test it and see whats wrong 
Regards

**Comment by jeromegamez** [comment]
Good catch! This is actually a bug, I will fix it soon and release a new 1.x version. Thanks!

**Comment by jeromegamez** [comment]
[Release 1.1.1](https://github.com/kreait/firebase-php/releases/tag/1.1.1) including the fix is out, please update your dependencies, and thanks again for finding the bug!
