### ISSUE TITLE
request code status '400 (bad request)', '404 (not found)' error result but if request code status is '201 (created)', '200 (ok)' is work

### ISSUE THREAD

**Issue by ragil000** [kreait/firebase-php#431]
Type: GuzzleHttp\Exception\ClientException

Message: Client error: `POST http://localhost/bestada-food/server/api/Slide` resulted in a `400 Bad Request` response: {"status":false,"message":"data gagal ditambah."}

Filename: C:\xampp-5\htdocs\bestada-food\backend\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php

Line Number: 113

Backtrace:

File: C:\xampp-5\htdocs\bestada-food\backend\vendor\guzzlehttp\guzzle\src\Middleware.php
Line: 65
Function: create

File: C:\xampp-5\htdocs\bestada-food\backend\vendor\guzzlehttp\promises\src\Promise.php
Line: 203
Function: GuzzleHttp\{closure}

File: C:\xampp-5\htdocs\bestada-food\backend\vendor\guzzlehttp\promises\src\Promise.php
Line: 156
Function: callHandler

File: C:\xampp-5\htdocs\bestada-food\backend\vendor\guzzlehttp\promises\src\TaskQueue.php
Line: 47
Function: GuzzleHttp\Promise\{closure}

File: C:\xampp-5\htdocs\bestada-food\backend\vendor\guzzlehttp\promises\src\Promise.php
Line: 246
Function: run

File: C:\xampp-5\htdocs\bestada-food\backend\vendor\guzzlehttp\promises\src\Promise.php
Line: 223
Function: invokeWaitFn

File: C:\xampp-5\htdocs\bestada-food\backend\vendor\guzzlehttp\promises\src\Promise.php
Line: 267
Function: waitIfPending

File: C:\xampp-5\htdocs\bestada-food\backend\vendor\guzzlehttp\promises\src\Promise.php
Line: 225
Function: invokeWaitList

File: C:\xampp-5\htdocs\bestada-food\backend\vendor\guzzlehttp\promises\src\Promise.php
Line: 62
Function: waitIfPending

File: C:\xampp-5\htdocs\bestada-food\backend\vendor\guzzlehttp\guzzle\src\Client.php
Line: 182
Function: wait

File: C:\xampp-5\htdocs\bestada-food\backend\application\models\slides\SlideModel.php
Line: 37
Function: request

File: C:\xampp-5\htdocs\bestada-food\backend\application\controllers\slides\Slide.php
Line: 38
Function: postData

File: C:\xampp-5\htdocs\bestada-food\backend\index.php
Line: 315
Function: require_once

**Comment by jeromegamez** [comment]
Sorry but this is not enough information - I don‘t know what you have tried to do, this just looks like a general Guzzle error and could be caused by anything 😅
