### ISSUE TITLE
Get Public URL from file uploaded to Firebase Storage. I can't readily view the image as it requires access token.

### ISSUE THREAD

**Issue by xemacscode** [kreait/firebase-php#433]
how to retrieve images from Firebase Storage? I can't readily view the image as it requires access token. Is there a way to view the images from my website? Or is it even possible to get a public url for my image after uploading?

**Comment by jeromegamez** [comment]
You can find an implementation example at https://github.com/jeromegamez/firebase-php-examples/blob/master/src/Command/UploadFileCommand.php

**Comment by xemacscode** [comment]
@jeromegamez I tried it, but I'm getting this 404 error: `The requested URL was not found on this server. That’s all we know.`

`var_dump($up->gcsUri());`

That's where I'm getting the uri.

**Comment by xemacscode** [comment]
I just want to display it on my website after upload.

**Comment by jeromegamez** [comment]
What did you actually try? The only way to get a public URL to a file is by composing it manually with the bucket name and file name (you can see that at the end of the referenced example).

`gcsUri()` returns a `gs://` URI, not an HTTP URI.

**Comment by xemacscode** [comment]
I tried using gcsUri() and I also tried composing it manually with the bucket name and file name but I'm still getting 404.

**Comment by xemacscode** [comment]
`https://android-42ed6.appspot.com/diy.jpg`

Not the real bucket name.

**Comment by jeromegamez** [comment]
You're not generous with information, are you 😅? Without seeing the code that you've written, I can only guess and guesses are often wrong 😅.

If the default Cloud Storage bucket is not the one the image is located in, you can select a specific bucket with `$storage->getBucket('real-bucket-name')`. ([official Docs](https://googleapis.github.io/google-cloud-php/#/docs/cloud-storage/v1.21.1/storage/storageclient?method=bucket), but if your `$up` references a file that you just uploaded to a bucket, I wonder why the uploaded-to bucket is not "the real one".

However... if you know the real bucket name, instead of 

```php
$publicUrl = "https://{$bucket->name()}.storage.googleapis.com/{$uploadedFile->name()}";
```

use

```php
$publicUrl = "https://the-real-name.storage.googleapis.com/{$uploadedFile->name()}";
```

**Comment by xemacscode** [comment]
This is working instead:

https://firebasestorage.googleapis.com/v0/b/<bucketName>/o/<urlEncodedFilePath>?alt=media

**Comment by wildangunawan** [comment]
Finally after digging for some times and try to duplicate what I found [here](https://stackoverflow.com/questions/59432624/how-can-i-generate-access-token-to-file-uploaded-to-firebase-storage), I finally found how we can generate our own access token.

When uploading the file, we can provide a metadata with key "firebaseStorageDownloadTokens" and value of UUID. I implement this in Laravel using laravel-firebase package but should be similar to vanilla PHP implementation:

```php
$uuid = \Str::uuid(); // Laravel helper to generate UUID

$uploaded_file = $storage->getBucket() // equivalent of https://github.com/jeromegamez/firebase-php-examples/blob/master/src/Command/UploadFileCommand.php#L54
    ->upload( // equivalent of https://github.com/jeromegamez/firebase-php-examples/blob/master/src/Command/UploadFileCommand.php#L61
        'this is text',
        [
            'name' => 'text3.txt',
            'metadata' => [
                'metadata' => [
                    'firebaseStorageDownloadTokens' => $uuid
                ]
            ]
        ]
    )->info();

$bucket = $uploaded_file['bucket'];
$filepath = urlencode($uploaded_file['name']);

$link_to_file = "https://firebasestorage.googleapis.com/v0/b/$bucket/o/$filepath?alt=media&token=$uuid";
```

This way, you don't need to allow read in your Firebase Storage rules. User can still read as long as they have access token to your file. This might be useful to be added in the docs :)

Ps. Yes, user can see all of your file if you allow read in Firebase Storage rules via https://firebasestorage.googleapis.com/v0/b/{bucketName}/o
