### ISSUE TITLE
invalid Json data payload 

### ISSUE THREAD

**Issue by zubairIftikharKwe** [kreait/firebase-php#434]
```
$message = CloudMessage::withTarget('token', $registrationToken)
                ->withNotification($notification)
                ->withData($data['data'])
```
```
    public function withData($data)
    {
        $new = clone $this;
        $new->data = $data instanceof MessageData ? $data : MessageData::fromArray($data);

        return $new;
    }
```
**withData** require array ..
i'm receiving :Data Payload: `{key1=value, key2=value}`.
our requirement is payload in string so Android developer convert it easy into Json format..
what i want: Data Payload: `{"key1":"value", "key2":"value"}`
My question is how to send Notification Data  with String or Json format data..

**Comment by jeromegamez** [comment]
If `$data['data']` contains a JSON-Payload, you can convert it to an array with `json_decode()`, so, from your example, it would probably be

```php
$message = CloudMessage::withTarget('token', $registrationToken)
    ->withNotification($notification)
    ->withData(json_decode($data['data'], true));
```
