### ISSUE TITLE
Firestore Regarding.

### ISSUE THREAD

**Issue by Rashrish** [kreait/firebase-php#435]
Hi Jerome, I have been using your firebase-php for Admin SDK and my sincere thanks to you.  Now, I am trying to migrate to Firestore and went through your documents but I could not see Admin SDK in PHP for Firestore, kindly correct me if I am wrong.  Please guide me on how I can go about it.  Thank you again.

**Comment by jeromegamez** [comment]
Thank you for the kind words, Rashrish 🌺!

The SDK only provides a bridge to the official `google/cloud-firestore` - the benefit is that the SDK provides an already configured instance of the Firestore Client (with the same Service Account), but doesn’t do more than that.

Have you seen https://firebase-php.readthedocs.io/en/5.4.0/cloud-firestore.html ? On that page you can find a small introduction, but more importantly links to the `google/cloud-firestore` docs and usage examples.

**Comment by Rashrish** [comment]
Thank you Jerome for your prompt reply.  I went through the content of the link before writing to you and agin now.  Exploring further and gradually progressing.
