### ISSUE TITLE
Multicast send reports are empty for Firebase Cloud Messaging

### ISSUE THREAD

**Issue by MH15** [kreait/firebase-php#436]
**Describe the bug**
Multicast send reports are empty when a message is sent to multiple recipients.

**To Reproduce**
```php
use Kreait\Firebase\Factory;
use Kreait\Firebase\Messaging\CloudMessage;
use Kreait\Firebase\Messaging\Notification;

$factory = (new Factory)->withServiceAccount($firebase_credentials);
$messaging = $factory->createMessaging();

$recipients = ["a","b","c"];
$message = CloudMessage::new();
$notification = Notification::create($title, $body);
$message = $message->withNotification($notification);

$report = $messaging->sendMulticast($message, $recipients);
```

**Expected behavior**
When I send a multicast to one recipient, I get a meaningful response whether I passed a valid token or not. That behavior should happen here, as documented for [Multicast](https://firebase-php.readthedocs.io/en/5.4.0/cloud-messaging.html#send-messages-to-multiple-devices-multicast).

**Environment:**
 - OS: Windows 10
 - PHP version: 7.2.25
 - Firebase SDK Version: 5.4.0

**Additional context**
The `$report` value I'm getting has a key of "items", which is an empty array.

**Comment by jeromegamez** [comment]
Unfortunately, this seems to happen sometimes that the Firebase API returns an empty response to a multicast request with multiple recipients - in the past, this has resolved "itself" after a couple of hours, but of course, I can't rule out the possibility that there is a problem in the handling of the multicast responses.

So far, I wasn't able to reproduce the issue, but I'm currently working on adding support for logging HTTP requests and responses, this should help us to debug this issue further 🤞

**Comment by jeromegamez** [comment]
If you update the SDK to the just-released [5.5.0](https://github.com/kreait/firebase-php/releases/tag/5.5.0) you will be able to provide it with a Logger which should help with debugging. [You can find the documentation here](https://firebase-php.readthedocs.io/en/5.5.0/setup.html#logging)

Please let me know of your findings 🙏

**Comment by MH15** [comment]
When you say you weren't able to reproduce the result, do you mean Firebase responded correctly or you were unable tog et the sample to run?

And thanks! I'll bump the version today and use the Logger.

**Comment by jeromegamez** [comment]
I wasn‘t able to reproduce it, because I only have one token to test with (a separate browser on my computer) 🙈, and I was lazy because I assumed that this is one of the cases that the Firebase API acts up (which was always the case the previous times someone reported this issue).

But now that you caught me (please forgive me 😅), I‘ll do a proper test with two tokens and hope so can reproduce the issue 🤞

**Comment by MH15** [comment]
No worries! Thanks so much for this package, by the way. But actually, you shouldn't need any tokens to test this. The Firebase API should respond telling you which tokens are invalid, as it does for a Multicast with a single recipient.

**Comment by jeromegamez** [comment]
Oh, good point!

I added an integration test for this case (https://github.com/kreait/firebase-php/commit/c83b05ad5cc5ce6ef895781791e0e8143d7d19c2) and unfortunately, it works 🤔

**Comment by MH15** [comment]
Interesting... I'll try some more things and get back to you. I noticed similar behavior in `sendAll` so hopefully I can resolve that as well. Thanks for your help!

**Comment by MH15** [comment]
I've done more testing on my setup. When up to 3 using real, valid device tokens I get the correct multicast response. When I use 1 invalid gibberish token I get the correct response. In all other scenarios I get an empty "items" array.

**Comment by jeromegamez** [comment]
Just for clarity: 4 valid tokens trigger an unexpected API response? Could you share it with me?

If you don‘t want to order the response for possible security-relevant items (and trust me enough) you could share it with me on Discord, if you‘d like

**Comment by MH15** [comment]
What's the discord link? I'll remove all security-related items but discord would be best as to not clutter this thread

**Comment by jeromegamez** [comment]
There‘s a badge in the readme (I‘m currently not at my computer, so finding and copying involves more steps than I‘m feeling comfortable with... hey, now that I admitted to being lazy it‘s much easier to just go with it 😂)

**Comment by MH15** [comment]
For anyone who comes across a similar problem, here's what we eventually figured out: The version of cURL that ships with PHP 7.2.25 has an issue when parsing HTTP multipart requests on Windows. Locate the curl DLL in the `ext` folder of your PHP installation and overwrite it with a newer version. You may want to copy the version you already have as a backup, of course. For me, installing cURL 7.70 fixed my issues.

**Comment by jeromegamez** [comment]
Thank you for sharing your findings, @MH15 🌺. 

I added a section to the troubleshooting docs for future reference: https://firebase-php.readthedocs.io/en/latest/troubleshooting.html#multicast-sendreports-are-empty
