### ISSUE TITLE
Can't find a way to pass server token in FCM

### ISSUE THREAD

**Issue by KaungKaung0** [kreait/firebase-php#437]
I tried to push message with 
`$message = CloudMessage::withTarget('token', $deviceToken)
    ->withNotification($notification) // optional
    ->withData($data) // optional
;
`
And it throws an exception
"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential"

I think I need to pass server key but don't know where to put it.

Can u help me ?

**Comment by jeromegamez** [comment]
This Admin SDK (like the official Admin SDKs) doesn‘t use server keys for authentication, but Google Service Account credentials as described in the setup instructions: https://firebase-php.readthedocs.io/en/5.5.0/setup.html
