### ISSUE TITLE
This package requires php 7.2

### ISSUE THREAD

**Issue by stojankukrika** [kreait/firebase-php#439]
Hi,
Do you plan to release a new version that supports newer versions of PHP, for example, 7.3?

**Comment by jeromegamez** [comment]
7.2 is only the **minimum** version, newer versions are supported as well ☺️

**Comment by stojankukrika** [comment]
No, they are not. I get an error: 
  Problem 1
    - This package requires php 7.2 but your PHP version (7.3.16) does not satisfy that requirement.

**Comment by stojankukrika** [comment]
Uppsss I find out that in mine project I have php7.2 and in my local is 7.3. Sorry.
