### ISSUE TITLE
Error: Permission denied.

### ISSUE THREAD

**Issue by joseSantacruz** [kreait/firebase-php#44]
After follow the tutorial I get the error Permission denied. This is my code:

```
	$firebase = Firebase::fromServiceAccount(__DIR__.'/service_account.json');

	$database = $firebase->getDatabase();


	$event = $database->getReference('/');
	$event->getSnapshot();
```

I validate and the JSON file is found it and open it.

**Comment by waleedazam** [comment]
you try to read data from parent ('/') this mean you shoud set rule to read and write data in to it 
move to rule tab and try to sit rules like this 

```
{
  "rules": {
    ".read":true,
      ".write":true

     }
}
```
this  will pass you permission issue but you should read in deep in rules to set specific and advance rules for logged in user 

check this reference 
[https://firebase.google.com/docs/database/security/](Rules)

**Comment by jeromegamez** [comment]
Could you please check if the `project_id` field contains the same value as your Firebase application's subdomain? So, if your JSON file names "project_xyz", then the SDK expects the domain to be "project_xyz.firebaseio.com".

If this isn't the case in your project, try instantiating the Firebase-Instance like this:

```php
$firebase = Firebase::fromServiceAccount(
    __DIR__.'/service_account.json',
    'https://my-project.firebaseio.com'
);
```

**Comment by jeromegamez** [comment]
@joseSantacruz @waleedazam I just released a new beta with the aforementioned changes: [kreait/firebase-php@2.0.0-beta2](https://github.com/kreait/firebase-php/releases/tag/2.0.0-beta2)

Please update your dependencies and make use of the new method, in your case, @joseSantacruz:

```php
$firebase = Firebase::fromServiceAccount(__DIR__.'/service_account.json')
    ->withDatabaseUri('https://your-project.firebaseio.com');
```

Please re-open this issue, if necessary.

**Comment by sebardo** [comment]
I had the same problem and the solution as @jeromegamez said "service account must be associated with firebase project, check service account creation in https://console.cloud.google.com/apis/credentials?project=PROJECT_ID
