### ISSUE TITLE
Message data is empty when received by device using sendMulticast

### ISSUE THREAD

**Issue by algorun77** [kreait/firebase-php#442]
**Describe the bug**
Hi,

I'm trying to implement this SDK (thanks for this because I do not understand why Google is not providing a legit PHP SDK) and until now it worked fine.
I'm able to send messages to specific devices one by one but now, I would like to use sendMulticast method to send the same message to multiple devices at the same time.

I did managed to write this code but for an unknown reason, my message content is "lost" on its way between the call to sendMulticast and my onMessageReceived on Android.

**To Reproduce**
I'm using the following code in my app :

```php
private function sendMessageToDevices(array $data, array $tokens)
{
    $messaging = $this->factory->createMessaging();
    $reports = [
        'sent' => 0,
        'successes' => 0,
        'failures' => 0,
        'errors' => [],
    ];

    dump($data);
    dump($tokens);
    foreach ($tokens as $batch) {
        dump($batch);
        $report = $messaging->sendMulticast($data, $batch);

        $reports['sent'] += count($batch);
        $reports['successes'] += $report->successes()->count();
        $reports['failures'] += $report->failures()->count();

        if ($report->hasFailures()) {
            foreach ($report->failures()->getItems() as $failure) {
                $reports['errors'][] = $failure->error()->getMessage();
            }
        }
    }
    dump($reports);
    return $reports;
}
```

The dumps are for debug purpose and do NOT break any code. The content of my variables are available below.

**Expected behavior**
The behaviour expected is that : 
- My reports should tell me that my messages have been successfully sent :heavy_check_mark: 
- I should receive my messages on my devices :heavy_check_mark: 
- I should be able to handle this message in Android :no_entry_sign: -> Content is empty !

**Screenshots**
This is my variables :
![Screenshot_2020-06-26 Symfony Profiler](https://user-images.githubusercontent.com/24519881/85860751-8bc80700-b7bf-11ea-9b82-2264806f575b.png)

From this screenshot, you can see my message is NOT empty when I call the sendMulticast() method

From my debug console in Android Studio :
![Screenshot from 2020-06-26 15-06-14](https://user-images.githubusercontent.com/24519881/85860782-971b3280-b7bf-11ea-9929-45fde9095448.png)

Note: I write the content of the data in the console when a message is received. When I send a message to a signle device, it works. But not when I send a message to multiple devices

**Environment (please complete the following information):**
 - OS: Docker (Debian)
 - PHP version: 7.2.31
 - Firebase SDK Version: From composer :
kreait/clock => 1.0.1
kreait/firebase-php => 5.4.0
kreait/firebase-tokens => 1.10.0

**Additional context**
To be honest, I only tried with a single token in sendMulticast as shown in the variable content. I don't have access to a second device to test right now and I think that if it's a bug from the SDK, it should work event if a pass a single device in a multicast send.

Following my previous statement, I don't know if it's a SDK related bug or if it comes from FCM. I'm experience this issue for a week now, it never work using multicast...

If you need any information I missed, please ask.

Hope you could help,

Thanks a lot :smiley:

**Comment by jeromegamez** [comment]
Thank you for reporting the issue and the detailed description. I was able to reproduce the case with the following script:

```php
$messaging = (new Factory())->createMessaging();

$token = "<token>";
$tokens = [$token];

$messageData = [
    '__order__' => 'order-group',
    'group' => 6,
];

$messaging->send(CloudMessage::withTarget('token', $token)->withData($messageData));

$messaging->sendMulticast($messageData, $tokens);
```

and testing it with a local instance of https://github.com/firebase/quickstart-js/tree/master/messaging which gave me the following result:

<img width="300" alt="result" src="https://user-images.githubusercontent.com/67554/85932917-3b40ce80-b8d1-11ea-8001-a789ebe52cf3.png">

I'll now start investigating what the underlying issue might be 🤞

**Comment by jeromegamez** [comment]
I think I found the reason - the data in the `$data` array needs to be wrapped inside a `data` field.

`CloudMessage::withData($data)` wraps the given data in a data field, so the resulting payload looks like this:

```php
$payload = [
    'data' => [
        '__order__' => 'order-group',
        'group' => 6,
    ],
];
```
👆 This arrives as intended at the client-side.

When you pass an array to `Messaging::send()` or `Messaging::sendMulticast()`, the array is converted to a `CloudMessage` instance, and all unknown fields are dropped.

You can replicate the issue if you execute the following:

```php
$message = CloudMessage::fromArray($messageData)->withChangedTarget('token', $token);

$messaging->send($message);
```
👆 The message data doesn't arrive intended at the client-side.

To cut a long story short: to fix this, I would recommend changing your code to something like this:

```php
$message = CloudMessage::new()->withData($data);

foreach ($tokens as $batch) {
    $report = $messaging->sendMulticast($message, $batch);
    // ...
}
```

Side note: I would replace

```php
$reports['sent'] += count($batch);
```

with 

```php
$reports['sent'] = $report->count();
```

**Comment by algorun77** [comment]
Hi,

Thank you for your answer. I tried to update my code as suggested and now it works flawlessly :smiley: 
As you mentioned it, I was just missing the part when I create a CloudMessage object, like a fool... !

I also took note of your suggestion at the end of your message. I now have the following code :

```php
private function sendMessageToDevice(array $data, string $token)
{
    $messaging = $this->factory->createMessaging();
    $message = CloudMessage::withTarget('token', $token)->withData($data);
    return $messaging->send($message);
}

private function sendMessageToDevices(array $data, array $tokens)
{
    $messaging = $this->factory->createMessaging();
    $message = CloudMessage::new()->withData($data);

    $reports = [
        'sent' => 0,
        'successes' => 0,
        'failures' => 0,
        'errors' => [],
    ];

    foreach ($tokens as $batch) {
        $report = $messaging->sendMulticast($message, $batch);

        $reports['sent'] += $report->count();
        $reports['successes'] += $report->successes()->count();
        $reports['failures'] += $report->failures()->count();

        if ($report->hasFailures()) {
            foreach ($report->failures()->getItems() as $failure) {
                $reports['errors'][] = $failure->error()->getMessage();
            }
        }
    }

    return $reports;
}
```

And in Android I now get the data correctly :
![Screenshot from 2020-06-29 08-25-57](https://user-images.githubusercontent.com/24519881/85980594-00c75680-b9e3-11ea-8274-7be9f2b4d8c7.png)

Since it is resolved, I'm going to close this ticket.
Thanks a lot for your help and for your work ! :+1: 

I wish you a nice day !
