### ISSUE TITLE
Empty nofification with function sendMulticast of CloudMessaging

### ISSUE THREAD

**Issue by hyquoccuong** [kreait/firebase-php#443]
I'm using 4.44.0 version for my php 7.0 server
But I catch a problem with function sendMulticast of CloudMessaging feature

When I using this method, create a new message object and bind notification and data, then call sendMulticast function, i got notification on device but it had no title and body, just empty notification
```
$deviceTokens = [
    'xxx',
    'yyy'
];
$message = CloudMessage::new(); // Any instance of Kreait\Messaging\Message
$message->withNotification(Notification::create('Title', 'Body'));
$message->withData(['key' => 'value']);
$send = $messaging->sendMulticast($message, $deviceTokens);
```
After that, I change the method to build message from object to from array

```
$message = CloudMessage::fromArray([
    'notification' => [
        'title' => 'Test',
        'body' => 'This is a test'
    ],
    'data' => [
        'key' => 'value'
    ],
]);
$send = $messaging->sendMulticast($message, $deviceTokens);
```
Then I receive a notification has title and body properly

**Environment**
 - OS:  Windows 10
 - PHP version: 7.0.13
 - Firebase SDK Version: 4.44.0 

Could you please check what cause problem with the 1st method to build CloudMessage object?

**Comment by jeromegamez** [comment]
The message object is immutable, this means that method calls will return a new object and leave the original object untouched.

If you use 

```php
$message = $message->with*(...);
```

you will have the expected result 🤞

**Comment by hyquoccuong** [comment]
I have a related question, fcm support send messages to multiple devices (1000) on a request to their server https://fcm.googleapis.com/fcm/send

How is it going with our sdk? Do you applied this feature to send message to multiple devices or send it one by one (1 request per device in loop)?

**Comment by jeromegamez** [comment]
The SDK uses the same API - you can send up to 1000 messages in one request 🥳

**Comment by hyquoccuong** [comment]
> The SDK uses the same API - you can send up to 1000 messages in one request 🥳

Glad to hear that, but when I read the docs, it said that max number of tokens is 500, is it okay if I use array of 1000 tokens to send?

**Comment by jeromegamez** [comment]
Oh, my bad, you're right, the limit here is currently 500 - Firebase must have upped the limits in the meantime.

I'll change the limit after I confirm this in the official SDKs and create new releases.

**Comment by hyquoccuong** [comment]
thank you for your reply, I will close the issue

**Comment by jeromegamez** [comment]
The official Node Admin SDK (still( has the 500 messages per batch limit (https://github.com/firebase/firebase-admin-node/blob/master/src/messaging/messaging.ts#L45 - I'll change it here when they change it, too 😅
