### ISSUE TITLE
Unable to set collapse_key (for android) and apns-collapse-id (for apple)

### ISSUE THREAD

**Issue by spengilley** [kreait/firebase-php#445]
As the subject suggests I need to collapse messages but have been unable to work out how to set these values using this SDK.
I have tried in the notification, AndroidConfig::fromArray(), ApnsConfig::fromArray(), CloudMessage::fromArray() at the top level. All fail.

Are you able to help please?

**Comment by jeromegamez** [comment]
Please use this for reference:

```php
$message = CloudMessage::withTarget('token', $token)
    ->withAndroidConfig([
        'collapse_key' => 'collapse_key'
    ])
    ->withApnsConfig([
        'headers' => [
            'apns-collapse-id' => 'collapse_id',
        ],
    ]);
``` 

It works on my machine™ 😅
