### ISSUE TITLE
Allow add parameter `click_action` in Notification 

### ISSUE THREAD

**Issue by jessiesiat** [kreait/firebase-php#446]
As document here https://github.com/fechanique/cordova-plugin-fcm and https://firebase.google.com/docs/cloud-messaging/http-server-ref

 `click_action` is needed for the callback to work when Application is in background or closed

**Comment by jessiesiat** [comment]
My bad, i was actually using this cordova plugin https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated

**Comment by jessiesiat** [comment]
My bad, i was actually using this cordova plugin https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated

i have it worked using `withAndroidConfig`

`
CloudMessage::new()
                ->withAndroidConfig([
                    'notification' => [
                        'click_action' => 'FCM_PLUGIN_ACTIVITY',
                    ],
                ])
`

**Comment by aroon9002ahmed** [comment]
i hop this help

```
$config = WebPushConfig::fromArray([
            'notification' => [
                'title' => $title,
                'body' => $body,
                'icon' => $icon,
            ],
            'fcm_options' => [
                'link' => $link,
            ],
        ]);
```
