### ISSUE TITLE
Notification not received in Firefox

### ISSUE THREAD

**Issue by KaungKaung0** [kreait/firebase-php#448]
FCM onmessage() not works in Firefox.

I have User A and User B 
A is logged in on Firefox
B is on Chrome

When I sent message from A to B , 

  ```
$message = CloudMessage::withTarget('topic', $topic)
        ->withNotification($notification)
        ->withData($data);
```
I got "onmessage" in chrome, which is good. as I expected.
```
    messaging.onMessage((payload) => {
            console.log("message", payload);
});
```

but when I sent message from B to A ,

Message is sent .
But no "onmessage"  output in Firefox.
I tried by changing users and other devices.
in chrome , I got all notification
but in Firefox ,I got nothing.

I also checked for topic subscriptions and everything is fine. nothing wrong.
I just can't get notification in Firefox. 

Can you help me ? 
Sorry for my english skills.
Thanks.

 - OS: Ubuntu 20.04
 - PHP version: 7.4.3
 - "kreait/laravel-firebase": "^1.2",
     "laravel/framework": "^6.2",

**Comment by jeromegamez** [comment]
Could you please check if https://github.com/kreait/firebase-php/issues/447#issuecomment-654546199 helps identifying the problem?

**Comment by KaungKaung0** [comment]
I don't think that "restricted package name" for android would be error because I didn't send to android. 
I tried to send message as you said in above issue.

```
use Kreait\Firebase\Messaging\CloudMessage;

$payload = CloudMessage::fromArray($payload)->withChangedTarget('token', $firefoxToken);

$result = $message->send($payload);
dump($result);
```
well.. I got "Apns or Webpush Auth Error" .

I do connected with service account in firebase config and I can send topic message. So its okay and I got a little improvement. 

I got notification from my laptop's Firefox !!
I still don't get from my PC's Firefox .  Both are same version 78.0.1 and also OS, ubuntu 20.04 64bit. 
I can't figure it out.
This is my first time using firebase in my project.

Thanks alot for giving your time.

**Comment by jeromegamez** [comment]
You're welcome! It's too bad I can't be of better help, though... There seem to be quite some edge cases between different recipients and environments, I hope you will be able to figure it out!

Concerning the Android payload: as far as I understood from the other issue, if the payload **has** the restricted package name, then Firefox will not accept it.
