### ISSUE TITLE
400 Bad Request when searching data

### ISSUE THREAD

**Issue by diegolaz** [kreait/firebase-php#449]
Hello, first steps with firebase so probably I'm doing something wrong... 

`
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: 
GET https://.......firebaseio.com/dbName/usuarios?orderBy=%22email_pwd%22&equalTo=%22someEmail%40gmail.com_HASHEDPWD%22&limitToFirst=1 resulted
 in a 400 Bad Request response: in C:\pathtoproject\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
`

Executing this code:
```
public function getLogin(string $email = NULL, string $pwd = NULL) 
{
        if (empty($email) || !isset($email) || empty($pwd) || !isset($pwd)) 
         { 
            return false;
          }
		$clave_combianda = $email . "_" . $pwd;
		$ref = $this->database->getReference($this->dbname);			
		$busqueda = $ref->orderByChild("email_pwd")->equalTo($clave_combianda);
		return $busqueda->limitToFirst(1)->getValue();
  }

```

But insert code works fine:
```
public function insert(array $data)
 {
        if (empty($data) || !isset($data)) { return false;}
        {
            foreach ($data as $key => $value)
            {                
                $this->database->getReference($this->dbname)->getChild($key)->set($value);
            }
            return true;
        }
        return false;
    }
```

Is the search wrong formed?
Thanks!

**Comment by diegolaz** [comment]
sorry... not sure why the code sections don't get marked/formatted.

**Comment by jeromegamez** [comment]
For code blocks, you can wrap them in triple backticks, like (inception incoming...)

```php
// put PHP code here
```

or, without syntax highlighting:

```
This is just a block of
monospaced text
```

![image](https://user-images.githubusercontent.com/67554/87346204-97eaed00-c551-11ea-9fda-0e4e9f7ebd59.jpeg)

**Comment by diegolaz** [comment]
Thanks! now ready for someone to read it properly and help me solve it :D

**Comment by jeromegamez** [comment]
I just tried it with this query to try to emulate yours:

```php
try {
    $value = $db->getReference('test')
        ->orderByChild('email_pwd')
        ->equalTo('email@domain.tld_asjdkfghfasdf546')
        ->limitToFirst(1)
        ->getValue();

    var_dump($value);
} catch (\Kreait\Firebase\Exception\DatabaseException $e) {
    echo $e->getMessage();
}
```

This is the error message I got:

```
Index not defined, add ".indexOn": "email_pwd", for path "/test", to the rules
```

Do you get the same error if you catch the exception?

**Comment by diegolaz** [comment]
Yes! Added the try catch and got the exact same error....
![image](https://user-images.githubusercontent.com/3466466/87356262-29e5fc00-c538-11ea-98ed-916c2da23a9f.png)

I'll look into that rules section

**Comment by diegolaz** [comment]
So this is the exported DB structure:
```
{
  "dbName" : {
    "usuarios" : [ null, {
      "apellido" : "SuperUser",
      "celular" : "+549110000000",
      "email" : "someemail@gmail.com",
      "email_pwd" : "someemail@gmail.com_dHASHEDPWD6f3",
      "esAdmin" : true,
      "fechaNacimiento" : "1979/08/22",
      "nombre" : "Admin"
    } ]
  }
}
```

On the rules I had:
```
{
  /* Visit https://firebase.google.com/docs/database/security to learn more about security rules. */
  "rules": {
    ".read": false,
    ".write": false   
  }
}
```
and changed to
```
{
  /* Visit https://firebase.google.com/docs/database/security to learn more about security rules. */
  "rules": {
    ".read": false,
    ".write": false,
    "usuarios": {
        ".indexOf": ["email_pwd"]
      }
  }
}
```
but nothing changed...

**Comment by jeromegamez** [comment]
If I interpret your database structure correctly, you forgot to specify the `dbName` reference. Try this:

```json
{
  "rules": {
    ".read": false,
    ".write": false,
      
    "dbName": {
      "usuarios": {
        ".indexOn": ["email_pwd"]
      }
    }
  }
}
```

**Comment by diegolaz** [comment]
Perfect! Now it brings data back! 
Thanks a lot!

**Comment by diegolaz** [comment]
Sorry, reopened if anyone needed to ask/comment... will close it later

**Comment by jeromegamez** [comment]
Glad you got it to work! Since the issue is resolved and not related to the SDK, I'd prefer it to be closed, commenting is still possible :)
