### ISSUE TITLE
Any reason why PHP7 is required? (Google App Engine issue)

### ISSUE THREAD

**Issue by NordlingArt** [kreait/firebase-php#45]
Currently Google App Engine is running PHP version 5.5. Our backend is therefor restricted to that version. Is there any reason to why PHP7 is forced?

**Comment by jeromegamez** [comment]
PHP 5.5 has reached end of life this summer, PHP 5.6 will lose active support by the end of this year, and PHP 7 makes it much easier to write, test and maintain the code - not to forget the much better performance of PHP 7 compared to PHP 5.x, which is certainly favorable when working with the realtime database.

**Comment by jeromegamez** [comment]
I also hope Google will add support for PHP 7 sooner than later, perhaps, *if* this project gains a little bit of popularity, it would be a good incentive ^^.

The changes are not very significant *yet*, 1.x is more of a CRUD wrapper around the REST API with a syntax that I personally don't like anymore :), and it's not really open for extension featurewise, which was a reason why I wanted to rewrite it.

In the future 2.x will gain features that 1.x will not have, like access to the Firebase security rules, an easy API to the Firebase Storage and hopefully more.

So, at this moment, 1.x is certainly a "safe" choice, but it's in a "bugfix and support only" state.

**Comment by NordlingArt** [comment]
@jeromegamez - Got it. Thanks for the explanation! Will definitely check this out either way. Hopefully Google apps PHP 7 support soon.

**Comment by jeromegamez** [comment]
That's good to hear, thank you for the feedback! I will close this issue now, but if you have any further questions, feel free to reopen it or create another issue, I'll be happy to answer either way :).
