### ISSUE TITLE
I received the Notification on Android but does not emit any sound

### ISSUE THREAD

**Issue by ederluca** [kreait/firebase-php#454]
good evening

I am facing a problem where when sending a notification I am normally receiving the same on my android device and also on my IOS, however the notifications do not display any kind of sound, or vibration I tried several settings and I could not solve the problem they could help me I sent the attached code for analysis.

The version I'm using from SDK is version 4.35.

```php
<?php   
    require_once __DIR__ . '/_vendor/autoload.php';         
    use Kreait\Firebase\Factory;    
    use Kreait\Firebase\Exception\MessagingException;    
    use Kreait\Firebase\Exception\Messaging\InvalidMessage;    
    use Kreait\Firebase\Messaging\CloudMessage;      
    
    function sendPush($device_token = "", $fields = array(), $origem = '', $ProjetoFirebase) {   
        if (!empty($device_token)) { #If the is not empty the variable $device_token I trigger the push
            if (!empty($ProjetoFirebase)) {#If the is not empty to variable $ProjetoFirebase I trigger the push        
                # Select the Firebase administration file to trigger the data
                $JSON = '';
                switch($ProjetoFirebase) {
                    case '01': 
                        $JSON = __DIR__ . '/_inc/firebase/admin/app01.json';
                    break;                    
                }

                
                $data = array(
                    "body" => $fields['body'],
                    "title" => $fields['title'],
                    "click_action" => "FLUTTER_NOTIFICATION_CLICK",                        
                    "Origem" => $origem,
                    "EComID" => $fields['EComID'],
                    "EComLogID" => $fields['EComLogID'],
                    "EComDesc" => $fields['EComDesc'], 
                    "EComDTH" => $fields['EComDTH'], "d/m/Y H:i:s",
                    "EComAss" => $fields['EComAss'],
                    "EcomAnx" => ((empty($fields['EcomAnx']))?'':$fields['EcomAnx']),
                    "EComEmpID" => $fields['EComEmpID'],
                    "LogNome" => $fields['LogNome'],											
                    "LogAvatar" => $fields['LogAvatar'] 
                );                
                
                # Shipping Service Creation
                $factory = (new Factory)->withServiceAccount($JSON);
                $messaging = $factory->createMessaging();          
            
                #Message Assembly for Sending
                $message = CloudMessage::fromArray([
                    'token' => $device_token,
                    'notification' => [
                        'title' => $fields['title'],
                        'body' => $fields['body'],                                            
                    ], 
                    'data' => $data, 
                    'android' => [
                        'priority' => 'high',
                        'notification' => [
                            'default_vibrate_timings' => true,
                            'default_sound' => true,
                            'notification_count' => 42,                            
                            'notification_priority' => 'PRIORITY_HIGH' // PRIORITY_LOW , PRIORITY_DEFAULT , PRIORITY_HIGH , PRIORITY_MAX
                        ],
                    ],
                    'apns' => [
                        'headers' => [
                            'apns-priority' => '10',
                        ],
                        'payload' => [
                            'aps' => [
                                'alert' => [
                                    'title' => $fields['title'],
                                    'body' => $fields['body'],
                                ],
                                'sound' => 'default',
                                'badge' => 42,
                            ],
                        ],
                    ],
                ]);  
                
                # Perform message validation
                $mensagemvalida = true;    
                try {
                    $messaging->validate($message->withChangedTarget('token', $device_token));
                } catch (MessagingException $e) {         
                    $mensagemvalida = false;                    
                    print_r($e->errors(),$message);
                }

                # If the Message is validated it is sent
                if ($mensagemvalida) {
                    try {
                        $messaging->send($message);
                    } catch (MessagingException $e) {                    
                        print_r($e->errors(),$message);
                    }
                }
            } else { # Generates Firebase Project Log
                print_r ('Firebase Project Not Reported at Office 1');
            }
        } else { # Generates Log of Token Device Not Informed
            print_r ('Token not Informed');
        }
    }         
?>
```

[suporte.txt](https://github.com/kreait/firebase-php/files/4957216/suporte.txt)

**Comment by jeromegamez** [comment]
Could you try adding `'sound' => 'default',` to the notification payload to see if that helps?

Side note: you don't need to validate your message before you send it, just sending is enough and will save you one HTTP request.

PS: I edited the issue for better readability (you can use triple backticks instead of single backticks for code blocks)

**Comment by b8ne** [comment]
@jeromegamez confirmed that adding `'sound' => 'default'` to notification payload does not produce a sound.

**Comment by jeromegamez** [comment]
I want to add that this kind of "misbehaving" is not related to the/an SDK itself, but caused by a combination of platform specific payloads that Firebase itself or the receiving clients are interpreting differently.

There's a good chance that you will get better and more timely responses when asking on StackOverflow as there is more combined knowledge available.

The SDK uses the HTTP V1 API (not the legacy or XMPP protocols), so this information in addition to the payload and the receiving devices (phones, browsers) should give others enough information to be able to help. 🤞

**Comment by b8ne** [comment]
@jeromegamez also to anyone else looking for this in the future, I actually fixed this issue and got successful notifications going by using `'sound' => "default",` instead of `'sound' => 'default',`.
So although the Firebase API accepts the message, there must be something in their system that doesn't parse single quotes correctly.

**Comment by jeromegamez** [comment]
Uh! Thank you @b8ne for sharing! What a weird behavior, I currently don't know what to think - it _should_ not make a difference if you use single or double quotes, but if this solves the problem, I'll add this to the troubleshooting docs. Thanks again!

**Comment by andreas-aeschlimann** [comment]
Hey guys, it's actually funny that I had the same issue. It took me over half a year until I noticed that sounds were not played. I always assumed that sound is automatically added. It would be nice if there were an easy way to add sounds to all platforms automatically.

I cannot confirm the issue with the double quotes. But better use them to be safe. :)

In case some future reader is interested, here is my solution:

```
$cloudMessage = CloudMessage::withTarget("topic", $topic)->withNotification([
    "title" => $title,
    "body" => $text,
]);

$cloudMessage = $cloudMessage->withApnsConfig([
    "payload" => [
        "aps" => [
            "sound" => "default",
        ]
    ]
]);

$cloudMessage = $cloudMessage->withAndroidConfig([
    "notification" => [
            "default_sound" => true,
    ]
]);

```

**Comment by jeromegamez** [comment]
Thank you @andreas-aeschlimann! I'm definitely thinking about adding a method to help with sound in notifications, especially since you provided those examples 🤞🥰

If it's alright with you, I'll make a PR and ping you so that you could test it 🙏

**Comment by andreas-aeschlimann** [comment]
> Thank you @andreas-aeschlimann! I'm definitely thinking about adding a method to help with sound in notifications, especially since you provided those examples 🤞🥰
> 
> If it's alright with you, I'll make a PR and ping you so that you could test it 🙏 

Sounds great, thank you.

It was of course my fault for not knowing that Firebase doesn't automatically issue a sound.

Maybe this new helper method could have parameters for sound and badge (number)? Both are used a lot on iOS.

**Comment by jeromegamez** [comment]
As a first step, I was thinking about adding a `withDefaultSounds()` method to the Notification class that would then propagate to the platform-specific payloads. I'm afraid this could get messy when there are different sounds/properties that need to be "translated" depending on the target platform 🤔, but one step at a time 😅. 

Could you point me to the Apple docs where the different badges and sounds are described so that I could have a look at it?

**Comment by andreas-aeschlimann** [comment]
Probably we want this: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943363

```
{
   “aps” : {
      “badge” : 9
      “sound” : “bingbong.aiff” // or default
   }
}
```

AFAIK Apple has 3 main properties: alert, badge and sound. Badge sets the number at the app's icon.

The alert property is already handled by this library, so only badge and sound are missing. It could be done with two methods:
- `withSound(string $sound = "default")`
- `withBadge(int $badge = 1)`

**Comment by jeromegamez** [comment]
Here's the PR 🤞  https://github.com/kreait/firebase-php/pull/490
