### ISSUE TITLE
timeout for guzzle client defaults to 0, making a job never end, withHttpClientConfig was deprecated?

### ISSUE THREAD

**Issue by sleenen** [kreait/firebase-php#458]
**Problem** 
Connections not timing out, so it if can't connect, it will wait indefinitely.

**Description**
We send quite a bit of push messages, using background jobs. It seems like something the connection to google can not be made. I think because of the default timeout of 0 (indefinite), it will wait indefinitely. The `withHttpClientConfig()` is deprecated. But it would be a good idea imo if you can still set this option on the client. 

Is there another way to do this? Or any other ideas?

**Comment by jeromegamez** [comment]
Hey @sleenen, sorry for the late reply! `withHttpClientConfig()` has been deprecated in 4.x and removed in 5.x to be able to slowly migrate to an implementation that is not tied to Guzzle specifically anymore.

If you're using a 4.x release and planning to stay with it, you can continue to use the `withHttpClientConfig()` method.

For 5.x I'm currently working on an alternative to providing HTTP client options and will let you know once it's ready and released.

**Comment by jeromegamez** [comment]
Starting with [release 5.8.0](https://github.com/kreait/firebase-php/releases/tag/5.8.0) you can specify the timeout like this:

```php
use Kreait\Firebase\Factory;
use Kreait\Firebase\Http\HttpClientOptions;

$factory = (new Factory())->withHttpClientOptions(
    HttpClientOptions::default()->withTimeout(3.14) // timeout in seconds as a float value
);
```

More detailed documentation: https://firebase-php.readthedocs.io/en/latest/setup.html#http-client-options
