### ISSUE TITLE
Fatal error during initialization of auth object

### ISSUE THREAD

**Issue by Bestak** [kreait/firebase-php#461]
**Describe the bug**
Hi, I ran into a error during initialization of the auth object.
This error comes up:
> Fatal error: Declaration of Kreait\Firebase\Auth\ApiClient::request($method, $uri, array $options = Array): Psr\Http\Message\ResponseInterface must be compatible with GuzzleHttp\ClientInterface::request(string $method, $uri, array $options = Array): Psr\Http\Message\ResponseInterface in {path}/libs/vendor/kreait/firebase-php/src/Firebase/Auth/ApiClient.php on line 25

**To Reproduce**
I followed the tutorial in the documentation [here](https://firebase-php.readthedocs.io/en/stable/overview.html) step by step.

I downloaded the composer. Then I used it to download this set of libraries. I moved the created directories through ftp onto the server. There I tried to run this code and I got the error.

```php
require "../libs/vendor/autoload.php";
use Kreait\Firebase\Factory;
use Kreait\Firebase\Auth\Token\Exception\InvalidToken;
use Kreait\Firebase\ServiceAccount;

if(isset($_POST['idTokenString'])) {
     $idTokenString  = $_POST['idTokenString'];
		
     //create Firebase factory object
     $factory = (new Factory())->withServiceAccount('../privatekey.json');
     $auth = $factory->createAuth(); //this line makes the error
}
```

**Expected behavior**
It should run without an error.

**Environment (please complete the following information):**
 - OS: Windows 10
 - PHP version: 7.1.33-15+0\~20200419.36+debian8~1.gbp2384b3
 - Firebase SDK Version: 5.7

**Other info**
Sorry if this isn't the place where to place error, but I don't know where else to post it.
Thanks for help in advance.

**Comment by isteiger** [comment]
please use PHP 7.2 or up to ensure no errors occur

**Comment by jeromegamez** [comment]
As @isteiger said, the 5.x releases of the SDK require at least PHP 7.2 to run. If you're stuck with PHP 7.1, you will need a 4.x release. 

You can downgrade by changing the version constraint in your `composer.json`:

```
"kreait/firebase-php": "^4.44"
```

Please keep in mind that the 4.x releases have not all the features that the 5.x releases have - you can find the documentation for version 4.44 at https://firebase-php.readthedocs.io/en/4.44.0/index.html

PHP 7.1 has reached its end of life in 2019 (it doesn't receive bugfixes or security fixes anymore), I strongly recommend upgrading to a newer version, preferably PHP 7.4.

**Comment by mikiamomik** [comment]
Hi,
i have the same error

`Fatal error: Declaration of Kreait\Firebase\Auth\ApiClient::request(string $method, $uri, array $options = Array): Psr\Http\Message\ResponseInterface must be compatible with GuzzleHttp\ClientInterface::request($method, $uri, array $options = Array) in /srv/www/diredonna.it/current/vendor/kreait/firebase-php/src/Firebase/Auth/ApiClient.php on line 46`

but i'm using php 7.4.18 (using trellis) in my local and production machine.

How can i solve this?

**Comment by jeromegamez** [comment]
Please make sure that you also have a current version of Guzzle (6.5 or 7.3) and the SDK (7.20) installed. You can check this by running `composer show` in your project directory.

A `composer update --with-all-dependencies` could be a quick fix.🤞

Unfortunately, I wasn't able to reproduce the problem so far, but I will try again later.

**Comment by mikiamomik** [comment]
After doing `composer show`
```
guzzlehttp/guzzle                          6.5.5              Guzzle is a PHP HTTP client library
guzzlehttp/promises                        1.4.1              Guzzle promises library
guzzlehttp/psr7                            1.8.2              PSR-7 message implementation that also provides common utility methods
kreait/clock                               1.1.0              A PHP 7.0 compatible clock abstraction
kreait/firebase-php                        5.20.0             Firebase Admin SDK
kreait/firebase-tokens                     1.15.0             A library to work with Firebase tokens
```
All seems good...

But I think the problem is _https://github.com/drunomics/php-paapi5-sdk_. Deleting the plugin with this dep all work fine.

**Comment by mikiamomik** [comment]
Errata corrige... https://github.com/flowdee/paapi5-php-sdk this dep is the problem

**Comment by jeromegamez** [comment]
Do you know why? I have looked at it just briefly, but on first sight, I wasn't able to determine where the SDK and that library conflict 👀

**Comment by jeromegamez** [comment]
I was able to reproduce the problem, it seems to be a combination of PHP 7.4, kreait/firebase-php 5.20, and Guzzle 6.x

I was able to make it work again by locking the SDK to release 5.19 (`composer require "kreait/firebase-php:5.19"`), but that's - of course - not a solution. I started working on this and will create a new issue/PR as soon as I can.

**Comment by jeromegamez** [comment]
To clarify: this is not per se a problem with the paapi5 SDKs that you linked. It's the Firebase SDK not working properly with older versions of its dependencies, here Guzzle 6.x - as soon as I can reproduce this in the test pipeline, I'll create a PR and let you know here.

**Comment by jeromegamez** [comment]
You can track the progress here: https://github.com/kreait/firebase-php/pull/607

Thank you @mikiamomik for pointing me in the right direction! 🙏

**Comment by mikiamomik** [comment]
> have looked at it just briefly, but on first sight, I wasn't able to determine where the SDK and that library conflict 👀

I do not understand why, but if I delete _paapi5-php-sdk_ all works fine.
With 5.19 also work, without delete _paapi5-php-sdk_.

I keep monitored [#607](https://github.com/kreait/firebase-php/pull/607)

Thank you @jeromegamez

**Comment by jeromegamez** [comment]
The reason for this is that the paapi library doesn't support Guzzle 7 - if you install the SDK alone, you probably have Guzzle 7 installed; if you install both, then you have Guzzle 6 installed, and Guzzle 6 support in the SDK is currently broken 😞

**Comment by jeromegamez** [comment]
I just released 5.20.1 which should fix the problem. Please let me know if everything works, and especially if it still doesn't work 😅

**Comment by mikiamomik** [comment]
now it's ok!

I just wanted to tell you that sometimes I get this error
Parse error: syntax error, unexpected end of file, expecting variable (T_VARIABLE) in /vendor/kreait/firebase-php/src/Firebase/Auth.php on line 645

**Comment by jeromegamez** [comment]
When it only happens sometimes, it's really difficult to determine/guess what the problem is. Syntax errors usually happen when code runs in an unsupported environment, so for example, on my computer I'm on PHP 7, on the server there's just PHP 5, then working code here will be syntax error there. At the moment I don't know another reason why this could happen. 🤔
