### ISSUE TITLE
u should have written how to connect to db

### ISSUE THREAD

**Issue by praveenpl03** [kreait/firebase-php#462]
U write everything about firebase but the guy or team giving documentation on initial connection is badly badly not explanatory .....

**Comment by jeromegamez** [comment]
I'm "the guy" and until now, quite some people seem to have been able to make use of the SDK with the current documentation.

If you have a concrete question or have found a bug, please create a new issue describing the problem, what you have tried to do and what didn't work.

If you want to improve the badly badly not explanatory documentation, feel free to create a pull request.
