### ISSUE TITLE
Is it possible to know the device received the message or not FCm

### ISSUE THREAD

**Issue by eslam2010011** [kreait/firebase-php#464]
Is it possible to know the device received the message or not FCm

**Comment by jeromegamez** [comment]
This is not possible programmatically, but you can see statistics for messages on https://console.firebase.google.com/u/0/project/_/notification/reporting - there, you can filter the reports by message type, data, or analytics label.

You can find more detailed information on https://firebase.google.com/docs/cloud-messaging/understand-delivery
