### ISSUE TITLE
Unable to connect to the API: Connection refused for URI https://oauth2.googleapis.com/token

### ISSUE THREAD

**Issue by shouvick** [kreait/firebase-php#466]
I am getting this error. previously it's working fine. I am using a firebase realtime database

Kreait\Firebase\Exception\Database\ApiConnectionFailed Unable to connect to the API: Connection refused for URI https://oauth2.googleapis.com/token

what is the possible problem?

**Comment by jeromegamez** [comment]
If it worked at one time but not the other, it's probably not an issue within the SDK.

Please check the stacktrace of the exception to find out the original cause.

As this doesn't seem to be a more specific exception (e.g. an authentication/authorization error), I can only guess without the error details, but it could be that the connection is blocked by some kind of Firewall.

**Comment by shouvick** [comment]
![s-1](https://user-images.githubusercontent.com/21361177/91681847-8a290f80-eb71-11ea-909f-979ccd98f8c2.png)
![s-2](https://user-images.githubusercontent.com/21361177/91681846-8a290f80-eb71-11ea-870f-25520ce19077.png)
![s-3](https://user-images.githubusercontent.com/21361177/91681844-872e1f00-eb71-11ea-92e1-c8ec50fe744f.png)
![s-4](https://user-images.githubusercontent.com/21361177/91681851-8bf2d300-eb71-11ea-871e-dd2f0a7b96c4.png)
![s-5](https://user-images.githubusercontent.com/21361177/91681848-8ac1a600-eb71-11ea-9325-38d52257d87c.png)

**Comment by shouvick** [comment]
Here is the sequence of trace but the problem is I have multiple firebase applications on the same server if its blocked IP/firewall it will have a problem with all other applications but it's only occurring on one application.

**Comment by jeromegamez** [comment]
I was just guessing. You asked "what's the possible problem?", and I gave you a possibility.

If you look into the stack trace, you'll see that it starts with a `ConnectException`, which hints at a networking error, that's why my guess was sons kind of Firewall. 

http://docs.guzzlephp.org/en/stable/quickstart.html?highlight=connectexception#exceptions

I'll not continue to guess, but if you say that you haven't got any problem with other Firebase applications on the same server, than it's probably something in the application/application environment.

**Comment by vegadvarsha30** [comment]
I am also facing same issues after updating to v5.8.0. I have downgraded back to v5.7.0 and it working fine!

**Comment by vegadvarsha30** [comment]
https://github.com/kreait/firebase-php/compare/5.7.0...5.8.0#diff-8fdb27e6c8e003f42f34ec30433098f2R53

**Comment by jeromegamez** [comment]
Now, this is interesting! Thank you for the additional information, I'll have a closer look as soon as I can!

**Comment by shouvick** [comment]
I am using laravel 6.0. Today I have host to another droplet it works its quite weird. Needs to find out the actual issue.

**Comment by jeromegamez** [comment]
@vegadvarsha30 Is it working in your project as well on one host, but not the other? 

@vegadvarsha30 @shouvick Concerning the changes between 5.7.0 and 5.8.0 - I had to change the exception handling to address a problem with Guzzle 7, and the handling of networking errors **should** not have changed, but if you find a breaking difference, please let me know.

But in the end, the exception **has** been thrown from Guzzle and been handled by the SDK, so I do believe that this actually is a "real" connection issue.

**Comment by vegadvarsha30** [comment]
@jeromegamez It is working fine on localhost (with docker image).

But I am facing issue with AWS ec2 machines. I verified on multiple machines from multiple AWS regions, I can reproduce the issue on all the machines with php 7.2 and php 7.4.

Then I used official node.js https://firebase.google.com/docs/auth/admin/verify-id-tokens on same machines and its working fine. 

After downgrading to 5.7.0, its working fine on all ec2 machines and as well on localhost.

PS: https://stackoverflow.com/questions/31141956/google-oauth2-api-connection-refused

**Comment by jeromegamez** [comment]
Could you please add/replace the dependency to the SDK in your `composer.json` with

```
"kreait/firebase-php": "dev-http-client-options as 5.8.1"
```

and see if that helps?

**Comment by shouvick** [comment]
@jeromegamez yes it works :D

**Comment by jeromegamez** [comment]
Thanks for the feedback, @shouvick.

@shouvick @vegadvarsha30 I've just released 5.8.1 with the same change, I hope this really solves the issue - if not, please let me know 🙏

**Comment by vegadvarsha30** [comment]
@vegadvarsha30 yes it does fixed the issue. thanks!

**Comment by b8ne** [comment]
@jeromegamez I'm only recently getting these errors and notifications are failing. Some of the exception responses are:

- `cURL error 55: getpeername() failed with errno 107: Transport endpoint is not connected (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://oauth2.googleapis.com/token`

- `Unable to connect to the API: cURL error 52: Empty reply from server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://oauth2.googleapis.com/token`

It does work sometimes, so not an implementation error.  I've got me sending setup as a Laravel Job with multiple retries, so it may fail 4-5 times and then it works. Sometimes it works first try.

I understand that is most likely not and SDK issue, but not sure where to look next.  Has anyone else had a similar issue?

- currently on v5.26.5

**Comment by jeromegamez** [comment]
Whew, this looks like a faulty network connection or proxy to me 😕.

To be sure it's not the SDK or PHP and one of its dependencies (e.g. cURL), I would suggest updating all of them (I don't support 5.x releases anymore) and see if the problem persists.

If it does, it might be something on the proxy/server side - that's where I like and hate to suggest a "Have you tried turning it off and on again?" 🙈
