### ISSUE TITLE
How to write/read user data for each one not always refresh the same one?

### ISSUE THREAD

**Issue by Antonio78318** [kreait/firebase-php#467]
Hello, I'm a newbie for firebase, I made my unity game with PHP webserver & firebase realtime database for data write/read, a User login my game will get UID from Anonymous FirebaseAuth, Now my problem is everyone login my game even they got own UID but they all use the same one table to do write/read, I wanna they have separate own player_info data, Can you suggest me how to do that? attached my table&write/read code, Thanks in advance !! 
![11](https://user-images.githubusercontent.com/33215857/91686072-e5b5c600-eb8e-11ea-8fab-3649347d5650.jpg)
![22](https://user-images.githubusercontent.com/33215857/91686197-3b8a6e00-eb8f-11ea-9b5a-3fe077026025.jpg)
![33](https://user-images.githubusercontent.com/33215857/91686200-3f1df500-eb8f-11ea-8b8a-d71ab50225c0.jpg)

**Comment by jeromegamez** [comment]
Hi Antonio, thanks for reaching out! 

In a Firebase Client environment (like Unity), you always have a current user which makes it easy to store user-related data, so you don't need an Admin SDK to do this on a dedicated server.

https://firebase.google.com/docs/database/unity/save-data

You can use security rules to limit a user's access to their own data only. For example, you could save the data to `user_info/<userId>`, store a user's data below that leaf and configure a security rule accordingly.

Unfortunately, I'm not able to give general support on how to use Firebase in general here in this repo (which is primarily meant for bugs and feature requests concerning the PHP SDK itself).

My general advice is that you need a server environment only for administrative tasks, everything that can be controlled by an application user should happen within the client application.

I suggest reading through the official docs, and, for more detailed questions, joining the Firebase Slack Community at https://firebase.community/

**Comment by Antonio78318** [comment]
Hi Jérôme, thanks for replying
According to your suggestion, So I don't need to through my PHP server to write/read data, I can control it from my client(unity C#)?

**Comment by jeromegamez** [comment]
Exactly! You only need an admin SDK if you want to control something from the outside, for example regular clean up jobs, sending notifications or programmatically change application settings.
