### ISSUE TITLE
SenderId mismatch

### ISSUE THREAD

**Issue by raghunathmestry** [kreait/firebase-php#468]
hi I got an error in previous days from this module here is the code and screenshot, please I need help to resolve this issue. 
**error is SenderId mismatch**
1. I create two SHA 1 Keys one for development and the second one is for production.
2. Also, I change my SHA 1 key from the google developer account for the google play store uploaded file.
 any problems with the above changes in the project?

        $title = 'My Notification Title';
        $body = 'My Notification Body';

        $notification = Notification::fromArray([
            'title' => $title,
            'body' => $body,
        ]);

        $notification = Notification::create($title, $body);

        $messaging = app('firebase.messaging');
        $deviceToken = 'i add my token here.....';

        $message = CloudMessage::withTarget('token', $deviceToken)->withNotification($notification); // optional;

        $message = CloudMessage::fromArray([
            'token' => $deviceToken
        ]);
        try {
            ...
            $messaging->send($message);
        }  catch (\Kreait\Firebase\Exception\MessagingException $e) {
            dd($e->errors());
        }
![Untitled](https://user-images.githubusercontent.com/35745713/92073443-459baf00-edd1-11ea-9405-025128ae15a2.jpg)

**Comment by devroll79** [comment]
What project id??

**Comment by devroll79** [comment]
> The usual reason with that kind of error is that the project id in a backend application and the project id in a client application doesn't match. This could happen if the device has been registered in the dev project, but the admin SDK is using the prod project or vice versa.
> 
> I don't know too much about the client applications, but if you changed the key, it could be that previously registered devices have to re-register, because the old device tokens have become invalid. 🤔 

What project id?

**Comment by jeromegamez** [comment]
The Firebase project ID. You can find it in the downloaded Service Account JSON file and in the project settings in the Firebase Web console.

**Comment by devroll79** [comment]
thank you for your reply, but I still don't understand.
i used laravel, firebase, expo
what is the project ID in backend application? (laravel? firebase?)
what is the project ID in the client application? (expo?)

**Comment by JamesPJ** [comment]
@jeromegamez I've 3 projects configured in firebase.php config

But, if I send notification for any project apart from the first one, I'm getting `SenderId mismatch` error. I've cross checked the issue by moving up and down the projects in the array. 
I've no idea why it is only taking the first project.

I'm on `"version": "4.2.0"`

**Comment by jeromegamez** [comment]
@JamesPJ Please create a new issue 🙏🏻

**Comment by sachinmohanweb** [comment]
facing same issue.have you got any solution 

>
