### ISSUE TITLE
Cannot set configuration file with 1.x

### ISSUE THREAD

**Issue by trondeh80** [kreait/firebase-php#47]
Hi
I tried to set up firebase-php using a service account, but I keep getting this error:

 PHP Fatal error:  Call to undefined method Google_Client::setAuthConfigFile() in .../vendor/kreait/firebase-php/src/Configuration.php on line 143

Is the service account auth method not supported in 1.x?

**Comment by jeromegamez** [comment]
It is supported and works, this is what I did to try to reproduce the issue:

```bash
mkdir authtest
cd authtest
composer require kreait/firebase-php ^1.0
cp /path/to/google-service-account.json .
```

Then I created the following test file:

```php

require_once __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Configuration;
use Kreait\Firebase\Firebase;

$config = new Configuration();
$config->setAuthConfigFile(__DIR__ . '/google-service-account.json');

$firebase = new Firebase('https://my-project.firebaseio.com', $config);

var_dump($firebase->get('/'));
```

and executed it with `php test.php` - everything worked fine. Please try this with your google service account JSON file and your Firebase domain and tell me if it worked.

Unfortunately, without being able to reproduce the issue, there's not much I can do :)

**Comment by trondeh80** [comment]
You are absolutely right. Was an issue on my part. The json file was not readable for the webserver. I am truly sorry. Thanks for the quick reply!

**Comment by jeromegamez** [comment]
No problem, I'm glad it turned out to be such a solvable problem :)
