### ISSUE TITLE
How to use actions buttons?

### ISSUE THREAD

**Issue by timmetj** [kreait/firebase-php#470]
Hello,

Is it possible to add actions to the notification?
Add a "accept" and "decline" button to it with some action behind it?

ref:
https://firebase.googleblog.com/2018/05/web-notifications-api-support-now.html

Greetings

**Comment by jeromegamez** [comment]
I can't confirm that it works, but you could try by adding the described payload from the article as a platform specific config to the message (https://firebase-php.readthedocs.io/en/5.8.1/cloud-messaging.html#webpush)

If the message goes through, Firebase has accepted it and you should be able to act on it in your web application.
