### ISSUE TITLE
Which url to paste if it is firestore cloud database

### ISSUE THREAD

**Issue by rahulmanek** [kreait/firebase-php#474]
```
$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    -withDatabaseUri('')
    ->create();

```
what to paste in withdatabaseuri

**Comment by jeromegamez** [comment]
I assume you have followed a tutorial on the internet - the code you posted refers to a 4.x release of the SDK - the current supported version is 5.x.

Please use this code to initialize the factory:

```php
$factory = (new Factory)->withServiceAccount(__DIR__.'/google-service-account.json');
```

from there you can initialize the Firestore component with

```php
$firestore = $factory->createFirestore();
```

https://firebase-php.readthedocs.io/en/5.8.1/cloud-firestore.html

**Comment by rahulmanek** [comment]
I just visited your website in which instructions,setup n all is given

Main thing I want to ask is that I'm using 000webhost free hosting so is it
necessary to use gpsr in it ?

**Comment by jeromegamez** [comment]
Unfortunately yes - the Firestore component requires gRPC to be installed, most free web hosting providers don't provide that 😕. Everything else can be used without gRPC.
