### ISSUE TITLE
Logo/Color Scheme for kreait/firebase-php

### ISSUE THREAD

**Issue by jeromegamez** [kreait/firebase-php#475]
I'm looking for someone who would be willing to contribute a nice looking logo and accompanying color scheme for this project.

It would be super if the logo had two variants: one with and one without a text. The text should include "Firebase" and "PHP" (but not "firebase-php") and it would be nice if the colors somehow related to the colors of the PHP logo and the Firebase logo. 

The new logo would be featured at the top of the readme, the color scheme would be used for new documentation pages coming in the future, and your name will appear in the readme and documentation, including a link to your GitHub profile.

I'm not a designer, but I know what I like or don't like when I see it 😅. If you're interested in contributing your time and work, or have any questions concerning the logo and colors, please add a comment to this issue and/or hit me up on Discord at https://discord.gg/nbgVfty

Please note that I'm currently looking for a free contribution - as soon as I decide to pay for design work out of my own pocket (my work on this project is unpaid) I will reach out to designers myself and close this issue.

Thank you!

:octocat:

### Details

This library is about Google Firebase and PHP, so it would be nice if the logo and color scheme could reflect those connections. I would like the logo/colors to reflect that this is a "friendly" project, so it can be playful, but not too playful 😅. For example, pixel art would be something that I personally would like.

It would be nice to have two logo variants: one variant as standalone-logo (which could be used for avatars) and one with text.

Official PHP and Firebase logos/colors for reference:

![image](https://user-images.githubusercontent.com/67554/95076355-fe774580-0711-11eb-84ec-087b69a1a70e.png)
![image](https://user-images.githubusercontent.com/67554/95076380-08994400-0712-11eb-8e7e-6360995cc67d.png)

**Comment by MansiAyer** [comment]
Hi, I'm interested in contributing to this.

**Comment by jeromegamez** [comment]
Hey @MansiAyer! Thanks for reaching out - I've updated the OP with some more detail that came to my mind. I can't think of a hard requirement or no-go at the moment, so if you'd still like to take this on, let your creativity flow 😅.

Please feel free to add further comments if you have questions or if you want to make proposals, and/or join [our Discord Server](https://discord.gg/nbgVfty) if you prefer a more interactive communication. Thanks again!

**Comment by MansiAyer** [comment]
👍 Joining Discord
