### ISSUE TITLE
Multicast send report, wrong success and failure

### ISSUE THREAD

**Issue by dihak** [kreait/firebase-php#478]
**Describe the bug**
When sending a multicast message, cant get success and failure token

**To Reproduce**
This code will give output

Success : 0
Failure : 0

```php
        $data = [
            "data" => [
                "click_action" => "FLUTTER_NOTIFICATION_CLICK",
                "body" => "Description Message",
                "title" => "This is title",
                "notif_type" => "order_dikirim",
                "unique_id" => "a445316c-f3c2-497c-bf2f-9f16179444fc",
            ],
            "notification" => [
                "title" => "This is title",
                "body" => "Description Message",
                "image" => null,
            ]
        ];
        $token = [
            "xxxxx",
            "TOKEN123"
        ];
        $messaging = app('firebase.messaging');
        $report = $messaging->sendMulticast($data, $token);
        echo 'Successful sends: '.$report->successes()->count().PHP_EOL;
        echo 'Failed sends: '.$report->failures()->count().PHP_EOL;
```

**Expected behavior**
Successful : 1
Failed : 1

**Environment (please complete the following information):**
 - OS: Windows 10
 - PHP version: 7.4
 - Firebase SDK Version: latest

**Comment by dihak** [comment]
![image](https://user-images.githubusercontent.com/10445482/95287633-93a04880-0890-11eb-8fbe-b85c8b9279b5.png)

**Comment by jeromegamez** [comment]
Thank you for the report and the debug output. Can you please confirm that you have the latest version of cURL installed? see https://firebase-php.readthedocs.io/en/5.9.0/troubleshooting.html#multicast-sendreports-are-empty

**Comment by dihak** [comment]
My curl version is 7.72.0

**Comment by dihak** [comment]
Thanks, it's work after upgrade curl
