### ISSUE TITLE
how to upload image or file using this library

### ISSUE THREAD

**Issue by waleedazam** [kreait/firebase-php#48]
Hello 
I try to upload image to storage in firebase  is this possible here ? 
Regards

**Comment by jeromegamez** [comment]
Not with 1.x, and not *yet* with 2.x - this will be possible as soon as the SDK receives Storage support.

**Comment by waleedazam** [comment]
so I must save it as base64 string

**Comment by jeromegamez** [comment]
Don't store files in the Realtime Database (I don't know if this is even possible :)). Have a look at the Google SDK instead, they provide access to Google Storage.

**Comment by waleedazam** [comment]
not file just storing the long string in field what the  problem  if so ?!

**Comment by jeromegamez** [comment]
the base64 string is still the file, just encoded as a base64 string. You can try to store those encoded files in the database, but take care when querying the database - for example, if you store all your below one database reference, and you query that reference, Firebase will send all files in one big JSON blob, and this will probably blow up things.

I still think this is a bad idea. If you have to upload files, use the Google Cloud Storage SDK, here is some more information: 

https://cloud.google.com/storage/docs/json_api/v1/libraries
https://cloud.google.com/storage/docs/json_api/v1/json-api-php-samples
https://cloud.google.com/storage/docs/json_api/v1/libraries
