### ISSUE TITLE
"FIREBASE_CREDENTIALS" is not set & GOOGLE_APPLICATION_CREDENTIALS" is not set

### ISSUE THREAD

**Issue by Antonio78318** [kreait/firebase-php#480]
**Describe the bug**
I made a php file, i wanna my users auth is identical with realtime database, but it shows :

Fatal error: Uncaught Kreait\Firebase\Exception\ServiceAccountDiscoveryFailed: Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "FIREBASE_CREDENTIALS" is not set. Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "GOOGLE_APPLICATION_CREDENTIALS" is not set. Kreait\Firebase\ServiceAccount\Discovery\FromGoogleWellKnownFile: The well known file is not readable or invalid in /opt/lampp/htdocs/api/v1/vendor/kreait/firebase-php/src/Firebase/ServiceAccount/Discoverer.php:48 Stack trace: #0 /opt/lampp/htdocs/api/v1/vendor/kreait/firebase-php/src/Firebase/Factory.php(148): Kreait\Firebase\ServiceAccount\Discoverer->discover() #1 /opt/lampp/htdocs/api/v1/vendor/kreait/firebase-php/src/Firebase/Factory.php(191): Kreait\Firebase\Factory->getServiceAccount() #2

Just wonder if i miss something to set so shows this error.

**To Reproduce**
----------The file create new user-----------
include("/opt/lampp/htdocs/firebase/dbAuth.php");

if(!$database->getReference('users/'.$uid.'/')->getSnapshot()->exists())
{
        $fileName = "NewPlayerData.json";
        $file = fopen($fileName, "r");
        $newData = fread($file, filesize($fileName));
        fclose($file);

        //echo $newData;

        $newData = json_decode($newData,true);

        $newData['Profile']['UserID'] = $uid;

        $database->getReference("users/")->getChild($uid)->set($newData);

        echo "Create New User";
}

$newData = $database->getReference("users/")->getChild($uid)->getValue();
echo json_encode($newData);

--------------dbAuth.php-------------

require __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__ . '/secret/xxx.json');
$factory = new Factory;
$firebase = $factory
   ->withServiceAccount($serviceAccount)
   ->withDatabaseUri('https://xxx.com')
   ->create();
$database = $firebase->getDatabase();

$auth = $factory->createAuth();

$token = $_POST["Token"];

$uid = "User_1234";

**Comment by jeromegamez** [comment]
I see from your code that you're using a 4.x release of the SDK, please consider upgrading to a 5.x release, the 4.x is only supported for security fixes.

I can't see from your stack trace where the error is actually thrown (please consider updating the post to apply code formatting), so I can't tell you why this is happening, but the error is explaining the cause: the credentials you provided are not picked up. Perhaps it has something to do with the include, but I'm just guessing.

I'll close this now because it's not a bug with the SDK, but I invite you to add further comments and/or share your findings so that others can benefit from them. If you'd like, you can also join the Discord linked in the Readme, where you'll find other users of the SDK that might be able to help.

**Comment by Antonio78318** [comment]
Hello Jérôme thanks for your reply, I already did what you mean about SDK upgrading to 5.x release and composer update,
![5 x](https://user-images.githubusercontent.com/33215857/95645920-1544e000-0af6-11eb-8272-814e8748c2ca.jpg)
![composer](https://user-images.githubusercontent.com/33215857/95645923-1970fd80-0af6-11eb-9198-52e590866a62.jpg)
But it still shows :
Fatal error: Uncaught Error: Class 'Firebase\Auth\Token\Verifier' not found in /opt/lampp/htdocs/api/v1/vendor/kreait/firebase-php/src/Firebase/Factory.php:168 Stack trace: #0 /opt/lampp/htdocs/api/v1/vendor/kreait/firebase-php/src/Firebase/Factory.php(197): Kreait\Firebase\Factory->getIdTokenVerifier() #1 /opt/lampp/htdocs/api/v1/dbAuth.php(10): Kreait\Firebase\Factory->createAuth() #2 /opt/lampp/htdocs/api/v1/CreateNewPlayer.php(3): include('/opt/lampp/htdo...') #3 {main} thrown in /opt/lampp/htdocs/api/v1/vendor/kreait/firebase-php/src/Firebase/Factory.php on line 168

Did i need to change something for my setting?

**Comment by Antonio78318** [comment]
Hello Jérôme, thanks for your reply. I tried to do your suggestion, I did composer require kreait/firebase-php ^5.0 & composer update --lock, then it was actually upgrade well, but still shows: 
Fatal error: Uncaught Error: Call to undefined method Kreait\Firebase\Factory::create() in /opt/lampp/htdocs/api/v1/dbAuth.php:11 Stack trace: #0 /opt/lampp/htdocs/api/v1/CreateNewPlayer.php(3): include() #1 {main} thrown in /opt/lampp/htdocs/api/v1/dbAuth.php on line 11

it seems firebase-php composer.json not be handle with, is that probably i did something wrong process my upgrading, so made the structure going wrong? thank you very much

**Comment by jeromegamez** [comment]
Please have a look at https://firebase-php.readthedocs.io/en/5.9.0/troubleshooting.html#call-to-private-method to see how to change the initialization of the SDK after the upgrade from 4.x to 5.x

Please let me know if that helped 🙏🤞

**Comment by Antonio78318** [comment]
Hello Jérôme,Thanks for your help, but that seems doesnt work for me, So i decided to show you my process of upgrading, maybe i got something wrong with that.

![try](https://user-images.githubusercontent.com/33215857/95657591-d9d30180-0b47-11eb-9888-50404e574dd8.jpg)
![try1](https://user-images.githubusercontent.com/33215857/95657595-ddff1f00-0b47-11eb-9936-622ea7a4b33b.jpg)
![try2](https://user-images.githubusercontent.com/33215857/95657597-e22b3c80-0b47-11eb-9dfa-29ae2bffc5ef.jpg)

Just dont know if i made mistake for the question i did red frame you can see, cos i just type y to answer those questions. Thank you again for always tried to figure out my problems. :)

**Comment by jeromegamez** [comment]
Please try this: delete the vendor directory, and do a new `composer install` after that.

If this doesn't help, delete the vendor directory again and try a `composer install --prefer-dist`

If this doesn't work please have a look at your PHP installation - I can see from the screenshot that you don't seem to have the zip and unzip PHP extensions installed - this prevents composer from downloading the release packages and causes it to git clone every library instead. This will lead to conflicts in case you have modified files inside the vendor directory, which then leads to conflicts during a git clone.

All in all, something seems to be not right or at least not optimal with the PHP environment 😕

**Comment by Antonio78318** [comment]
Hello i already tried to delete vendor file then run composer install & composer install --prefer-dist, They both didnt work for me, And you mentioned about the zip and unzip PHP extensions installed that i dont really know cos i installed my php environment by 
"xampp-linux-x64-7.4.6-0-installer.run", I also searched that and tried to run something,But it seems nothing happened.

![try4](https://user-images.githubusercontent.com/33215857/95659466-e0677600-0b53-11eb-9acf-736f33bf2da2.jpg)

Can you please tell me more about how to do that if its my PHP environment problem made that conflicts, Thank you :)

**Comment by Antonio78318** [comment]
Hello i already tried to delete vendor file then run composer install & composer install --prefer-dist, They both didnt work for me, And you mentioned about the zip and unzip PHP extensions installed that i dont really know cos i installed my php environment by
"xampp-linux-x64-7.4.6-0-installer.run", I also searched that and tried to run something,But it seems nothing happened.

![try4](https://user-images.githubusercontent.com/33215857/95659574-8a470280-0b54-11eb-819d-92ead8272951.jpg)

Can you please tell me more about how to do that if its my PHP environment problem made that conflicts, Thank you :)

**Comment by jeromegamez** [comment]
I see from your latest screenshots that a php-zip package has been installed, but still, in your previous screenshots it's written that it's missing, so something must be off 🤔

I'm sorry, but I'll have to leave you on your own here, general development support is out of scope of the SDK and of what I can provide here 😅

**Comment by Antonio78318** [comment]
Thanks for your helping, I can understand it already out of scope of the SDK, But can you provide me a standard procedure of installation for php-firebase, Cos i will try to make a new one if i can avoid something wrong that would be better. :)

**Comment by Antonio78318** [comment]
Hello Finally i fixed my problem,I can see src in my firebase-tokens file, So my php file can work now, Thanks so much for your help :)

**Comment by Antonio78318** [comment]
Hello Jérôme,
I completed my game and will release soon, but I had a problem with the efficacy of my server(PHP) with firebase, It's slow when my game read/store with firebase, I check my server status is pretty good, So I wanna know how I can improve the situation Or its feature of PHP handle about data read/store with firebase slower than other languages, Thx :)

**Comment by jeromegamez** [comment]
It's not a "feature" of PHP being slow, this I can say :).

Not knowing your application, I can say this: if you developed your game to call a remote server that then, in turn, calls Firebase, will always be slower than calling Firebase directly from within your game. Assuming your game runs on a mobile device or in the browser (which also is a client), it would be better to use one of the Firebase Client SDKs instead of a server SDK.

With a client SDK the communication flow is:

Client -> Firebase -> Client

With an admin SDK running on the server (e.g. PHP, but it's the same with the other admin SDKs), the flow is:

Client -> Server -> Firebase -> Server -> Client

The second flow _must_ be slower than the first one because it involves more HTTP requests and more processing of the individual responses.

**Comment by Antonio78318** [comment]
Hello Jérôme,
Thanks for your reply, I can understand client SDK must be faster than the server SDK, But consider those data unsafe to handle on the client-side, We have to through the server to read/store, I tried to use the profiler built into the Firebase CLI to get insights into how my database instance is performing, I have a question about why that didn't display those speeds data on my snapshot, But I can get other data, Thank you!
![speed](https://user-images.githubusercontent.com/33215857/98623676-3001b300-2347-11eb-8b61-645d8ffe43eb.jpg)

**Comment by jeromegamez** [comment]
The reason is that the PHP SDK has no profiler built-in 😅

**Comment by Antonio78318** [comment]
Hello Jérôme,
I found this issue 
https://stackoverflow.com/questions/51694810/using-php-with-firebase-database-is-slow
Its just the question i got now, Why it took so long time getValue() on realtime database,
That made my game read data slowly, Do you have any better idea to fix it? Or i only can do less calls on my game? Thx
