### ISSUE TITLE
Support for Remote Config grouped parameters 

### ISSUE THREAD

**Issue by plantas** [kreait/firebase-php#483]
Grouped parameters are part of the template and not handled by library. Upon template saving grouped parameters got lost.
Please add support for grouped parameters.
https://firebase.google.com/docs/remote-config/automate-rc

**Comment by jeromegamez** [comment]
@plantas Could you have a look at #486 and check that I haven't missed something? 🙏

**Comment by plantas** [comment]
@jeromegamez Great work! 💯  Thanks
