### ISSUE TITLE
Client error: `POST https://fcm.googleapis.com/v1/projects/[id project]/messages:send` resulted in a `400 Bad Request` response:

### ISSUE THREAD

**Issue by putu-eka-mulyana** [kreait/firebase-php#484]
Hi, I want to send a notification to the Android application, but I get an error "The registration token is not a valid FCM registration token
".

`$data = [
            'time' => 'now',
            'title' => 'good morning"',
            'msg' => 'good morning  ',
        ];
        $message = CloudMessage::withTarget('token',$token)
            ->withData($data);
        $this->messaging->send($message);
`

**Comment by jeromegamez** [comment]
What's your question? 😅

**Comment by putu-eka-mulyana** [comment]
how to solve errors Client error: `POST https://fcm.googleapis.com/v1/projects/[id project]/messages:send` resulted in a `400 Bad Request`

**Comment by jeromegamez** [comment]
The error was already quite telling: the registration token you're trying to send a message to is not valid. I honestly don't know what I can tell you more than that - use a valid registration token and it will work.

**Comment by putu-eka-mulyana** [comment]
error message "The registration token is not a valid FCM registration token"

**Comment by jeromegamez** [comment]
Yes, I understood that from the first message already. There are multiple reasons why a registration token can be invalid:

* It has the wrong format
* It's a registration token that has been unregistered from your Firebase project
* It's a registration token that has been generated for a different Firebase project than the one you're using

**Comment by kevdu228** [comment]
i have the same problem and the problem is that after instal the sdk in php file we cannot no more get $_post data.

i send the title,body and the token via postman with post method but the file cant get the data i send via post ant it return "The registration token is not a valid FCM registration token
" because the token variable is empty
