### ISSUE TITLE
400 Bad Request error even after adding the rules

### ISSUE THREAD

**Issue by ashokssrkc** [kreait/firebase-php#487]
I was trying to check if the value is exist by 

Code
$reference = $this->database->getReference('tasks/'.$current_date)->orderByChild('driver_id')->equalTo($driver_id);
$snapshot = $reference->getSnapshot();

Database structure:
![image](https://user-images.githubusercontent.com/73097976/96412115-351b8880-1207-11eb-9962-1988e694ff08.png)

Rule:
![image](https://user-images.githubusercontent.com/73097976/96413768-be33bf00-1209-11eb-9b22-cedf956e4292.png)

Error:

"error" : "Index not defined, add \".indexOn\": \"driver_id\", for path \"/tasks/19-10-2020\", to the rules"

But if you see the structure the  19-10-2020 is dynamically created. Please help to resolve the issue.

**Comment by jeromegamez** [comment]
```json
{
  "rules": {
    ".read": true,
    ".write": true,
    "tasks": {
      "$date": {
        ".indexOn": ["driver_id"]
      }
    }
  }
}
```

> Note that `$date` could be any name really, seems like you can specify a variable value using any `$identifier`.

Source:
- https://stackoverflow.com/a/49015713/284325
- https://www.google.com/search?q=realtime+database+index+on+dynamic+subtree

**Comment by ashokssrkc** [comment]
Thanks a lot for the quick response. It worked!!!!
