### ISSUE TITLE
Composer require works on brand new project, fails on existing

### ISSUE THREAD

**Issue by ok200paul** [kreait/firebase-php#49]
When I use `composer require kreait/firebase-php ^2.0@beta` on a brand new project (laravel) all is well, but when there are already packages installed, `"laravel/cashier": "~7.0"` and `"laravel/spark": "*@dev"`, the composer require script gives the below errors:

```
Problem 1
    - kreait/firebase-php 2.0.0-beta1 requires firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].
    - kreait/firebase-php 2.0.0-beta2 requires firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].
    - Conclusion: don't install firebase/token-generator v3.0.0
    - Installation request for kreait/firebase-php ^2.0@beta -> satisfiable by kreait/firebase-php[2.0.0-beta1, 2.0.0-beta2].
```

Let me know if you need anything further - cheers guys

**Comment by ok200paul** [comment]
It had something to do with the `@dev` status of `laravel/spark` as installed by the laravel spark installer. Using `"laravel/spark": "~2.0",` in composer.json and the following worked:

```
"repositories": [
        {
            "type": "composer",
            "url": "https://spark-satis.laravel.com"
        }
    ]
```

**Comment by jeromegamez** [comment]
Happy it worked out, thank you for also posting the solution!

**Comment by jakeols** [comment]
I'm having the same issue using the 1.x branch.. I'm using laravel, but not spark. 


```
Problem 1
- kreait/firebase-php 1.0 requires firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].
- kreait/firebase-php 1.0.1 requires firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].
- kreait/firebase-php 1.1 requires firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].
- kreait/firebase-php 1.1.1 requires firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].
- kreait/firebase-php 1.2 requires firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].
- kreait/firebase-php 1.2.1 requires firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].
- Conclusion: don't install firebase/token-generator v3.0.0
- Installation request for kreait/firebase-php ^1.0 -> satisfiable by kreait/firebase-php[1.0, 1.0.1, 1.1, 1.1.1, 1.2, 1.2.1].
```

**Comment by jeromegamez** [comment]
@jakeols The Firebase Tokengenerator relies on the firebase/php-jwt 3.0 package - if you already have php-jwt 4.x somewhere in your project, it is probably the reason for the failure.

As I need it only for the authentication through database secrets and that has been deprecated by Firebase, this dependency will eventually be removed in a 3.0 release of this package.

I am also evaluating to refactor the token generation to not rely on the TokenGenerator package, but I can't decide yet if it's worth it, when database secret authentication will be dropped anyways :).

**Comment by jeromegamez** [comment]
Another possibility: I could fork the token generator package and use it as a replacement dependency. I will check and test it.

**Comment by jakeols** [comment]
Yeah- I'm using a different package to handle user auth that uses php-jwt ^4.x.
