### ISSUE TITLE
Add ability to get headers from FCM response

### ISSUE THREAD

**Issue by krasilnikovm** [kreait/firebase-php#491]
### Context
from time to time FCM return 500 error and firebase documentation tell us how handle the errors https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode one of them is `Honor the Retry-After header if it is included in the response from the FCM Connection Server.` but when we call send method we can get only response body.

### Possible solution
Return response model which will contain response body and headers or in response body add extra key with headers but I'm not sure that a good idea mix response body with headers.

What do you think about that changes? or should we extend Messaging service on our side?

**Comment by jeromegamez** [comment]
Hey @krasilnikovm 👋, and thank you for bringing this up! I share your concern about mixing response headers and bodies, and while I was thinking about what to propose, I looked through the code, changed some lines here and there, and then it suddenly was ready for a PR 😅

Could you have a look at #492? This should enable you to catch 429 and 503 errors specifically, and get the `Retry-After` value from them, if available 🤞 

 If you have questions, comments, and/or suggestions, let's discuss them over there 🙏

**Comment by krasilnikovm** [comment]
@jeromegamez Thank you. I had a look your pr, It looks awesome. ❤

**Comment by jeromegamez** [comment]
This is now merged and will be included in the next release, thanks again!
