### ISSUE TITLE
MessagingException::errors() does not really return string[]

### ISSUE THREAD

**Issue by paveljanda** [kreait/firebase-php#494]
**Describe the bug**
MessagingException or the classes that inherit it (NotFound, InvalidMessage, etc) have errrors property which by php doc should be a `string[]`. But that is not true. An example:

```php
array(1) {
	["error"]=>
	array(4) {
		["code"]=>
		int(404)
		["message"]=>
		string(31) "Requested entity was notfound."
		["status"]=>
		string(9) "NOT_FOUND"
		["details"]=>
		array(1) {
			[0]=>
			array(2) {
				["@type"]=>
				string(51) "type.googleapis.com/google.firebase.fcm.v1.FcmError"
				["errorCode"]=>
				string(12) "UNREGISTERED"
			}
		}
	}
}
```

**To Reproduce**
Send for example a push notifications with and old (unregistered) puth token to firebase api.

**Expected behavior**
I would expect more detailed errors structure or an property named `$originalError` which would be simply of type `array`, not `string[]`.

**Environment (please complete the following information):**
 - OS: eny
 - PHP version: 7.4.7
 - Firebase SDK Version: 5.10.0

**Comment by jeromegamez** [comment]
The PHPDoc is fixed with https://github.com/kreait/firebase-php/commit/e613798df618c666d586135be7dea51b46ee38f4, thanks for the notice!
