### ISSUE TITLE
Error while sending notification to any topic. Error : Recipient of the message is not set...

### ISSUE THREAD

**Issue by VivekGuna1994** [kreait/firebase-php#497]
**Describe the bug**
Hello  @jeromegamez ,I am sending the push notification to subscribed to topic and its giving me following error :-

**Fatal error</b>: Uncaught Kreait\Firebase\Exception\Messaging\InvalidMessage: Recipient of the message is not set.**

**To Reproduce**
A self-contained code example to reproduce the behavior

```php
        public static function sendNotificationToTopic($topic_name,$title,$body,$data) {
            $factory = self::getFCMFactory();
            $messaging = $factory->createMessaging();
            
            $message = CloudMessage::fromArray([
                'topic' => $topic,
                'notification' => [
                    'title' => $title,
                    'body' => $body
                ],
                'data' => $data
            ]);
            
            $messaging->send($message);
        }
```

**Environment**
 - OS: Windows 10
 - PHP version: 7.3
 - Firebase SDK Version: 5.0

**Comment by jeromegamez** [comment]
The message looks good to me, so the error should not happen 😭. Just to be sure, could you please upgrade from 5.0 to the latest version (5.11 currently). (The version constraint in your `composer.json` should be `^5.11`, so that you can get future updates as well.)

Does the `getFCMFactory` "just" return the Factory from the SDK, or is the `createMessaging()` method a custom method from your application?

**Comment by VivekGuna1994** [comment]
Hi @jeromegamez ,
I have upgraded to latest version and **error is gone**. Thanks you so much for that.

But after upgrade following error is coming.Only send to topic is not working.
Can you please help me out with that ?

**Error**
Fatal error</b>: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST
https://fcm.googleapis.com/v1/projects/masterapp-xxxxxx/messages:send` resulted in a **`400 Bad Request`** response:
(truncated...)
in C:\xampp\htdocs\wordpress\wp-content\plugins\sb-api\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 C:\xampp\htdocs\wordpress\wp-content\plugins\sb-api\vendor\guzzlehttp\guzzle\src\Middleware.php(69):
GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL,
Array, NULL)
#1 C:\xampp\htdocs\wordpress\wp-content\plugins\sb-api\vendor\guzzlehttp\promises\src\Promise.php(204):
GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 C:\xampp\htdocs\wordpress\wp-content\plugins\sb-api\vendor\guzzlehttp\promises\src\Promise.php(153):
GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 C:\xampp\htdocs\wordpress\wp-content\plugins\sb-api\vendor\guzzlehttp\promises\src\TaskQ in
<b>C:\xampp\htdocs\wordpress\wp-content\plugins\sb-api\vendor\kreait\firebase-php\src\Firebase\Exception\Messaging\InvalidMessage.php</b>


**Thanks**

**Comment by VivekGuna1994** [comment]
Hi @jeromegamez ,
Thank you so much , after upgrading to latest version its working now.
your library is amazing, Thank You!

**Comment by jeromegamez** [comment]
I'm glad the issue is resolved and that you like the library 😊🌺
