### ISSUE TITLE
404 Bad Request

### ISSUE THREAD

**Issue by dralnegar** [kreait/firebase-php#50]
In my first attempt to use:

```
$sortedUsers = $users
			->orderByChild('username', SORT_DESC)
			->limitToFirst(10)
			->getValue(); // shortcut for ->getSnapshot()->getValue()
```

I get the following error:

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET {MyProjectURL}/users?orderBy=%22username%22` resulted in a `400 Bad Request` response:
{
  "error" : "Index not defined, add \".indexOn\": \"username\", for path \"/users\", to the rules"
}
```

If I comment out ->orderByChild('username', SORT_DESC) and try again I get: 
```
_PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET {MyProjectURL}/users?limitToFirst=10` resulted in a `400 Bad Request` response:
{
  "error" : "orderBy must be defined when other query parameters are defined"
}
```
Is the syntax of .../user?orderby=%22username%22 getting corrupted by the %22 values? If so is this something that is causing the problem on my server setup?

**Comment by jeromegamez** [comment]
This is related to #39  - it's not an error, but a inconvenience - in order to be able to order retrieved data by child, you have to add an index to the reference in question, as described in the Firebase docs: https://firebase.google.com/docs/database/security/indexing-data

**Comment by jeromegamez** [comment]
The `%22%` values are perfectly fine, these are just HTML encoded double quotes (`"`), what you have to do, is to add this to your Firebase security rules:

```json
{
  "rules": {
    "users": {
      ".indexOn": ["username"]
    }
  }
}
```

**Comment by dralnegar** [comment]
Going to Database / Rules tab, the rules now looks like:
```
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null",
    "users": {
      ".indexOn": ["username"]
    }
  }
}
```
Using the example code, I am now getting the expected result.

As always thanks for the help Jermoe :)

**Comment by jeromegamez** [comment]
You're welcome :)
