### ISSUE TITLE
php8 compat

### ISSUE THREAD

**Issue by mitalcoi** [kreait/firebase-php#508]
First need to resolve this issue: https://github.com/kreait/firebase-tokens-php/issues/33 and then update that repo to patched version of kreait/firebase-tokens-php

**Comment by jeromegamez** [comment]
You can follow the progress at #509

**Comment by jeromegamez** [comment]
PHP 8.0 support has been implemented and release with [v5.13](https://github.com/kreait/firebase-php/releases/tag/5.13.0) 🥳
