### ISSUE TITLE
kreait/firebase-php is not working with jwt auth package due to mutual 3rd package "lcobucci/jwt"

### ISSUE THREAD

**Issue by Jamilbilal47** [kreait/firebase-php#510]
well I am using this kreait package in my existing project in which I already used JWT auth, so basically these both packages are using 'lcobucci/jwt' this package so jwt auth required version of 3.3.3 and kreait required this package version of 3.4.1, can you please tell me any solution how I can use this package within my existing project without any conflict?
this is my required array currently I am using
 "require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "lcobucci/jwt": "3.3.3",
        "pusher/pusher-php-server": "^4.1",
        "twilio/sdk": "^6.10",
        "tymon/jwt-auth": "^1.0.0-beta.3@dev",
        "wildbit/swiftmailer-postmark": "^3.1"
    },

**Comment by jeromegamez** [comment]
The problem should be solved as soon as you replace 

```
"lcobucci/jwt": "3.3.3",
```

with 

```
"lcobucci/jwt": "^3.3.3",
```


The first one tells composer "only 3.3.3", the second says "_at least_ 3.3.3, but if there's a newer 3.x version, that's even better" 🤞

**Comment by akalongman** [comment]
@jeromegamez
could you add support of the 4.x version of "lcobucci/jwt"? 

laravel/passport  and league/oauth2-server  requires  lcobucci/jwt (^3.4 || ^4.0)  and thus installed 4.x version.

**Comment by jeromegamez** [comment]
@akalongman This topic is already adressed in #508 and will be handled with #509 - I'm closing this issue now since it's closely related, please follow one of the to be notified about the progress 🤞

**Comment by jeromegamez** [comment]
PHP 8.0 support (and with it, support for `lcobucci/jwt:^3.4|^4.0`) has been implemented and released with [v5.13](https://github.com/kreait/firebase-php/releases/tag/5.13.0) 🥳
