### ISSUE TITLE
Question: how to validate thousands of tokens without send anything to them?

### ISSUE THREAD

**Issue by goncalogoncalves** [kreait/firebase-php#511]
Hello

Is it possible to check if thousands of tokens are valid without send anything to them?

I can do

`$messaging = $this->factory->createMessaging();
$message = CloudMessage::withTarget('token', $token)
            ->withNotification([
                'title' => 'Hello',
                'body' => 'Have a nice day'
            ]);
$resultValidate = $messaging->validate($message);`

to validate one token, and I can do 

`$messaging->sendMulticast(`

to send a push to several tokens. How can I join the two? to send a "validate_only" to a multicast?

Thank you

**Comment by jeromegamez** [comment]
That's a good one! I will get to it once after I managed finishing the PHP 8 stuff 💪
