### ISSUE TITLE
IDN conversion failed

### ISSUE THREAD

**Issue by vpaflah** [kreait/firebase-php#512]
**Describe the bug**
When I use Firebase Realtime database getValue() function, it returns an error saying  

> "Kreait \ Firebase \ Exception \ Database \ DatabaseError
> IDN conversion failed"

**To Reproduce**
The error is returned from this code section

/home/sobincee/public_html/stockboy/kuppy/kuppy/vendor/kreait/firebase-php/src/Firebase/Exception/DatabaseApiExceptionConverter.php

        private $responseParser;
     
        /**
         * @internal
         */
        public function __construct()
        {
            $this->responseParser = new ErrorResponseParser();
        }
     
        /**
         * @return DatabaseException
         */
        public function convertException(Throwable $exception): FirebaseException
        {
            if ($exception instanceof RequestException) {
                return $this->convertGuzzleRequestException($exception);
            }
     
            return new DatabaseError($exception->getMessage(), $exception->getCode(), $exception);
        }
     
        private function convertGuzzleRequestException(RequestException $e)
        {
            $message = $e->getMessage();
            $code = $e->getCode();
     
            if ($e instanceof ConnectException) {
                return new ApiConnectionFailed('Unable to connect to the API: '.$message, $code, $e);
            }
     
            if ($response = $e->getResponse()) {
                $message = $this->responseParser->getErrorReasonFromResponse($response);
                $code = $response->getStatusCode();
            }

```php
This is my code for getting values from Firebase realtime database

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/firebaseKey.json');
        
        $factory = (new Factory)
        ->withEnabledDebug()
        ->withServiceAccount($serviceAccount)
        ->create();
        // $factory = $factory->withEnabledDebug();
        
        $database = $factory->getDatabase();
        
        $reference = $database->getReference('recipes');
        $values = $reference->getValue(); //This is the section returning the error

```

**Expected behavior**
I'm expecting a json output from the realtime database

**Screenshots**

**Environment (please complete the following information):**
 - Cpanel Hosting
 - Laravel: 5.7
 - PHP version: 7.1
 - Firebase SDK Version: 4.44

**Additional context**

**Comment by jeromegamez** [comment]
It seems that you don't have the `intl` PHP extension installed, you can check with `php -m` and see if `intl` appears in the list.

A workaround could be to install the `intl` polyfill with `composer install symfony/polyfill-intl-idn`.

**Comment by vpaflah** [comment]
Thank you for your faster response, and I already have the `intl` PHP extension installed before I got the error, But I run this command `composer install symfony/polyfill-intl-idn` , It's worked fine hurray
