### ISSUE TITLE
im trying to connect the firebase with php and got this problem ....

### ISSUE THREAD

**Issue by mahmoud-hamdan99** [kreait/firebase-php#514]
the error is : Expected parameter of type 'Kreait\Firebase\string', 'string' provided 

its happend in this row :
 $serviceAccount = ServiceAccount::fromJsonFile(__DIR__ . '/covid2020-b5242-firebase-adminsdk-y3nme-d1e74e3d98.json');

this is my php code 👍 
<?php
require __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__ . '/covid2020-b5242-firebase-adminsdk-y3nme-d1e74e3d98.json');
$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->withDatabaseUri('https://covid2020-b5242.firebaseio.com')
    ->create();

$database = $firebase->getDatabase();

?>

I'm using composer- v: 4.17

**Comment by jeromegamez** [comment]
The latest 4.x release is 4.44, please update at least to that version.

Please note that this SDK requires at least PHP 7.0 - the error you get is an indication that you are on PHP 5.x

**Comment by jeromegamez** [comment]
I'm going to close this now because it's not an issue with the SDK, but feel free to add further comments or join the Discord server mentioned in the Readme.

**Comment by mahmoud-hamdan99** [comment]
im still have the same problem ?
do u have a video toturial on how to connect firebase database with php that i can watch it maybe ?

**Comment by jeromegamez** [comment]
https://firebase-php.readthedocs.io/en/5.12.0/tutorials.html has a list of tutorials, but they're targeted towards 4.x releases of the SDK, and the current version is 5.x.

But with both versions you will need at least PHP 7.0 to work with them

**Comment by mahmoud-hamdan99** [comment]
my php version is :

$ php -v
PHP 7.4.12 (cli) (built: Oct 27 2020 17:18:47) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

i tried SDK version 4.17 and the next php code : 

<?php
require __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__ . '/covid2020-b5242-firebase-adminsdk-y3nme-d1e74e3d98.json');
$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->withDatabaseUri('https://covid2020-b5242.firebaseio.com')
    ->create();

$database = $firebase->getDatabase();

?>


and im still have a problem ..

**Comment by jeromegamez** [comment]
Which problem? The same as described in your first post?

My first advice still holds: please update the SDK from your currently used version 4.17 to 4.44. This is usually done with a `composer update`.  Alternatively you can also try 

```bash
$ composer require "kreait/firebase-php:^4.44"
```

**Comment by mahmoud-hamdan99** [comment]
i did that ...
right now i have SDK 4.44 .
still the same problem .

**Comment by mahmoud-hamdan99** [comment]
take a look at the pic plz .
![Untitled1](https://user-images.githubusercontent.com/75495152/101365675-c1b00200-38ac-11eb-9a01-031d362992c2.png)

**Comment by jeromegamez** [comment]
Please try this ([as documented in the docs for 4.x](https://firebase-php.readthedocs.io/en/4.44.0/setup.html)):

```php
use Kreait\Firebase\Factory;

$factory = (new Factory)
    ->withServiceAccount(__DIR__. '/path-to-your-service-account.json')
    ->withDatabaseUri('https://your-database.firebaseio.com');

$database = $factory->createDatabase();
```

**Comment by mahmoud-hamdan99** [comment]
thanks a lot mate 👍 
no problem right now .

i just wanna ask if u have the code to retreive the data from firebase database .

**Comment by jeromegamez** [comment]
I'm sorry, but you'll have to write that code yourself 😅. But here's the relevant part of the docs: https://firebase-php.readthedocs.io/en/4.44.0/realtime-database.html#retrieving-data
