### ISSUE TITLE
Authentication with Apple

### ISSUE THREAD

**Issue by cristiano-linvix** [kreait/firebase-php#516]
Good morning, I would like to login with apple via PHP SDK, I didn't find any documentation to be able to perform the method, is there any way?
I really don't know if it exists or not, so I don't know if it's a resource request.

**Comment by jeromegamez** [comment]
Sign-in with Apple can be done on the client side, not the backend side:

* https://firebase.google.com/docs/auth/web/apple
* https://firebase.google.com/docs/auth/android/apple
* https://firebase.google.com/docs/auth/ios/apple

Using one of these methods will enable you to receive an `idToken` on the client that you can then send to your backend server (see https://firebase-php.readthedocs.io/en/5.12.0/authentication.html#verify-a-firebase-id-token)
