### ISSUE TITLE
How to create a child node off the parent?

### ISSUE THREAD

**Issue by pnsean** [kreait/firebase-php#52]
So the scenario is this.  I need to create a child off of the root node.  I am however getting a permission denied when attempting to do so.

I'm attempting this using a push right now thinking it would create the path if it doesn't already exist?

```
$fbConfig = new Configuration();
$fbConfig->setAuthConfigFile(__DIR__.'/app/config/firebase.conf.json');
$firebase = new Firebase('https://abstract-key-nnnnn.firebaseio.com', $fbConfig);

$metaArray = array(' .... ');

$firebaseId = $firebase->push($metaArray, 'metadata');
```

In the scenario above, metadata does not yet exist in the first iteration.  The push above is contained in a foreach where a large volume of records will be written to /metadata

Am I missing something?  Somewhat new to Firebase so forgive any ignorrance.

**Comment by jeromegamez** [comment]
Pushing will create a child with an autogenerated ID below the `metadata` node, so, if you execute

```php
$firebaseId = $firebase->push($metaArray, 'metadata');
```

as you wrote above, this would result in `$firebaseId` being set to the key name in the likes of `-KUTVaYdHmIiVmki2JgH`, which you could the fetch again by issuing

```php
$metadata = $firebase->get('metadata/'.$firebaseId);
```

If you want to create a new node, you can use `set`, whether the given node exists or not - just keep in mind: *if* there is existing data, it will be completely overwritten, including all potentially existing sub-nodes.

So, you could approach you target in two different ways: you could set the `metadata` node in one run by uploading your whole metadata array:

```php
$firebaseId = $firebase->set($metaArray, 'metadata');
$metaArray = $firebase->get('metadata'); // Should be exactly the same
```

If you would like to split up the operation in multiple steps, you could iterate `$metaArray`:

```php
foreach ($metaArray as $key => $value) {
    $firebase->set($value, 'metadata/'.$key); // On the first iteration, if the "metadata" location doesn't exist, it will be created automatically, including its child "metadata/$id"
}

$metaArray = $firebase->get('metadata'); // Should be exactly the same again
```

Or you could in fact push the `$metaArray` values to the `metadata` location:

```php
foreach ($metaArray as $key => $value) {
    $firebase->push([$key => $value], 'metadata);
}
/* "metadata" now looks like this:
[
    '-KUTVaYdHmIiVmki2JgH' => [
        'key_1' => 'value_1',
    ],
    '-KUTVaYdHmIiVmki2JgI' => [
        'key_2' => 'value_2',
    ],
    ...
)
*/
```

I don't know if that makes sense for your use case, of course :)

**Comment by jeromegamez** [comment]
Sorry for the lengthy reply, I hope I didn't overcomplicate things :).

One addition, just in case, because I didn't know it at first: Firebase will not store `null` as a value and just discard the key as well. Here is an example:

```php
$metadata = [
    'a_string' => 'my_string',
    'a_number' => 123,
    'a_null_value' => null,
];

$firebase->set($metadata, 'metadata');

print_r($firebase->get('metadata'));
```
the output will be
```
Array
(
    [a_number] => 123
    [a_string] => my_string
)
```

So, the 'a_null_value' has been discarded, so stored data is not 100% same as the data you put into the database. `false`, `0` and other "nully" values are not affected, though.

**Comment by pnsean** [comment]
Actually found the issue.

```
$fbConfig->setAuthConfigFile(__DIR__.'/app/config/firebase.conf.json');
$firebase = new Firebase('https://abstract-key-nnnnn.firebaseio.com', $fbConfig);
```

I set the incorrect path for the config file.  The file did not exist at the path above, I would have thought that the library would throw a IO exception when it failed to read the file?

Anyway, once I corrected the path, everything worked as expected. :)

**Comment by jeromegamez** [comment]
Ooops, sorry! I totally overlooked the part where you said that you are getting a permission denied error 😓😅.

There should have been an exception, though - the file path is given to the underlying Google library which which throws an `\InvalidArgumentException` if the file doesn't exist.

**Comment by pnsean** [comment]
No worries, that was my bad.  That said, no exception is being thrown -- very strange.  But that was definitely the issue, the file didn't exist at the path above.  As soon as I corrected the path, everything worked fine.
