### ISSUE TITLE
Authenticate with twitter issue

### ISSUE THREAD

**Issue by harishksoft** [kreait/firebase-php#525]
@jeromegamez 

require __DIR__.'/../../vendor/autoload.php';
use Kreait\Firebase\Factory; /*** version installed is 4.44 **/
use Kreait\Firebase\ServiceAccount;
use Kreait\Firebase\Auth;
use Kreait\Firebase\Auth\SignInResult\SignInResult;
use Kreait\Firebase\Auth\SignInWithIdpCredentials;

$firebase = (new Factory())->withServiceAccount($this->config->item('firebase_app_key'));
$this->auth = $firebase->createAuth();

$res = $this->auth->signInWithIdpAccessToken($data['type'],$data['auth_token'],'http://localhost',$data['auth_secrete']);
print_r($res);

When printing the result, getting the error as follows:
installed Kreait version is **4.44**

**INVALID_CREDENTIAL_OR_PROVIDER_ID : Invalid IdP response\/credential: http:\/\/localhost?access_token=<my_token>&providerId=twitter.com**

its working correctly when running with google auth_token with the following :
$res = $this->auth->signInWithIdpAccessToken('google.com',$data['auth_token']);

**Comment by jeromegamez** [comment]
Try replacing `auth_secrete` with `auth_secret` 🤞

**Comment by jeromegamez** [comment]
You're welcome 🌺
