### ISSUE TITLE
Firebase expired token is not considered

### ISSUE THREAD

**Issue by NafaaAzaiez** [kreait/firebase-php#526]
I have two API versions on my server, one is using `"kreait/firebase-bundle": "^2.1"` on the other one is using `"kreait/firebase-bundle": "^2.3"`.

I tried authentication with an expired firebase token on both of them, the older one returned and expiration exception while the newer one accepted the token and I was authenticated.

**-> An expired token allowed me to be authenticated**

I checked my vendors and found this [code](https://github.com/kreait/firebase-php/blob/5.x/src/Firebase/Auth/IdTokenVerifier.php#L105)

```php
# Kreait\Firebase\Auth\IdTokenVerifier

catch (ExpiredToken $e) {
            // Re-check expiry with the clock
            if ($this->isNotExpired($token, $now)) {
                return $token;
            }

...

    private function isNotExpired(Token $token, DateTimeImmutable $now): bool
    {
        return $token->isExpired($now->modify('-'.($this->leewayInSeconds + 1).' seconds'));
    }
```

Here `isNotExpired`is returning the result of `isExpired` without reversing it.

---

- The Operating System: Ubuntu 20.04
- The PHP version: 7.4.7
- Versions:
```
kreait/clock                              1.1.0              A PHP 7.0 compatible clock abstraction
kreait/firebase-bundle                    2.3.0              Symfony Bundle for the Firebase Admin SDK
kreait/firebase-php                       5.13.0             Firebase Admin SDK
kreait/firebase-tokens                    1.14.0             A library to work with Firebase tokens
```

**Comment by jeromegamez** [comment]
The Bundle ist "just" for integrating the SDK with Symfony, and the version constraints are the same, so I'm not sure if the problem lies in the Bundle or the SDK.

You shared one output of `composer show`, for which one of the projects is it, the "older" or the "newer" one? Could you share the other too, please? I think the version of `lcobucci/jwt` on both projects would be interesting as well.

**Comment by NafaaAzaiez** [comment]
So I checked, I had the same `kreait/firebase-bundle` version on both but their dependencies were updated (firebase-php `5.11` to `5.13`)

I think the problem lies in the `isNotExpired` function in this repository `firebase-php` as explained in the issue unless I missed something.

Here are the [PR changes](https://github.com/kreait/firebase-php/pull/509/files#diff-575d70178be54c031eec2074b1bbedad8511969132456c8fdac5748f3ecd4e4eR105)

**OLD code**
```php
# Kreait\Firebase\Auth\IdTokenVerifier

    private function isNotExpired(Token $token, DateTimeImmutable $now): bool
    {
        $claim = $token->getClaim('exp');

        // We add another second to account for possible microseconds that could be in $now, but not in $expiresAt
        $check = $now->modify('-'.($this->leewayInSeconds + 1).' seconds');
        $expiresAt = $now->setTimestamp((int) $claim);

        return $expiresAt > $check;
    }
```

### NEW code
```php

    private function isNotExpired(Token $token, DateTimeImmutable $now): bool
    {
        return $token->isExpired($now->modify('-'.($this->leewayInSeconds + 1).' seconds'));
    }

```


The composer show I put is for the newer one where I have the bug. 

Here are both:

### OLD composer (it works fine)
```
kreait/clock                              1.1.0            
kreait/firebase-bundle                    2.3.0             
kreait/firebase-php                       5.11.0           
kreait/firebase-tokens                    1.11.0           

lcobucci/jwt                              3.3.3
```

### NEW composer (token expired bug)
```
kreait/clock                              1.1.0              
kreait/firebase-bundle                    2.3.0             
kreait/firebase-php                       5.13.0             
kreait/firebase-tokens                    1.14.0           

lcobucci/jwt                              4.0.0             
```

**Comment by jeromegamez** [comment]
Good catch! Looks like a case of a missing exclamation mark :/. I'll have a closer look as soon as I get to a computer and will release a fix soon. Thanks you!

**Comment by jeromegamez** [comment]
[5.14](https://github.com/kreait/firebase-php/releases/tag/5.14.0) is out and should™ (🤞) fix the issue. Please let me know if it still doesn't work as expected 🙏
