### ISSUE TITLE
Call to undefined method Lcobucci\\JWT\\Token\\Plain::getClaim()

### ISSUE THREAD

**Issue by AliHassan13** [kreait/firebase-php#531]
There is issue when i run the command `composer update` it's update the version of  **lcobucci/jwt** **4.0** it cause the issue and show the error
**Call to undefined method Lcobucci\\JWT\\Token\\Plain::getClaim()**
for the temporary fix solution you need to rollback the version of **lcobucci/jwt** to **3.4.1** by running the following command. 
**composer require lcobucci/jwt 3.4.1**

**firebase-php version 5.14.0**

**Comment by jeromegamez** [comment]
The issue is that `getClaim()` has been deprecated in 3.4 and removed in 4.0. I assume you're using the method somewhere in your code, but since you didn't share code, I can only guess :)

If you found the `getClaim()` somewhere in the code or docs of the SDK, please let me know or create a PR 🙏
