### ISSUE TITLE
Use firebase-php for token verification?

### ISSUE THREAD

**Issue by andig** [kreait/firebase-php#54]
According to https://firebase.google.com/docs/auth/admin/verify-id-tokens the official firebase admin SDKs can be used to validate ID tokens. I'm looking for this functionality inside `firebase-php` where it doesn't seem to exist?

**Comment by jeromegamez** [comment]
That's right, it doesn't exist yet, but this issue will now serve as a todo list item :)

**Comment by ruudboon** [comment]
+1 for this one also 👍

**Comment by ruudboon** [comment]
For everybody waiting out here. @jeromegamez  submitted a new project: https://github.com/kreait/firebase-tokens-php

**Comment by jeromegamez** [comment]
And now it's also implemented in the SDK 🎉 : https://github.com/kreait/firebase-php/releases/tag/2.1.0 /cc @andig
