### ISSUE TITLE
link in fcm_options (part WebPushConfig) not working

### ISSUE THREAD

**Issue by RomanTruhanov** [kreait/firebase-php#567]
Hi all. I have a problem wich fcm_options link not working in laravel 8 and windows 10, but notification config work fine. Find old question about my problem this https://github.com/kreait/firebase-php/issues/316 read and not get right workable solusion my code is 

```php
$config = WebPushConfig::fromArray([
    'notification' => [
        'title' => 'Backend',
        'body' => 'Тест работы Firebase Cloud Messenger (FCM)',
        'icon' => 'http://localhost:3000/favicon.ico',
    ],

    'fcm_options' => [
        'link' => 'https://www.google.com/'
    ],
]);

$deviceToken = User::whereNotNull('device_token')->pluck('device_token')->all();
$notification = Notification::create($request->title, $request->body)->withImageUrl('https://picsum.photos/400/200');
$message = CloudMessage::withTarget(MessageTarget::TOKEN, $deviceToken[0])->withNotification($notification)->withWebPushConfig($config);

$messaging = app('firebase.messaging');

$response = $messaging->send($message);
```

**Comment by jeromegamez** [comment]
What exactly is not working? Do you get an error/exception, or does the notification not arrive at the target device?

**Comment by RomanTruhanov** [comment]
i don't get any errors my fcm message is look at this 
![image](https://user-images.githubusercontent.com/13104248/107988726-a9adda80-6fe1-11eb-91f2-9539d2a13897.png)
but if clicked him just closed (don't go to link)

**Comment by jeromegamez** [comment]
Unfortunately, I can't tell you why this is happening and I don't know a solution to it... the official docs say that it _should_ be working, but from this Admin SDK's perspective there's not much we can do. I just checked in the Admin Node SDK and it's defined in the same way there: https://github.com/firebase/firebase-admin-node/blob/93362d5721fc45f3fc541543813d5739eda8ba2d/src/messaging/index.ts#L148-L155

As I can't adequately help you here, I think StackOverflow or the Firebase Support would be a better way to find a solution to this - if you find a solution, please share it with us here, perhaps I can make a new FAQ item out of it! 🙏🏼

**Comment by aroon9002ahmed** [comment]
link not work if you open same site on google chrom .... close website page than click on message website will open
