### ISSUE TITLE
Realtime Database Uri issue

### ISSUE THREAD

**Issue by WaseemRakab** [kreait/firebase-php#570]
Im having an issue in getting the exact database url
when im pushing data, deleting, i get 404 not found error, 
i checked the source code, went into Factory.php Line 380~ at method "getDatabaseUri()"
this method returns the wrong url for my firebase project which i checked in the firebase console,
it's different from what i have
the one i get is from this method is -> "https://(project-id).firebaseio.com/"
in firebase console is -> "https://(project-id)-default-rtdb.firebaseio.com/"
please fix this issue asap.
thank you
current specs: 
```
kreait/clock                   1.1.0   A PHP 7.0 compatible clock abstraction
kreait/firebase-php            5.14.1  Firebase Admin SDK
kreait/firebase-tokens         1.14.0  A library to work with Firebase tokens
Mac OS 11.2
PHP 8.0.2
```

**Comment by jeromegamez** [comment]
This issue can asap be fixed by reading the documentation.
thank you

https://firebase-php.readthedocs.io/en/5.14.1/setup.html#realtime-database-uri
