### ISSUE TITLE
Ability to generate custom token (JWT) to use elsewhere in application

### ISSUE THREAD

**Issue by hmazter** [kreait/firebase-php#58]
With the Official SDK for node and Java it's possible to use the SDK to create a custom token to be used in other places of the application. For example automatically log in a user against Firebase that is already logged-in in "my"-system.

It would be fantastic to have this functionality as part of the PHP SDK as well.

I'm currently doing this manually in my code to accomplish it (pretty much a standard JWT encode with the private key from the service account file):
```
        $serviceAccount = $this->getServiceAccount();
        $serviceAccountEmail = $serviceAccount['client_email'];
        $privateKey = $serviceAccount['private_key'];

        $nowSeconds = time();
        $payload = array(
            "iss" => $serviceAccountEmail,
            "sub" => $serviceAccountEmail,
            "aud" => "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
            "iat" => $nowSeconds,
            "exp" => $nowSeconds + (60 * 60),  // one hour
            "uid" => $userId
        );
        return JWT::encode($payload, $privateKey, 'RS256');
```

**Comment by jeromegamez** [comment]
Hey @hmazter, thanks for reaching out! To make sure that I understand correctly and that we are on the same page:

1. Are you using version 2.x of the PHP SDK? (Hint: Version 1.x is feature-frozen 😅)
2. Do I understand correctly that, when you create the custom token, you have made sure that the user is logged in, and `$userId` contains the Firebase user ID of a user? If so, you should be able to log in the user against your Firebase application by using the methods described in http://firebase-php.readthedocs.io/en/latest/authentication.html#authentication-overrides-a-k-a-custom-tokens, so `$firebase->asUserWithClaims($userId)` should be sufficient.

Could you explain in more detail what you are accomplishing with the custom token that you are currently generating manually?

**Comment by hmazter** [comment]
@jeromegamez Thanks for a quick reply!

Yes I am currently using version 2.0.2.

No the `$userId` is just a unique identifier (in this case the id of the user in my system)
I saw the page you linked to about creating custom tokens. But as far as I understand these can only be used with the `asUserWithClaim` function in the PHP SDK. And it's not possible to get the actual JWT back. 

I'll try to explain what I'm currently using the function for:
I have a system build with PHP (and Laravel) with a full auth system. When a user is logged in, they can navigate to a page where I have som real time data from my firebase database showing through a javascript app.
This database is of course only available to logged in user. And to make my users that is authorized in the php system authorized with firebase without any additional steps for the user, I generate a JWT token (custom token) and pass that to `firebase.auth().signInWithCustomToken(token)` in my javascript app.
Hope that made some sense :smile: 

So what I need is to get the full JWT token that is signed with my Google Service account file (email and private key)
And since this is possible with the other SDK and Firebase PHP already handles the service account file I thought i would be good to do it with this package as well.

The current situation, which I use, for PHP is described here: https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_a_third-party_jwt_library

**Comment by jeromegamez** [comment]
I think I am understanding better now, thank you for the explanation! Expect the means to create JWT tokens in the next release! (I can't tell how long that will take, though 😅)

**Comment by ruudboon** [comment]
Would like to do the same thing over here.

**Comment by jeromegamez** [comment]
@hmazter @ruudboon I'm on it, like, right now :)

**Comment by ruudboon** [comment]
@jeromegamez That's awesome. Please let me know if you push something, would love to try it.

**Comment by jeromegamez** [comment]
@ruudboon Just got your email concerning #54, thanks for reaching out! #54 is next on the list and will be based on the work of this feature here (both are JWT related after all), so I wouldn't recommend putting work into that until the ground work is done!

If you're interested, join the Firebase Community Slack at https://firebase-community.appspot.com - there's a #php channel with a decent amount of PHP devs in it :+1:

**Comment by ruudboon** [comment]
For everybody waiting out here. @jeromegamez  submitted a new project: https://github.com/kreait/firebase-tokens-php

**Comment by jeromegamez** [comment]
And now it's also implemented in the SDK 🎉 : https://github.com/kreait/firebase-php/releases/tag/2.1.0
