### ISSUE TITLE
Failed to install on Laravel 8.12

### ISSUE THREAD

**Issue by nakarimi** [kreait/firebase-php#600]
I just try to install it on Laravel 8 project, but failed, it needs some dependency that is blocked and has conflict with the current version.
I try both `composer require kreait/laravel-firebase` and `composer require kreait/firebase-php`, that both of them failed.
what should I do to install it successfully?

This is my composer.json
```
"require": {
        "php": "^7.3|^8.0",
        "appzcoder/laravel-admin": "^3.3",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.2",
        "livewire/livewire": "^2.4",
        "pusher/pusher-php-server": "^5.0",
        "spatie/laravel-backup": "^6.15",
        "tymon/jwt-auth": "^1.0"
    },
```
![image](https://user-images.githubusercontent.com/28529970/116821500-546c7880-ab8f-11eb-99a5-4f700841c411.png)
![image](https://user-images.githubusercontent.com/28529970/116821557-985f7d80-ab8f-11eb-8ac7-b751ee5c8577.png)

**Comment by jeromegamez** [comment]
This is due to the tymon/jwt-auth package preventing the installation of a required dependency. You can read more about it at kreait/firebase-php#581
