### ISSUE TITLE
Symfony\Component\ErrorHandler\Error\FatalError: Declaration of Kreait\Firebase\Messaging\ApiClient::request

### ISSUE THREAD

**Issue by Vebion** [kreait/firebase-php#608]
After update "kreait/firebase-php": "5.18" to "kreait/firebase-php": "5.20" result error:

Symfony\Component\ErrorHandler\Error\FatalError: Declaration of Kreait\Firebase\Messaging\ApiClient::request(string $method, $uri, array $options = Array): Psr\Http\Message\ResponseInterface must be compatible with GuzzleHttp\ClientInterface::request($method, $uri, array $options = Array)

Package "laravel-notification-channels/fcm": "~2.0"

**Comment by jeromegamez** [comment]
If possible, please upgrade guzzle in your project to a 7.x version, or downgrade the SDK to 5.19.

I'm currently working on a fix at https://github.com/kreait/firebase-php/pull/607 and will provide a new version as soon as possible. Sorry for the inconvenience!

**Comment by jeromegamez** [comment]
I just released [5.20.1](https://github.com/kreait/firebase-php/releases/tag/5.20.1) which should fix the problem. Please let me know if everything works and feel free to reopen the issue if it doesn't! 🤞
