### ISSUE TITLE
Unable to generate FCM by device token or topic

### ISSUE THREAD

**Issue by nakarimi** [kreait/firebase-php#617]
How getting registration token/ Device token, I trying to send notification, but I couldn't find how and where I can find the device token?

Even I use topic, that doesn't need device token, still it doesn't create notification. here is the code: 

```
        $path = base_path('config/fooddelivery-firebase.json');
        $title = 'My Notification Title';
        $body = 'My Notification Body';
        $notification = Notification::create($title, $body);
        $factory = (new Factory)->withServiceAccount($path);
        $messaging = $factory->createMessaging();

        // $deviceToken = '';
        // $message = CloudMessage::withTarget('token', $deviceToken)
        $message = CloudMessage::withTarget('topic', 'mytopic')
            ->withNotification($notification);


        try {
            $factory->createMessaging()->validate($message);
            return $messaging->send($message);

            // Result:
            // {
            //     "name": "projects/fooddelivery-cc39b/messages/757376859954639368"
            // }
            
        } catch (InvalidMessage $e) {
            print_r($e->errors());
        }
        die;

```

**Comment by jeromegamez** [comment]
First of all, you don't need to validate AND send, the message will be validated automatically when you send it. Validating is only useful when you don't already know what the message looks like. You also don't need to call `createMessaging()` twice.

You can get a registration token for the device on the client, for example, on Android: https://firebase.google.com/docs/cloud-messaging/android/client?hl=en#retrieve-the-current-registration-token

If you are using iOS or a Web Client, the Firebase docs have sections on that as well.

If you want to send a message to a topic, a client must be subscribed to the topic first. Again, for Android: https://firebase.google.com/docs/cloud-messaging/android/topic-messaging

In general: As mentioned in the issue template, for "How to...?" Questions, please use the discussions or join the Discord server. If you believe this is a bug in the SDK, please let me know and I'll re-open the issue.
