### ISSUE TITLE
 SSL certificate problem

### ISSUE THREAD

**Issue by bkr32** [kreait/firebase-php#62]
i'm pretty new to using this framework so excuse my noobness,
i'm attempting to retrieve registration ID's saved in firebase database and then push notifications to those devices.

```
require 'vendor/autoload.php';
$firebase = Firebase::fromServiceAccount(
    __DIR__.'/google-service-account.json',
    'https://c9029.firebaseio.com'
);

$database = $firebase->getDatabase();
$reference = $database->getReference('/tokens/');
$value = $reference->getValue();
echo ("id is$value");
//$title = $_POST["title"];
//$body = $_POST["body"];
$registrationIds = array($RID);
```

this is the code i am using to fetch those values.
in the database it is structured as `/tokens/UniqueOrRandomID/token:value` 

however the following error is returned 

`Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\xampp\htdocs\fcm\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\xampp\htdocs\fcm\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\fcm\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\fcm\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\fcm\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Ha in C:\xampp\htdocs\fcm\vendor\kreait\firebase-php\src\Firebase\Exception\ApiException.php on line 28`

i am running this using xampp locally

hope someone can help, thanks

**Comment by jeromegamez** [comment]
Please have a look at http://firebase-php.readthedocs.io/en/latest/troubleshooting.html, perhaps the steps described there can help with the problem.

SSL errors usually hint to a problem of the system the application is running on, so maybe it could also help if you upgrade your xampp environment (if there is an update available).

**Comment by bkr32** [comment]
adding the certificate file definitely worked :D 
oddly no notifications are pushed

**Comment by jeromegamez** [comment]
The PHP SDK currently only supports working with the realtime database - I don't know how notifications work, but there's nothing built-in here.

**Comment by bkr32** [comment]
i found another php script online that takes care of notifications 


```
<?php
require 'vendor/autoload.php';
$firebase = Firebase::fromServiceAccount(
    __DIR__.'/google-service-account.json',
    'https://riara-c9029.firebaseio.com'
);

$database = $firebase->getDatabase();
$reference = $database->getReference('/tokens/');
$value = $reference->getValue();


echo ("id is$value");
//$title = $_POST["title"];
//$body = $_POST["body"];
$registrationIds = $RID; 
//was $registrationIds = arrays($RID);

       $message = array
       (
        'message'   => '123',
        'title'     => '123',
        'subtitle'  =>  '123',
        'tickerText'    =>  '123',
        'vibrate'   => 1,
        'sound'     => 1,
        'largeIcon' => 'large_icon',
        'smallIcon' => 'small_icon'
       );


       $url = 'https://fcm.googleapis.com/fcm/send';
       $fields = array(
         'registration_ids' => $registrationIds,
         'notification' => $message
        );
       $headers = array(
        'Authorization:key = AAAARG56bIg:APA91bFUOwbmV8PeqnJiOBw62TCHIpHjqYbxyXC9z9kWdnrV5xEwTzS5UbRVzQwYaRW3KoB77FV4mjFpBRX390jl23tcFWmqodgsTY6wBL29gB_ykMXcSUhdsnj8VYsH8PmlYe3N7icLKBE1MwcojEeDdgZgyg1kFw',
        'Content-Type: application/json'
        );
       $ch = curl_init();
       curl_setopt($ch, CURLOPT_URL, $url);
       curl_setopt($ch, CURLOPT_POST, true);
       curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
       curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
       curl_setopt ($ch, CURLOPT_SSL_VERIFYHOST, 0);  
       curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
       curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
       $result = curl_exec($ch);           
       if ($result === FALSE) {
           die('Curl failed: ' . curl_error($ch));
       }
       curl_close($ch);

       echo $result;
```

**Comment by jeromegamez** [comment]
Uuh, thanks! This might come in handy for a future feature addition! <3

**Comment by bkr32** [comment]
welcome hope i get it to work
