### ISSUE TITLE
Hi guys I am new to firebase and I got this error while I was dealing with a site given by somebody

### ISSUE THREAD

**Issue by Mohsing511** [kreait/firebase-php#639]
Hi guys I am new to firebase and I got this error while I was dealing with a site given by somebody.
my error is given below
`
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://consultancy-ef482.firebaseio.com/admin_login/` resulted in a `423 Locked` response: in C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\guzzlehttp\promises\src\Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true) #5 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\guzzlehttp\promises\src\Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\guzzlehttp\promises\src\Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #7 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\guzzlehttp\promises\src\Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #8 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #9 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\guzzlehttp\guzzle\src\Client.php(129): GuzzleHttp\Promise\Promise->wait() #10 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Http\WrappedGuzzleClient.php(26): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array) #11 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Database\ApiClient.php(188): Kreait\Firebase\Database\ApiClient->send(Object(GuzzleHttp\Psr7\Request), Array) #12 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Database\ApiClient.php(45): Kreait\Firebase\Database\ApiClient->requestApi('GET', Object(GuzzleHttp\Psr7\Uri)) #13 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Database\Reference.php(282): Kreait\Firebase\Database\ApiClient->get(Object(GuzzleHttp\Psr7\Uri)) #14 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Database\Reference.php(247): Kreait\Firebase\Database\Reference->getSnapshot() #15 C:\xampp\htdocs\consultancyproject\admin_panel\php\admin_login.php(12): Kreait\Firebase\Database\Reference->getValue() #16 {main} Next Kreait\Firebase\Exception\Database\DatabaseError: The Firebase database 'consultancy-ef482' has been deactivated. in C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Exception\DatabaseApiExceptionConverter.php:65 Stack trace: #0 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Exception\DatabaseApiExceptionConverter.php(37): Kreait\Firebase\Exception\DatabaseApiExceptionConverter->convertGuzzleRequestException(Object(GuzzleHttp\Exception\ClientException)) #1 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Database\ApiClient.php(190): Kreait\Firebase\Exception\DatabaseApiExceptionConverter->convertException(Object(GuzzleHttp\Exception\ClientException)) #2 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Database\ApiClient.php(45): Kreait\Firebase\Database\ApiClient->requestApi('GET', Object(GuzzleHttp\Psr7\Uri)) #3 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Database\Reference.php(282): Kreait\Firebase\Database\ApiClient->get(Object(GuzzleHttp\Psr7\Uri)) #4 C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Database\Reference.php(247): Kreait\Firebase\Database\Reference->getSnapshot() #5 C:\xampp\htdocs\consultancyproject\admin_panel\php\admin_login.php(12): Kreait\Firebase\Database\Reference->getValue() #6 {main} thrown in C:\xampp\htdocs\consultancyproject\admin_panel\includes\vendor\kreait\firebase-php\src\Firebase\Exception\DatabaseApiExceptionConverter.php on line 65
{"mode":"full","isActive":false}`

**Comment by jeromegamez** [comment]
Please share the code that lead to this error - I have never seen `423 Locked` occur, so I'm curious to see what might have caused this.
