### ISSUE TITLE
Excuse me, I found my mistake when creating the instance, I leave the code in case someone had a similar problem

### ISSUE THREAD

**Issue by SergioRe** [kreait/firebase-php#642]
Excuse me, I found my mistake when creating the instance, I leave the code in case someone had a similar problem

<img width="717" alt="captura de pantalla 2018-06-01 a la s 23 34 48" src="https://user-images.githubusercontent.com/7634958/40870529-1d085d72-65f7-11e8-8b59-a857d763a988.png">

_Originally posted by @erixrevolver in https://github.com/kreait/firebase-php/issues/204#issuecomment-394058548_

**Comment by SergioRe** [comment]
Solution: https://github.com/kreait/firebase-php/issues/641

**Comment by jeromegamez** [comment]
Thanks for sharing! Please use the discussions feature instead of opening a bug report to share your findings 🙏
