### ISSUE TITLE
I always get a faied open stream error for Firebase\\Auth\\Token\\Cache\\InMemoryCache.php when I try to send message

### ISSUE THREAD

**Issue by lalojunkyard** [kreait/firebase-php#644]
### Describe the issue you are experiencing

I'm trying to send a FCM with firebase-php and I always get the error file "PHP message: PHP Warning:  require_once(../../model/Firebase\\Auth\\Token\\Cache\\InMemoryCache.php): failed to open stream", looks like the application is trying to open that file directly on the folder where I'm calling the vendor/autoload file instead of use its own route to get the right folder

### Installed packages

composer require kreait/firebase-php

### PHP version and extensions

PHP 7.4

### On which operating system(s) does the issue occur?

- [ ] Linux
- [ ] MacOS
- [X] Windows

### Steps to reproduce the issue.

```php
require __DIR__ . '/../lib/firebase/vendor/autoload.php';
use Kreait\Firebase\Factory;
use Kreait\Firebase\Messaging\CloudMessage;
use Kreait\Firebase\Messaging\Notification;
$jsonDir = __DIR__. '/../lib/firebase/azulik-tribe.json';
$factory = ( new Factory )->withServiceAccount( $jsonDir );
$messaging = $factory->createMessaging();
$message = CloudMessage::withTarget( 'token', $token )->withNotification( Notification::create( $titulo, $mensaje ) );
$messaging->send( $message );
```

### Error message/Stack trace

[Wed Aug 04 11:31:51.186836 2021] [proxy_fcgi:error] [pid 28601:tid 140598295230208] [client 187.189.50.236:13516] AH01071: Got error 'PHP message: PHP Warning:  require_once(../../model/Firebase\\Auth\\Token\\Cache\\InMemoryCache.php): failed to open stream: No such file or directory in /home/565140.cloudwaysapps.com/heyfcvvxxg/public_html/model/functions.php on line 9PHP message: PHP Fatal error:  require_once(): Failed opening required '../../model/Firebase\\Auth\\Token\\Cache\\InMemoryCache.php' (include_path='.:/usr/share/php') in /home/565140.cloudwaysapps.com/heyfcvvxxg/public_html/model/functions.php on line 9'

**Comment by jeromegamez** [comment]
This looks like an autoloading issue, not a bug in the SDK itself. I don't know what the reason for this could be since I'm missing the context of the code (e.g. if it's standalone or embedded/called from another script).

You could try replacing

```php
require __DIR__ . '/../lib/firebase/vendor/autoload.php';
```

with 

```php
require_once __DIR__ . '/../lib/firebase/vendor/autoload.php';
```

just to be sure that the composer autoloader is not required multiple times, but apart from that I have no ideas 🤔

**Comment by lalojunkyard** [comment]
I also try with require_once and I get the same result

**Comment by jeromegamez** [comment]
@lalojunkyard Did you find the reason for the problem?

**Comment by AdeSupriyadi** [comment]
I have same problem.

When I check .json file not there.
then I put there and tadaa it's works.
