### ISSUE TITLE
JWT created with empty claims errors with INVALID_CLAIMS

### ISSUE THREAD

**Issue by hmazter** [kreait/firebase-php#65]
First off, great work with the JWT generator.
One problem though, I think.

When I create a token and don't pass any claims (defaults to a empty array)
```
return (string)$tokenHandler->createCustomToken((string)$auth->id);
```
I get the follow error when trying to use the generated token with firebase:
```
{"error":{"errors":[{"domain":"global","reason":"invalid","message":"INVALID_CLAIMS"}],"code":400,"message":"INVALID_CLAIMS"}}
```

But when i throw in ant random claim, everything works as expected:
```
return (string)$tokenHandler->createCustomToken((string)$auth->id, ['foo' => 'bar']);
```

My guess is that setting an empty claim array in the token is not valid. I tested this by removing the line `$this->builder->set('claims', $claims);` and that also worked.

**Comment by hmazter** [comment]
This should probably have been in the kreait/firebase-tokens-php repo

**Comment by jeromegamez** [comment]
Hey Kristoffer, thanks for bringing this up! Interestingly I couldn't reproduce the issue when testing via the REST API, but better safe than sorry :)

https://github.com/kreait/firebase-tokens-php/commit/44dbe40b488802ed136c3fc3f1b88eae05e22159 should fix this (I just pushed new releases of both libraries) and let me know if it [now/still not] works.

**Comment by hmazter** [comment]
Yes its seems to work fine now. Thanks!
