### ISSUE TITLE
Support nonce for Apple login

### ISSUE THREAD

**Issue by chyt** [kreait/firebase-php#654]
### Describe the feature you would like to see

When performing login with Apple, there are cases where a [nonce](https://developer.apple.com/documentation/sign_in_with_apple/clientconfigi/3386668-nonce) is required in the response body to associate a client session and an ID token. I don't believe this option is yet supported by this library. 

An implementation of this can be in my fork [here](https://github.com/watchcharts/firebase-php/commit/9869fcf79acf84d51b215c1d0fa1009306565c22?w=1). However it was written a while back and not compatible with the current codebase.

**Comment by jeromegamez** [comment]
Thanks @chyt! This seems pretty straight forward thanks to your fork, I'll try to get it to the main branch shortly 🤞

**Comment by jeromegamez** [comment]
Hey @chyt, could you give https://github.com/kreait/firebase-php/pull/658 a try and confirm that it works as expected? Unfortunately I can't really test this myself and can only work on the assumption that I implemented the requirements correctly 🤞

**Comment by chyt** [comment]
@jeromegamez I will give this a try in the next few days and report back.
