### ISSUE TITLE
Errors in code

### ISSUE THREAD

**Issue by drpain** [kreait/firebase-php#66]
1350#0: *2098534 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/vendor/kreait/firebase-php/src/Firebase.php on line 23"

Really should have error_reporting enabled man

**Comment by jeromegamez** [comment]
@drpain Your error is a result of using the library with PHP < 7.0, see [Return type declarations in the PHP manual](http://php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration).

If you're using PHP 5.x, the [1.x release](https://github.com/kreait/firebase-php/tree/1.x) might fit your needs.

Really should have read the readme man 😛

**Comment by drpain** [comment]
Weird because my severs are running PHP 7. I will have to look again, but caused 30minutes of downtime so I would have to do it carefully.

**Comment by jeromegamez** [comment]
@SYK360 Be assured, if you get a syntax error, the environment you're running the script in is *not* running PHP 7.x.

You can check this by adding the line `echo phpversion(); exit` somewhere in your script and run it on the environment you're getting the error with.

**Comment by naeimrezaeian** [comment]
how can run code on php under 7.x ?

**Comment by drpain** [comment]
I have personaly bumped my php version to 7.2 since this will be the new LTS for php from the end of 2018, and I am now using the library with great success. 

Example of my dockerfile for reference.
https://github.com/drpain/DockIt/blob/master/images/php-fpm/Dockerfile

**Comment by jeromegamez** [comment]
@naeimrezaeian If you have to use a PHP version < 7.0, you can try the 1.2.2 version of this SDK: https://firebase-php.readthedocs.io/en/1.2.2/ - but it has limited features, and I can't provide support for it.
