### ISSUE TITLE
 Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `PUT https://my-database-uri-rtdb.firebaseio.com/Social_links/` resulted in a `400 Bad Request` response: 

### ISSUE THREAD

**Issue by imselmon** [kreait/firebase-php#660]
### Describe the issue you are experiencing

I'm Tring to set the values in the  database but getting this error 

### Update_data.php
```PHP


<?php
session_start();
include 'fire_config.php';


if(isset($_POST['Social_update'])){

  $social_instagram = $_POST['social_instagram'];
  $social_github = $_POST['social_github'];
  $social_spotify = $_POST['social_spotify'];
  $social_linkedin = $_POST['social_linkedin'];
  $social_skype = $_POST['social_skype'];
  $social_dev = $_POST['social_dev'];
  $social_twitter = $_POST['social_twitter'];
  $social_facebook = $_POST['social_facebook'];
  $social_fb_msg = $_POST['social_fb_msg'];
  $social_youtube   = $_POST['social_youtube'];
  $social_email = $_POST['social_email'];
  $social_telegram = $_POST['social_telegram'];

  $postdata = [
                      'Instagram'  =>$social_instagram,
                      'Github'  =>$social_github,
                      'Spotify'  =>$social_spotify,
                      'LinkedIn'  =>$social_linkedin,
                      'Skype'  =>$social_skype,
                      'Dev.to'  =>$social_dev,
                      'Twitter'  =>$social_twitter,
                      'Facebook'  =>$social_facebook,
                      'Massanger'  =>$social_fb_msg,
                      'Youtube'  =>$social_youtube,
                      'Email'  =>$social_email,
                      'Telegram'  =>$social_telegram

  ];
  $ref = "Social_links/";
  $pushData = $database->getReference($ref)->set($postdata);
      header("Location:home.php");
}

?>

```

### Fire_Config.php

```PHP
<?php

require __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Factory;


$factory = (new Factory)
->withServiceAccount('key.json')
->withDatabaseUri('https://my-database-uri-rtdb.firebaseio.com/');


$database = $factory->createDatabase();

?>

```

### Installed packages

`$ composer require kreait/firebase-php
`

### PHP version and extensions

PHP Version 8

- [X] Windows

### Error message/Stack trace

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `PUT https://coder-salman-default-rtdb.firebaseio.com/Social_links/` resulted in a `400 Bad Request` response:

**Comment by jeromegamez** [comment]
Please wrap your code with a try/catch block to see more details of the error, e.g.

```php
try {
    $pushData = $database->getReference($ref)->set($postdata);
} catch (\Throwable $e) {
    echo $e->getMessage();
    exit;
}
```

**Comment by imselmon** [comment]
Thank you for your valuable response - Got the Solution 

It's was a little Bug in the given Code snippet on line no 2nd where I am passing Dev.to in a String, In this string there is one "." In between the Decleard Word so we can't add any type of point or Dot in the string if we did then it will throw the error 

 **Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `PUT https://my-database-uri-rtdb.firebaseio.com/Social_links/` resulted in a `400 Bad Request` response: **


# Not Working code 

`PHP

'Skype' =>$social_skype, 
'Dev.to' =>$social_dev,`


#  Working code 

`PHP

'Skype' =>$social_skype, 
'Devto' =>$social_dev,`




@jeromegamez

**Comment by codersalman** [comment]
> Thank you for your valuable response - Got the Solution 
> 
> It's was a little Bug in the given Code snippet on line no 2nd where I am passing Dev.to in a String, In this string there is one "." In between the Decleard Word so we can't add any type of point or Dot in the string if we did then it will throw the error 
> 
>  **Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `PUT https://my-database-uri-rtdb.firebaseio.com/Social_links/` resulted in a `400 Bad Request` response: **
> 
> 
> # Not Working code 
> 
> `PHP
> 
> 'Skype' =>$social_skype, 
> 'Dev.to' =>$social_dev,`
> 
> 
> #  Working code 
> 
> `PHP
> 
> 'Skype' =>$social_skype, 
> 'Devto' =>$social_dev,`
> 
> 
> 
> 
> 

@jeromegamez
