### ISSUE TITLE
Not found exeption

### ISSUE THREAD

**Issue by jgodstime** [kreait/firebase-php#662]
### Describe the issue you are experiencing

I am using version 5.x of this package, I get the error below, and i don't know why, please help out

```
{"file":"C:\\laragon\\www\\creamella-core\\vendor\\kreait\\firebase-php\\src\\Firebase\\Messaging.php","line":58,"function":"becauseTokenNotFound","class":"Kreait\\Firebase\\Exception\\Messaging\\NotFound","type":"::","args":["eqQb9GthR-i6f4TxVBu7Sw:APA91bG8bLt1PGV2l3tThBMmUvLiUbp0d0lQDjdgr_Nppe-1aeUokoAkP733ScjMD3zF2QMg8SGH9mnwPweL5jARYirkk_q5O7lrO4CJdvp5ECCJks5hANrROA0RiGMBJ8mt32PZfS9Z"]},
```

The token exists and its still showing me this error

### Installed packages

Here is my list of installed packages 

```
       "php": "^7.3|^8.0",
        "cloudinary-labs/cloudinary-laravel": "^1.0",
        "dingo/api": "^3.0",
        "fruitcake/laravel-cors": "^2.0",
        "fzaninotto/faker": "^1.9",
        "guzzlehttp/guzzle": "^7.3",
        "kreait/firebase-php": "5.x",
        "laravel/framework": "^8.54",
        "laravel/socialite": "^5.2",
        "laravel/tinker": "^2.5",
        "spatie/laravel-fractal": "^5.8",
        "spatie/laravel-permission": "^4.2",
        "tymon/jwt-auth": "^1.0",
        "yabacon/paystack-php": "^2.2"
```

### PHP version and extensions

7.4

### On which operating system(s) does the issue occur?

- [ ] Linux
- [ ] MacOS
- [X] Windows

### Steps to reproduce the issue.

1. ...
2. ...
3. ...

```php


  try {
            if (is_array($data))
                $data = (object)$data;

            $factory = (new Factory)->withServiceAccount(app_path('Channels/google-service-account.json'));

            $messaging = $factory->createMessaging();

            $notification = Notification::create($data->title, $data->body);


            $message = CloudMessage::withTarget('token', $token)
                ->withNotification($notification);
                // ->withDefaultSounds();

                if(property_exists($data,'meta_data')){
                    $message = $message->withData($data->meta_data);
                }


            $messaging->send($message);
        } catch (\Exception $exception) {
            Log::error(json_encode($exception->getTrace()));
        }


// ...
```

### Error message/Stack trace

`{"file":"C:\\laragon\\www\\creamella-core\\vendor\\kreait\\firebase-php\\src\\Firebase\\Messaging.php","line":58,"function":"becauseTokenNotFound","class":"Kreait\\Firebase\\Exception\\Messaging\\NotFound","type":"::","args":["eqQb9GthR-i6f4TxVBu7Sw:APA91bG8bLt1PGV2l3tThBMmUvLiUbp0d0lQDjdgr_Nppe-1aeUokoAkP733ScjMD3zF2QMg8SGH9mnwPweL5jARYirkk_q5O7lrO4CJdvp5ECCJks5hANrROA0RiGMBJ8mt32PZfS9Z"]},`

**Comment by jeromegamez** [comment]
The registration token/device token (the message target) you're using is valid, but could not be found within the project in which you're using it = the token belongs to another Firebase project.

This usually happens when you register the token on a device that uses project A, but your server uses project B, this can be the case when you work with different app environments (e.g. dev, qa, staging, prod) - so, if your PHP environment is running with dev, you can't send a message to a device that is running with prod.

I hope this helps! 🤞

**Comment by anassrakibi** [comment]
Hey I'm getting the same exception, but this is my setup. 
on Firebase I have 2 projects (ios & android). On each of these apps I collect the device token and send it to a 3 project (api built in PHP), where I store it in the DB. Then from this Api, I trigger the push notification. For the API I'm using the firebase SDK based on the keys I generate in the firebase
