### ISSUE TITLE
Add Github & OTP Signin

### ISSUE THREAD

**Issue by imselmon** [kreait/firebase-php#666]
### Describe the feature you would like to see

Add Signinwithgithub feature and Signin with OTP Method

**Comment by jeromegamez** [comment]
This is already possible, please see ["Sign In with IdP credentials"](https://firebase-php.readthedocs.io/en/stable/authentication.html#sign-in-with-idp-credentials) to get started. The provider you'll need is named `github.com` (see the [list of supported providers](https://firebase.google.com/docs/projects/provisioning/configure-oauth#add-idp) in the official Google docs).

It is not possible to sign in as a user to GitHub through Firebase. The user must first sign in to GitHub (with or without a One-Time-Password), and you can then use OAuth Token returned from GitHub to sign the same user into your Firebase app.
