### ISSUE TITLE
passwordHash not working

### ISSUE THREAD

**Issue by desmeit** [kreait/firebase-php#670]
### Describe the issue you are experiencing

I try to import a user from wordpress to Firebase Auth:

```
$userProperties = [
	'uid' => $current_user->ID,
    'email' => $current_user->user_email,
    'emailVerified' => true,
    //'phoneNumber' => '+15555550100',
    'passwordHash' => 'dGV4dA==',
	//'passwordSalt' => $salt,
    'displayName' => $current_user->user_login,
    //'photoUrl' => 'http://www.example.com/12345678/photo.png',
	//'metadata' => [
//        'createdAt' => $user_registered,
//		//'lastLoginAt' => $date,
//		//'passwordUpdatedAt' => $date,
//        //lastRefreshAt' => $date
//    ],
    'disabled' => false,
	'hash' => array('algorithm' => 'MD5', 'rounds' => 8192),
];
```

```
The output is:
object(Kreait\Firebase\Auth\UserRecord)[6494]
  public 'uid' => string '323' (length=4)
  public 'email' => string 'info@test.de' (length=17)
  public 'emailVerified' => boolean true
  public 'displayName' => string 'info@test.de' (length=17)
  public 'photoUrl' => null
  public 'phoneNumber' => null
  public 'disabled' => boolean false
  public 'metadata' => 
    object(Kreait\Firebase\Auth\UserMetaData)[6470]
      public 'createdAt' => 
        object(DateTimeImmutable)[6440]
          public 'date' => string '2021-11-19 13:07:18.048000' (length=26)
          public 'timezone_type' => int 3
          public 'timezone' => string 'UTC' (length=3)
      public 'lastLoginAt' => null
      public 'passwordUpdatedAt' => null
      public 'lastRefreshAt' => null
  public 'providerData' => 
    array (size=0)
      empty
  public 'passwordHash' => null
  public 'passwordSalt' => null
  public 'customClaims' => 
    array (size=0)
      empty
  public 'tokensValidAfterTime' => 
    object(DateTimeImmutable)[6490]
      public 'date' => string '2021-11-19 13:07:18.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'UTC' (length=3)
  public 'tenantId' => null
```

passwordHash and passwordSalt is null. How is the right way to add hash passwords? 

### Installed packages

{
    "require": {
        "kreait/firebase-php": "^5.19",
        "google/cloud-firestore": "^1.20",
        "grpc/grpc": "^1.39"
    }
}

### PHP version and extensions

PHP 7.2.34

### On which operating system(s) does the issue occur?

- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Steps to reproduce the issue.

1. ...
2. ...
3. ...

```php
use Kreait\Firebase;

$factory = (new Firebase\Factory())
    ->withServiceAccount('/path/to/firebase_credentials.com')
    ->withDatabaseUri('https://my-project.firebaseio.com')
;

// ...
```

### Error message/Stack trace

passwordHash is null

**Comment by jeromegamez** [comment]
Importing users is not supported by this SDK, please use the Firebase CLI for this (https://firebase.google.com/docs/cli/auth)

You can read more about why this isn't yet available in the PHP SDK at https://github.com/kreait/firebase-php/pull/440#issuecomment-797396703 and https://github.com/kreait/firebase-php/pull/650#issuecomment-905960893

**Comment by desmeit** [comment]
Okay, but I'm able to import users, but only without PasswordHash.
What do you mean by "importing users"? The user itself is imported but without the correct password.

**Comment by jeromegamez** [comment]
The API to create users is different than the one to import users. The API to create users only accepts clear text passwords, not password hashes and salts.

**Comment by desmeit** [comment]
Okay thanks
