### ISSUE TITLE
Syntax error vendor/psr/cache/src/CacheItemInterface.php:104

### ISSUE THREAD

**Issue by filipponicchi** [kreait/firebase-php#675]
### Describe the issue you are experiencing

Hi,
when I try to send a message with send function it doesn't work and in php error log I receive this error:

PHP Fatal error:  Uncaught ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in .../vendor/psr/cache/src/CacheItemInterface.php:104
Stack trace:
......

Someone can help me to solve it?
Thanks!

### Installed packages

I have installed firebase-php without composer.

### PHP version and extensions

php 7.4.3

### On which operating system(s) does the issue occur?

- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Steps to reproduce the issue.

1. ...
2. ...
3. ...

```php
use Kreait\Firebase;

$factory = (new Firebase\Factory())
    ->withServiceAccount('/path/to/firebase_credentials.com')
    ->withDatabaseUri('https://my-project.firebaseio.com')
;

// ...
```

### Error message/Stack trace

PHP Fatal error:  Uncaught ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/html/intranet/unieventiREST/firebase-php/vendor/psr/cache/src/CacheItemInterface.php:104
Stack trace:
#0 /var/www/html/intranet/unieventiREST/firebase-php/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 /var/www/html/intranet/unieventiREST/firebase-php/vendor/google/auth/src/Cache/Item.php(25): spl_autoload_call()
#3 /var/www/html/intranet/unieventiREST/firebase-php/vendor/composer/ClassLoader.php(571): include('/var/www/html/i...')
#4 /var/www/html/intranet/unieventiREST/firebase-php/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#6 /var/www/html/intranet/unieventiREST/firebase-php/vendor/google/auth/src/Cache/MemoryCacheItemPool.php(54): spl_autoload_call()
#7 /var/www/html/intranet/unieventiREST/firebase-php/vendor/google/auth/src/Cache/MemoryCacheItemPool.php(43): Google\Auth\Cache\MemoryCacheItemPool->getItems()
#8 /var/www/html/intranet/unieventiREST/firebase-php/vendor/google/auth/src/CacheTrait.php(39): Google\Auth\Cache\MemoryCacheItemPool->getItem()
#9 /var/www/html/intranet/unieventiREST/firebase-php/vendor/google/auth/src/FetchAuthTokenCache.php(250): Google\Auth\FetchAuthTokenCache->getCachedValue()
#10 /var/www/html/intranet/unieventiREST/firebase-php/vendor/google/auth/src/FetchAuthTokenCache.php(80): Google\Auth\FetchAuthTokenCache->fetchAuthTokenFromCache()
#11 /var/www/html/intranet/unieventiREST/firebase-php/vendor/google/auth/src/Middleware/AuthTokenMiddleware.php(122): Google\Auth\FetchAuthTokenCache->fetchAuthToken()
#12 /var/www/html/intranet/unieventiREST/firebase-php/vendor/google/auth/src/Middleware/AuthTokenMiddleware.php(102): Google\Auth\Middleware\AuthTokenMiddleware->fetchToken()
#13 /var/www/html/intranet/unieventiREST/firebase-php/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): Google\Auth\Middleware\AuthTokenMiddleware->Google\Auth\Middleware\{closure}()
#14 /var/www/html/intranet/unieventiREST/firebase-php/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#15 /var/www/html/intranet/unieventiREST/firebase-php/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#16 /var/www/html/intranet/unieventiREST/firebase-php/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke()
#17 /var/www/html/intranet/unieventiREST/firebase-php/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#18 /var/www/html/intranet/unieventiREST/firebase-php/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke()
#19 /var/www/html/intranet/unieventiREST/firebase-php/vendor/guzzlehttp/guzzle/src/Client.php(107): GuzzleHttp\Client->transfer()
#20 /var/www/html/intranet/unieventiREST/firebase-php/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->sendAsync()
#21 /var/www/html/intranet/unieventiREST/firebase-php/vendor/kreait/firebase-php/src/Firebase/Messaging/ApiClient.php(42): GuzzleHttp\Client->send()
#22 /var/www/html/intranet/unieventiREST/firebase-php/vendor/kreait/firebase-php/src/Firebase/Messaging.php(54): Kreait\Firebase\Messaging\ApiClient->send()
#23 /var/www/html/intranet/admin/test-notification.php(29): Kreait\Firebase\Messaging->send()
#24 {main}

Next Kreait\Firebase\Exception\Messaging\MessagingError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/html/intranet/unieventiREST/firebase-php/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingApiExceptionConverter.php:56
Stack trace:
#0 /var/www/html/intranet/unieventiREST/firebase-php/vendor/kreait/firebase-php/src/Firebase/Messaging/ApiClient.php(44): Kreait\Firebase\Exception\MessagingApiExceptionConverter->convertException()
#1 /var/www/html/intranet/unieventiREST/firebase-php/vendor/kreait/firebase-php/src/Firebase/Messaging.php(54): Kreait\Firebase\Messaging\ApiClient->send()
#2 /var/www/html/intranet/admin/test-notification.php(29): Kreait\Firebase\Messaging->send()
#3 {main}
  thrown in /var/www/html/intranet/unieventiREST/firebase-php/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingApiExceptionConverter.php on line 56

**Comment by jeromegamez** [comment]
The error points at the `psr/cache` library (https://github.com/php-fig/cache/blob/aa5030cfa5405eccfdcb1083ce040c2cb8d253bf/src/CacheItemInterface.php#L104) in version 2.0/3.0

```php
public function expiresAfter(int|\DateInterval|null $time): static;
```

Since you are using PHP 7.4, you can only install `psr/cache` in the version 1.x (https://github.com/php-fig/cache/releases/tag/1.0.1).

> I have installed firebase-php without composer.

You are of course free to install the library as you wish, but please note that this is not a use case I support. Composer would have prevented the installation of an unsupported dependency 😅
