### ISSUE TITLE
Unauthorized request error when using Service Account

### ISSUE THREAD

**Issue by x1nixmzeng** [kreait/firebase-php#68]
Hello!

I am using this library for a PHP service worker which can read/write to a Firebase database.

I am using the `2.1.3` tree, and reading the service account key from JSON before trying to fetch data like so:

```php
<?
include_once '../vendor/autoload.php';

$firebase =  Firebase::fromServiceAccount(__DIR__.'/key.json');
$firebaseDb = $firebase->getDatabase();

$ref = $firebaseDb->getReference('test');
print $ref->getValue();
```

Which logs a warning in PHP:

> Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://XXX.firebaseio.com/test` resulted in a `401 Unauthorized` response:
>  {
> 	"error" : "Unauthorized request.
>  }
> 

I'm not sure where this error comes from! `Query.php` describes this error if the Firebase rules are set:

     * Append '.json' to the URL when typed into a browser to download JSON formatted data.
     * If the location is secured (not publicly readable) you will get a permission-denied error.

This documentation is correct if you visit the raw URL:

> {
>   "error" : "Permission denied"
> }

Any ideas?

**Comment by x1nixmzeng** [comment]
Is it that the request isn't sent with `.json` as part of the URL?

**Comment by jeromegamez** [comment]
There's a middleware that ensures that the `.json` is always appended to the requests, so this shouldn't be the issue.

Could you post the database rules that you have configured?

Another reason could be that the Service Account has not the required permissions to access the database at all - we had another dev with this issue in the Firebase Community Slack. Feel free to join us there (the link is in the readme), perhaps he can share some insights with you.

**Comment by x1nixmzeng** [comment]
I've given my Service Account full permissions for now, and the database rules are completely open; ie:

```{ ".read": true, ".write": true }```

I'm pretty sure the requests should be done using the .json URLs, which the logs are not showing.

However, in the 2.2.0 tagged release, the `fromServiceAccount` is now throwing a deprecated warning - maybe I'm using the wrong method for this?

**Comment by x1nixmzeng** [comment]
I've had some luck tweaking the account permissions. If I set the Service Account permissions to *Project Editor* it can now read open data!

I'll close this bug, the library is behaving as expected - although could perhaps catch this exception?

**Comment by jeromegamez** [comment]
Good news, thank you for the feedback!

**Comment by jeromegamez** [comment]
Unfortunately, the feedback from the Firebase REST API is not detailed enough to determine the cause of the permission error (yet), but I have an open feature request for that already (Debug Headers in API responses). So, at the moment, there's no way for the library to know if a service account has sufficient permissions.

Concerning the deprecation warnings: they're new, but the methods still work as previously - please check the 2.2.0 release notes or the changelog for the new recommended approach.

I like deprecation warnings: they trigger developers, but not live systems :)
