### ISSUE TITLE
google/auth 1.18 does not support  psr/cache ^3.0

### ISSUE THREAD

**Issue by therealsamsquanch** [kreait/firebase-php#680]
### Describe the issue you are experiencing

I tried to update my composer.json to require psr/cache 3.0. Version `6.0.0` of `firebase-php` says that `psr-cache ^3.0` is supported, but it appears that it is not supported by `google/auth 1.18`.

### Installed packages

aura/router                            3.1.0   Powerful, flexible web routing for PSR-7 requests.
aura/session                           2.1.0   Provides session management functionality, including lazy session st...
aura/sql                               4.0.0   A PDO extension that provides lazy connections, array quoting, query...
bacon/bacon-qr-code                    2.0.4   BaconQrCode is a QR code generator for PHP.
beste/clock                            1.0.0   A collection of Clock implementations
composer/ca-bundle                     1.3.1   Lets you find a path to the system CA bundle, and includes a fallbac...
dasprid/enum                           1.0.3   PHP 7.1 enum implementation
daveearley/daves-email-validation-tool 1.2.0   An easy to use, accurate-ish & extensible email validation library f...
embed/embed                            v4.4.0  PHP library to retrieve page info using oembed, opengraph, etc
endroid/qr-code                        4.4.7   Endroid QR Code
ezyang/htmlpurifier                    v4.14.0 Standards compliant HTML filter written in PHP
fig/http-message-util                  1.1.5   Utility classes and constants for use with PSR-7 (psr/http-message)
filp/whoops                            2.14.5  php error handling for cool kids
firebase/php-jwt                       v5.5.1  A simple library to encode and decode JSON Web Tokens (JWT) in PHP. ...
google/auth                            v1.18.0 Google Auth Library for PHP
google/cloud-core                      v1.43.1 Google Cloud PHP shared dependency, providing functionality useful t...
google/cloud-storage                   v1.25.2 Cloud Storage Client for PHP
google/crc32                           v0.1.0  Various CRC32 implementations
google/recaptcha                       1.2.4   Client library for reCAPTCHA, a free service that protects websites ...
guzzlehttp/guzzle                      7.4.1   Guzzle is a PHP HTTP client library
guzzlehttp/promises                    1.5.1   Guzzle promises library
guzzlehttp/psr7                        2.1.0   PSR-7 message implementation that also provides common utility methods
intervention/image                     2.7.1   Image handling and manipulation library with support for Laravel int...
jdenticon/jdenticon                    1.0.0   Render PNG and SVG identicons.
kreait/firebase-php                    6.0.0   Firebase Admin SDK
kreait/firebase-tokens                 2.0.1   A library to work with Firebase tokens
ksubileau/color-thief-php              v1.4.1  Grabs the dominant color or a representative color palette from an i...
laminas/laminas-diactoros              2.8.0   PSR HTTP Message implementations
lcobucci/clock                         2.1.0   Yet another clock abstraction
lcobucci/jwt                           4.1.5   A simple library to work with JSON Web Token and JSON Web Signature
matthiasmullie/minify                  1.3.66  CSS & JavaScript minifier, in PHP. Removes whitespace, strips commen...
matthiasmullie/path-converter          1.1.3   Relative path converter
mimmi20/browser-detector               7.0.1   Library to detect Browsers and Devices
mimmi20/browser-detector-version       7.0.7   Version Class for the Browser Detector
mimmi20/ios-build                      2.0.7   Class wrapper for peterkahl/apple-ios-build-version
mimmi20/macos-build                    2.0.7   Class wrapper for peterkahl/apple-os-x-build-version
mimmi20/ua-browser-type                8.0.5   a class collection for different browser types
mimmi20/ua-device-type                 8.0.5   a class collection for different device types
mimmi20/ua-generic-request             7.0.0   the Generic Request Object extracted from Wurfl for PHP 7.1+
mimmi20/ua-normalizer                  5.1.3   the Normalizers extracted from the UaNormalizer PHP Library for PHP 7+
mimmi20/ua-result                      8.0.6   Library for PHP 7.4+ to handle useragent parser results
ml/iri                                 1.1.4   IRI handling for PHP
ml/json-ld                             1.2.0   JSON-LD Processor for PHP
monolog/monolog                        2.3.5   Sends your logs to files, sockets, inboxes, databases and various we...
mtdowling/jmespath.php                 2.6.1   Declaratively specify how to extract elements from a JSON document
oscarotero/html-parser                 v0.1.6  Parse html strings to DOMDocument
phpfastcache/phpfastcache              9.0.1   PHP Abstract Cache Class - Reduce your database call using cache sys...
phpmailer/phpmailer                    v6.5.3  PHPMailer is a full-featured email creation and transfer class for PHP
psr/cache                              2.0.0   Common interface for caching libraries
psr/http-client                        1.0.1   Common interface for HTTP clients
psr/http-factory                       1.0.1   Common interfaces for PSR-7 HTTP message factories
psr/http-message                       1.0.1   Common interface for HTTP messages
psr/log                                1.1.4   Common interface for logging libraries
psr/simple-cache                       2.0.0   Common interfaces for simple caching
ralouphie/getallheaders                3.0.3   A polyfill for getallheaders.
respect/stringifier                    0.2.0   Converts any value to a string
respect/validation                     2.2.3   The most awesome validation engine ever created for PHP
riverline/multipart-parser             2.0.9   One class library to parse multipart content with encoding and chars...
rize/uri-template                      0.3.4   PHP URI Template (RFC 6570) supports both expansion & extraction
smarty/smarty                          v4.0.0  Smarty - the compiling PHP template engine
symfony/deprecation-contracts          v3.0.0  A generic function and convention to trigger deprecation notices
symfony/http-foundation                v6.0.2  Defines an object-oriented layer for the HTTP specification
symfony/polyfill-mbstring              v1.24.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php80                 v1.24.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP ver...
symfony/polyfill-php81                 v1.24.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP ver...

### PHP version and extensions

composer                   2.2.3     Composer package
composer-plugin-api        2.2.0     The Composer Plugin API
composer-runtime-api       2.2.2     The Composer Runtime API
ext-apcu                   5.1.21    The apcu PHP extension
ext-bz2                    8.0.14    The bz2 PHP extension
ext-calendar               8.0.14    The calendar PHP extension
ext-ctype                  8.0.14    The ctype PHP extension
ext-curl                   8.0.14    The curl PHP extension
ext-date                   8.0.14    The date PHP extension
ext-dom                    20031129  The dom PHP extension
ext-exif                   8.0.14    The exif PHP extension
ext-ffi                    8.0.14    The FFI PHP extension
ext-fileinfo               8.0.14    The fileinfo PHP extension
ext-filter                 8.0.14    The filter PHP extension
ext-ftp                    8.0.14    The ftp PHP extension
ext-gd                     8.0.14    The gd PHP extension
ext-gettext                8.0.14    The gettext PHP extension
ext-hash                   8.0.14    The hash PHP extension
ext-iconv                  8.0.14    The iconv PHP extension
ext-igbinary               3.2.6     The igbinary PHP extension
ext-imagick                3.5.1     The imagick PHP extension
ext-imap                   8.0.14    The imap PHP extension
ext-intl                   8.0.14    The intl PHP extension
ext-json                   8.0.14    The json PHP extension
ext-libxml                 8.0.14    The libxml PHP extension
ext-mailparse              3.1.2     The mailparse PHP extension
ext-mbstring               8.0.14    The mbstring PHP extension
ext-mcrypt                 1.0.4     The mcrypt PHP extension
ext-memcached              3.1.5     The memcached PHP extension
ext-msgpack                2.1.2     The msgpack PHP extension
ext-mysqli                 8.0.14    The mysqli PHP extension
ext-mysqlnd                0         The mysqlnd PHP extension (actual version: mysqlnd 8.0.14)
ext-oauth                  2.0.7     The OAuth PHP extension
ext-openssl                8.0.14    The openssl PHP extension
ext-pcntl                  8.0.14    The pcntl PHP extension
ext-pcre                   8.0.14    The pcre PHP extension
ext-pdo                    8.0.14    The PDO PHP extension
ext-pdo_mysql              8.0.14    The pdo_mysql PHP extension
ext-pdo_sqlite             8.0.14    The pdo_sqlite PHP extension
ext-phar                   8.0.14    The Phar PHP extension
ext-posix                  8.0.14    The posix PHP extension
ext-pspell                 8.0.14    The pspell PHP extension
ext-psr                    1.1.0     The psr PHP extension
ext-readline               8.0.14    The readline PHP extension
ext-redis                  5.3.4     The redis PHP extension
ext-reflection             8.0.14    The Reflection PHP extension
ext-session                8.0.14    The session PHP extension
ext-shmop                  8.0.14    The shmop PHP extension
ext-simplexml              8.0.14    The SimpleXML PHP extension
ext-sockets                8.0.14    The sockets PHP extension
ext-sodium                 8.0.14    The sodium PHP extension
ext-spl                    8.0.14    The SPL PHP extension
ext-sqlite3                8.0.14    The sqlite3 PHP extension
ext-sysvmsg                8.0.14    The sysvmsg PHP extension
ext-sysvsem                8.0.14    The sysvsem PHP extension
ext-sysvshm                8.0.14    The sysvshm PHP extension
ext-tidy                   8.0.14    The tidy PHP extension
ext-tokenizer              8.0.14    The tokenizer PHP extension
ext-uuid                   1.2.0     The uuid PHP extension
ext-xdebug                 3.1.1     The xdebug PHP extension
ext-xml                    8.0.14    The xml PHP extension
ext-xmlreader              8.0.14    The xmlreader PHP extension
ext-xmlwriter              8.0.14    The xmlwriter PHP extension
ext-xsl                    8.0.14    The xsl PHP extension
ext-zend-opcache           8.0.14    The Zend OPcache PHP extension
ext-zip                    1.19.5    The zip PHP extension
ext-zlib                   8.0.14    The zlib PHP extension
lib-bz2                    1.0.8     The bz2 library
lib-curl                   7.68.0    The curl library
lib-curl-libssh            0.9.3     curl libssh version
lib-curl-openssl           1.1.1.6   curl OpenSSL version (1.1.1.6)
lib-curl-zlib              1.2.11    curl zlib version
lib-date-timelib           2020.03   date timelib version
lib-date-zoneinfo          0         zoneinfo ("Olson") database for date
lib-fileinfo-libmagic      539       fileinfo libmagic version
lib-gd                     2.3.0     The gd library
lib-iconv                  2.31      The iconv library
lib-icu                    66.1      The ICU unicode and globalization support library
lib-icu-cldr               36.1      ICU CLDR project version
lib-icu-unicode            13.0.0    ICU unicode version
lib-imagick-imagemagick    6.9.10.23 The imagick-imagemagick library
lib-libsodium              1.0.18    The libsodium library
lib-libxml                 2.9.12    libxml library version
lib-libxslt                1.1.34    The libxslt library
lib-libxslt-libxml         2.9.10    libxml version libxslt is compiled against
lib-mbstring-libmbfl       1.3.2     mbstring libmbfl version
lib-mbstring-oniguruma     6.9.4     mbstring oniguruma version
lib-memcached-libmemcached 1.0.18    libmemcached version
lib-openssl                1.1.1.6   OpenSSL 1.1.1f  31 Mar 2020
lib-pcre                   10.39     The pcre library
lib-pcre-unicode           14.0.0    PCRE Unicode version support
lib-pdo_sqlite-sqlite      3.31.1    The pdo_sqlite-sqlite library
lib-sqlite3-sqlite         3.31.1    The sqlite3-sqlite library
lib-zip-libzip             1.7.3     The zip-libzip library
lib-zlib                   1.2.11    The zlib library
php                        8.0.14    The PHP interpreter
php-64bit                  8.0.14    The PHP interpreter, 64bit
php-ipv6                   8.0.14    The PHP interpreter, with IPv6 support

### On which operating system(s) does the issue occur?

- [X] Linux
- [ ] MacOS
- [ ] Windows

### Steps to reproduce the issue.

Configure composer.json to require psr-cache ^3.0 and try to update

### Error message/Stack trace

`- google/auth v1.18.0 requires psr/cache ^1.0|^2.0 -> found psr/cache[1.0.0, 1.0.1, 2.0.0] but it conflicts with your root composer.json require (^3.0).
    - kreait/firebase-php 6.0.0 requires google/auth ^1.18 -> satisfiable by google/auth[v1.18.0].`

**Comment by jeromegamez** [comment]
`google/auth` is not maintained by me, but the maintainers of the library are aware of it, you can follow the status of their implementation by keeping an eye on one of the issues/PRs on https://github.com/googleapis/google-auth-library-php/issues?q=psr+cache

`^3.0` is included in the `require` section of this SDK because it doesn't **not** support it 😅 and to not block projects from using it once all dependencies support it as well.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/67554/148696095-73fc7fb6-91b1-43e4-8f43-960748d6db1a.png">

Since this is nothing I can fix in the SDK, I'm closing the issue, but thank you for raising it!
