### ISSUE TITLE
create and manage tropics

### ISSUE THREAD

**Issue by alissonrodrigo** [kreait/firebase-php#681]
### Describe the feature you would like to see

In the documentation I didn't see functions to be able to create or remove tropics to send messages to them, is it possible?

Grateful

**Comment by jeromegamez** [comment]
Firebase message topics cannot be created on their own - they start to exist as soon as one device is subscribed to them and stop existing when no device is subscribed.

I answered the question with a little more detail here: https://stackoverflow.com/a/62645130/284325

**Comment by alissonrodrigo** [comment]
so this management is done by firebase I can ask to register a token in a tropic that doesn't exist yet firebase will create it

**Comment by jeromegamez** [comment]
Yes, exactly! https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#topic-management

**Comment by alissonrodrigo** [comment]
Thank you for your patience and feedback. I haven't read all the firebase documentation.

**Comment by jeromegamez** [comment]
You're welcome!
