### ISSUE TITLE
token verification

### ISSUE THREAD

**Issue by alissonrodrigo** [kreait/firebase-php#684]
### Describe the feature you would like to see

To avoid returning an invalid token, I need to check it, but I don't know how the array of this token is formed. Would you help me? Grateful

	function ValidaToken($Token){
		$tokens = ['eQbb6IpuR8k:APA91bFWUhhkaZjnmxo9WolwRrI6SfiDRc-9pZwulB9B1XSH0uJhbR7QqZyhqB7TKkOwLx9aovICqd0av9Rh-9zJ1dBuSxy1TOdp5avQ3tZPo0q_wHQ9hw356tK7okVQwCgQeMU2v8th'];
		return $messaging->validateRegistrationTokens($tokens);	
	}

as you can see I test one token at a time, how do I form this array correctly. Grateful

**Comment by jeromegamez** [comment]
This looks right, but I notice that you use `$messaging` without declaring it first. Are you in the context of a class and meant to use `$this->messaging`?

Please refer to https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#validating-registration-tokens to know what you can expect this method to return.

FYI, feature requests are meant to be used for features the SDK **doesn't** already have 😅  When you created this issue, you were given multiple options on how to get support. "How to use" questions are best suited for the Community Discord Server 🙏
