### ISSUE TITLE
Unable to connect to the API: cURL error 6: Could not resolve host: oauth2.googleapis.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://oauth2.goog leapis.com/token

### ISSUE THREAD

**Issue by darshan9093** [kreait/firebase-php#689]
### Describe the issue you are experiencing

I am receiving this error while registration login everywhere firebase used.

Unable to connect to the API: cURL error 6: Could not resolve host: oauth2.googleapis.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://oauth2.googleapis.com/token

Firebase was working fine last week.

### Installed packages

No extra package installed

### PHP version and extensions

PHP Version: 7.3.33

### On which operating system(s) does the issue occur?

- [ ] Linux
- [ ] MacOS
- [X] Windows

### Error message/Stack trace

Unable to connect to the API: cURL error 6: Could not resolve host: oauth2.googleapis.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://oauth2.goog
leapis.com/token

**Comment by jeromegamez** [comment]
Connection problems are unfortunately not something the SDK can solve. This could be a DNS problem, perhaps you're behind a proxy, or it could have another reason, but it's most likely not one within the SDK. My first suggestion would be to try from another computer/server at another physical location.

Perhaps one of the many other questions and their comments can give you more ideas: https://github.com/kreait/firebase-php/issues?q=curl

Also have a look at https://firebase-php.readthedocs.io/en/stable/troubleshooting.html#curl-error-xx, just to be sure.

**Comment by darshan9093** [comment]
I have installed the same package on another laptop but got the same error.

This may not SDK can solve but any guidance to resolve this?

**Comment by jeromegamez** [comment]
You could try changing the DNS settings on your computer, 8.8.8.8/8.8.4.4 ([Google's Public DNS servers](https://developers.google.com/speed/public-dns)) would be my suggestion - if they can't resolve their own services, who else would 😅. It's most likely a networking problem, so the laptop you're using wouldn't make a difference if they both are at the same location.

Try if `ping oauth2.googleapis.com` works, if it doesn't, it's a networking problem. If it does work, but not within the SDK, it could have something to do with the PHP curl extension. In that case you should try updating cURL to a current version.

**Comment by darshan9093** [comment]
Hi Jeromegamez,

I have tried with DNS settings but no luck. I tried with Xampp also but no joy. Then I have tried with mobile internet and it is working as expected then again I connected with Wifi and not worked in Wifi. 

I have no idea why is it working with mobile data? Any thoughts from your end?

**Comment by jeromegamez** [comment]
I'm sorry, but I can't fix your WiFi, I hope you can understand 😅🙏
