### ISSUE TITLE
Does this package support Firebase Auth emulator?

### ISSUE THREAD

**Issue by andrewhamili** [kreait/firebase-php#691]
### Describe the feature you would like to see

![image](https://user-images.githubusercontent.com/20767537/156122963-2b211c38-34ea-40af-9023-9373be9201b0.png)

We are currently struggling to use Firebase Auth on UAT environments specifically when testing a scenario that involves using a new user account.

**Comment by jeromegamez** [comment]
It's in the works, but it needs a substantial overhaul and I haven't got the resources lately to continue working on it.

If you or your business want to support development of this feature, please consider sponsoring the project.

In the meantime, a common practice is to create a new Firebase project specifically for integration tests - that's what I do for the integration tests of the SDK at the moment, you can look into the integration testsuite of this project to see how it's done.

**Comment by jeromegamez** [comment]
Two answer your initial question - of course, the SDK supports the Auth Simulator 😇

Jokes aside, I just released a new version (https://github.com/kreait/firebase-php/releases/tag/6.3.0) supporting it 🥳
