### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\uri_for()

### ISSUE THREAD

**Issue by djurovicigoor** [kreait/firebase-php#694]
### Describe the issue you are experiencing

Get Call to undefined function GuzzleHttp\Psr7\uri_for() when trying to use Firebase web push notification

### Installed packages

alymosul/exponent-server-sdk-php             1.3.0              Server-side library for working with Expo push notifications using PHP
alymosul/laravel-exponent-push-notifications v2.4.0             Exponent push notifications driver for laravel
asm89/stack-cors                             v2.1.1             Cross-origin resource sharing library and stack middleware
aws/aws-crt-php                              v1.0.2             AWS Common Runtime for PHP
aws/aws-sdk-php                              3.215.1            AWS SDK for PHP - Use Amazon Web Services in your PHP project
barryvdh/laravel-ide-helper                  v2.12.3            Laravel IDE Helper, generates correct PHPDocs for all Facade classes, to improve auto-completion.
barryvdh/laravel-snappy                      v0.4.8             Snappy PDF/Image for Laravel
barryvdh/reflection-docblock                 v2.0.6            
beyondcode/laravel-dump-server               1.8.0              Symfony Var-Dump Server for Laravel
beyondcode/laravel-websockets                1.13.1             An easy to use WebSocket server
brick/math                                   0.9.3              Arbitrary-precision arithmetic library
cboden/ratchet                               v0.4.4             PHP WebSocket library
coconutcraig/laravel-postmark                v2.11.2            Laravel package for sending mail via the Postmark API
composer/pcre                                3.0.0              PCRE wrapping library that offers type-safe preg_* replacements.
cybercog/laravel-ban                         4.7.0              Laravel Ban simplify blocking and banning Eloquent models.
dflydev/dot-access-data                      v3.0.1             Given a deep data structure, access data by dot notation.
djurovicigoor/lara-files                     v1.3.1             Lara-files is a package which will make it easier to work with files. Package has built-in support for DigitalOcean spaces and Amazon S3.
djurovicigoor/larajsonresponse               v1.0.4             Laravel API wrapper for returning JSON response.
doctrine/cache                               2.1.1              PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/dbal                                3.3.3              Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/deprecations                        v0.5.3             A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for packages.
doctrine/event-manager                       1.1.1              The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                           2.0.4              PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator                        1.4.1              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                               1.2.3              PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
dompdf/dompdf                                v1.2.0             DOMPDF is a CSS 2.1 compliant HTML to PDF converter
dragonmantank/cron-expression                v3.3.1             CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
egulias/email-validator                      2.1.25             A library for validating emails against several RFCs
eklundkristoffer/seedster                    4.0               
evenement/evenement                          v3.0.1             Événement is a very simple event dispatching library for PHP
ezyang/htmlpurifier                          v4.14.0            Standards compliant HTML filter written in PHP
facade/flare-client-php                      1.9.1              Send PHP errors to Flare
facade/ignition                              2.17.5             A beautiful error page for Laravel applications.
facade/ignition-contracts                    1.0.2              Solution contracts for Ignition
fakerphp/faker                               v1.19.0            Faker is a PHP library that generates fake data for you.
fideloper/proxy                              4.4.1              Set trusted proxies for Laravel
fig/http-message-util                        1.1.5              Utility classes and constants for use with PSR-7 (psr/http-message)
filp/whoops                                  2.14.5             php error handling for cool kids
firebase/php-jwt                             v5.5.1             A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
fruitcake/laravel-cors                       v2.2.0             Adds CORS (Cross-Origin Resource Sharing) headers support in your Laravel application
giggsey/libphonenumber-for-php               8.12.45            PHP Port of Google's libphonenumber
giggsey/locale                               2.1                Locale functions required by libphonenumber-for-php
google/auth                                  v1.18.0            Google Auth Library for PHP
google/cloud-core                            v1.44.0            Google Cloud PHP shared dependency, providing functionality useful to all components.
google/cloud-storage                         v1.26.1            Cloud Storage Client for PHP
google/crc32                                 v0.1.0             Various CRC32 implementations
graham-campbell/result-type                  v1.0.4             An Implementation Of The Result Type
guzzlehttp/guzzle                            7.4.2              Guzzle is a PHP HTTP client library
guzzlehttp/promises                          1.5.1              Guzzle promises library
guzzlehttp/psr7                              2.2.1              PSR-7 message implementation that also provides common utility methods
h-farm/laravel-searchable                    1.0.0              Laravel Searchable
hamcrest/hamcrest-php                        v2.0.1             This is the PHP port of Hamcrest Matchers
hubspot/hubspot-php                          3.2.1              HubSpot PHP API client
imanghafoori/laravel-anypass                 dev-master 6bfda4c A minimal yet powerful package to help you in development.
imanghafoori/laravel-masterpass              v2.0.10            A minimal yet powerful package to help you easily impersonate your users.
intervention/image                           2.7.1              Image handling and manipulation library with support for Laravel integration
jeremykenedy/laravel-roles                   v5.1.0             A Powerful package for handling roles and permissions in Laravel. Supports Laravel 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 6.0, and 7.0.
josiasmontag/laravel-recaptchav3             0.6.0              Recaptcha V3 for Laravel package
knplabs/knp-snappy                           v1.4.1             PHP library allowing thumbnail, snapshot or PDF generation from a url or a html page. Wrapper for wkhtmltopdf/wkhtmltoimage.
kreait/clock                                 1.1.0              A PHP 7.0 compatible clock abstraction
kreait/firebase-php                          5.9.0              Firebase Admin SDK
kreait/firebase-tokens                       1.11.0             A library to work with Firebase tokens
kreait/laravel-firebase                      2.4.0              A Laravel package for the Firebase PHP Admin SDK
laracasts/flash                              3.2.1              Easy flash notifications
laravel-notification-channels/fcm            2.4.0              FCM (Firebase Cloud Messaging) Notifications Driver for Laravel
laravel/cashier                              v12.17.0           Laravel Cashier provides an expressive, fluent interface to Stripe's subscription billing services.
laravel/framework                            v8.83.5            The Laravel Framework.
laravel/helpers                              v1.5.0             Provides backwards compatibility for helpers in the latest Laravel release.
laravel/serializable-closure                 v1.1.1             Laravel Serializable Closure provides an easy and secure way to serialize closures in PHP.
laravel/slack-notification-channel           v2.4.0             Slack Notification Channel for laravel.
laravel/socialite                            v5.2.2             Laravel wrapper around OAuth 1 & OAuth 2 libraries.
laravel/telescope                            v4.8.0             An elegant debug assistant for the Laravel framework.
laravel/tinker                               v2.7.1             Powerful REPL for the Laravel framework.
laravel/ui                                   v3.4.5             Laravel UI utilities and presets.
laravolt/avatar                              4.1.6              Turn name, email, and any other string into initial-based avatar or gravatar.
lcobucci/jwt                                 3.3.3              A simple library to work with JSON Web Token and JSON Web Signature
league/commonmark                            2.2.3              Highly-extensible PHP Markdown parser which fully supports the CommonMark spec and GitHub-Flavored Markdown (GFM)
league/config                                v1.1.1             Define configuration arrays with strict schemas and access values with dot notation
league/flysystem                             1.1.9              Filesystem abstraction: Many filesystems, one API.
league/flysystem-aws-s3-v3                   1.0.29             Flysystem adapter for the AWS S3 SDK v3.x
league/mime-type-detection                   1.9.0              Mime-type detection for Flysystem
league/oauth1-client                         v1.10.0            OAuth 1.0 Client Library
maatwebsite/excel                            3.1.37             Supercharged Excel exports and imports in Laravel
maennchen/zipstream-php                      2.1.0              ZipStream is a library for dynamically streaming dynamic zip files from PHP without writing to the disk at all on the server.
markbaker/complex                            3.0.1              PHP Class for working with complex numbers
markbaker/matrix                             3.0.0              PHP Class for working with matrices
mockery/mockery                              1.5.0              Mockery is a simple yet flexible PHP mock object framework
moneyphp/money                               v3.3.1             PHP implementation of Fowler's Money pattern
monolog/monolog                              2.4.0              Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/jmespath.php                       2.6.1              Declaratively specify how to extract elements from a JSON document
myclabs/deep-copy                            1.11.0             Create deep copies (clones) of your objects
myclabs/php-enum                             1.8.3              PHP Enum implementation
namshi/jose                                  7.2.3              JSON Object Signing and Encryption library for PHP.
nesbot/carbon                                2.57.0             An API extension for DateTime that supports 281 different languages.
nette/schema                                 v1.2.2             📐 Nette Schema: validating data structures against a given Schema.
nette/utils                                  v3.2.7             🛠  Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON encoding/decoding, validation, slug or strong password generati...
nikic/php-parser                             v4.13.2            A PHP parser written in PHP
nunomaduro/collision                         v5.11.0            Cli error handling for console/command-line PHP applications.
opis/closure                                 3.6.3              A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
orangehill/iseed                             v2.6.4             Generate a new Laravel database seed file based on data from the existing database table.
paragonie/random_compat                      v9.99.100          PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
paragonie/sodium_compat                      v1.17.0            Pure PHP implementation of libsodium; uses the PHP extension if it exists
phar-io/manifest                             2.0.3              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                              3.2.1              Library for handling version information and constraints
phenx/php-font-lib                           0.5.4              A library to read, parse, export and make subsets of different types of font files.
phenx/php-svg-lib                            0.4.1              A library to read, parse and export to PDF SVG files.
phpdocumentor/reflection-common              2.2.0              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock            5.3.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver                  1.6.0              A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoffice/phpspreadsheet                     1.22.0             PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpoption/phpoption                          1.8.1              Option Type for PHP
phpspec/prophecy                             v1.15.0            Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                    9.2.15             Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                    3.0.6              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                          3.1.1              Invoke callables with a timeout
phpunit/php-text-template                    2.0.4              Simple template engine.
phpunit/php-timer                            5.0.3              Utility class for timing
phpunit/phpunit                              9.5.19             The PHP Unit Testing framework.
predis/predis                                v1.1.10            Flexible and feature-complete Redis client for PHP and HHVM
psr/cache                                    1.0.1              Common interface for caching libraries
psr/container                                1.1.2              Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                         1.0.0              Standard interfaces for event handling.
psr/http-client                              1.0.1              Common interface for HTTP clients
psr/http-factory                             1.0.1              Common interfaces for PSR-7 HTTP message factories
psr/http-message                             1.0.1              Common interface for HTTP messages
psr/log                                      1.1.4              Common interface for logging libraries
psr/simple-cache                             1.0.1              Common interfaces for simple caching
psy/psysh                                    v0.11.2            An interactive shell for modern PHP.
pusher/pusher-php-server                     v3.4.1             Library for interacting with the Pusher REST API
ralouphie/getallheaders                      3.0.3              A polyfill for getallheaders.
ramsey/collection                            1.2.2              A PHP library for representing and manipulating collections.
ramsey/uuid                                  4.2.3              A PHP library for generating and working with universally unique identifiers (UUIDs).
rap2hpoutre/laravel-log-viewer               v1.7.0             A Laravel log reader
ratchet/rfc6455                              v0.3.1             RFC6455 WebSocket protocol handler
react/cache                                  v1.1.1             Async, Promise-based cache interface for ReactPHP
react/dns                                    v1.9.0             Async DNS resolver for ReactPHP
react/event-loop                             v1.3.0             ReactPHP's core reactor event loop that libraries can use for evented I/O.
react/http                                   v1.6.0             Event-driven, streaming HTTP client and server implementation for ReactPHP
react/promise                                v2.9.0             A lightweight implementation of CommonJS Promises/A for PHP
react/promise-stream                         v1.3.0             The missing link between Promise-land and Stream-land for ReactPHP
react/promise-timer                          v1.8.0             A trivial implementation of timeouts for Promises, built on top of ReactPHP.
react/socket                                 v1.11.0            Async, streaming plaintext TCP/IP and secure TLS socket server and client connections for ReactPHP
react/stream                                 v1.2.0             Event-driven readable and writable streams for non-blocking I/O in ReactPHP
ringcentral/psr7                             1.3.0              PSR-7 message implementation
riverline/multipart-parser                   2.0.9              One class library to parse multipart content with encoding and charset support.
rize/uri-template                            0.3.4              PHP URI Template (RFC 6570) supports both expansion & extraction
sabberworm/php-css-parser                    8.4.0              Parser for CSS Files written in PHP
sebastian/cli-parser                         1.0.1              Library for parsing CLI options
sebastian/code-unit                          1.0.8              Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup           2.0.3              Looks up which function or method a line of code belongs to
sebastian/comparator                         4.0.6              Provides the functionality to compare PHP values for equality
sebastian/complexity                         2.0.2              Library for calculating the complexity of PHP code units
sebastian/diff                               4.0.4              Diff implementation
sebastian/environment                        5.1.3              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                           4.0.4              Provides the functionality to export PHP variables for visualization
sebastian/global-state                       5.0.5              Snapshotting of global state
sebastian/lines-of-code                      1.0.3              Library for counting the lines of code in PHP source code
sebastian/object-enumerator                  4.0.4              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector                   2.0.4              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context                  4.0.4              Provides functionality to recursively process PHP variables
sebastian/resource-operations                3.0.3              Provides a list of PHP built-in functions that operate on resources
sebastian/type                               3.0.0              Collection of value objects that represent the types of the PHP type system
sebastian/version                            3.0.2              Library that helps with managing the version number of Git-hosted PHP projects
sendinblue/api-v3-sdk                        v7.4.5             Official SendinBlue provided RESTFul API V3 php library
spatie/db-dumper                             2.21.1             Dump databases
spatie/enum                                  3.12.0             PHP Enums
spatie/laravel-backup                        6.16.5             A Laravel package to backup your application
spatie/laravel-package-tools                 1.11.3             Tools for creating Laravel packages
spatie/laravel-stripe-webhooks               2.6.2              Handle stripe webhooks in a Laravel application
spatie/laravel-webhook-client                2.7.5              Receive webhooks in Laravel apps
spatie/temporary-directory                   1.3.0              Easily create, use and destroy temporary directories
stripe/stripe-php                            v7.117.0           Stripe PHP Library
swiftmailer/swiftmailer                      v6.3.0             Swiftmailer, free feature-rich PHP mailer
symfony/console                              v5.4.5             Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                         v6.0.3             Converts CSS selectors to XPath expressions
symfony/deprecation-contracts                v3.0.0             A generic function and convention to trigger deprecation notices
symfony/error-handler                        v5.4.3             Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher                     v6.0.3             Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts           v3.0.0             Generic abstractions related to dispatching event
symfony/finder                               v5.4.3             Finds files and directories via an intuitive fluent interface
symfony/http-foundation                      v5.4.6             Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                          v5.4.6             Provides a structured process for converting a Request into a Response
symfony/mime                                 v5.4.3             Allows manipulating MIME messages
symfony/polyfill-ctype                       v1.25.0            Symfony polyfill for ctype functions
symfony/polyfill-iconv                       v1.25.0            Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme               v1.25.0            Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu                    v1.25.0            Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn                    v1.25.0            Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer             v1.25.0            Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                    v1.25.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                       v1.20.0            Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php72                       v1.25.0            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                       v1.25.0            Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                       v1.25.0            Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81                       v1.25.0            Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                              v5.4.5             Executes commands in sub-processes
symfony/psr-http-message-bridge              v2.1.2             PSR HTTP message bridge
symfony/routing                              v5.4.3             Maps an HTTP request to a set of configuration variables
symfony/service-contracts                    v2.4.1             Generic abstractions related to writing services
symfony/string                               v6.0.3             Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                          v6.0.6             Provides tools to internationalize your application
symfony/translation-contracts                v3.0.0             Generic abstractions related to translation
symfony/var-dumper                           v5.4.6             Provides mechanisms for walking through any arbitrary PHP variable
theseer/tokenizer                            1.2.1              A small library for converting tokenized PHP source code into XML and potentially other formats
tijsverkoyen/css-to-inline-styles            2.2.4              CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very useful when you're sending emails.
torann/currency                              1.1.1              This provides Laravel with currency functions such as currency formatting and conversion using up-to-date exchange rates.
tymon/jwt-auth                               1.0.2              JSON Web Token Authentication for Laravel and Lumen
vansteen/laravel-sendinblue                  v1.4               A Laravel 5/6/7/8 service provider, facade and config file for the SendinBlue's API v3 official PHP library.
vlucas/phpdotenv                             v5.4.1             Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
voku/portable-ascii                          1.6.1              Portable ASCII library - performance optimized (ascii) string functions for php.
webmozart/assert                             1.10.0             Assertions to validate method input/output with nice error messages.
zanysoft/laravel-zip                         dev-master 86028aa laravel-zip is the world's leading zip utility for file compression and backup.

### PHP version and extensions

composer-plugin-api     2.0.0     The Composer Plugin API
composer-runtime-api    2.0.0     The Composer Runtime API
ext-calendar            8.0.16    The calendar PHP extension
ext-ctype               8.0.16    The ctype PHP extension
ext-curl                8.0.16    The curl PHP extension
ext-date                8.0.16    The date PHP extension
ext-dom                 20031129  The dom PHP extension
ext-exif                8.0.16    The exif PHP extension
ext-ffi                 8.0.16    The FFI PHP extension
ext-fileinfo            8.0.16    The fileinfo PHP extension
ext-filter              8.0.16    The filter PHP extension
ext-ftp                 8.0.16    The ftp PHP extension
ext-gd                  8.0.16    The gd PHP extension
ext-gettext             8.0.16    The gettext PHP extension
ext-hash                8.0.16    The hash PHP extension
ext-iconv               8.0.16    The iconv PHP extension
ext-igbinary            3.2.6     The igbinary PHP extension
ext-imagick             3.6.0     The imagick PHP extension
ext-intl                8.0.16    The intl PHP extension
ext-json                8.0.16    The json PHP extension
ext-libxml              8.0.16    The libxml PHP extension
ext-mbstring            8.0.16    The mbstring PHP extension
ext-msgpack             2.1.2     The msgpack PHP extension
ext-mysqli              8.0.16    The mysqli PHP extension
ext-mysqlnd             0         The mysqlnd PHP extension (actual version: mysqlnd 8.0.16)
ext-openssl             8.0.16    The openssl PHP extension
ext-pcntl               8.0.16    The pcntl PHP extension
ext-pcre                8.0.16    The pcre PHP extension
ext-pdo                 8.0.16    The PDO PHP extension
ext-pdo_mysql           8.0.16    The pdo_mysql PHP extension
ext-phar                8.0.16    The Phar PHP extension
ext-posix               8.0.16    The posix PHP extension
ext-readline            8.0.16    The readline PHP extension
ext-reflection          8.0.16    The Reflection PHP extension
ext-session             8.0.16    The session PHP extension
ext-shmop               8.0.16    The shmop PHP extension
ext-simplexml           8.0.16    The SimpleXML PHP extension
ext-sockets             8.0.16    The sockets PHP extension
ext-sodium              8.0.16    The sodium PHP extension
ext-spl                 8.0.16    The SPL PHP extension
ext-sysvmsg             8.0.16    The sysvmsg PHP extension
ext-sysvsem             8.0.16    The sysvsem PHP extension
ext-sysvshm             8.0.16    The sysvshm PHP extension
ext-tidy                8.0.16    The tidy PHP extension
ext-tokenizer           8.0.16    The tokenizer PHP extension
ext-xml                 8.0.16    The xml PHP extension
ext-xmlreader           8.0.16    The xmlreader PHP extension
ext-xmlrpc              1.0.0RC3  The xmlrpc PHP extension
ext-xmlwriter           8.0.16    The xmlwriter PHP extension
ext-xsl                 8.0.16    The xsl PHP extension
ext-zend-opcache        8.0.16    The Zend OPcache PHP extension
ext-zip                 1.19.5    The zip PHP extension
ext-zlib                8.0.16    The zlib PHP extension
lib-curl                7.68.0    The curl library
lib-curl-libssh         0.9.3     curl libssh version
lib-curl-openssl        1.1.1.6   curl OpenSSL version (1.1.1.6)
lib-curl-zlib           1.2.11    curl zlib version
lib-date-timelib        2020.03   date timelib version
lib-date-zoneinfo       0         zoneinfo ("Olson") database for date
lib-fileinfo-libmagic   539       fileinfo libmagic version
lib-gd                  2.3.0     The gd library
lib-iconv               2.31      The iconv library
lib-icu                 66.1      The ICU unicode and globalization support library
lib-icu-cldr            36.1      ICU CLDR project version
lib-icu-unicode         13.0.0    ICU unicode version
lib-imagick-imagemagick 6.9.10.23 The imagick-imagemagick library
lib-libsodium           1.0.18    The libsodium library
lib-libxml              2.9.12    libxml library version
lib-libxslt             1.1.34    The libxslt library
lib-libxslt-libxml      2.9.10    libxml version libxslt is compiled against
lib-mbstring-libmbfl    1.3.2     mbstring libmbfl version
lib-mbstring-oniguruma  6.9.4     mbstring oniguruma version
lib-openssl             1.1.1.6   OpenSSL 1.1.1f  31 Mar 2020
lib-pcre                10.39     The pcre library
lib-pcre-unicode        14.0.0    PCRE Unicode version support
lib-zip-libzip          1.7.3     The zip-libzip library
lib-zlib                1.2.11    The zlib library
php                     8.0.16    The PHP interpreter
php-64bit               8.0.16    The PHP interpreter, 64bit
php-ipv6                8.0.16    The PHP interpreter, with IPv6 support

### On which operating system(s) does the issue occur?

- [X] Linux
- [ ] MacOS
- [ ] Windows

### Steps to reproduce the issue.

    /**
     * Get the FCM representation of the notification.
     *
     * @return FcmMessage
     */
    public function toFcm(): FcmMessage
    {
        return FcmMessage::create()
            ->setNotification(\NotificationChannels\Fcm\Resources\Notification::create()
                ->setTitle($this->title)
                ->setBody($this->body)
                ->setImage(url('img/notifications/push-notification-icon.png')));
    }

### Error message/Stack trace

Call to undefined function GuzzleHttp\Psr7\uri_for() {"exception":"[object] (Error(code: 0): Call to undefined function GuzzleHttp\\Psr7\\uri_for() at /vendor/kreait/firebase-php/src/Firebase/Messaging/Http/Request/SendMessage.php:20)
[stacktrace]
#0 /vendor/kreait/firebase-php/src/Firebase/Messaging/Http/Request/SendMessages.php(32): Kreait\\Firebase\\Messaging\\Http\\Request\\SendMessage->__construct()

**Comment by jeromegamez** [comment]
You are using a really outdated version of the SDK (5.9.0) - the latest 5.x version is 5.26.1.

**Comment by djurovicigoor** [comment]
I am using 'laravel-notification-channels/fcm' : '2.4.0'.
How I can update SDK version using this package?

**Comment by jeromegamez** [comment]
Add/Change your composer.json so that it contains `"kreait/laravel-firebase": "^4.0"` and then do a `composer update -W`, that should do it 🤞

**Comment by djurovicigoor** [comment]
@jeromegamez Thanks
