### ISSUE TITLE
BindingResolutionException on Kreait\Firebase\Auth\ApiClient v6.2

### ISSUE THREAD

**Issue by gaetanobongiovanni** [kreait/firebase-php#696]
### Describe the issue you are experiencing

Hi, today I have updated to version 6.2 to be able to use 'Session cookies'. When I called my bees I got the following error: "BindingResolutionException - Error Unresolvable dependency resolving [Parameter #0 [ <required> string $projectId ]] in class Kreait\Firebase\Auth\ApiClient". I tested version 5.26, the error does not show up, but I cannot use it as it does not have the method: Auth :: verifySessionCookie ()

### Installed packages

beste/clock                        1.0.0    A collection of Clock implementations
beste/json                         1.0.0    A simple JSON helper to decode and encode JSON
brick/math                         0.9.3    Arbitrary-precision arithmetic library
classpreloader/classpreloader      4.2.0    Helps class loading performance by generating a single PHP file containing all of th...
dflydev/dot-access-data            v3.0.1   Given a deep data structure, access data by dot notation.
doctrine/inflector                 2.0.4    PHP Doctrine Inflector is a small library that can perform string manipulations with...
doctrine/instantiator              1.4.1    A small, lightweight utility to instantiate objects in PHP without invoking their co...
doctrine/lexer                     1.2.3    PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Pa...
dragonmantank/cron-expression      v3.3.1   CRON for PHP: Calculate the next or previous run date and determine if a CRON expres...
egulias/email-validator            2.1.25   A library for validating emails against several RFCs
fakerphp/faker                     v1.19.0  Faker is a PHP library that generates fake data for you.
fig/http-message-util              1.1.5    Utility classes and constants for use with PSR-7 (psr/http-message)
firebase/php-jwt                   v5.5.1   A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform t...
flipbox/lumen-generator            8.2.2    A Lumen Generator You Are Missing
google/auth                        v1.19.0  Google Auth Library for PHP
google/cloud-core                  v1.44.1  Google Cloud PHP shared dependency, providing functionality useful to all components.
google/cloud-storage               v1.26.1  Cloud Storage Client for PHP
google/crc32                       v0.1.0   Various CRC32 implementations
graham-campbell/result-type        v1.0.4   An Implementation Of The Result Type
guzzlehttp/guzzle                  7.4.2    Guzzle is a PHP HTTP client library
guzzlehttp/promises                1.5.1    Guzzle promises library
guzzlehttp/psr7                    2.2.1    PSR-7 message implementation that also provides common utility methods
hamcrest/hamcrest-php              v2.0.1   This is the PHP port of Hamcrest Matchers
illuminate/auth                    v8.83.6  The Illuminate Auth package.
illuminate/broadcasting            v8.83.6  The Illuminate Broadcasting package.
illuminate/bus                     v8.83.6  The Illuminate Bus package.
illuminate/cache                   v8.83.6  The Illuminate Cache package.
illuminate/collections             v8.83.6  The Illuminate Collections package.
illuminate/config                  v8.83.6  The Illuminate Config package.
illuminate/console                 v8.83.6  The Illuminate Console package.
illuminate/container               v8.83.6  The Illuminate Container package.
illuminate/contracts               v8.83.6  The Illuminate Contracts package.
illuminate/database                v8.83.6  The Illuminate Database package.
illuminate/encryption              v8.83.6  The Illuminate Encryption package.
illuminate/events                  v8.83.6  The Illuminate Events package.
illuminate/filesystem              v8.83.6  The Illuminate Filesystem package.
illuminate/hashing                 v8.83.6  The Illuminate Hashing package.
illuminate/http                    v8.83.6  The Illuminate Http package.
illuminate/log                     v8.83.6  The Illuminate Log package.
illuminate/macroable               v8.83.6  The Illuminate Macroable package.
illuminate/mail                    v8.83.6  The Illuminate Mail package.
illuminate/pagination              v8.83.6  The Illuminate Pagination package.
illuminate/pipeline                v8.83.6  The Illuminate Pipeline package.
illuminate/queue                   v8.83.6  The Illuminate Queue package.
illuminate/session                 v8.83.6  The Illuminate Session package.
illuminate/support                 v8.83.6  The Illuminate Support package.
illuminate/testing                 v8.83.6  The Illuminate Testing package.
illuminate/translation             v8.83.6  The Illuminate Translation package.
illuminate/validation              v8.83.6  The Illuminate Validation package.
illuminate/view                    v8.83.6  The Illuminate View package.
kreait/firebase-php                6.2.0    Firebase Admin SDK
kreait/firebase-tokens             2.2.0    A library to work with Firebase tokens
kreait/laravel-firebase            4.1.0    A Laravel package for the Firebase PHP Admin SDK
laravel/lumen-framework            v8.3.4   The Laravel Lumen Framework.
laravel/serializable-closure       v1.1.1   Laravel Serializable Closure provides an easy and secure way to serialize closures i...
lcobucci/clock                     2.1.0    Yet another clock abstraction
lcobucci/jwt                       4.1.5    A simple library to work with JSON Web Token and JSON Web Signature
league/commonmark                  2.2.3    Highly-extensible PHP Markdown parser which fully supports the CommonMark spec and G...
league/config                      v1.1.1   Define configuration arrays with strict schemas and access values with dot notation
mockery/mockery                    1.5.0    Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                    2.4.0    Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/jmespath.php             2.6.1    Declaratively specify how to extract elements from a JSON document
myclabs/deep-copy                  1.11.0   Create deep copies (clones) of your objects
nesbot/carbon                      2.57.0   An API extension for DateTime that supports 281 different languages.
nette/schema                       v1.2.2   📐 Nette Schema: validating data structures against a given Schema.
nette/utils                        v3.2.7   🛠  Nette Utils: lightweight utilities for string & array manipulation, image hand...
nikic/fast-route                   v1.3.0   Fast request router for PHP
nikic/php-parser                   v4.13.2  A PHP parser written in PHP
opis/closure                       3.6.3    A library that can be used to serialize closures (anonymous functions) and arbitrary...
phar-io/manifest                   2.0.3    Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    3.2.1    Library for handling version information and constraints
phpdocumentor/reflection-common    2.2.0    Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  5.3.0    With this component, a library can provide support for annotations via DocBlocks or ...
phpdocumentor/type-resolver        1.6.1    A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoption/phpoption                1.8.1    Option Type for PHP
phpspec/prophecy                   v1.15.0  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          9.2.15   Library that provides collection, processing, and rendering functionality for PHP co...
phpunit/php-file-iterator          3.0.6    FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                3.1.1    Invoke callables with a timeout
phpunit/php-text-template          2.0.4    Simple template engine.
phpunit/php-timer                  5.0.3    Utility class for timing
phpunit/phpunit                    9.5.20   The PHP Unit Testing framework.
psr/cache                          2.0.0    Common interface for caching libraries
psr/container                      1.1.2    Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0    Standard interfaces for event handling.
psr/http-client                    1.0.1    Common interface for HTTP clients
psr/http-factory                   1.0.1    Common interfaces for PSR-7 HTTP message factories
psr/http-message                   1.0.1    Common interface for HTTP messages
psr/log                            2.0.0    Common interface for logging libraries
psr/simple-cache                   1.0.1    Common interfaces for simple caching
psy/psysh                          v0.10.12 An interactive shell for modern PHP.
ralouphie/getallheaders            3.0.3    A polyfill for getallheaders.
ramsey/collection                  1.2.2    A PHP library for representing and manipulating collections.
ramsey/uuid                        4.3.1    A PHP library for generating and working with universally unique identifiers (UUIDs).
riverline/multipart-parser         2.0.9    One class library to parse multipart content with encoding and charset support.
rize/uri-template                  0.3.4    PHP URI Template (RFC 6570) supports both expansion & extraction
sebastian/cli-parser               1.0.1    Library for parsing CLI options
sebastian/code-unit                1.0.8    Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup 2.0.3    Looks up which function or method a line of code belongs to
sebastian/comparator               4.0.6    Provides the functionality to compare PHP values for equality
sebastian/complexity               2.0.2    Library for calculating the complexity of PHP code units
sebastian/diff                     4.0.4    Diff implementation
sebastian/environment              5.1.3    Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 4.0.4    Provides the functionality to export PHP variables for visualization
sebastian/global-state             5.0.5    Snapshotting of global state
sebastian/lines-of-code            1.0.3    Library for counting the lines of code in PHP source code
sebastian/object-enumerator        4.0.4    Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         2.0.4    Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        4.0.4    Provides functionality to recursively process PHP variables
sebastian/resource-operations      3.0.3    Provides a list of PHP built-in functions that operate on resources
sebastian/type                     3.0.0    Collection of value objects that represent the types of the PHP type system
sebastian/version                  3.0.2    Library that helps with managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer            v6.3.0   Swiftmailer, free feature-rich PHP mailer
symfony/cache                      v6.0.6   Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.5.0   Generic abstractions related to caching
symfony/console                    v5.4.7   Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v6.0.3   Converts CSS selectors to XPath expressions
symfony/deprecation-contracts      v3.0.0   A generic function and convention to trigger deprecation notices
symfony/error-handler              v5.4.7   Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v6.0.3   Provides tools that allow your application components to communicate with each other...
symfony/event-dispatcher-contracts v3.0.0   Generic abstractions related to dispatching event
symfony/finder                     v5.4.3   Finds files and directories via an intuitive fluent interface
symfony/http-foundation            v5.4.6   Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.4.7   Provides a structured process for converting a Request into a Response
symfony/mime                       v5.4.7   Allows manipulating MIME messages
symfony/polyfill-ctype             v1.25.0  Symfony polyfill for ctype functions
symfony/polyfill-iconv             v1.25.0  Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme     v1.25.0  Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn          v1.25.0  Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.25.0  Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.25.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.25.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.25.0  Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.25.0  Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.25.0  Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                    v5.4.7   Executes commands in sub-processes
symfony/service-contracts          v2.4.1   Generic abstractions related to writing services
symfony/string                     v6.0.3   Provides an object-oriented API to strings and deals with bytes, UTF-8 code points a...
symfony/translation                v6.0.7   Provides tools to internationalize your application
symfony/translation-contracts      v3.0.0   Generic abstractions related to translation
symfony/var-dumper                 v5.4.6   Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v6.0.7   Allows exporting any serializable PHP data structure to plain PHP code
theseer/tokenizer                  1.2.1    A small library for converting tokenized PHP source code into XML and potentially ot...
tijsverkoyen/css-to-inline-styles  2.2.4    CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-...
vlucas/phpdotenv                   v5.4.1   Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automa...
voku/portable-ascii                1.6.1    Portable ASCII library - performance optimized (ascii) string functions for php.
webmozart/assert                   1.10.0   Assertions to validate method input/output with nice error messages.

### PHP version and extensions

composer-plugin-api    2.1.0    The Composer Plugin API
composer-runtime-api   2.1.0    The Composer Runtime API
ext-bcmath             8.0.12   The bcmath PHP extension
ext-bz2                8.0.12   The bz2 PHP extension
ext-calendar           8.0.12   The calendar PHP extension
ext-ctype              8.0.12   The ctype PHP extension
ext-curl               8.0.12   The curl PHP extension
ext-date               8.0.12   The date PHP extension
ext-dba                8.0.12   The dba PHP extension
ext-dom                20031129 The dom PHP extension
ext-exif               8.0.12   The exif PHP extension
ext-ffi                8.0.12   The FFI PHP extension
ext-fileinfo           8.0.12   The fileinfo PHP extension
ext-filter             8.0.12   The filter PHP extension
ext-ftp                8.0.12   The ftp PHP extension
ext-gd                 8.0.12   The gd PHP extension
ext-gettext            8.0.12   The gettext PHP extension
ext-gmp                8.0.12   The gmp PHP extension
ext-hash               8.0.12   The hash PHP extension
ext-iconv              8.0.12   The iconv PHP extension
ext-intl               8.0.12   The intl PHP extension
ext-json               8.0.12   The json PHP extension
ext-ldap               8.0.12   The ldap PHP extension
ext-libxml             8.0.12   The libxml PHP extension
ext-mbstring           8.0.12   The mbstring PHP extension
ext-mcrypt             1.0.4    The mcrypt PHP extension
ext-mysqli             8.0.12   The mysqli PHP extension
ext-mysqlnd            0        The mysqlnd PHP extension (actual version: mysqlnd 8.0.12)
ext-odbc               8.0.12   The odbc PHP extension
ext-openssl            8.0.12   The openssl PHP extension
ext-pcntl              8.0.12   The pcntl PHP extension
ext-pcre               8.0.12   The pcre PHP extension
ext-pdo                8.0.12   The PDO PHP extension
ext-pdo_dblib          8.0.12   The pdo_dblib PHP extension
ext-pdo_mysql          8.0.12   The pdo_mysql PHP extension
ext-pdo_odbc           8.0.12   The PDO_ODBC PHP extension
ext-pdo_pgsql          8.0.12   The pdo_pgsql PHP extension
ext-pdo_sqlite         8.0.12   The pdo_sqlite PHP extension
ext-pgsql              8.0.12   The pgsql PHP extension
ext-phar               8.0.12   The Phar PHP extension
ext-phpdbg_webhelper   8.0.12   The phpdbg_webhelper PHP extension
ext-posix              8.0.12   The posix PHP extension
ext-pspell             8.0.12   The pspell PHP extension
ext-readline           8.0.12   The readline PHP extension
ext-reflection         8.0.12   The Reflection PHP extension
ext-session            8.0.12   The session PHP extension
ext-shmop              8.0.12   The shmop PHP extension
ext-simplexml          8.0.12   The SimpleXML PHP extension
ext-soap               8.0.12   The soap PHP extension
ext-sockets            8.0.12   The sockets PHP extension
ext-sodium             8.0.12   The sodium PHP extension
ext-spl                8.0.12   The SPL PHP extension
ext-sqlite3            8.0.12   The sqlite3 PHP extension
ext-sysvmsg            8.0.12   The sysvmsg PHP extension
ext-sysvsem            8.0.12   The sysvsem PHP extension
ext-sysvshm            8.0.12   The sysvshm PHP extension
ext-tidy               8.0.12   The tidy PHP extension
ext-tokenizer          8.0.12   The tokenizer PHP extension
ext-xml                8.0.12   The xml PHP extension
ext-xmlreader          8.0.12   The xmlreader PHP extension
ext-xmlwriter          8.0.12   The xmlwriter PHP extension
ext-xsl                8.0.12   The xsl PHP extension
ext-zend-opcache       8.0.12   The Zend OPcache PHP extension
ext-zip                1.19.4   The zip PHP extension
ext-zlib               8.0.12   The zlib PHP extension
lib-bz2                1.0.6    The bz2 library
lib-curl               7.80.0   The curl library
lib-curl-libssh2       1.10.0   curl libssh2 version
lib-curl-zlib          1.2.11   curl zlib version
lib-date-timelib       2020.03  date timelib version
lib-date-zoneinfo      2021.1   zoneinfo ("Olson") database for date
lib-fileinfo-libmagic  539      fileinfo libmagic version
lib-gd                 2.3.3    The gd library
lib-gmp                6.2.1    The gmp library
lib-icu                69.1     The ICU unicode and globalization support library
lib-icu-cldr           39       ICU CLDR project version
lib-icu-unicode        13.0.0   ICU unicode version
lib-ldap-openldap      2.5.8    OpenLDAP version of ldap
lib-libsodium          1.0.18   The libsodium library
lib-libxml             2.9.4    libxml library version
lib-libxslt            1.1.29   The libxslt library
lib-libxslt-libxml     2.9.4    libxml version libxslt is compiled against
lib-mbstring-libmbfl   1.3.2    mbstring libmbfl version
lib-mbstring-oniguruma 6.9.7    mbstring oniguruma version
lib-openssl            1.1.1.12 OpenSSL 1.1.1l  24 Aug 2021
lib-pcre               10.39    The pcre library
lib-pcre-unicode       14.0.0   PCRE Unicode version support
lib-pdo_pgsql-libpq    14.0     libpq for pdo_pgsql
lib-pdo_sqlite-sqlite  3.36.0   The pdo_sqlite-sqlite library
lib-sqlite3-sqlite     3.36.0   The sqlite3-sqlite library
lib-zip-libzip         1.8.0    The zip-libzip library
lib-zlib               1.2.11   The zlib library
php                    8.0.12   The PHP interpreter
php-64bit              8.0.12   The PHP interpreter, 64bit
php-ipv6               8.0.12   The PHP interpreter, with IPv6 support

### On which operating system(s) does the issue occur?

- [ ] Linux
- [X] MacOS
- [ ] Windows

### Steps to reproduce the issue.

1. ...
2. ...
3. ...

```php
use Kreait\Firebase\Auth as FireAuth;
use Kreait\Firebase\Auth\CreateSessionCookie\FailedToCreateSessionCookie;


public function __construct(FireAuth $auth) {
        $this->auth = $auth;
        //$this->host = env('HOST_ANGULAR');
        $this->host = env('HOST_WP');
}
public function test() {

  $token = $request->input('token');
  $duration = new \DateInterval('P14D');
  try {
      $sessionCookieString = $this->auth->createSessionCookie($token, $duration);
  } catch (FailedToCreateSessionCookie $e) {
      return response()->json($e->getMessage(), 401);
  }
}
// ...
```

### Error message/Stack trace

Error Unresolvable dependency resolving [Parameter #0 [ <required> string $projectId ]] in class Kreait\Firebase\Auth\ApiClient

**Comment by jeromegamez** [comment]
You're using version 4.1 of the Laravel Package which has some breaking changes compared to version 3.x. One of them is that you should now inject the Firebase Interfaces instead of their implementations (see https://github.com/kreait/laravel-firebase/#usage)

If you replace
```php
use Kreait\Firebase\Auth as FireAuth;
```
with
```php
use Kreait\Firebase\Contract\Auth as FireAuth;
```
I'm confident it will work again 🤞

**Comment by gaetanobongiovanni** [comment]
Thanks for your help, with your suggestion I was able to solve my problem.
