### ISSUE TITLE
Is firebase-php compatible with the 2.x.x JS SDK?

### ISSUE THREAD

**Issue by johnparkerg** [kreait/firebase-php#70]
I'm having a hard time verifying tokens created by the 2.4.1 JS SDK. Everytime I use verifyIdToken($token) on a $token generated by it I get an error:

```
#0 /var/www/html/vendor/kreait/firebase-tokens/src/Verifier.php(69): Lcobucci\JWT\Token->getClaim('iss')
#1 /var/www/html/vendor/kreait/firebase-tokens/src/Verifier.php(47): Firebase\Auth\Token\Verifier->verifyIssuer(Object(Lcobucci\JWT\Token))
#2 /var/www/html/vendor/kreait/firebase-tokens/src/Handler.php(32): Firebase\Auth\Token\Verifier->verifyIdToken(Object(Lcobucci\JWT\Token))
#3 /var/www/html/perfil.php(25): Firebase\Auth\Token\Handler->verifyIdToken('eyJ0eXAiOiJKV1Q...')
#4 {main}
```

Any help will be appreciated.

**Comment by jeromegamez** [comment]
What is the error?

**Comment by jeromegamez** [comment]
You have posted the stack trace, but the error is missing :). Alternatively, you could post an ID Token that fails, I wil then look at it.

**Comment by johnparkerg** [comment]
Sorry Jerome. Here is the error:

PHP message: PHP Fatal error:  Uncaught OutOfBoundsException: Requested claim is not configured in /var/www/html/vendor/lcobucci/jwt/src/Token.php:175

And the token, being generated by the Firebase JS SDK after successful login, I'm trying to verify:

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG4uaGVucnkucGFya2VyQGdtYWlsLmNvbSIsInByb3ZpZGVyX2lkIjoiMTAxNTYxNDQxNjM5NTUxNTgiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlhdCI6MTQ4OTUzMjgzNCwidiI6MCwiZCI6eyJ1aWQiOiJmYWNlYm9vazoxMDE1NjE0NDE2Mzk1NTE1OCIsInByb3ZpZGVyIjoiZmFjZWJvb2sifX0.So8Rwe90siLkjkWZ7SZobmciJ627bEDY5tkNTmfVG2A

**Comment by jeromegamez** [comment]
@johnparkerg Thank you for the token! I have removed it from your comment, just in case it contains some private data that shouldn't be exposed an will look into it!

**Comment by johnparkerg** [comment]
Thanks! I appreciate it.

**Comment by jeromegamez** [comment]
@johnparkerg The token does not seem to be an ID token as defined by Firebase (https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library)

You can check this yourself by executing the following script:

```php
use Lcobucci\JWT\Parser;

$idTokenString = '<Your JWT token>';

$parsed = (new Parser())->parse($idTokenString);

print_r($parsed->getClaims());
print_r($parsed->getHeaders());
```

For example, the token you showed my, specifies "HS256" as an encoding algorithm although Firebase needs it to be "RS256". Also, the claims in your token don't include an `"iss"` claim, which is required as well.

I don't know if this has something to do with the fact that you're using version 2.4.1 of the JS SDK (the current version 3.7.2 ([Release Notes](https://firebase.google.com/support/release-notes/js#3.7.2)), or if there is another reason.

Are you following the instructions as described on https://firebase.google.com/docs/auth/admin/verify-id-tokens#retrieve_id_tokens_on_clients ? The docs say that this would be the way to go:

```js
firebase.auth().currentUser.getToken(/* forceRefresh */ true).then(function(idToken) {
  // Send token to your backend via HTTPS
  // ...
}).catch(function(error) {
  // Handle error
});
```

I hope this helps! Please let me know if you have been able to solve the issue.

In any case your issue has shown me that the token verification could be more helpful, I will update the library accordingly soon!

**Comment by johnparkerg** [comment]
Thanks, looks like I'm going to have to update my code to the current version. I would've liked to understand what happened, but I guess firebase changed their algorithm without notice. I will let you know later today when it is working. I greatly appreciate your feedback.

**Comment by jeromegamez** [comment]
I just created a new release of the underlying [kreait/firebase-tokens](https://packagist.org/packages/kreait/firebase-tokens) library.

If you update your project dependencies, you should get more meaningful error messages

```bash
composer update kreait/firebase-php --with-dependencies
# or
composer update kreait/firebase-tokens
```

**Comment by johnparkerg** [comment]
@jeromegamez I can confirm that it is working today after updating to firebase 3.

Thanks for the support and the plugin.
