### ISSUE TITLE
php 7.4 support is a hoax

### ISSUE THREAD

**Issue by BenasPaulikas** [kreait/firebase-php#703]
### Describe the issue you are experiencing

Exception 'Kreait\Firebase\Exception\Messaging\MessagingError' with message 'syntax error, unexpected 'static' (T_STATIC)'

in /var/www/html/website/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingApiExceptionConverter.php:52

Caused by: Exception 'ParseError' with message 'syntax error, unexpected 'static' (T_STATIC)'

in /var/www/html/website/vendor/psr/cache/src/CacheItemInterface.php:75

### Installed packages

php -v
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:02) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### PHP version and extensions

php -v
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:02) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### On which operating system(s) does the issue occur?

- [X] Linux
- [ ] MacOS
- [ ] Windows

### Steps to reproduce the issue.

1. ...
2. ...
3. ...

```php
use Kreait\Firebase;

        $factory = (new Factory)
            ->withServiceAccount($file);

// ...
```

### Error message/Stack trace

provided above

**Comment by BenasPaulikas** [comment]
And on top of that no way to disable cache ? Which would solve my issue..

**Comment by BenasPaulikas** [comment]
sorry must likely duplicate of https://github.com/kreait/firebase-php/issues/675

**Comment by jeromegamez** [comment]
The library is thoroughly tested with all supported PHP versions. A syntax error is an indicator that you're invoking a PHP version <7.4.

In the past, this was usually caused when the CLI and the web server are using different PHP versions, for example with XAMPP.

Another reason could be not installing the library with composer or installing the dependencies with composer, but with the `--ignore-platform-reqs` flag.

On a side note: when you're looking for free support on a free library, calling any part of it a hoax is not the best way to ask for help.
