### ISSUE TITLE
MessageData keys are lowercased [Since 6.4.0]

### ISSUE THREAD

**Issue by SkylekFR** [kreait/firebase-php#709]
### Describe the issue you are experiencing

Our system is using firebase-php in 6.4.0 version (6.3.0 previously).

We are sending notification to our mobile app and we are setting data keys with camelCase keys.
Example, in the MessageData, we are putting a key like this:

['notificationType'] = 'exemple'

So when we send the notification, the app is testing the data as 'notificationType' but the value received is 'notificationtype'.

The key has been lowercased due to the $key = assertValidKey($key) method.
Because in the 6.3.0 version, the key wasn't overrided.

So the mobile app is not able to decode the key since we've updated this package.

### Installed packages

amphp/amp                            v2.5.2    A non-blocking concurrency framework for PHP applications.
amphp/byte-stream                    v1.8.1    A stream abstraction to make working with non-blocking I/O simple.
amphp/cache                          v1.4.0    A promise-aware caching API for Amp.
amphp/dns                            v1.2.3    Async DNS resolution for Amp.
amphp/hpack                          v3.1.0    HTTP/2 HPack implementation.
amphp/http                           v1.6.3    Basic HTTP primitives which can be shared by servers and clients.
amphp/http-client                    v4.5.5    Asynchronous concurrent HTTP/2 and HTTP/1.1 client built on the Amp concurrency framework
amphp/parser                         v1.0.0    A generator parser to make streaming parsers simple.
amphp/process                        v1.1.1    Asynchronous process manager.
amphp/serialization                  v1.0.0    Serialization tools for IPC and data storage in PHP.
amphp/socket                         v1.1.3    Async socket connection / server tools for Amp.
amphp/sync                           v1.4.0    Mutex, Semaphore, and other synchronization tools for Amp.
amphp/windows-registry               v0.3.3    Windows Registry Reader.
api-platform/core                    v2.5.7    Build a fully-featured hypermedia or GraphQL API in minutes
brick/math                           0.9.2     Arbitrary-precision arithmetic library
cocur/background-process             v0.7      Start processes in the background that continue running when the PHP process exists.
composer/package-versions-deprecated 1.11.99.1 Composer plugin that provides efficient querying for installed package versions (no runtime IO)
consolidation/self-update            1.2.0     Provides a self:update command for Symfony Console applications.
daverandom/libdns                    v2.0.2    DNS protocol implementation written in pure PHP
doctrine/annotations                 1.13.2    Docblock Annotations Parser
doctrine/cache                       1.12.1    PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections                 1.6.8     PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                      3.2.2     PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, proxies...   
doctrine/data-fixtures               1.5.0     Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        2.13.7    Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/deprecations                v0.5.3    A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for packages.
doctrine/doctrine-bundle             2.3.2     Symfony DoctrineBundle
doctrine/doctrine-fixtures-bundle    3.4.0     Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle  2.2.2     Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.1     The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                   2.0.4     PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator                1.4.0     A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       1.2.2     PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  2.3.3     PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily dep...   
doctrine/orm                         2.8.4     Object-Relational-Mapper for PHP
doctrine/persistence                 2.3.0     The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/sql-formatter               1.1.1     a PHP SQL highlighting library
easycorp/easy-deploy-bundle          v1.0.6    The easiest way to deploy Symfony applications
egulias/email-validator              3.1.2     A library for validating emails against several RFCs
ezyang/htmlpurifier                  v4.13.0   Standards compliant HTML filter written in PHP
fig/http-message-util                1.1.5     Utility classes and constants for use with PSR-7 (psr/http-message)
fig/link-util                        1.1.2     Common utility implementations for HTTP links
firebase/php-jwt                     v5.5.1    A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
friendsofphp/proxy-manager-lts       v1.0.4    Adding support for a wider range of PHP versions to ocramius/proxy-manager
gesdinet/jwt-refresh-token-bundle    v1.1.0    Implements a refresh token system over Json Web Tokens in Symfony
giggsey/libphonenumber-for-php       8.12.22   PHP Port of Google's libphonenumber
giggsey/locale                       1.9       Locale functions required by libphonenumber-for-php
google/auth                          v1.19.0   Google Auth Library for PHP
google/cloud-core                    v1.44.1   Google Cloud PHP shared dependency, providing functionality useful to all components.
google/cloud-storage                 v1.26.1   Cloud Storage Client for PHP
google/crc32                         v0.1.0    Various CRC32 implementations
gordalina/cachetool                  6.3.1     Manage your OPcache & APCu cache through the CLI
guzzlehttp/guzzle                    7.4.2     Guzzle is a PHP HTTP client library
guzzlehttp/promises                  1.5.1     Guzzle promises library
guzzlehttp/psr7                      1.8.3     PSR-7 message implementation that also provides common utility methods
hollodotme/fast-cgi-client           v3.1.5    A PHP fast CGI client to send requests (a)synchronously to PHP-FPM.
jms/metadata                         2.5.0     Class/method/property metadata management in PHP
jms/serializer                       3.12.3    Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle                3.9.1     Allows you to easily serialize, and deserialize data of any complexity
jsor/doctrine-postgis                v1.8.0    Spatial and Geographic Data with PostGIS and Doctrine.
kelunik/certificate                  v1.1.2    Access certificate details and transform between different formats.
kreait/clock                         1.1.0     A PHP 7.0 compatible clock abstraction
kreait/firebase-bundle               4.0.0     Symfony Bundle for the Firebase Admin SDK
kreait/firebase-php                  5.26.1    Firebase Admin SDK
kreait/firebase-tokens               1.16.1    A library to work with Firebase tokens
laminas/laminas-code                 4.2.2     Extensions to the PHP Reflection API, static code scanning, and code generation
laminas/laminas-eventmanager         3.3.1     Trigger and listen to events within a PHP application
laminas/laminas-zendframework-bridge 1.2.0     Alias legacy ZF class names to Laminas Project equivalents.
lcobucci/clock                       2.0.0     Yet another clock abstraction
lcobucci/jwt                         4.0.4     A simple library to work with JSON Web Token and JSON Web Signature
league/uri                           6.4.0     URI manipulation library
league/uri-interfaces                2.2.0     Common interface for URI representation
league/uri-parser                    1.4.1     userland URI parser RFC 3986 compliant
lexik/jwt-authentication-bundle      v2.10.7   This bundle provides JWT authentication for your Symfony REST API
maennchen/zipstream-php              2.1.0     ZipStream is a library for dynamically streaming dynamic zip files from PHP without writing to the disk at all on the server.
markbaker/complex                    2.0.0     PHP Class for working with complex numbers
markbaker/matrix                     2.1.2     PHP Class for working with matrices
maxakawizard/json-collection-parser  1.8.0     Streaming parser for large JSON files containing array of objects
microsoft/azure-storage-blob         1.5.2     This project provides a set of PHP client libraries that make it easy to access Microsoft Azure Storage Blob APIs.
microsoft/azure-storage-common       1.5.1     This project provides a set of common code shared by Azure Storage Blob, Table, Queue and File PHP client libraries.
microsoft/azure-storage-file         1.2.4     This project provides a set of PHP client libraries that make it easy to access Microsoft Azure Storage File APIs.
monolog/monolog                      2.5.0     Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/jmespath.php               2.6.1     Declaratively specify how to extract elements from a JSON document
myclabs/php-enum                     1.8.0     PHP Enum implementation
namshi/jose                          7.2.3     JSON Object Signing and Encryption library for PHP.
nelmio/cors-bundle                   2.1.1     Adds CORS (Cross-Origin Resource Sharing) headers support in your Symfony application
nikic/php-parser                     v4.13.2   A PHP parser written in PHP
phpdocumentor/reflection-common      2.2.0     Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    5.2.2     With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver          1.4.0     A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoffice/phpspreadsheet             1.17.1    PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpstan/phpdoc-parser                0.5.4     PHPDoc parser with support for nullable, intersection and generic types
predis/predis                        v1.1      Flexible and feature-complete PHP client library for Redis
psr/cache                            1.0.1     Common interface for caching libraries
psr/container                        1.1.2     Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                 1.0.0     Standard interfaces for event handling.
psr/http-client                      1.0.1     Common interface for HTTP clients
psr/http-factory                     1.0.1     Common interfaces for PSR-7 HTTP message factories
psr/http-message                     1.0.1     Common interface for HTTP messages
psr/link                             1.0.0     Common interfaces for HTTP links
psr/log                              1.1.4     Common interface for logging libraries
psr/simple-cache                     1.0.1     Common interfaces for simple caching
ralouphie/getallheaders              3.0.3     A polyfill for getallheaders.
ramsey/collection                    1.1.3     A PHP 7.2+ library for representing and manipulating collections.
ramsey/uuid                          4.1.1     A PHP library for generating and working with universally unique identifiers (UUIDs).
ramsey/uuid-doctrine                 1.8.1     Use ramsey/uuid as a Doctrine field type.
riverline/multipart-parser           2.0.9     One class library to parse multipart content with encoding and charset support.
rize/uri-template                    0.3.4     PHP URI Template (RFC 6570) supports both expansion & extraction
salsify/json-streaming-parser        v8.2.0    A streaming parser for JSON in PHP.
sensio/framework-extra-bundle        v5.6.1    This bundle provides a way to configure your controllers with annotations
setasign/fpdf                        1.8.3     FPDF is a PHP class which allows to generate PDF files with pure PHP. F from FPDF stands for Free: you may use it for any kind of usage and modify it to suit you...   
setasign/fpdi                        v2.3.6    FPDI is a collection of PHP classes facilitating developers to read pages from existing PDF documents and use them as templates in FPDF. Because it is also possi...   
snc/redis-bundle                     3.4.0     A Redis bundle for Symfony
symfony/amqp-messenger               v5.4.3    Symfony AMQP extension Messenger Bridge
symfony/asset                        v5.4.3    Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/cache                        v5.4.3    Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts              v2.5.0    Generic abstractions related to caching
symfony/config                       v5.4.3    Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                      v5.4.3    Eases the creation of beautiful and testable command line interfaces
symfony/dependency-injection         v5.4.3    Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts        v2.5.1    A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge              v5.4.3    Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger           v5.4.3    Symfony Doctrine Messenger Bridge
symfony/dotenv                       v5.4.3    Registers environment variables from a .env file
symfony/error-handler                v5.4.3    Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher             v5.4.3    Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts   v2.5.0    Generic abstractions related to dispatching event
symfony/expression-language          v5.4.3    Provides an engine that can compile and evaluate expressions
symfony/filesystem                   v5.4.3    Provides basic utilities for the filesystem
symfony/finder                       v5.4.3    Finds files and directories via an intuitive fluent interface
symfony/flex                         v1.18.5   Composer plugin for Symfony
symfony/form                         v5.4.3    Allows to easily create, process and reuse HTML forms
symfony/framework-bundle             v5.4.4    Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                  v5.4.3    Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts        v2.5.0    Generic abstractions related to HTTP clients
symfony/http-foundation              v5.4.3    Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                  v5.4.4    Provides a structured process for converting a Request into a Response
symfony/intl                         v5.4.3    Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                       v5.4.3    Helps sending emails
symfony/maker-bundle                 v1.38.0   Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mercure                      v0.4.1    Symfony Mercure Component
symfony/mercure-bundle               v0.2.6    Symfony MercureBundle
symfony/messenger                    v5.4.3    Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                         v5.4.3    Allows manipulating MIME messages
symfony/monolog-bridge               v5.4.3    Provides integration for Monolog with various Symfony components
symfony/monolog-bundle               v3.7.1    Symfony MonologBundle
symfony/options-resolver             v5.4.3    Provides an improved replacement for the array_replace PHP function
symfony/password-hasher              v5.4.3    Provides password hashing utilities
symfony/phpunit-bridge               v5.4.3    Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme       v1.24.0   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu            v1.24.0   Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn            v1.25.0   Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer     v1.25.0   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.25.0   Symfony polyfill for the Mbstring extension
symfony/polyfill-php73               v1.24.0   Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.25.0   Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81               v1.25.0   Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                      v5.4.3    Executes commands in sub-processes
symfony/property-access              v5.4.3    Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info                v5.4.3    Extracts information about PHP class' properties using metadata of popular sources
symfony/redis-messenger              v5.4.3    Symfony Redis extension Messenger Bridge
symfony/routing                      v5.4.3    Maps an HTTP request to a set of configuration variables
symfony/security-bundle              v5.4.5    Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core                v5.4.3    Symfony Security Component - Core Library
symfony/security-csrf                v5.4.3    Symfony Security Component - CSRF Library
symfony/security-guard               v5.4.3    Symfony Security Component - Guard
symfony/security-http                v5.4.3    Symfony Security Component - HTTP Integration
symfony/serializer                   v5.4.3    Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts            v2.5.0    Generic abstractions related to writing services
symfony/stopwatch                    v5.4.3    Provides a way to profile code
symfony/string                       v5.4.3    Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/thanks                       v1.2.10   Encourages sending ⭐ and 💵 to fellow PHP package maintainers (not limited to Symfony components)!
symfony/translation                  v5.4.3    Provides tools to internationalize your application
symfony/translation-contracts        v2.5.0    Generic abstractions related to translation
symfony/twig-bridge                  v5.4.3    Provides integration for Twig with various Symfony components
symfony/twig-bundle                  v5.4.3    Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                    v5.4.3    Provides tools to validate values
symfony/var-dumper                   v5.4.3    Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                 v5.4.3    Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                     v5.4.3    Manages links between resources
symfony/web-profiler-bundle          v5.4.3    Provides a development tool that gives detailed information about the execution of any request
symfony/workflow                     v5.4.3    Provides tools for managing a workflow or finite state machine
symfony/yaml                         v5.4.3    Loads and dumps YAML files
symfonycasts/reset-password-bundle   v1.8.0    Symfony bundle that adds password reset functionality.
twig/twig                            v3.3.8    Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                     1.10.0    Assertions to validate method input/output with nice error messages.
willdurand/negotiation               v2.3.1    Content Negotiation tools for PHP provided as a standalone library.

### PHP version and extensions

composer-plugin-api    2.0.0    The Composer Plugin API
composer-runtime-api   2.0.0    The Composer Runtime API
ext-amqp               1.11.0   The amqp PHP extension
ext-bcmath             7.4.2    The bcmath PHP extension
ext-calendar           7.4.2    The calendar PHP extension
ext-ctype              7.4.2    The ctype PHP extension
ext-curl               7.4.2    The curl PHP extension
ext-date               7.4.2    The date PHP extension
ext-dom                20031129 The dom PHP extension
ext-fileinfo           7.4.2    The fileinfo PHP extension
ext-filter             7.4.2    The filter PHP extension
ext-gd                 7.4.2    The gd PHP extension
ext-hash               7.4.2    The hash PHP extension
ext-iconv              7.4.2    The iconv PHP extension
ext-json               7.4.2    The json PHP extension
ext-libxml             7.4.2    The libxml PHP extension
ext-mbstring           7.4.2    The mbstring PHP extension
ext-mysqlnd            0        The mysqlnd PHP extension (actual version: mysqlnd 7.4.2)
ext-openssl            7.4.2    The openssl PHP extension
ext-pcre               7.4.2    The pcre PHP extension
ext-pdo                7.4.2    The PDO PHP extension
ext-pdo_pgsql          7.4.2    The pdo_pgsql PHP extension
ext-phar               7.4.2    The Phar PHP extension
ext-readline           7.4.2    The readline PHP extension
ext-reflection         7.4.2    The Reflection PHP extension
ext-session            7.4.2    The session PHP extension
ext-simplexml          7.4.2    The SimpleXML PHP extension
ext-spl                7.4.2    The SPL PHP extension
ext-tokenizer          7.4.2    The tokenizer PHP extension
ext-xml                7.4.2    The xml PHP extension
ext-xmlreader          7.4.2    The xmlreader PHP extension
ext-xmlwriter          7.4.2    The xmlwriter PHP extension
ext-zip                1.15.5   The zip PHP extension
ext-zlib               7.4.2    The zlib PHP extension
lib-amqp-librabbitmq   0.9.0    AMQP librabbitmq version
lib-amqp-protocol      0.9.1    AMQP protocol version
lib-curl               7.67.0   The curl library
lib-curl-libssh2       1.8.2    curl libssh2 version
lib-curl-openssl       1.1.1.4  curl OpenSSL version (1.1.1.4)
lib-curl-zlib          1.2.11   curl zlib version
lib-date-timelib       2018.03  date timelib version
lib-date-zoneinfo      2019.3   zoneinfo ("Olson") database for date
lib-fileinfo-libmagic  537      fileinfo libmagic version
lib-gd                 2.0.35   The gd library
lib-gd-freetype        2.9.1    freetype version for gd
lib-gd-libjpeg         9.0      libjpeg version for gd
lib-gd-libpng          1.6.34   libpng version for gd
lib-gd-libxpm          3.5.12   libxpm version for gd
lib-iconv              1.16     The iconv library
lib-libxml             2.9.10   libxml library version
lib-mbstring-libmbfl   1.3.2    mbstring libmbfl version
lib-mbstring-oniguruma 6.9.4    mbstring oniguruma version
lib-openssl            1.1.1.4  OpenSSL 1.1.1d  10 Sep 2019
lib-pcre               10.33    The pcre library
lib-pcre-unicode       11.0.0   PCRE Unicode version support
lib-pdo_pgsql-libpq    11.4     libpq for pdo_pgsql
lib-zlib               1.2.11   The zlib library
php                    7.4.2    The PHP interpreter
php-64bit              7.4.2    The PHP interpreter, 64bit
php-ipv6               7.4.2    The PHP interpreter, with IPv6 support
php-zts                7.4.2    The PHP interpreter, with Zend Thread Safety

### On which operating system(s) does the issue occur?

- [X] Linux
- [ ] MacOS
- [ ] Windows

### Steps to reproduce the issue.

Our system is using firebase-php in 6.4.0 version (6.3.0 previously).

We are sending notification to our mobile app and we are setting data keys with camelCase keys.
Example, in the MessageData, we are putting a key like this:

['notificationType'] = 'exemple'

So when we send the notification, the app is testing the data as 'notificationType' but the value received is 'notificationtype'.

The key has been lowercased due to the $key = assertValidKey($key) method.
Because in the 6.3.0 version, the key wasn't overrided.

### Error message/Stack trace

no stack strace, no error

**Comment by jeromegamez** [comment]
Thank you for the report! I'll look into it in an instant!

**Comment by jeromegamez** [comment]
Thank you for bringing this up! I fixed it with a29d520d58991b27a491b00f416885687e1cabe4 and will release it shortly.

**Comment by jeromegamez** [comment]
Here it is https://github.com/kreait/firebase-php/releases/tag/6.5.1 🚀 

Thanks again!
