### ISSUE TITLE
Define icons for android possible?

### ISSUE THREAD

**Issue by basbroens** [kreait/firebase-php#710]
### Describe the feature you would like to see

I can send a cloud message with this package, but i can;t find anywhere if it is possible to define the android icon.

```
$notification = [
            'title'     => $request->title,
            'body'      => $request->body,
            'image'     => $image_url,
        ];

`  $message   = CloudMessage::withTarget('token', $request->firebase_token)
            ->withNotification($notification);
```

Works like a charm on android. I even get the image. But the icon is just a circle with the first letter of the website in it.

Is it possible to define/set the wanted icon with this package?

**Comment by jeromegamez** [comment]
You can define platform-specific configuration with the `withAndroidConfig()` method.

https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html

In the docs above you'll find a link that points to the official docs describing the possible config values:

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

**Comment by bloodykheeng** [comment]
try this u can use the fcm options
for me in mycase i wnated to change the icon of the web thats why i had to use this WebPushConfig
but for ur case uill use AndroidConfig::fromArray([

read more from firebase-php site ive attached link below

```
   public function sendNotificationToTopic($topic, $title, $body, $data = [])
    {
        try {
            $imageUrl = env('FRONTEND_URL', 'http://localhost:3000') . "/cfp_logo.png";
            $imageUrl = "https://picsum.photos/400/200";

            $notification = Notification::create()
                ->withTitle($title)
                ->withBody($body);
            // ->withImageUrl($imageUrl);

            $config = WebPushConfig::fromArray([
                'notification' => [
                    'icon' => 'https://picsum.photos/400/200',
                ],
                'fcm_options'  => [
                    'link' => 'https://my-server.example/some-page',
                ],
            ]);

            $message = CloudMessage::new ()
                ->toTopic($topic)
                ->withNotification($notification)
                ->withDefaultSounds()
                ->withData(array_merge($data, ['image' => $imageUrl]))
                ->withWebPushConfig($config);

            $this->messaging->send($message);
        } catch (\Kreait\Firebase\Exception\MessagingException $e) {
            // Log the error or handle it as needed
            error_log('Error sending notification: ' . $e->getMessage());
        }
    }
```



find the fcm for android
here [firebase php](https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html)
