### ISSUE TITLE
Android config PR #714 breaks future installations

### ISSUE THREAD

**Issue by Cannonb4ll** [kreait/firebase-php#719]
### Describe the issue you are experiencing

I'm not sure with others, but the PR #714 just broke all my notifications in my Laravel app, because there was no default TTL set, the exception that I was suddenly getting:

```
The TTL of an AndroidConfig must be an positive integer or string matching /^\d+s$/
```

I would've expected to have some backwards compatibility with this if there's no TTL set from out the user, which is 4 weeks default: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/#androidconfig

```
How long (in seconds) the message should be kept in FCM storage if the device is offline. The maximum time to live supported is 4 weeks, and the default value is 4 weeks if not set. Set it to 0 if want to send the message immediately. In JSON format, the Duration type is encoded as a string rather than an object, where the string ends in the suffix "s" (indicating seconds) and is preceded by the number of seconds, with nanoseconds expressed as fractional seconds. For example, 3 seconds with 0 nanoseconds should be encoded in JSON format as "3s", while 3 seconds and 1 nanosecond should be expressed in JSON format as "3.000000001s". The ttl will be rounded down to the nearest second.
```

### Installed packages

laravel/framework
kreait/laravel-firebase

### PHP version and extensions

PHP 8.1

### On which operating system(s) does the issue occur?

- [ ] Linux
- [X] MacOS
- [ ] Windows

### Steps to reproduce the issue.

**Breaks:**
```php
->setAndroid(
    AndroidConfig::create()
        ->setFcmOptions(AndroidFcmOptions::create()->setAnalyticsLabel('analytics'))
        ->setNotification(AndroidNotification::create()->setSound('default'))
)
```

**Works:**

```php
->setAndroid(
    AndroidConfig::create()
        ->setTtl(4 * 604800)
        ->setFcmOptions(AndroidFcmOptions::create()->setAnalyticsLabel('analytics'))
        ->setNotification(AndroidNotification::create()->setSound('default'))
)

```

### Error message/Stack trace

```
The TTL of an AndroidConfig must be an positive integer or string matching /^\d+s$/
```

**Comment by jeromegamez** [comment]
Thanks for reporting, I'm checking!

**Comment by jeromegamez** [comment]
@Cannonb4ll Please check #720 - I ran this locally and didn't get failures.

I just noticed - all methods you are using are not part of the SDK's API, are you using another library on top?

**Comment by Glennmen** [comment]
@jeromegamez That is not what he was talking about 😅 
With the current change it requires the TTL to be set but firebase has this field optional.
It can be null.

**Comment by Cannonb4ll** [comment]
@jeromegamez I'm sorry, I wasn't explicit enough on that.

Yes, I am using https://github.com/laravel-notification-channels/fcm, which utilizes this in the end, not passing a `setTtl` method to this will break and not use the default value. It works in version 6.5.0 if I lock it down to that, the recent change with the TTL breaks it for some reason..

**Comment by jeromegamez** [comment]
AAAAAAH! Sorry, I was too fast thinking I broke something. Will check again 🗡️

**Comment by jeromegamez** [comment]
Okay, I just dug into it, and the problem is in the notifications library - 

https://github.com/laravel-notification-channels/fcm/blob/0aec40adb46a4d60143cf587f4c1936cf5575f41/src/Resources/AndroidConfig.php#L20 and https://github.com/laravel-notification-channels/fcm/blob/0aec40adb46a4d60143cf587f4c1936cf5575f41/src/Resources/AndroidConfig.php#L100 allow the TTL to be`null`

and serialize it in https://github.com/laravel-notification-channels/fcm/blob/0aec40adb46a4d60143cf587f4c1936cf5575f41/src/Resources/AndroidConfig.php#L191 without removing it.

Technically it's not the intended usage, but I'll change it to allow `null`, because it is a breaking change otherwise.

Thanks for notifying me, I'll get to it in #720 and release it as soon as I made sure it works 🤞

**Comment by Cannonb4ll** [comment]
No rush! I've just manually updated all my notification classes to grab the `4 * 604800` TTL so it works, but I can imagine someone else running into this as well.

Also, open up one-time-payment sponsors to your profile, please 🙃

**Comment by jeromegamez** [comment]
Done 🙈

**Comment by jeromegamez** [comment]
Thank you so much, @Cannonb4ll, I really appreciate it! 🥰
