### ISSUE TITLE
Doesn't support String values for Realtime Database Queries?

### ISSUE THREAD

**Issue by smaker** [kreait/firebase-php#721]
### Describe the feature you would like to see

Only Support Scalar Value? startAt method throws InvalidArgumentException. endAt method is same too.

```
Only scalar values are allowed for "startAt" queries.
```
I need a function to search for the value of the string type.

**Comment by jeromegamez** [comment]
Yes, limit- and filter queries only work with scalar values. This is given by the Firebase backend, the error you're receiving is a response from the Firebase API, so there's nothing we can do here.

https://firebase.google.com/docs/database/rest/retrieve-data
