### ISSUE TITLE
get last record from a data array in firebase.

### ISSUE THREAD

**Issue by vitorhugosg** [kreait/firebase-php#725]
Hello, all right, I would like to know something, I'm implementing it with a logic with your LIB, which by the way is very good, but I'm not able to make the query I'm doing get only the last data from an array .

![image](https://user-images.githubusercontent.com/17458174/184974538-11bba2a5-1f15-4eef-a45c-ea2d483ec34f.png)
![image](https://user-images.githubusercontent.com/17458174/184974602-2ffde788-2fe2-45dc-8dc1-9b14b282971c.png)

The limitToLast function, if I understand correctly, does it dictate how many items I am retrieving?

If not does anyone know how I can handle this situation?

**Comment by jeromegamez** [comment]
Hey @vitorhugosg, and thanks for discovering and reporting this issue!

It's indeed an error that I introduced when adding Emulator Support for the Realtime Database! I'm currently working on a fix and will let you know once it's done!

**Comment by jeromegamez** [comment]
The https://github.com/kreait/firebase-php/releases/tag/6.7.1 should have fixed the issue, please let me know if it works for you 🙏

**Comment by vitorhugosg** [comment]
Hi, sorry for the delay, I'll test it :) do you know if it's already available?
