### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by kiwo12345** [kreait/firebase-php#73]
I wonder what kind of exception I can use in a try/catch method
Eg if I use one of these functions, how can I check if they have failed?

//Insert a new
```
app('firebase')->getDatabase()->getReference('items/'.$newItem->i_id)->set([
             'title' => $request->input('title'),
             'active' => (int) 1,
        ]);
```

//Update a item
```
$updateFields = [
                  'title' => "some new title",
                  'active' => (int) 0,
              ];
                app('firebase')->getDatabase()->getReference('items/'.$id)->update($updateFields);
```

**Comment by jeromegamez** [comment]
If a request fails, one of the following exceptions will be thrown: https://github.com/kreait/firebase-php/tree/master/src/Firebase/Exception - each exception implements the `FirebaseException`, so you could at least check for that. Most probably you would receive an `ApiException` or a `PermissionDenied` exception.

If authentication/authorization is not the problem, I haven't had a single time that a request failed, I must say :). Do you have an example?

**Comment by kiwo12345** [comment]
@jeromegamez thanks for the info!
No I never had a request fail, I just wanted to know in case :)
