### ISSUE TITLE
Login with Facebook after password reset results in empty tokens

### ISSUE THREAD

**Issue by azurlake** [kreait/firebase-php#763]
### Describe the bug

In a test project, Login is set up via Firebase with email, Facebook and Google providers and works OK. Password resetting also works; I obtain the link on the backend given the email and send the password reset link to the client if the email exists. The link is obtained like this:

```
$auth = app('firebase.auth');
$link = $auth->getPasswordResetLink($request->email);
```

The problem is not critical since it's not an everyday scenario, but it comes when logging in with Facebook (it doesn't happen with Google), log out, then the user clicks on "Did you forget your password?" and obtains the link, and resets the password. At this moment, in Firebase, the login provider changes back from Facebook to email as expected, but if the user tries to login again with Facebook, the signin itself doesn't throw any error (and I obtain expected user data like the Firebase ID, name, etc.) but the access and refresh tokens are empty. This is the code used for the sign in:

```
$auth = app('firebase.auth');
$signInToken = $request->token; // The token obtained at the client's side, needed to perform the login in Firebase
$signInProvider = $request->provider; // This will be 'google.com' or 'facebook.com'
try {
    $signInResult = $auth->signInWithIdpAccessToken($signInProvider, $signInToken, null, null, null, null);

    // The following traces are all empty in the described case
    Log::debug('Sign in result idToken: ' . $signInResult->idToken());
    Log::debug('Sign in result accessToken: ' . $signInResult->accessToken());
    Log::debug('Sign in result tokenResponse: ' . print_r($signInResult->asTokenResponse(), true));

    //But this data() object indeed shows data from the user logged in:
    Log::debug('Sign in result data: ' . print_r($signInResult->data(), true));

} catch(FailedToSignIn $e) {
    Log::debug('Error signing in with provider: ' . $e->getMessage()); //This doesn't get called in the described scenario
}
```

The behaviour only happens with Facebook provider. The same actions done with Google sign in results in a valid token.

### Installed packages

```json
"require": {
        "php": "^7.3|^8.0",
        "doctrine/dbal": "^3.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "hostbrook/laravel-dkim": "^1.2",
        "kreait/laravel-firebase": "^4.2",
        "laravel/framework": "^8.75",
        "laravel/passport": "^10.4",
        "laravel/sanctum": "^2.15",
        "laravel/tinker": "^2.5"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^5.10",
        "phpunit/phpunit": "^9.5.10"
    },
```

### PHP version and extensions

```shell
composer-plugin-api    2.0.0    The Composer Plugin API
composer-runtime-api   2.0.0    The Composer Runtime API
ext-bz2                7.4.30   The bz2 PHP extension
ext-calendar           7.4.30   The calendar PHP extension
ext-ctype              7.4.30   The ctype PHP extension
ext-curl               7.4.30   The curl PHP extension
ext-date               7.4.30   The date PHP extension
ext-dom                20031129 The dom PHP extension
ext-exif               7.4.30   The exif PHP extension
ext-fileinfo           7.4.30   The fileinfo PHP extension
ext-filter             7.4.30   The filter PHP extension
ext-ftp                7.4.30   The ftp PHP extension
ext-gd                 7.4.30   The gd PHP extension
ext-gettext            7.4.30   The gettext PHP extension
ext-hash               7.4.30   The hash PHP extension
ext-iconv              7.4.30   The iconv PHP extension
ext-json               7.4.30   The json PHP extension
ext-libxml             7.4.30   The libxml PHP extension
ext-mbstring           7.4.30   The mbstring PHP extension
ext-mysqli             7.4.30   The mysqli PHP extension
ext-mysqlnd            0        The mysqlnd PHP extension (actual version: mysqlnd 7.4.30)
ext-openssl            7.4.30   The openssl PHP extension
ext-pcntl              7.4.30   The pcntl PHP extension
ext-pcre               7.4.30   The pcre PHP extension
ext-pdo                7.4.30   The PDO PHP extension
ext-pdo_mysql          7.4.30   The pdo_mysql PHP extension
ext-pdo_sqlite         7.4.30   The pdo_sqlite PHP extension
ext-phar               7.4.30   The Phar PHP extension
ext-readline           7.4.30   The readline PHP extension
ext-reflection         7.4.30   The Reflection PHP extension
ext-session            7.4.30   The session PHP extension
ext-simplexml          7.4.30   The SimpleXML PHP extension
ext-sockets            7.4.30   The sockets PHP extension
ext-sodium             7.4.30   The sodium PHP extension
ext-spl                7.4.30   The SPL PHP extension
ext-sqlite3            7.4.30   The sqlite3 PHP extension
ext-tokenizer          7.4.30   The tokenizer PHP extension
ext-xml                7.4.30   The xml PHP extension
ext-xmlreader          7.4.30   The xmlreader PHP extension
ext-xmlrpc             7.4.30   The xmlrpc PHP extension
ext-xmlwriter          7.4.30   The xmlwriter PHP extension
ext-xsl                7.4.30   The xsl PHP extension
ext-zend-opcache       7.4.30   The Zend OPcache PHP extension
ext-zip                1.18.2   The zip PHP extension
ext-zlib               7.4.30   The zlib PHP extension
lib-bz2                1.0.6    The bz2 library
lib-curl               7.61.1   The curl library
lib-curl-libssh        0.9.6    curl libssh version
lib-curl-openssl       1.1.1.11 curl OpenSSL version (1.1.1.11)
lib-curl-zlib          1.2.11   curl zlib version
lib-date-timelib       2018.04  date timelib version
lib-fileinfo-libmagic  537      fileinfo libmagic version
lib-gd                 2.2.5    The gd library
lib-iconv              2.28     The iconv library
lib-libsodium          1.0.18   The libsodium library
lib-libxml             2.9.7    libxml library version
lib-libxslt            1.1.32   The libxslt library
lib-libxslt-libxml     2.9.7    libxml version libxslt is compiled against
lib-mbstring-libmbfl   1.3.2    mbstring libmbfl version
lib-mbstring-oniguruma 6.8.2    mbstring oniguruma version
lib-openssl            1.1.1.11 OpenSSL 1.1.1k  FIPS 25 Mar 2021
lib-pcre               10.32    The pcre library
lib-pcre-unicode       11.0.0   PCRE Unicode version support
lib-pdo_sqlite-sqlite  3.26.0   The pdo_sqlite-sqlite library
lib-sqlite3-sqlite     3.26.0   The sqlite3-sqlite library
lib-zip-libzip         1.6.1    The zip-libzip library
lib-zlib               1.2.11   The zlib library
php                    7.4.30   The PHP interpreter
php-64bit              7.4.30   The PHP interpreter, 64bit
php-ipv6               7.4.30   The PHP interpreter, with IPv6 support
```

### Steps to reproduce the issue.

```shell
1. Login with Facebook from the client
2. Send the Facebook token to the backend, perform login and send the Firebase access and refresh tokens back to the client
3. Log out the client and invalidate user refresh token
4. Reset password (user that lost the Facebook account... or dumb user), enters same email
5. Account email syncing is enabled in Fibebase
6. The auth provider changes back to email when the user resets the password.
7. Perform Facebook login again from the client with the code below.
8. The login works (no exception, obtained user data) but tokens are empty.


$auth = app('firebase.auth');
$signInToken = $request->token; // The token obtained at the client's side, needed to perform the login in Firebase
$signInProvider = $request->provider; // This will be 'google.com' or 'facebook.com'
try {
    $signInResult = $auth->signInWithIdpAccessToken($signInProvider, $signInToken, null, null, null, null);

    // The following traces are all empty in the described case
    Log::debug('Sign in result idToken: ' . $signInResult->idToken());
    Log::debug('Sign in result accessToken: ' . $signInResult->accessToken());
    Log::debug('Sign in result tokenResponse: ' . print_r($signInResult->asTokenResponse(), true));

    //But this data() object indeed shows data from the user logged in:
    Log::debug('Sign in result data: ' . print_r($signInResult->data(), true));

} catch(FailedToSignIn $e) {
    Log::debug('Error signing in with provider: ' . $e->getMessage()); //This doesn't get called in the described scenario
}
```
```


### Additional information

Not happening with google.com provider

**Comment by jeromegamez** [comment]
Thank you for providing such a detailed description of the problem.

Unfortunately, I can't reproduce the issue because I don't have a Facebook account to test this with. 

If I understand you correctly, the `$signInResult->data()` includes some kind of user data (including tokens?), but the `idToken()` and `accessToken()` methods don't return values that are included in the `data()` response?

In that case, could you provide me with the output of the `data()` method? I would then be able to modify the other methods to return the expected values.

If the data doesn't include tokens, but other data, I can't throw an error from within the SDK because, technically, the Firebase Auth API returns a "successful" Sign-In (because it returns an HTTP response with HTTP Status Code 200).

If the Sign In is "successful" but you would expect an error, I see two solutions (at the moment):

You could raise an issue at Google/Firebase describing the problem, perhaps they can explain why the API behaves like this, or fixes the API response to return an error.

Although probably not optimal, another approach could be to, once a user triggers/completes the reset password flow, explicitly [unlink the Facebook Provider from the user](https://firebase-php.readthedocs.io/en/stable/authentication.html#linking-and-unlinking-identity-providers). The next time they try to login with Facebook, they would have to freshly re-authenticate with Facebook.

Another approach could be: If a user signs in with Facebook after having reset their password and the SignIn Result doesn't include the tokens, retrigger the Facebook authentication flow.

I hope the issue is just™ that the response include tokens in a field that the SDK currently isn't evaluating, this would be an easy fix - otherwise I'm afraid I don't know how I can help resolve the problem from the SDK's perspective :/

**Comment by azurlake** [comment]
Thanks for the quick reply.

Here are the actual traces:

[2023-01-30 08:48:36] staging.DEBUG: Sign in result tokenResponse: Array
(
    [token_type] => Bearer
    [access_token] => 
    [id_token] => 
    [refresh_token] => 
    [expires_in] => 
)
  
[2023-01-30 08:48:36] staging.DEBUG: Sign in result data: Array
(
    [federatedId] => http://facebook.com/101673[redacted]
    [providerId] => facebook.com
    [email] => az...[redacted]
    [emailVerified] => 
    [firstName] => [redacted]
    [fullName] => [redacted]
    [lastName] => [redacted]
    [photoUrl] => https://graph.facebook.com/101[redacted]
    [localId] => sYR[redacted]
    [displayName] => [redacted]
    [needConfirmation] => 1
    [oauthAccessToken] => EAAVB6[redacted]
    [rawUserInfo] => {"name":"<redacted>","last_name":"[redacted]","id":"101673[redacted]","first_name":"[redacted]","email":"az[redacted]","picture":{"data":{"is_silhouette":false,"width":100,"url":"https://platform-lookaside.fbsbx.com/[redacted]","height":101}}}
    [kind] => identitytoolkit#VerifyAssertionResponse
)

As you can see, there's no idToken or accessToken anywhere.

I'll try forcing the unlink provider upon password reset and let you know if this patches the problem.

Thank you

**Comment by jeromegamez** [comment]
It seems that `oauthAccessToken` could be what's needed. Could you try extracting it from the `data()` return value and see if you can work with it?

**Comment by azurlake** [comment]
You mean trying a secondary login with that oauth access token? I'll try, let me see :/ seems strange to have to do 2 logins, doesn't it?

**Comment by azurlake** [comment]
Hey,

I tried logging in a second time using the oAuthAccessToken provided by the Facebook login with no success - same result. I tried both approaches below:

`$signInResult = $auth->signInWithIdpAccessToken($request->provider, $signInResult->data()['oauthAccessToken'], null, null, null, null);`

and

```
$signInToken = $request->token; // This is the client token provided by Facebook / iOS or Android
$signInResult = $auth->signInWithIdpAccessToken($request->provider, $signInToken, null, $signInResult->data()['oauthAccessToken'], null, null);
```

I will test the other approach of unlinking the provider.

**Comment by jeromegamez** [comment]
> You mean trying a secondary login with that oauth access token? I'll try, let me see :/ seems strange to have to do 2 logins, doesn't it?

You're right, I forgot the issue in that suggestion 🙈.

Unlinking and let the user re-link the Facebook-Account (if this even works) would be a suboptimal workaround anyway; I'm afraid the only way to remedy the underlying problem is to raise a ticket with Firebase directly and ask them why the tokens are not included when signing in 🤔

**Comment by azurlake** [comment]
OK, I also tried unlinking the Facebook provider before trying. No luck.
Actually when obtaining the password reset link, the Facebook provider disappears from Firebase (it seems to be automatically unlinked), and the "provider" column appears empty for this account until I reset the password - at this point, the envelop icon appears. But at this point, and even before when there are no providers listed, the Facebook login fails in the same way - login OK but no access tokens.

**Comment by azurlake** [comment]
> > You mean trying a secondary login with that oauth access token? I'll try, let me see :/ seems strange to have to do 2 logins, doesn't it?
> 
> You're right, I forgot the issue in that suggestion 🙈.
> 
> Unlinking and let the user re-link the Facebook-Account (if this even works) would be a suboptimal workaround anyway; I'm afraid the only way to remedy the underlying problem is to raise a ticket with Firebase directly and ask them why the tokens are not included when signing in 🤔

Thanks for this suggestion - I'll create the ticket to them. You can close this issue if you think there's nothing to do on this side! Thanks for your help.
