### ISSUE TITLE
Catch 401 Unauthorized response

### ISSUE THREAD

**Issue by jdknopp** [kreait/firebase-php#766]
### Describe the feature you would like to see

Some percentage of notices we send out trigger a Guzzle error that just provides a useless "401 Unauthorized". There is no information in the stack to figure out where from within the firebase-php library it is originating and no further details about the error or the payload that caused it. Other notices succeed as expected.

My request is if this error could be caught to provide more info about what's happening and to allow calling code to handle the error.

I'm guessing this may be the same situation as #68 in which case this feature is already in the works, pending Firebase cooperating. It may be useful to catch this error even without additional info though, as right now my code below doesn't catch it even with the generic Exception catch at the end, so I'm left with a fatal error instead of a handled one.

```
        $factory = (new Kreait\Firebase\Factory)->withServiceAccount($FIREBASE);
        $messaging = $factory->createMessaging();
        $notification = [
                'title' => $title,
                'body' => $body,
                'showWhenInForeground' => true
        ];
        $protoMessage = ( $url != '' )
                ? Kreait\Firebase\Messaging\CloudMessage::withTarget('token', "PUSH_TOKEN_PLACEHOLDER")
                        ->withNotification($notification)
                        ->withData([ 'url' => $url ])
                : Kreait\Firebase\Messaging\CloudMessage::withTarget('token', "PUSH_TOKEN_PLACEHOLDER")
                        ->withNotification($notification);
        foreach ($to as $token) {
                try {
                        $message = $protoMessage->withChangedTarget('token', $token);
                        $messaging->send($message);
                } catch (\Kreait\Firebase\Exception\Messaging\NotFound $e) {
                        // Bad token, delete it
                        trigger_error('Bad push token '.$token."\n\n".$e->getMessage(),E_USER_WARNING);
                } catch (Exception $e) {
                        trigger_error('App notification failed to '.$token."\n\n".$e->getMessage(),E_USER_WARNING);
                }
        }
```

**Comment by Badboiopenp** [comment]
Release

**Comment by jeromegamez** [comment]
Please try catching `Throwable` instead of `Exception`, that will definitely allow you to handle errors, and also show the exception trace to figure out where it came from.

Also, based on your code example, it might be advisable to use the `sendMulticast()` or `sendAll()` methods instead - depending on the number of messages this will save you processing time and definitely requests (I don't know your use case, just wanted to mention it).

**Comment by jdknopp** [comment]
Thanks Jerome. That did indeed provide a lot more info. Appears to have been the result of a bad APNs token (even though it _was_ working fine and Apple indicated it was still valid).

Re Multi/All: tried before but couldn't get it working. Will look at that again though.

Thanks again, and sorry, clearly not an issue with your library.

**Comment by jeromegamez** [comment]
Don't be sorry, it could as well have been a problem or an opportunity for improvement in the SDK.

Did the response/error message contain some text/information about the specific issue? If yes, could you share it with me, preferably with the full stack trace when the error is thrown? Perhaps I can then convert it to a more specific exception when the problem occurs.

**Comment by jdknopp** [comment]
Here's the beginning of the Throwable dump. I think it includes all the useful info there is to be found (the stack continues long past this but appears to be mostly basic http details from Guzzle, but let me know if the pages-long output is needed).

```Kreait\Firebase\Exception\Messaging\AuthenticationError::__set_state(array(
   'message' => 'Auth error from APNS or Web Push Service',
   'string' => '',
   'code' => 401,
   'file' => '<PATH>/vendor/kreait/firebase-php/src/Firebase/Exception/Messaging/AuthenticationError.php',
   'line' => 22,
   'trace' => 
  array (
    0 => 
    array (
      'file' => '<PATH>/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingApiExceptionConverter.php',
      'line' => 102,
      'function' => 'withErrors',
      'class' => 'Kreait\\Firebase\\Exception\\Messaging\\AuthenticationError',
      'type' => '->',
      'args' => 
      array (
        0 => 
        array (
          'error' => 
          array (
            'code' => 401,
            'message' => 'Auth error from APNS or Web Push Service',
            'status' => 'UNAUTHENTICATED',
            'details' => 
            array (
              0 => 
              array (
                '@type' => 'type.googleapis.com/google.firebase.fcm.v1.FcmError',
                'errorCode' => 'THIRD_PARTY_AUTH_ERROR',
              ),
              1 => 
              array (
                '@type' => 'type.googleapis.com/google.firebase.fcm.v1.ApnsError',
                'statusCode' => 403,
                'reason' => 'InvalidProviderToken',
              ),
            ),
          ),
        ),
      ),
    ),```

**Comment by jeromegamez** [comment]
Thank you for sharing! I think the rest of the stack trace is not needed, it looks indeed as if the SDK's API Exception Converter is already catching the error and extracting the error message.

With this information that I just looked up again as well, Instead of catching the catch-all `Throwable` it should be enough to catch `Kreait\Firebase\Exception\MessagingException` or the specific exceptions in `src/Firebase/Exception/Messaging` to handle different errors differently. I'm sure you've already seen that, but I'm saying it just in case and for others that might stumble over this while researching a similar problem.

Thanks again!

**Comment by jdknopp** [comment]
Thank you.
Ultimately my mistake was thinking that a simple Exception catch would deal with anything (except the "Bad push token" error I catch separately), not realizing a more general Throwable was necessary.
