### ISSUE TITLE
PHP Promises using guzzle

### ISSUE THREAD

**Issue by prantikv** [kreait/firebase-php#77]
Hey there,
Loving the plugin as it makes my life easy to manage only one server on which I run my blog and not a nodejs server, not to mention the cost of an additional server.

Is it possible to incorporate promises into the SDK using [guzzle](https://github.com/guzzle/promises).

I haven't tried it though, but one can implement guzzle along side firebase SDK as well. But was wondering if this can be implemented out of the box.

-Thanks

**Comment by jeromegamez** [comment]
That's a great idea, consider this issue a new item on my todo list :+1:. I'm currently in the process of refactoring the library for a next major release and will keep this in mind. Thank you!

**Comment by jeromegamez** [comment]
It will perhaps not be labeled "Promises" and use another solution than Guzzle, but I got the gist and will work something out :)

**Comment by soundsgoodsofar** [comment]
Would be great if they *could* be labeled promises and use guzzle!  They're fairly widely used, and interoperability would be wonderful to support promise chaining, etc.

If you want an example, the AWS sdk is a good example of a similar library that was written on top of the guzzle/promise architecture.  I've found it convenient to use myself.

https://aws.amazon.com/blogs/developer/tag/guzzle/
