### ISSUE TITLE
Issue Messaging Unable to determine the Firebase Project ID

### ISSUE THREAD

**Issue by MODE83-PROJET-DEV** [kreait/firebase-php#779]
### Describe the bug

It is impossible to use your API, no documentation to determine how to bootstrap Firebase services correctly.

I used the code below to connect to the API:

require_once $_SERVER['DOCUMENT_ROOT'] . '/vendor/autoload.php';
use Kreait\Firebase\Factory;
use Kreait\Firebase\Messaging\CloudMessage;
use Kreait\Firebase\Messaging\Notification;

$factory = new Factory;
$factory->withServiceAccount($_SERVER['DOCUMENT_ROOT'] . '/app/data/configuration/firebase_client.json');

$messaging = $factory->createMessaging();

$message = CloudMessage::withTarget('topic', 'nom_de_votre_topic');
$message->withNotification(Notification::create('Titre de la notification', 'Contenu de la notification'));

$messaging->send($message);

I got the json file which is on my PHP server
I have an error that is triggered: 
Fatal error: Uncaught Kreait\Firebase\Exception\RuntimeException: Unable to determine the Firebase Project ID 
\kreait\firebase-php\src\Firebase\Factory.php on line 595

### Installed packages

```json
{
    "require": {
        "kreait/firebase-php": "^7.1"
    }
}
```

### PHP version and extensions

```shell
php 8.1 with composer enabled
```

### Steps to reproduce the issue.

require_once $_SERVER['DOCUMENT_ROOT'] . '/vendor/autoload.php';
use Kreait\Firebase\Factory;
use Kreait\Firebase\Messaging\CloudMessage;
use Kreait\Firebase\Messaging\Notification;

$factory = new Factory;
$factory->withServiceAccount($_SERVER['DOCUMENT_ROOT'] . '/app/data/configuration/firebase_client.json');

$messaging = $factory->createMessaging();

$message = CloudMessage::withTarget('topic', 'nom_de_votre_topic');
$message->withNotification(Notification::create('Titre de la notification', 'Contenu de la notification'));

$messaging->send($message);

### Error message/Stack trace

```shell
Fatal error: Uncaught Kreait\Firebase\Exception\RuntimeException: Unable to determine the Firebase Project ID 
\kreait\firebase-php\src\Firebase\Factory.php on line 595
```

### Additional information

As I said I don't have any documentation for this step, I found sample code but I'm afraid it's not enough

**Comment by jeromegamez** [comment]
```php
$factory = new Factory;
$factory->withServiceAccount(...);
```

The factory is immutable, so `withServiceAccount()` doesn't modify the state of `$factory` but returns a new instance.

You can do either

```php
$factory = new Factory;
$factory = $factory->withServiceAccount(...);
```

or

```php
$factory = (new Factory)
    ->withServiceAccount(...)
    // ...
;
```

You can find a QuickStart usage example right on the frontage of the documentation at https://firebase-php.readthedocs.io/en/

The Troubleshooting page (https://firebase-php.readthedocs.io/en/stable/troubleshooting.html) talks about the use of immutable objects.

On a personal note, I feel frustrated to read "impossible to use" and "no documentation" when many projects use the SDK and the documentation is there. 

Also, I would have appreciated if you had used the tools GitHub provides to format your code and had followed the hints in the issue template - it took me a considerable amount of time to parse the unformatted text and code.

**Comment by MODE83-PROJET-DEV** [comment]
"On a personal note, I feel frustrated to read "impossible to use" and "no documentation" when many projects use the SDK and the documentation is there."

Ok and where can I find the PHP documentation ? because I did not find it and the url you provide refers me to a page not found.

"Also, I would have appreciated if you had used the tools GitHub provides to format your code and had followed the hints in the issue template - it took me a considerable amount of time to parse the unformatted text and code."

I don't know what you're talking about ?! I rarely use Github.

**Comment by MODE83-PROJET-DEV** [comment]
If I had the information I'm looking for I would have avoided wasting your time. Because I'm also losing time believe me.

**Comment by jeromegamez** [comment]
My first URL didn't work because of a copy paste problem on my phone (I'm currently on the road), but the second one worked. Here's the correct one (also linked in the project description on the repos page: https://firebase-php.readthedocs.io

That you are rarely using GitHub of course explains that it wasn't possible for you to make it easier for me to help you, or that you didn't find the link to the docs on the front page of this repo. A Google search for "firebase php" returns the link to the docs as first result.

Please consider: this is a free library that I'm maintaining in my limited free time and for which I'm not paid. If you're not happy with it, feel free to copy and modify it to your needs, or use another library that you like better. We can, of course, also talk about paid consulting services so that I can provide you with 1:1 support.

I addressed the particular problem that I extracted from you report, so I'm closing this issue. Feel free to add further comments, if you wish, but I'd appreciate if you could be a little bit friendlier, because that would definitely increase my motivation to provide you with help in general, and in particular with a problem that isn't a problem within this library or its documentation.

**Comment by MODE83-PROJET-DEV** [comment]
Ha sorry if you work for Google and Microsoft for free.

Despite the communication problem I found what I wanted and I thank you.

Otherwise it works well indeed, sorry if I was unpleasant with you.

But not used to chatting on Github, my English is limited.

Cordially

**Comment by MODE83-PROJET-DEV** [comment]
Concretely I find it a pity that you are not paid for the work you have done.
You really deserve to be hired and paid for this! It's absolutely amazing to read this.

The worst is that we pay Firebase on our side and I find that scandalous.

In any case if services such as you offer existed, I think I would have paid for the service a long time ago, you deserve it.

None of your competitors convinced me, apart from you.

Best wishes.

**Comment by jeromegamez** [comment]
Thank you for your kind words, and sorry that I reacted so poorly earlier - I sometimes forget that many of us developers are not native speakers (myself included) and sometimes it's really just a misunderstanding.

Another reason is that I have been addressed a few times in an unkind manner here, and not everyone takes the time to explain why the communication might have gone wrong, so I thank you for taking the time to do it! 🌺

**Comment by jeromegamez** [comment]
(Closed, but the comments are still open)
