### ISSUE TITLE
Did namespace change?

### ISSUE THREAD

**Issue by Greg767** [kreait/firebase-php#78]
Hi,
I have installed your library with composer and I am unable to use Factory() as per your documentation since its not found.  Did something change? If yes, how do I use the JSON file with the config?
Thanks

**Comment by jeromegamez** [comment]
Which version of the library are you using? If you are running PHP 5.x, you probably have version 1.x installed and should refer to the 1.x documentation here: http://firebase-php.readthedocs.io/en/1.x/

**Comment by Greg767** [comment]
in composer json I find this: "kreait/firebase-php": "^0.6.2"
I have PHP 5.6 on the server
In that version I don't even have setAuthConfigFile.
I have my code in Codeigniter and I am not a Composer expert. Could you please help what the command to upgrade to 1.x?
Thanks very much

**Comment by Greg767** [comment]
OK I understand why it happens... on my WAMP I have PHP 5.4 so it install 0.6.x. I will update my php on my computer and will try to update after. Thanks. (I have found what to command to update)

**Comment by jeromegamez** [comment]
Glad you sorted it out - PHP 5.4 really is indeed very old :). If you can update to PHP 7 and your CodeIgniter project supports it, I would definitely recommend that. Version 2.x of this library is a lot nicer than the 1.x version :).
