### ISSUE TITLE
Add playgames.google.com to provider when using signInWithIdpIdToken

### ISSUE THREAD

**Issue by ghdnjs9012** [kreait/firebase-php#785]
### Describe the feature you would like to see

After logging in with playgames, if I enter playgames.google.com in the provider, I get an INVALID_CREDENTIAL_OR_PROVIDER_ID error. Can you add the provider in the official documentation?

	        $client = new Google_Client();
	        $client->setClientId($clientId);
	        $client->setClientSecret($clientSecret);  
	        $client->setRedirectUri($redirectUri);
	        $client->addScope('https://www.googleapis.com/auth/games');
	        $client->addScope(['email', 'profile']);
	        $service = new Google_Service_Oauth2($client);
	        $client->setAccessType('offline');

	        if (!isset($_GET['code'])) {
		        $authUrl = $client->createAuthUrl();
		        header('Location: ' . filter_var($authUrl, FILTER_SANITIZE_URL));
	        } else {
		        $code = $_GET['code'];
		        $token = $client->fetchAccessTokenWithAuthCode($code);
		        
		        try {
			        $factory = (new Factory)->withServiceAccount('../service_acount_key.json');
			        $auth = $factory->createAuth();
			        $signInResult = $auth->signInWithIdpIdToken('playgames.google.com', $token["id_token"]);
			        $authId = $signInResult->firebaseUserId();
		        } catch (FailedToVerifyToken $e) {
		        }
	        }

**Comment by jeromegamez** [comment]
Could you try this:

```php
$signInResult = $auth->signInWithIdpAccessToken('playgames.google.com', $token["access_token"])
```

As for the documentation, I currently don't see where I could add something, could you give me a hint where on https://firebase-php.readthedocs.io/en/stable/authentication.html#sign-in-with-idp-credentials you would have expected more information?

If you're really meaning the _official_ documentation at https://firebase.google.com/docs/projects/provisioning/configure-oauth#add-idp, I cannot edit the docs there, this is an unofficial SDK here 😅

**Comment by ghdnjs9012** [comment]
I'm sorry. The official document says we're only applying for Android

If you call the code you requested
Fatal error: Uncaught Kreait\Firebase\Auth\SignIn\FailedToSignIn: INVALID_CREDENTIAL_OR_PROVIDER_ID : Invalid IdP response/credential: http://localhost?

You get this kind of error
