### ISSUE TITLE
ConditionalValue docs don't match `basedOn` method definition parameters

### ISSUE THREAD

**Issue by anairamzap-mobomo** [kreait/firebase-php#786]
### Describe the feature you would like to see

Hi, wanted to report an error on the documentation, probably it does not qualify as a "Feature request", but certainly is not a Bug nor a security vulnerability, so feel free to change the issue type to whatever you think is best.

We were trying to set a parameter with a couple of conditional values depending on a condition already created on Firebase. We looked at the docs here: https://firebase-php.readthedocs.io/en/latest/remote-config.html#conditional-values and they state:

```php
$germanLanguageCondition = RemoteConfig\Condition::named('lang_german')
    ->withExpression("device.language in ['de', 'de_AT', 'de_CH']");

$germanWelcomeMessage = RemoteConfig\ConditionalValue::basedOn($germanLanguageCondition, 'Willkommen!');
``` 
But when checking the `ConditionalValue` class [basedOn](https://github.com/kreait/firebase-php/blob/7.x/src/Firebase/RemoteConfig/ConditionalValue.php#L51) method we realised the method only has a single parameter (`$condition`) which can be a string or a Condition obj:

```php
    /**
     * @param non-empty-string|Condition $condition
     */
    public static function basedOn($condition): self
```
We also checked other/older docs versions, but all looked the same.

I think the docs should be updated to something like:

```php
$germanLanguageCondition = RemoteConfig\Condition::named('lang_german')
    ->withExpression("device.language in ['de', 'de_AT', 'de_CH']");

$germanWelcomeMessage = ConditionalValue::basedOn($germanLanguageCondition)->withValue('Willkommen!');
```
So the value is not send as a param to the basedOn method but added with the `withValue` method.

I'll create a PR to add this fix suggestion to the docs.

Thanks,
Mariana

**Comment by jeromegamez** [comment]
Thank you very much, also for the detailed description, this way I could confidently merge this on the phone instead of having to look everything up 😅. Much appreciated! 🌺
