### ISSUE TITLE
Integrate Firebase Phone Authentication

### ISSUE THREAD

**Issue by mohammadSnamani** [kreait/firebase-php#791]
### Describe the feature you would like to see

Hello every body i want to use signInWithPhoneNumber class for use phone authentication 
how can i use it ?

**Comment by jeromegamez** [comment]
Server-side sign-in with a phone number is not supported by Firebase Admin SDKs.

You can find more information, including links to related information, in this email thread: https://groups.google.com/g/firebase-talk/c/cWdF8gkOH3w
