### ISSUE TITLE
add compatibility for psr/http-message 2.0 version

### ISSUE THREAD

**Issue by monta990** [kreait/firebase-php#794]
### Describe the feature you would like to see

its possible add compatibility for psr/http-message 2.0 version, this can helps us to keep updated our projects.

**Comment by jeromegamez** [comment]
The main branch already has the widened version constraints, but I think `google/auth`, which the SDK relies on, doesn't support it yet (I'm currently not at the desk so I can't check myself).

You could try requiring the main branch in your project and see if that updates the dependency - if it does, I can make a new release 🤞🏻

**Comment by jeromegamez** [comment]
Implemented with https://github.com/kreait/firebase-php/releases/tag/7.3.1, https://github.com/kreait/firebase-php/releases/tag/6.9.6 and https://github.com/kreait/firebase-php/releases/tag/5.26.5 🚀
