### ISSUE TITLE
Parameter value data type

### ISSUE THREAD

**Issue by stipic** [kreait/firebase-php#795]
### Describe the feature you would like to see

Hi, 

i would like tu suggest feature request or maybe that feature exists but i don't understand how to use it.

i saw on firebase docs that is possible to set parameter value data types: https://firebase.google.com/docs/remote-config/parameters#parameter_value_data_types

i have problem whenever i update my firebase parameters it always set data type to string. Example my parameter is boolean type (true or false) and when i update it set data type to string instead of boolean.

maybe you know how i can send “ value_type" for each parameter i'am updating.

**Comment by jeromegamez** [comment]
@stipic Could you please give #801 a go and tell me (in the PR comment thread) if this works for you?
