### ISSUE TITLE
Class 'Firebase\Factory' not found

### ISSUE THREAD

**Issue by sagardabade** [kreait/firebase-php#80]
i have included autoload file of composer ,using same code as on git 

$firebase = (new Firebase\Factory())
    ->withCredentials(__DIR__.'/xyz.json')
    ->withDatabaseUri('https://xyz.firebaseio.com')
    ->create();

**Comment by jeromegamez** [comment]
There's a missing `\` in front of `Firebase` - also make sure you have the 2.x release and are running on PHP7.

**Comment by acruche** [comment]
Hello,

I'm having the same problem. I'm using PHP 7.1.1.

I followed this installation guide.
https://firebase-php.readthedocs.io/en/latest/overview.html#installation
