### ISSUE TITLE
Why MessageData does not support multi-dimension arrays?

### ISSUE THREAD

**Issue by luninroman** [kreait/firebase-php#800]
### Describe the feature you would like to see

Why MessageData does not support multi-dimension arrays?

**Comment by jeromegamez** [comment]
Because that's how Google defined it 😅

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#resource:-message

**Comment by luninroman** [comment]
@jeromegamez oh indeed, excuse me then, gonna ask them;)
