### ISSUE TITLE
Phone number authentication issue with version 7^

### ISSUE THREAD

**Issue by harshvardhanbarhan** [kreait/firebase-php#802]
### Describe the bug

When i am trying to send a otp via version 7, 

methods are not available like

$auth->signInWithPhoneNumber($phoneNumber);

Here is my code

$phone_number = "+919759914600";
$factory = (new Factory)->withServiceAccount('../google_credentials.json');
        
        $auth = $factory->createAuth(); 
        $auth->signInWithPhoneNumber($phoneNumber);

### Installed packages

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "aws/aws-sdk-php": "^3.209",
        "coderello/laravel-passport-social-grant": "^3.0",
        "fideloper/proxy": "^4.4",
        "firebase/php-jwt": "^6.6",
        "fruitcake/laravel-cors": "^2.0",
        "google/apiclient": "^2.12.1",
        "guzzlehttp/guzzle": "^7.0.1",
        "hybridauth/hybridauth": "^3.7",
        "kreait/firebase-php": "^7.3",
        "laravel/framework": "^8.12",
        "laravel/passport": "^10.1",
        "laravel/socialite": "^5.2",
        "laravel/telescope": "^4.14",
        "laravel/tinker": "^2.5",
        "league/flysystem-aws-s3-v3": "^1.0",
        "maatwebsite/excel": "^3.1",
        "mavinoo/laravel-batch": "^2.2",
        "stripe/stripe-php": "^7.114",
        "swiftmailer/swiftmailer": "^6.2"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^0.0.5",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

### PHP version and extensions

```shell
php version is 8.1
```

### Steps to reproduce the issue.

```shell
# Insert the commands issued in the terminal if they are needed
# to reproduce the issue. Otherwise, delete this code block.
```

```php
// Insert the PHP code to reproduce the issue. Please ensure that it is code that
// can be copy pasted to reproduce it.
```

### Error message/Stack trace

```shell
Call to undefined method Kreait\Firebase\Auth::signInWithPhoneNumber()
```

### Additional information

I want to know how can i achieve the send otp and verify otp from this package

**Comment by jeromegamez** [comment]
As far as I remember (I haven't checked) the SDK never supported phone number authentication, what made you think it did?

To my knowledge, phone number authentication or issuing OTPs via an Admin SDK are not possible, and not advisable.

https://stackoverflow.com/a/55171266/284325

**Comment by jeromegamez** [comment]
If you can provide me with sources where another Firebase Admin SDK supports this or something similar, I can have a look.

**Comment by harshvardhanbarhan** [comment]
Here is what i have checked on internet regarding the plugin

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;
use Kreait\Firebase\Auth;

$serviceAccount = ServiceAccount::fromJsonFile('/path/to/serviceAccountCredentials.json');

$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->create();

$phoneNumber = '+123456789'; // Replace with the desired phone number

$auth->signInWithPhoneNumber($phoneNumber);

**Comment by jeromegamez** [comment]
Sorry, but where on the internet? The source of truth are the SDK docs at https://firebase-php.readthedocs.io/ - you can use the version switcher to inspect older releases; I honestly don't remember ever having had a sign in with phone number (I could be wrong, but I need proof and will then apologize for not remembering 😅).

You can _find_ a user by phone number (https://firebase-php.readthedocs.io/en/7.x/user-management.html#get-information-about-a-specific-user) but it's definitely not possible to generate or verify OTPs. OTPs for devices are handled within the Firebase _Client_ SDKs directly on the device.

**Comment by harshvardhanbarhan** [comment]
hi @jeromegamez 
May be i am wrong, but it tried the solution from this

https://chat.openai.com/share/58022604-2a05-4ab9-b1dd-8a4c3e8bb471


I want to confirm that is it safe to use Firebase client SDK for phone number authentication
Because keys will remain in front-end in the case of Firebase client sdk

**Comment by jeromegamez** [comment]
ChatGPT is wrong.

**Comment by jeromegamez** [comment]
Here's your chat continued: https://chat.openai.com/share/ccb6baed-bed1-458f-989f-7f7c31ca4ac4

![image](https://github.com/kreait/firebase-php/assets/67554/1158be7b-87ef-4715-a702-382739c8a52a)
