### ISSUE TITLE
Call to undefined method Kreait\Firebase\Auth::getUserInfo()

### ISSUE THREAD

**Issue by SRLQNL** [kreait/firebase-php#806]
### Describe the bug

when i use $auth->getUserInfo($user->getUid()); an error occurs

### Installed packages

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "google/cloud-firestore": "^1.34",
        "google/cloud-storage": "^1.31",
        "guzzlehttp/guzzle": "^7.2",
        "kreait/laravel-firebase": "5.2.0",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

### PHP version and extensions

```shell
php 8.1
```

### Steps to reproduce the issue.

-

### Error message/Stack trace

```shell
-
```

### Additional information

`<?php

namespace App\Http\Controllers;

use Kreait\Firebase\Exception\Auth\FailedToVerifyToken;
use Kreait\Firebase\Contract\Storage;
use Kreait\Firebase\Auth;
use Kreait\Firebase\Factory;
use Google\Cloud\Firestore\FirestoreClient;
use Kreait\Firebase\Auth\CreateSessionCookie\FailedToCreateSessionCookie;
use Kreait\Laravel\Firebase\Facades\Firebase;
use Illuminate\Http\Request;

class RegistController extends Controller
{
    public function submit(Request $request){
        $auth = app('firebase.auth');    
        $userProperties = [
        'email' => $request->email,
        'password' => $request->password,
        ];

        $createdUser = $auth->createUser($userProperties);
        $database = app('firebase.firestore')->database()->collection('Users')->document($createdUser->uid);

        $image = $request->file('image');
        $firebase_path = 'Profile_Images/';
        $localfolder = public_path('firebase-temp-uploads').'/';
        $name = $createdUser->uid;
        $extension = $image->getClientOriginalExtension();
        $file = $name;
        $image->move($localfolder,$file);
        $uploadedfile = fopen($localfolder.$file,'r');
        $object = app('firebase.storage')->getBucket()->upload($uploadedfile,['name'=>$firebase_path.$file]);
        $expiresAt = new \DateTime('15 min');
        $imageReference = app('firebase.storage')->getBucket()->object("Profile_Images/".$file);
        $image = $imageReference->signedUrl($expiresAt);
        $database->set([
            'userBio' => $request->message,
            'userBioLink' => $request->number,
            'userEmail' => $request->email,
            'userProfileURL' => $image,
            'userUID' => $createdUser->uid,
            'username' => $request->name,

        ]);
    }

    public function auth(Request $request){
        $auth = app('firebase.auth');
        $email = $request->input('email'); 
        $password = $request->input('password'); 
        $user = $auth->signInWithEmailAndPassword($email, $password);
        $userInfo = $auth->getUserInfo($user->getUid());
    }
}`

**Comment by jeromegamez** [comment]
The error message tells you already what the problem is: the `Auth` class has no `getUserInfo()` method. The correct method is `getUser()`.

https://firebase-php.readthedocs.io/en/stable/user-management.html#get-information-about-a-specific-user

Please read and follow the documentation 🙏🏻
