### ISSUE TITLE
Undefined property: Kreait\Firebase\Auth\SignInResult::$uid

### ISSUE THREAD

**Issue by SRLQNL** [kreait/firebase-php#808]
### Describe the bug

[Undefined property: Kreait\Firebase\Auth\SignInResult::$uid](http://127.0.0.1:8000/auth-submit#top)

### Installed packages

```json
-
```

### PHP version and extensions

```shell
-
```

### Steps to reproduce the issue.

-

### Error message/Stack trace

```shell
-
```

**Comment by jeromegamez** [comment]
See #803, #806, #807
