### ISSUE TITLE
how to disable browsing pages for unauthorized users?

### ISSUE THREAD

**Issue by SRLQNL** [kreait/firebase-php#809]
### Describe the bug

how to disable browsing pages for unauthorized users?

### Installed packages

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "google/cloud-firestore": "^1.34",
        "google/cloud-storage": "^1.31",
        "guzzlehttp/guzzle": "^7.2",
        "kreait/laravel-firebase": "5.2.0",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

### PHP version and extensions

```shell
php 8.1
```

### Steps to reproduce the issue.

-

### Error message/Stack trace

```shell
-
```

### Additional information

You can no longer send me to the documentation.
Can you give me a way to contact you if I need help (to avoid writing questions in the bugs anymore)

**Comment by jeromegamez** [comment]
I had prepared a long reply explaining how I maintain this Open Source project with zero funding and what you can expect and not expect from me, but I'll keep it short:

I don't provide free 1:1 support. If you're interested in having a direct line to me, the highest sponsorship tier entitles you to it or tell me how to contact you, and I can provide you with my hourly rate, if you need proper invoices.

You've opened four issues in the past three days with solutions that you could have figured out yourself. This fifth issue is not about the SDK but about Laravel in general. For this I can't provide free support as well.

The issues of this project are for bugs. If you tell me that I can no longer send you to the documentation, I won't.

If you choose to open further issues without context and/or inspecting the docs or code, I will tell you that I cannot help you and link to this comment. 

If you're not satisfied with what the SDK or I can provide, feel free to use another Firebase project, but please don't tell me what I can or cannot do.
