### ISSUE TITLE
HTTP error codes on exceptions

### ISSUE THREAD

**Issue by katjuncker** [kreait/firebase-php#819]
### Describe the feature you would like to see

Currently, when an exception is thrown sending a cloud message, the exceptions code is 0. The firebase API, however, returns HTTP codes to indicate what actually went wrong. (400 = invalid token, 404 = unknown token, etc.) and it would be helpful to be able to handle these events via the code set on the exceptions. 

The use case is that you want to delete unknown tokens so that they don't keep getting sent notifications which will always fail. There are other error codes where you need to keep the tokens because the issue might be a 500 code with Firebase and not caused by an invalid token.

The only current way to handle this is by regexing the exception message to try to figure out what the corresponding error code would be and this is bad because it's relying on undocumented behavior in the Firebase API responses. 

This the code we're having to use to get around this.

```php
$cloudMessage = CloudMessage::withTarget('token', $token->getToken())
    ->withNotification(Notification::create($title, $message, $imageUrl))
    ->withData($data)
;
try {
    $this->messaging->send($cloudMessage);
    $token->setLastSent(new \DateTimeImmutable());
    $this->notificationTokenRepository->save($token);
} catch (\Throwable $e) {
    $this->handleError($token, $e);
}
```

and the error handler
```php
//get the error code
$errorCode = $e->getCode();

//for some reason the code is always 0, so we have to check the message
if ($errorCode == 0) {
    if (str_contains($e->getMessage(), 'Invalid registration token')) {
        $errorCode = 400;
    } elseif (str_contains($e->getMessage(), 'it is not known to the Firebase project')) {
        $errorCode = 404;
    }
}

//400 = invalid token/argument, 404 = token not found/registered
if (in_array($errorCode, [400, 404])) {
    //remove the token from the database
    $this->notificationTokenRepository->delete($token);
} else {
    $this->logger->error('Error sending push notification: ' . '(' . $errorCode . ') - ' . $e->getMessage());
}

```

**Comment by jeromegamez** [comment]
You can catch specific exceptions when try/catching the `send()` method. It's discoverable by inspecting the code or by inspecting the thrown exception, but I obviously have forgotten adding this to the documentation (will do as soon as I find the time). In the meantime, you can look into https://github.com/kreait/firebase-php/blob/53232928c4fdb3c0676d25eea5152454258170e9/src/Firebase/Exception/MessagingApiExceptionConverter.php#L64-L112 to see which HTTP Status code leads to what exception.

With this information, here's what you can do:

```php
try {
    $this->messaging->send($cloudMessage);
    $token->setLastSent(new \DateTimeImmutable());
    $this->notificationTokenRepository->save($token);
} catch (\Kreait\Firebase\Exception\Messaging\NotFound $e) {
    // corresponds to 404
    $this->notificationTokenRepository->delete($token);
    return;
} catch (\Kreait\Firebase\Exception\Messaging\InvalidMessage $e) {
    // corresponds to 400
    $this->logger->error('Invalid Message: ' . $e->getMessage());
    return;
} catch (\Kreait\Firebase\Exception\MessagingException $e) {
    // Another error while performing the send() request
    $this->logger->error('Error sending push notification: ' . $e->getMessage());
} catch (\Throwable $e) {
    $this->logger->error('Not FCM-related error:' . $e->getMessage());
}
```

**Comment by jeromegamez** [comment]
Here's the updated documentation (it will be in the stable branch with the next release): https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html#error-handling

**Comment by katjuncker** [comment]
That's really helpful, thanks so much for the quick reply!
