### ISSUE TITLE
Is it possible to add a domain using the LIB?

### ISSUE THREAD

**Issue by raphaelvserafim** [kreait/firebase-php#823]
### Describe the bug

would it be possible to add a domain using PHP?
<img width="958" alt="Screenshot 2023-09-03 at 5 50 26 PM" src="https://github.com/kreait/firebase-php/assets/68257896/76b2b678-f91c-474c-b8f7-daf44461d184">

### Installed packages

```json
all
```

### PHP version and extensions

```shell
7
```

### Steps to reproduce the issue.

```shell
# Insert the commands issued in the terminal if they are needed
# to reproduce the issue. Otherwise, delete this code block.
```

```php
// Insert the PHP code to reproduce the issue. Please ensure that it is code that
// can be copy pasted to reproduce it.
```

### Error message/Stack trace

```shell
nenhum
```

**Comment by jeromegamez** [comment]
To my knowledge this is not possible. But If you can show me an API documentation or another Admin SDK that can do it, I'll be happy to look into it!
