### ISSUE TITLE
Please give sample code get content from firebase storage 

### ISSUE THREAD

**Issue by Faiznurullah** [kreait/firebase-php#827]
### Describe the feature you would like to see

I hope you can give sample all code for connect php application, example use laravel to connect with firebase, Thanks You Man

**Comment by jeromegamez** [comment]
You can find the Laravel Package at https://github.com/kreait/laravel-firebase and the SDK Documentation at https://firebase-php.readthedocs.io/

This should give you enough to get started 🤞🏻

**Comment by Faiznurullah** [comment]
Thanks You so much
