### ISSUE TITLE
Link to non-existent branches

### ISSUE THREAD

**Issue by szepeviktor** [kreait/firebase-php#834]
### Describe the bug

From #833 

These branches ceased to exist.

https://github.com/kreait/firebase-php/blob/117d4077ffe0ce23f8ae670fe7435aedf50b9a6d/composer.json#L110-L112

### Installed packages

```json
-
```

### PHP version and extensions

```shell
-
```

### Steps to reproduce the issue.

-

### Error message/Stack trace

```shell
-
```

**Comment by jeromegamez** [comment]
Fixed with b993129c5737b551c6b99391f1b93b7f8389bfec, thanks!
