### ISSUE TITLE
Firebase analytics not included

### ISSUE THREAD

**Issue by amirdora** [kreait/firebase-php#836]
### Describe the feature you would like to see

can you include firebase analytics in next update, if yes when.

**Comment by jeromegamez** [comment]
I need more information than that. Please tell me what you want explicitly, and include links to the documentation where that feature is described.

Please make sure this isn't a feature of the client SDKs, and that/if the feature is implemented in one of the official Admin SDKs.

Concerning the "when": as soon as my limited free time allows it. Please also read the funding section in the README of this project.
