### ISSUE TITLE
Add support to use storage from emulators suite

### ISSUE THREAD

**Issue by yopaz-tuanha** [kreait/firebase-php#839]
### Describe the feature you would like to see

Hi, can you add support to use storage from emulators suite.

Something like `FIREBASE_STORAGE_EMULATOR_HOST`

**Comment by jeromegamez** [comment]
The SDK provides just a bridge to the official Cloud Storage Library. Have you already tried setting the variable?

https://firebase.google.com/docs/emulator-suite/connect_storage#admin_sdks
