### ISSUE TITLE
sendMulticast is based on legacy Firebase API

### ISSUE THREAD

**Issue by hasan-app4orce** [kreait/firebase-php#843]
### Describe the feature you would like to see

Hi,
I have a question that whether sendMulticast($message, $deviceTokens) is based on legacy Firebase API or HTTP V1 API?
As mentioned on Firebase Document, we can send push notification to individual device registration token, topic, and Condition. But have not found anything related to send a push notification to multiple specific registration tokens?
Can you please help?
Thanks

**Comment by jeromegamez** [comment]
The SDK uses exclusively the HTTP V1 API, no legacy here 😄.

The `sendMulticast()` method originally used a dedicated endpoint with multipart requests, which has been deprecated. Now it just™ remains a convenience method which calls the `sendAll()` method internally.

https://github.com/kreait/firebase-php/blob/393a751a0a15291774070688cbfa4d0e954b9e54/src/Firebase/Messaging.php#L66-L82

I hope this helps!

**Comment by hasan-app4orce** [comment]
Hi,
Thanks for the reply.
So it means sendAll method is internally using (https://fcm.googleapis.com/v1/projects/{myproject}/messages:send) endpoint and looping through on each of the registration token and sending a push notification on it. We can use it as it is based on HTTP V1 API. Right?

**Comment by jeromegamez** [comment]
Yes.

This project is Open Source - if you are interested in the internals and which API endpoints are called, you can look it up by inspecting the code 🕵🏻‍♂️

**Comment by hasan-app4orce** [comment]
Sure. Thanks for the help.
