### ISSUE TITLE
Allow php 8.3

### ISSUE THREAD

**Issue by ankurk91** [kreait/firebase-php#845]
### Describe the feature you would like to see

php 8.3 has been released but this packages does not allow to be installed on php 8.3

**Comment by jeromegamez** [comment]
Correct!

 PHP 8.3 support will come, don't worry! If you're feeling adventurous, try `composer update --ignore-platform-req=php` or `--ignore-platform-reqs`🤞

**Comment by jeromegamez** [comment]
Please follow https://github.com/kreait/firebase-php/pull/847 for progress

**Comment by jeromegamez** [comment]
Implemented with f5f499bffd84c576bee26dace26a35e0130a1642 and released with https://github.com/kreait/firebase-php/releases/tag/7.9.0
