### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by acruche** [kreait/firebase-php#85]
Hello, 

I'm having the following problem, any idea how to solve it?

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\xampp\htdocs\futebol\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\xampp\htdocs\futebol\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\futebol\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\futebol\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\futebol\vendor\guzzlehttp\guzzle\src\Handler\Proxy.ph in C:\xampp\htdocs\futebol\vendor\kreait\firebase-php\src\Firebase\Exception\ApiException.php on line 28

**Comment by jeromegamez** [comment]
Please have a look at http://firebase-php.readthedocs.io/en/latest/troubleshooting.html, perhaps the steps described there can help with the problem.

SSL errors usually hint to a problem of the system the application is running on, so maybe it could also help if you upgrade your xampp environment (if there is an update available).

(I copied the answer from #62 ;))
