### ISSUE TITLE
Cannot mock final class for phpunit tests as it's return type is other final class

### ISSUE THREAD

**Issue by hitrov** [kreait/firebase-php#858]
### Describe the bug

there's a final class 
```php
Auth implements Kreait\Firebase\Contract\Auth
```
which you cannot mock. 
interface is used to create an instance upon dependency injection, 
and there's no problem to create Mock class which also implements it and use during testing.

problem is that some of the methods have return type of class (not interface!) which is also final, like
```php
public function getUserByEmail(Stringable|string $email): UserRecord;
```
so that you're getting
```
Class "Kreait\Firebase\Auth\UserRecord" is declared "final" and cannot be doubled
```

### Installed packages

```json
kreait/laravel-firebase
```

### PHP version and extensions

```shell
8.2
```

### Steps to reproduce the issue.

```php
$this->createMock(Kreait\Firebase\Contract\Auth::class);
```

### Error message/Stack trace

```shell
Class "Kreait\Firebase\Auth\UserRecord" is declared "final" and cannot be doubled
```

**Comment by jeromegamez** [comment]
[`UserRecord` is a value object](https://github.com/kreait/firebase-php/blob/e68a64239f5e3602f39704ad61c6608fdcf30155/src/Firebase/Auth/UserRecord.php), and value objects have no interfaces, you can build one to use in your tests:

```php
$userRecord = new \Kreait\Firebase\Auth\UserRecord(...);

$auth = $this->createMock(\Kreait\Firebase\Contract\Auth::class);

$auth
    ->method('getUserByEmail')
    ->willReturn($userRecord)
;
```

I admit it's cumbersome as `UserRecord` is quite big, but you could always add a helper/builder method.

**Comment by hitrov** [comment]
that's exactly what we used to have before, at it worked well with `v4.2.0`
<img width="774" alt="Screenshot 2024-01-22 at 12 48 37" src="https://github.com/kreait/firebase-php/assets/26094610/cb87a3ad-1d58-4370-b883-68c5137b515d">
but apparently not anymore

**Comment by hitrov** [comment]
value object instantiation works fine btw:
```php
UserRecord::fromResponseData([
            'localId' => 'foo',
            'rawId' => 'bar',
            'providerId' => 'baz',
            'createdAt' => (string) now(),
        ])
```

**Comment by hitrov** [comment]
here's reproducible example within GitHub action, hope you don't mind checking it https://github.com/hitrov/laravel-firebase-example/actions/runs/7611886562

**Comment by jeromegamez** [comment]
I see. So, I changed how the `UserRecord` gets constructed, but in my defense, this was two years ago, and I didn't anticipate anyone using it directly. However - it was almost 1.5 years ago, and since it was introduced in a new major release, a breaking change, which was also documented here: https://github.com/kreait/firebase-php/blob/7.x/UPGRADE-7.0.md

That being said, you can use the `fromResponseData()` method, but _should_ the Firebase API responses change, so would this method - for example, would Firebase change the `rawId` field to `raw_id`, you wouldn't know until your tests break again.

If you used the constructor of `UserRecord`, it would be more cumbersome to build it (which could be helped with a builder function), but it would be guaranteed to work at least until the next major release of the SDK

In general, I would recommend seeing the `UserRecord` as a DTO, not as something you should use in tests directly. I would wrap the Firebase SDK in your services and then mock your services instead of the services in the SDK.

For example:

```php
use Kreait\Firebase\Contract\Auth;
use Kreait\Firebase\Exception\Auth\UserNotFound;

final class MyUser
{
    public function __construct(
        public readonly string $userId,
        public readonly string $email,
    ) {}
}

interface UserRepository
{
    public function findById(string $id): MyUser;
}

final class FirebaseUserRepository implements UserRepository
{
    public function __construct(
        private readonly Auth $firebaseAuth
    ) {}

    public function findById(string $id): MyUser
    {
        try {
            $userRecord = $this->firebaseAuth->getUser($id);
        } catch (UserNotFound) {
            throw new RuntimeException("No user found with ID `$id`");
        }

        if ($userRecord->email === null || $userRecord->emailVerified === false) {
            throw new RuntimeException("The user with ID `$id` has no email or it isn't verified");
        }

        return new MyUser($userRecord->uid, $userRecord->email);
    }
}
```

This would allow you to mock/stub your `UserRepository` interface, or create an `InMemoryUserRepository` for your tests, without havin to rely on the SDK.

**Comment by jeromegamez** [comment]
I'm closing the issue since this will not lead to code changes on my side, but feel free to add further comments.

**Comment by hitrov** [comment]
unfortunately it does not help:
* `PHPUnit\Framework\MockObject\RuntimeException: Return value for Tests\Mocks\Auth::getUserByEmail() cannot be generated: Class "Kreait\Firebase\Auth\UserRecord" is declared "final" and cannot be doubled`
* `PHPUnit\Framework\MockObject\RuntimeException: Return value for App\Repository\Interfaces\Auth::changeUserEmail() cannot be generated: Class "Kreait\Firebase\Auth\UserRecord" is declared "final" and cannot be doubled`
* `PHPUnit\Framework\MockObject\RuntimeException: Return value for App\Repository\Interfaces\Auth::createUserWithEmailAndPassword() cannot be generated: Class "Kreait\Firebase\Auth\UserRecord" is declared "final" and cannot be doubled`

commit https://github.com/hitrov/laravel-firebase-example/commit/870bfc270e1b38d45ce1b6b25022d359eb7132cf
pipeline https://github.com/hitrov/laravel-firebase-example/actions/runs/7624758765/job/20767596616

**Comment by hitrov** [comment]
I'll just leave this straightforward example here
```php
public function testGetUserByEmailCalled(): void
    {
        $auth = $this->createMock(\Tests\Mocks\Auth::class);

        $service = new ExampleService($auth);

        $auth->expects($this->once())->method('getUserByEmail');

        $service->execute();
    }
```
`PHPUnit\Framework\MockObject\RuntimeException: Return value for Tests\Mocks\Auth::getUserByEmail() cannot be generated: Class "Kreait\Firebase\Auth\UserRecord" is declared "final" and cannot be doubled
`

**Comment by hitrov** [comment]
Apparently there’s no way of having any of package final classes in the “wrapper” class, we’re forced to create our own…

**Comment by hitrov** [comment]
...which is kinda weird as lots of changes may be needed to let's say wrap `Kreait\Firebase\Auth\SignInResult` to get 
* $idToken
* $accessToken
* $refreshToken
* $ttl
* $firebaseUserId

**Comment by hitrov** [comment]
was there a good reason of having those classes as final?

**Comment by jeromegamez** [comment]
As for the service classes, this article explains it best: https://ocramius.github.io/blog/when-to-declare-classes-final/

As for the value objects, I made it a habit to declare them final by default. If you need a `UserRecord` or `SignInResult` when testing one of your project's services, I am firmly convinced they should be part of an Integration Test (or a test using the Firebase Emulator Suite), not a unit test.

However, if need to mock the `Auth` interface, you can do it like this:

```php
<?php

namespace Kreait\Firebase\Tests\Unit\Auth;

use DateTimeImmutable;
use Kreait\Firebase\Auth\SignInResult;
use Kreait\Firebase\Auth\UserMetaData;
use Kreait\Firebase\Auth\UserRecord;
use Kreait\Firebase\Contract\Auth;
use Kreait\Firebase\Exception\Auth\UserNotFound;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    #[Test]
    public function itHandlesSignInResults(): void
    {
        $auth = $this->createMock(Auth::class);

        $auth->method('signInAnonymously')
            ->willReturn(
                SignInResult::fromData([
                    'idToken' => 'idToken',
                    'refreshToken' => 'refreshToken',
                    'accessToken' => 'accessToken',
                    'expiresIn' => 3600,
                ])
            );

        $signInResultForTest = $auth->signInAnonymously();

        $this->assertSame('idToken', $signInResultForTest->idToken());
    }

    #[Test]
    public function itFindsAUser(): void
    {
        $auth = $this->createMock(Auth::class);

        $auth->method('getUser')
            ->with('uid')
            ->willReturn(
                $this->userRecord(
                    uid: 'uid',
                    email: 'email@example.org',
                    tenantId: 'my-tenant'
                )
            );

        $userRecord = $auth->getUser('uid');

        $this->assertSame('email@example.org', $userRecord->email);
        $this->assertSame('my-tenant', $userRecord->tenantId);
    }

    #[Test]
    public function itDoesNotFindAUser(): void
    {
        $auth = $this->createMock(Auth::class);

        $auth->method('getUser')
            ->with('uid')
            ->willThrowException(new UserNotFound());

        $this->expectException(UserNotFound::class);
        $auth->getUser('uid');
    }

    /**
     * @param non-empty-string $uid
     * @param non-empty-string|null $email
     * @param non-empty-string|null $tenantId
     */
    private function userRecord(string $uid, ?string $email = null, ?string $tenantId = null): UserRecord
    {
        $now = new DateTimeImmutable();

        return new UserRecord(
            uid: $uid,
            email: $email,
            emailVerified: true,
            displayName: null,
            phoneNumber: null,
            photoUrl: null,
            disabled: false,
            metadata: new UserMetaData(
                createdAt: $now,
                lastLoginAt: $now,
                passwordUpdatedAt: $now,
                lastRefreshAt: $now,
            ),
            providerData: [],
            mfaInfo: null,
            passwordHash: null,
            passwordSalt: null,
            customClaims: [],
            tenantId: $tenantId,
            tokensValidAfterTime: $now,
        );
    }
}

```

Once done, you can extend the `userRecord()` builder method with as many parameters as you need, I added the `tenantId` just as an example.

The result is that you don't need any mocking except for the interface itself.

In the same way, here's the same example with a wrapper class

```php
<?php

namespace App;

use Kreait\Firebase\Contract\Auth;

class MyService
{
    public function __construct(private readonly Auth $auth)
    {
    }

    public function getTokensForUser(string $uid): array
    {
        return $this->auth
            ->signInAsUser($uid)
            ->asTokenResponse();
    }
}
```

and the corresponding test:

```php
<?php

namespace App\Tests;

use App\MyService;
use Kreait\Firebase\Auth\SignInResult;
use Kreait\Firebase\Contract\Auth;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

class MyServiceTest extends TestCase
{
    #[Test]
    public function itReturnsTokens(): void
    {
        $auth = $this->createMock(Auth::class);

        $auth->method('signInAsUser')
            ->with('uid')
            ->willReturn(
                SignInResult::fromData([
                    'idToken' => 'idToken',
                    'refreshToken' => 'refreshToken',
                    'accessToken' => 'accessToken',
                    'expiresIn' => 3600,
                ])
            );

        $service = new MyService($auth);

        $result = $service->getTokensForUser('uid');

        $this->assertSame('idToken', $result['id_token']);
    }
}
```

I hope this helps.

**Comment by hitrov** [comment]
I greatly appreciate your help and suggestions, they were really helpful 
(including pointing to the need of final classes).

Here's the commit with wrappers removal https://github.com/hitrov/laravel-firebase-example/commit/3f035c02b9b4623f89cd63aeba5e9cd692347b7f 
and fixed pipeline https://github.com/hitrov/laravel-firebase-example/actions/runs/7637499251

apparently you just can't do a thing to the right (screenshot):
<img width="1143" alt="Screenshot 2024-01-24 at 10 36 56" src="https://github.com/kreait/firebase-php/assets/26094610/581f578d-ba6a-4d82-aeff-4d697daa51bd">
the one to the left does work :)
