### ISSUE TITLE
json_decode error

### ISSUE THREAD

**Issue by rajcoder7** [kreait/firebase-php#86]
**Fatal error**: Uncaught Kreait\Firebase\Exception\InvalidArgumentException: json_decode error: Syntax error in C:\xampp\htdocs\Demo\vendor\kreait\firebase-php\src\Firebase\Util\JSON.php:55 Stack trace: #0 C:\xampp\htdocs\Demo\vendor\kreait\firebase-php\src\Firebase\Exception\ApiException.php(21): Kreait\Firebase\Util\JSON::decode('<!doctype html>...', true) #1 C:\xampp\htdocs\Demo\vendor\kreait\firebase-php\src\Firebase\Database\ApiClient.php(78): Kreait\Firebase\Exception\ApiException::wrapThrowable(Object(GuzzleHttp\Exception\ClientException)) #2 C:\xampp\htdocs\Demo\vendor\kreait\firebase-php\src\Firebase\Database\ApiClient.php(58): Kreait\Firebase\Database\ApiClient->request('POST', Object(GuzzleHttp\Psr7\Uri), Array) #3 C:\xampp\htdocs\Demo\vendor\kreait\firebase-php\src\Firebase\Database\Reference.php(343): Kreait\Firebase\Database\ApiClient->push(Object(GuzzleHttp\Psr7\Uri), Array) #4 C:\xampp\htdocs\Demo in C:\xampp\htdocs\Demo\vendor\kreait\firebase-php\src\Firebase\Util\JSON.php on line 55

**Comment by jeromegamez** [comment]
Please make sure you are using the library in a PHP 7 environment - the syntax error indicates that you are using PHP 5.

**Comment by fpilee** [comment]
Same on php 7 and php 7.2
```
vagrant://C:/Users/felipe/Homestead/usr/bin/php7.0 -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=10.0.2.2 /home/vagrant/code/argentinadolar/php/script.php
PHP Fatal error:  Uncaught Kreait\Firebase\Exception\InvalidArgumentException: json_decode error: Syntax error in /home/vagrant/code/argentinadolar/php/vendor/kreait/firebase-php/src/Firebase/Util/JSON.php:58
Stack trace:
#0 /home/vagrant/code/argentinadolar/php/vendor/kreait/firebase-php/src/Firebase/Database/ApiClient.php(42): Kreait\Firebase\Util\JSON::decode('<!DOCTYPE html>...', true)
#1 /home/vagrant/code/argentinadolar/php/vendor/kreait/firebase-php/src/Firebase/Database/Reference.php(353): Kreait\Firebase\Database\ApiClient->push(Object(GuzzleHttp\Psr7\Uri), Array)
#2 /home/vagrant/code/argentinadolar/php/script.php(25): Kreait\Firebase\Database\Reference->push(Array)
#3 {main}
  thrown in /home/vagrant/code/argentinadolar/php/vendor/kreait/firebase-php/src/Firebase/Util/JSON.php on line 58

Fatal error: Uncaught Kreait\Firebase\Exception\InvalidArgumentException: json_decode error: Syntax error in /home/vagrant/code/argentinadolar/php/vendor/kreait/firebase-php/src/Firebase/Util/JSON.php on line 58

Kreait\Firebase\Exception\InvalidArgumentException: json_decode error: Syntax error in /home/vagrant/code/argentinadolar/php/vendor/kreait/firebase-php/src/Firebase/Util/JSON.php on line 58

Call Stack:
    0.0646     352592   1. {main}() /home/vagrant/code/argentinadolar/php/script.php:0
    6.6524    2892000   2. Kreait\Firebase\Database\Reference->push(???) /home/vagrant/code/argentinadolar/php/script.php:25
    6.6524    2892000   3. Kreait\Firebase\Database\ApiClient->push(???, ???) /home/vagrant/code/argentinadolar/php/vendor/kreait/firebase-php/src/Firebase/Database/Reference.php:353
    7.6009    3244600   4. Kreait\Firebase\Util\JSON::decode(???, ???, ???, ???) /home/vagrant/code/argentinadolar/php/vendor/kreait/firebase-php/src/Firebase/Database/ApiClient.php:42
```

**Comment by fpilee** [comment]
the issue is the <!DOCTYPE html>... response from the api

**Comment by jeromegamez** [comment]
@fpilee This is a different error/cause. If it‘s still the case, please create a new issue and provide information about the response/error that the API returned.

You can debug/log requests by using a Guzzle middleware and/or enabling debug mode

https://firebase-php.readthedocs.io/en/latest/setup.html#http-client-options-and-middlewares

**Comment by Techiedie** [comment]
@jeromegamez  Sorry i was ping you in unrelated post but i have same problem and i could not get any solution #310
