### ISSUE TITLE
MFA authentication

### ISSUE THREAD

**Issue by llKoull** [kreait/firebase-php#864]
### Describe the feature you would like to see

Hello!

First of all, I would like to thank you for the tremendous effort put into this library; it works very well! 

I have a question about authentication via MFA. Currently, I am using the latest version of the library (7.9.1), and I don't know how I can perform authentication via MFA. 
After logging in with email and password, I can identify if a user has MFA enabled, but I can't find a way for Firebase to send the verification SMS. 

Is it possible to do it?

Thanks and best regards,

**Comment by jeromegamez** [comment]
Thank you for the kind words! MFA is something that has to be initiated and handled on the user devices with the Firebase Client SDK interacting with Google/Firebase Servers directly. It's not possible to trigger a verification SMS from a customer PHP Server backend. Here are the docs on how to implement this in clients (the link goes to web, but also has examples for Android and iOS): https://cloud.google.com/identity-platform/docs/web/mfa
