### ISSUE TITLE
Laravel integration

### ISSUE THREAD

**Issue by antpiantadosi** [kreait/firebase-php#87]
I've a problem with a laravel integration... I can't load Factory class... Any suggestion?

**Comment by jeromegamez** [comment]
This is a fairly unspecific problem description. Please check this thread/comment (based on firebase-php 2.2): https://github.com/kreait/firebase-php/issues/61#issuecomment-289094552 - also make sure that you are running on PHP 7 and have added all the necessary `use` statements at the top of the file. You can find further documentation at https://firebase-php.readthedocs.io/en/latest/
