### ISSUE TITLE
Laravel integration step 2

### ISSUE THREAD

**Issue by antpiantadosi** [kreait/firebase-php#88]
Hi again, sorry for ask continuously questions... I have integrated correctly everything in my laravel project. Now I have a question about token based auth... in my laravel project I have my auth system... now how can auth in firebase with my current user logged in?

**Comment by jeromegamez** [comment]
Hey @antpiantadosi - I am sorry to have to close this issue as well: it's really not in the scope of the Firebase PHP SDK itself, but a very specific and extended topic...

I'd like to encourage you to join the Firebase Slack Community at https://firebase-community.appspot.com/ - in the #php channel you will find other PHP developers who integrated Firebase in their PHP applications, and the other channels are also full of people certainly willing to help.

:octocat:
