### ISSUE TITLE
Is there a way to get a raw response?

### ISSUE THREAD

**Issue by yuki12321** [kreait/firebase-php#886]
### Describe the feature you would like to see

Thank you very much for providing this package.
I would like to express my deepest gratitude.
By the way, I have a question.

Why is the response below edited? Is there a way to get a raw response?
https://github.com/kreait/firebase-php/blob/7.x/src/Firebase/Messaging/AppInstanceApiClient.php#L58-L92
Thank you.

**Comment by jeromegamez** [comment]
The App Instance API always returns a 200 HTTP Status code, with an empty body on success, or an error when it's not successful (see https://developers.google.com/instance-id/reference/server#manage_relationship_maps_for_multiple_app_instances).

The SDK will always return results in the same format: an array with the topic names as keys and the operation results as values. This makes working and inspecting the results much easier.

The SDK transforms the responses of almost all API calls, raw API responses are not exposed in general.

If you need to debug HTTP Requests and Responses, you can do this with an [HTTP debug logger](https://firebase-php.readthedocs.io/en/7.10.0/troubleshooting.html#debugging) specifically and/or with [HTTP Client Options](https://firebase-php.readthedocs.io/en/7.10.0/setup.html#http-client-options) for more control.
