### ISSUE TITLE
Guzzlehttp dependency installation issue

### ISSUE THREAD

**Issue by dr1v3** [kreait/firebase-php#90]
Hi. When I'm trying to install firebase-php with Yii2 installed, i'm getting this error

```
  Problem 1
    - Conclusion: don't install kreait/firebase-php 3.0.1
    - Conclusion: remove guzzlehttp/guzzle 5.3.1
    - Installation request for kreait/firebase-php ^3.0 -> satisfiable by kreait/firebase-php[3.0.0, 3.0.1].
    - Conclusion: don't install guzzlehttp/guzzle 5.3.1
    - kreait/firebase-php 3.0.0 requires guzzlehttp/guzzle ^6.2.1 -> satisfiable by guzzlehttp/guzzle[6.2.1, 6.2.2, 6.2.3].
    - Can only install one of: guzzlehttp/guzzle[6.2.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.2, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.3, 5.3.1].
    - Installation request for guzzlehttp/guzzle (locked at 5.3.1) -> satisfiable by guzzlehttp/guzzle[5.3.1].
```
How I can workaround this?

**Comment by jeromegamez** [comment]
Yii2 itself doesn't seem to require Guzzle at all, so I assume another dependency in the `composer.json` of your project must be There must be another dependency requiring the 5.1 version. Here's what you can do to troubleshoot (this is not a step by step list, only a "possible approaches" list :) )

- Execute `composer why guzzlehttp/guzzle` to see which package requires it besides firebase-php
- Add `"guzzlehttp/guzzle": "^6.2.1"` in your main `composer.json`
- Delete the `vendors` directory, add kreait/firebase-php manually to your composer.json and try a `composer update`

I hope this helps, cheers!

**Comment by dr1v3** [comment]
I've noticed that it was boundstate/yii2-mailgun with old guzzlehttp. @jeromegamez, thanks a lot.

**Comment by bianjieandara** [comment]
jeromegamez, thanks!!
