### ISSUE TITLE
Fatal error: Class 'Firebase\Factory' not found in

### ISSUE THREAD

**Issue by sunnymumbai25** [kreait/firebase-php#91]
Unable to find Firebase\Factory class composer ran successfully.
below code ...

```
<?php
require __DIR__ . '/vendor/autoload.php';
$firebase = (new Firebase\Factory())->create();
# If the JSON file is located in a path accessible to your project,
# or if you want to create multiple dedicated instances
$firebase = (new Firebase\Factory())
    ->withCredentials(__DIR__.'/path/to/google-service-account.json')
    ->create();
?>

```
Can you please add this step install the package and special dependency are required ?

**Comment by jeromegamez** [comment]
If you use this code snippet, you have to add a `use Kreait\Firebase;` below the `require ...` line.

**Comment by sunnymumbai25** [comment]
After adding new code snippet use Kreait\Firebase;
Fatal error: Class 'Kreait\Firebase' not found

**Comment by jeromegamez** [comment]
Please check the version that you have installed. If you are on a 1.x or 2.x release, the usage is different and you can find its documentation at http://firebase-php.readthedocs.io/en/2.x/ or http://firebase-php.readthedocs.io/en/1.x/

Starting with 2.0, the library requires PHP 7, so I assume that you are on PHP 5.6

**Comment by sunnymumbai25** [comment]
{
    "name": "kreait/firebase-php",
    "description": "Firebase Admin SDK",
    "keywords": [
        "firebase",
        "google",
        "sdk",
        "api",
        "database"
    ],
    "homepage": "https://github.com/kreait/firebase-php",
    "license": "MIT",
    "authors": [
        {
            "name": "Jérôme Gamez",
            "homepage": "https://github.com/jeromegamez"
        }
    ],
    "require": {
        "php": "^7.0",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "fig/http-message-util": "^1.1",
        "google/auth": "^0.11.0",
        "guzzlehttp/guzzle": "^6.2.1",
        "kreait/firebase-tokens": "^1.1.1",
        "lcobucci/jwt": "^3.2",
        "mtdowling/jmespath.php": "^2.3"
    },
    "require-dev": {
        "phpunit/phpunit": "^6.0",
        "friendsofphp/php-cs-fixer": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "Kreait\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Kreait\\Tests\\": "tests"
        }
    },
    "config": {
        "platform": {
            "php": "7.0"
        },
        "sort-packages": true
    },
    "extra": {
        "branch-alias": {
            "dev-master": "3.x-dev"
        }
    }
}

**Comment by jeromegamez** [comment]
Please execute a `composer show kreait/firebase-php` inside your project root. The `versions: ...` line will show you the currently installed version.

`php -v` will show you the current PHP version.

**Comment by sunnymumbai25** [comment]
After exciting  "composer show kreait/firebase-php" and php (PHP 5.5.30 (cli) (built: Sep 30 2015 13:50:53))
  [UnexpectedValueException]
  "./composer.json" is not UTF-8, could not parse as JSON

**Comment by sourabh3697** [comment]
i am facing this issue after use above code:
 Fatal error: Uncaught Kreait\Firebase\Exception\LogicException: No service account has been found. Please set the path to a service account credentials file with Kreait\Firebase\Factory::withCredentials($path)() in E:\xampp\htdocs\firebase_test\vendor\kreait\firebase-php\src\Firebase\Factory.php:99 Stack trace: #0 E:\xampp\htdocs\firebase_test\vendor\kreait\firebase-php\src\Firebase\Factory.php(73): Kreait\Firebase\Factory->getServiceAccount() #1 E:\xampp\htdocs\firebase_test\test.php(15): Kreait\Firebase\Factory->create() #2 {main} thrown in E:\xampp\htdocs\firebase_test\vendor\kreait\firebase-php\src\Firebase\Factory.php on line 99

**Comment by jeromegamez** [comment]
Please make sure you have used the correct path to your Firebase Service Account file.

**Comment by sourabh3697** [comment]
i am using your new release version (https://github.com/kreait/firebase-php/releases/tag/3.0.1)
Here the file path in error : 
Fatal error: Uncaught Kreait\Firebase\Exception\CredentialsNotFound: No service account has been found. Tried [**[E:\xampp\htdocs\firebase3/google-services.json]([url](url))**]. Please set the path to a valid service account credentials file with Kreait\Firebase\Factory::withCredentials($path)() in E:\xampp\htdocs\firebase3\vendor\kreait\firebase-php\src\Firebase\Factory.php:99 Stack trace: #0 E:\xampp\htdocs\firebase3\vendor\kreait\firebase-php\src\Firebase\Factory.php(73): Kreait\Firebase\Factory->getServiceAccount() #1 E:\xampp\htdocs\firebase3\test.php(17): Kreait\Firebase\Factory->create() #2 {main} thrown in E:\xampp\htdocs\firebase3\vendor\kreait\firebase-php\src\Firebase\Factory.php on line 99

I copy the path from error and open in window , its correct . see attached screenshot

![patherror](https://user-images.githubusercontent.com/33743677/32931856-68ef1f60-cb8c-11e7-8858-9af82eee5861.png)

**Comment by sourabh3697** [comment]
[firebase3.zip](https://github.com/kreait/firebase-php/files/1481231/firebase3.zip)
I also attached the source code. Please review and let me know if any issue in code

**Comment by jeromegamez** [comment]
@sourabh3697 Please don't attach code containing private keys to your project. If someone downloads it, they get full access to your project.

**Comment by sourabh3697** [comment]
@jeromegamez  Thanks for information. will you help us to resolve the problem.

**Comment by jeromegamez** [comment]
@sourabh3697 Your test code (I downloaded it) works on my machine. Please not that you are safe to use `->withCredentials(__DIR__.'/google-services.json')` instead of `->withCredentials(__DIR__.'\google-services.json')` (use forward slashes instead of backward slashes). Also the final `?>` is not needed.

Other than that, this must be something weird on your machine, the code works fine.

**Comment by jeromegamez** [comment]
@sourabh3697 This is what I changed your code to on my computer (just minor changes/additions to display the top fields in your project):

```php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 'on');

require __DIR__.'/vendor/autoload.php';

use Kreait\Firebase;


echo "Path = " .  __DIR__.'/google-services.json';



$firebase = (new Firebase\Factory())
    ->withCredentials(__DIR__.'/google-services.json')
    ->create();

$db = $firebase->getDatabase();

$ref = $db->getReference('')->getValue();

print_r(array_keys($ref));
```

**Comment by sourabh3697** [comment]
I have tested on Live server. .
Now facing this bug 
 Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home1/handbyhand/public_html/handbyhandapp/firebase3/vendor/kreait/firebase-php/src/Firebase/Factory.php on line 39

**Comment by jeromegamez** [comment]
Your webserver is not running PHP 7.

**Comment by sourabh3697** [comment]
Okay, will changes in t and come back to you. Thanks for great help.

**Comment by sourabh3697** [comment]
@jeromegamez  i have upgrade PHP version to 7


But now faced same json path issue :

Fatal error: Uncaught Kreait\Firebase\Exception\CredentialsNotFound: No service account has been found. Tried [/home1/handbyhand/public_html/handbyhandapp/firebase3/google-services.json]. Please set the path to a valid service account credentials file with Kreait\Firebase\Factory::withCredentials($path)() in /home1/handbyhand/public_html/handbyhandapp/firebase3/vendor/kreait/firebase-php/src/Firebase/Factory.php:99 Stack trace: #0 /home1/handbyhand/public_html/handbyhandapp/firebase3/vendor/kreait/firebase-php/src/Firebase/Factory.php(73): Kreait\Firebase\Factory->getServiceAccount() #1 /home1/handbyhand/public_html/handbyhandapp/firebase3/test.php(16): Kreait\Firebase\Factory->create() #2 {main} thrown in /home1/handbyhand/public_html/handbyhandapp/firebase3/vendor/kreait/firebase-php/src/Firebase/Factory.php on line 99

**Comment by jeromegamez** [comment]
Please make sure that the service account JSON file is located in the given directory and is accessible by the PHP process (check owner, group and permissions). Unfortunately this is an issue with the environment, not the library itself, and I am unable to provide basic PHP support…

**Comment by sourabh3697** [comment]
@jeromegamez 
Here my actual requirement :
My records stored in firebase like this:
    "Users" : {
      "-JUAg9rVemiNQykfvvHs" : {
        "completed" : false,
        "done" : false,
        "group" : false,
        "private" : false,
        "subject" : "Q first"
      },
      "-JUAgAmgPwZLPr2iH1Ho" : {
        "completed" : false,
        "done" : false,
        "group" : false,
        "private" : false,
        "subject" : "Q second"
      },
      "-JUAgBfF8f7V5R5-XgrY" : {
        "completed" : false,
        "done" : false,
        "group" : false,
        "private" : true,
        "subject" : "Q third"
      }
    }
  }
}

and i would like to query todos to get all records with private:true. in PHP. Is this possible using any php code and how should i do it ?
