### ISSUE TITLE
your php version (8.2.12) does not satisfy that requirement

### ISSUE THREAD

**Issue by ripaym1970** [kreait/firebase-php#919]
### Describe the bug

  Problem 1
    - beste/clock 1.0.0 requires php ~7.4.0 || ~8.0.0 || ~8.1.0 -> your php version (8.2.12) does not satisfy that requirement.
    - kreait/firebase-php 6.2.0 requires beste/clock ^1.0 -> satisfiable by beste/clock[1.0.0].
    - Root composer.json requires kreait/firebase-php 6.2.0 -> satisfiable by kreait/firebase-php[6.2.0].

### Installed packages

```json
Problem 1
    - beste/clock 1.0.0 requires php ~7.4.0 || ~8.0.0 || ~8.1.0 -> your php version (8.2.12) does not satisfy that requirement.
    - kreait/firebase-php 6.2.0 requires beste/clock ^1.0 -> satisfiable by beste/clock[1.0.0].
    - Root composer.json requires kreait/firebase-php 6.2.0 -> satisfiable by kreait/firebase-php[6.2.0].
```

### PHP version and extensions

```shell
8.2.12
```

### Steps to reproduce the issue.

```shell
# Insert the commands issued in the terminal if they are needed
# to reproduce the issue. Otherwise, delete this code block.
```

```php
// Insert the PHP code to reproduce the issue. Please ensure that it is code that
// can be copy pasted to reproduce it.
```

### Error message/Stack trace

```shell
Problem 1
    - beste/clock 1.0.0 requires php ~7.4.0 || ~8.0.0 || ~8.1.0 -> your php version (8.2.12) does not satisfy that requirement.
    - kreait/firebase-php 6.2.0 requires beste/clock ^1.0 -> satisfiable by beste/clock[1.0.0].
    - Root composer.json requires kreait/firebase-php 6.2.0 -> satisfiable by kreait/firebase-php[6.2.0].
```

**Comment by jeromegamez** [comment]
You're not giving me much to work with, here, and omitted much of the information asked in the issue template.

This looks as if the dependencies in your project need to be updated, which you can do with a `composer update -W` or `composer require -W kreait/firebase-php`.
