### ISSUE TITLE
InvalidToken

### ISSUE THREAD

**Issue by jackloverde** [kreait/firebase-php#92]
Hi, i am using this lib for create a custom token, but i getting this error always!

> Fatal error: Uncaught Firebase\Auth\Token\Exception\InvalidToken: This token has an invalid issuer. in "MyPath"/vendor/kreait/firebase-tokens/src/Verifier.php:84

The line 84 is:
>private function verifyIssuer(Token $token)
    {
        if (!$token->hasClaim('iss')) {
            throw new InvalidToken($token, 'The claim "iss" is missing.');
        }
        //-> This line below
        if ($token->getClaim('iss') !== sprintf('https://securetoken.google.com/%s', $this->projectId)) {
            throw new InvalidToken($token, 'This token has an invalid issuer.');
        }
    }

Try to find why this error occur with this URL, and cant find, could you help me ?
Thanks

**Comment by jeromegamez** [comment]
The `verifyIdToken()` method is not to be used to verify custom tokens created with `createCustomToken`. A custom token is a token that you use to authenticate a server request to Firebase (see https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_the_firebase_admin_sdk) - an ID token is a token that you receive from Firebase after a user has signed in on the client side (see https://firebase.google.com/docs/auth/admin/verify-id-tokens#retrieve_id_tokens_on_clients).

**Comment by jackloverde** [comment]
Hummmm understand that.
Thanks for you answer!
