### ISSUE TITLE
factory->withCredentials does not resolve file contents

### ISSUE THREAD

**Issue by urm47** [kreait/firebase-php#93]
Hi
This is an impressive library. Thank you. My first tests work perfectly.

I have however one funny issue.

factory->withCredentials hands over the filename instead the content of the file. This results in a JSON syntax error.

a) does work 
Putting the application_default_credentials in $HOME/.config/gloud/application_default_credentials.json

b) does NOT work
```
$firebase = (new Firebase\Factory())
->withCredentials(__DIR__.'/application_default_credentials.json')
->create();
```

![bildschirmfoto 2017-06-08 um 14 28 45](https://user-images.githubusercontent.com/17439576/26928619-1490c1d0-4c57-11e7-96de-0fd82634c84f.png)

$json contains the filename, not its content
![bildschirmfoto 2017-06-08 um 14 31 24](https://user-images.githubusercontent.com/17439576/26928641-2ee7c772-4c57-11e7-9ac4-9e8239030100.png)

c) does work
```
$firebase = (new Firebase\Factory())
->withCredentials('{
  "type": "service_account",
  "project_id": "xxxx",
  "private_key_id": "xxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----xxxx\n",
  "client_email": "xxx",
  "client_id": "xxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "xxx"
}')
->create();
```

Using version 
kreait 3.0.1
php 7.1.4

Am I overlooking anything?

Thank you!

**Comment by jeromegamez** [comment]
Hey Urs, and thank you for the comprehensive bug report!

Is the file in `__DIR__.'/application_default_credentials.json'` by any chance a symlink to another file?

**Comment by urm47** [comment]
Thanks for responding so quickly.
No, it is not a symlink.

**Comment by jeromegamez** [comment]
That's really strange (it worked for me with a Symlink as well, I just wanted to make sure).

To debug further, could you please replace the version of `kreait/firebase-php` in your project's `composer.json` with `dev-debug-credentials` (it points to https://github.com/kreait/firebase-php/tree/debug-credentials) and do a `composer require kreait/firebase-php`?

If added a check for a symlink and one to check if we're really working with a file. You can see the changes here: https://github.com/kreait/firebase-php/commit/0ad8b0024c26b8cd02b13e2a2975627ec557824b#diff-8b9194fc7bb1baa738945c01e3f0e1b8

If this still doesn't work, we'll continue debugging, until we find the issue 👍 :)

**Comment by urm47** [comment]
It could not install the debug version via composer. So I copied the ServiceAccount.php manually.
Hope this is OK.

Result of fromJsonFile: 
- `if (is_link($filePath)) {` is false.
- None of the conditions are true.


![bildschirmfoto 2017-06-08 um 18 50 37](https://user-images.githubusercontent.com/17439576/26940652-c69e5904-4c7b-11e7-89e7-1c9e231dbcdd.png)

`return self::fromJson(file_get_contents($filePath));` does the job. 
Now I have the file contents, the code continues and I can retrieve a snapshot

![bildschirmfoto 2017-06-08 um 18 58 58](https://user-images.githubusercontent.com/17439576/26940858-90a1b886-4c7c-11e7-929a-23578014ab14.png)

**Comment by jeromegamez** [comment]
Does this mean that this works with the changed code now? I will then release a new version tonight - I have to make another change, but it's not directly related.

**Comment by urm47** [comment]
Yes. It works. 
To be clear, it first throws an exception on `fromJson` and then `fromJsonFile` makes it work.
```
            try {
                return self::fromJson($value);
            } catch (InvalidArgumentException $e) {
                return self::fromJsonFile($value);
            }
```

**Comment by jeromegamez** [comment]
That's expected! Thank you for helping out! There will be a new (3.0.2) release soon!

**Comment by jeromegamez** [comment]
Here it is: https://github.com/kreait/firebase-php/releases/tag/3.0.2

I'm closing this issue now - but if you encounter more issues, please don't hesitate to add another comment or open a new issue! And thank you again for using the library and taking the time to share the problem! 🤗
