### ISSUE TITLE
withServiceAccount(): Argument #1 ($value) must be of type array|string

### ISSUE THREAD

**Issue by PavelDeveloperUa** [kreait/firebase-php#940]
### Describe the feature you would like to see

Hi, I have a little problem. I update API in new version, now I get errors.

> Kreait\Firebase\Factory::withServiceAccount(): Argument #1 ($value) must be of type array|string, Kreait\Firebase\Factory given, called in /home/ug/web/admin.ultragroup.com.ua/public_html/libraries/components/fcm/Fcm.php on line 126

```
public function __construct($config = [])
    {
        parent::__construct($config);
        $config = $this->config;
        $this->service_account = ServiceAccount::fromJson($config);
    }
```

```
public function build()
    {
        $service = $this->service_account;
        $firebase = (new Factory())->withServiceAccount($service)->create();
        $this->messaging = $firebase->getMessaging();
        return $this;
    }
```

> Call to undefined method Kreait\Firebase\Database\Reference::sendMulticast()

```
public function send(array $device_to_send)
    {
        $message = CloudMessage::new();
        $message = $message->withApnsConfig($this->apns_config);
        $message = $message->withAndroidConfig($this->android_config);
        return $this->messaging->sendMulticast($message, $device_to_send);
    }
```

Thanks

**Comment by jeromegamez** [comment]
This is a problem in your project's code, not the SDK itself.

* I can't tell what `$config` contains
* The `ServiceAccount` class doesn't exist in the SDK anymore, so I don't know which version of the SDK you are using, but I do can tell you that it's outdated, and that you're probably following an outdated tutorial from the internet.
* You're trying to call a `sendMulticast()` method on a realtime database reference, that's visible from the error message

Please read the documentation at https://firebase-php.readthedocs.io/

Please note that I can't provide free support for topics not directly related to the SDK, and the GitHub issues are meant for bug reports or feature requests.
