### ISSUE TITLE
error in factory.php

### ISSUE THREAD

**Issue by wardberckmans** [kreait/firebase-php#95]
In Factory.php (/firebase-php/src/Firebase/Factory.php) of package version 3.1.1, I get an error on line 37. The error says: parse error, expecting `';'' or `'{''. This is on the line with "public function withCredentials(string $credentials): self"
I did not manually change this file so I have no clue where this error is coming from.

**Comment by jeromegamez** [comment]
Line 37 in the Factory is a comment (see https://github.com/kreait/firebase-php/blob/3.1.1/src/Firebase/Factory.php#L37).

My best guesses are that you are either not on PHP 7 or something went wrong when implementing the library.

The tests on Travis CI would have failed if there actually was a syntax error (https://travis-ci.org/kreait/firebase-php/builds/244075870).
