### ISSUE TITLE
Using firebase-php without a composer

### ISSUE THREAD

**Issue by theunreal** [kreait/firebase-php#97]
Hi,
I have really old native PHP website, and I'm trying to use the firebase-php library without a composer.

I tried to include it directly:

```
error_reporting(-1);
	require 'includes/firebase/Firebase.php';
use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;
$serviceAccount = ServiceAccount::fromJsonFile('realtime-chat-efadc-firebase-adminsdk.json');
```

but adding the `$serviceAccount` line throws error 500.
Any ideas?

**Comment by jeromegamez** [comment]
Hey @theunreal! I would suggest registering an autoloader for this, see http://php.net/manual/en/function.spl-autoload-register.php

You can find an adaptable implementation example here: http://www.php-fig.org/psr/psr-4/examples/

As PHP class autoloading is not in the scope of this library, I'm closing this issue, but feel free to add further comments if you habe additional questions.
