### ISSUE TITLE
Dinamically set the expiration of token

### ISSUE THREAD

**Issue by morfin** [kreait/firebase-php#98]
Hi,

The token expiration is hard coded:
 ```
 return $this->builder
            ->setIssuedAt($now)
            ->setExpiration($now + (60 * 60))
            ->sign($this->signer, $this->privateKey)
            ->getToken();

```

If I need to change it, what do you suggest? Wouldn't be nice if I could pass those parameters during 
`$tokenHandler->createCustomToken($uid, $claims, $mayBeHere);` ?

**Comment by jeromegamez** [comment]
@morfin I just released a new version of the tokens library which enables you to do this https://github.com/kreait/firebase-tokens-php/releases/tag/1.6.0

After updating the dependencies in your project, you will be able to do pass a custom expiration date:

```php
\Firebase\Auth\Token\Generator::createCustomToken($uid, array $claims = [], \DateTimeInterface $expiresAt = null): Token
\Firebase\Auth\Token\Handler::createCustomToken($uid, array $claims = [], \DateTimeInterface $expiresAt = null): Token
```

:octocat:
