### ISSUE TITLE
firebase-php 1.2.2 Usage with PHP 5.6 

### ISSUE THREAD

**Issue by theunreal** [kreait/firebase-php#99]
I am trying to use firebase-php 1.2.2 on PHP 5.6 powered website.

I followed the documentation for version 1.x and this is what I ended up with:

```
<?php
	require __DIR__.'/vendor/autoload.php';

	use Kreait\Firebase\Factory;
	use Kreait\Firebase\ServiceAccount;
	
	use Kreait\Firebase\Configuration;
	

	$config = new Configuration();
	$config->setAuthConfigFile(__DIR__.'realtime-chat-efadc-firebase-adminsdk-somecode.json');

	$firebase = new Firebase('https://realtime-chat-fasdc.firebaseio.com', $config);

	?>
```

The error I get is `Class 'Firebase' not found `

I tried to add `use Kreait\Firebase` to the code but then I get `Class 'Kreait\Firebase' not found `.

Not sure what I'm missing..

**Comment by theunreal** [comment]
use Kreait\Firebase\Firebase; did the trick

**Comment by jeromegamez** [comment]
Glad you got to make it work! I'll check the documentation if I missed something.
